### PR TITLE
Include external library dependencies in output of dune describe.

### PR DESCRIPTION
**Pull request by reubenrowe**
Rotor will also need details for external libraries that the workspace depends on, in order to resolve paths in the typed tree.

### CODE REVIEW

**Comment by reubenrowe** [comment]
Rotor will also need details for external libraries that the workspace depends on, in order to resolve paths in the typed tree.

**Comment by jeremiedimino** [comment]
@reubenrowe this is good to merge once the conflict is fixed

**Comment by reubenrowe** [comment]
In fact, I do not need the whole database - only those external libraries that are dependencies of the workspace. Let me try and modify the pull request to be more specific.

**Comment by jeremiedimino** [comment]
Thanks!

**Pull request merged**
