### PR TITLE
refactor: optimize [Path.reach]

### PR DESCRIPTION
**Pull request by rgrinberg**
Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Comment by snowleopard** [comment]
Could you do some microbenchmarks to show the difference? Seems like quite a lot of fiddly code to add unless there is a solid win.

**Comment by snowleopard** [comment]
Added @tov as a reviewer.

**Comment by rgrinberg** [comment]
Here are the results from micro benchmarking:
```
┌────────────────────────────────────────────────────────────────────────────┬──────────┬─────────┬────────────┐
│ Name                                                                       │ Time/Run │ mWd/Run │ Percentage │
├────────────────────────────────────────────────────────────────────────────┼──────────┼─────────┼────────────┤
│ [bench/micro/path_bench.ml] reach:from root long path                      │   6.37ns │         │      1.33% │
│ [bench/micro/path_bench.ml] reach:from root short path                     │   6.35ns │         │      1.33% │
│ [bench/micro/path_bench.ml] reach:reach root from short path               │  22.05ns │         │      4.60% │
│ [bench/micro/path_bench.ml] reach:reach root from long path                │ 393.12ns │  11.00w │     82.00% │
│ [bench/micro/path_bench.ml] reach:reach long path from similar long path   │ 479.44ns │   4.00w │    100.00% │
│ [bench/micro/path_bench.ml] reach:reach short path from similar short path │  61.28ns │   4.00w │     12.78% │
└────────────────────────────────────────────────────────────────────────────┴──────────┴─────────┴────────────┘
```

Which should be  compared to https://github.com/ocaml/dune/pull/10074

As we can see, this new implementation is dramatically faster across the board.

**Comment by snowleopard** [comment]
Awesome improvement! I wonder how this compares to Jenga's implementation of `Path.reach`. I remember doing some optimisation there a couple of years ago... We should double check!

**Comment by snowleopard** [comment]
Btw, there is a lot of finicky code here. We should definitely add some thorough tests to catch possible bugs.

**Comment by rgrinberg** [comment]
> Btw, there is a lot of finicky code here. We should definitely add some thorough tests to catch possible bugs.

Agreed. Before this PR, I've added 17 unit tests to make sure all the various cases are checked. Those tests plus the monorepo benchmark successfully completing make me fairly confident the semantics are the same.

**Review by tov — APPROVED** [review]

**Pull request merged**
