### PR TITLE
refactor: remove Lib.modules and its friends

### PR DESCRIPTION
**Pull request by rgrinberg**
Gets rid of a bunch of ugly forward declarations. Although it requires us to pass more Sctx in some places, it's better than sneakily passing it through forward declarations. I have upcoming pr's to get rid of much of this anyway.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Looks like this depends on some other PR's to break the cycle. Let me make sure I'm submitting the patches in the right order.

**Comment by rgrinberg** [comment]
Okay, it's fixed. I just needed to trick ocamldep a bit.

**Comment by rgrinberg** [comment]
gentle ping @bobot or @nojb  :)

**Review by nojb — APPROVED** [review]
LGTM

**Comment by nojb** [comment]
Nice! I love getting rid of forward references :)

**Pull request merged**
