### PR TITLE
feature(coq): warnings field for coq.theory

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by Alizter** [comment]
@ejgallego Are we planning to change Coq command line syntax? If it ever happens in the future, the correct fix would be to detect the Coq version and adapt based on that.

Keeping warnings in a separate field makes them more portable and stops users from messing around with `-w`. We should try to minimize flags passed to Coq as much as possible.

**Comment by ejgallego** [comment]
> Keeping warnings in a separate field makes them more portable

How does it make them "more portable"

Why is a problem for users to add "-w"?

Why we need to minimize flags passed to Coq? I'm lost here, what does that mean, and why does Dune care what the user wants w.r.t. flags?

I don't really want to worry now having to understand the specifics of Coq cmd line syntax, so NACK on this from me.

@rgrinberg , WDYT?

**Comment by ejgallego** [comment]
I don't know if there is a plan to change command line syntax, but it has changed a lot historically, and certainly is not frozen.

**Comment by ejgallego** [comment]
Another problem is that where to put warnings would become ambiguous, the user could use both flags or warnings, and this seems problematic to me too.

**Comment by Alizter** [comment]
OK, don't care enough to make this happen.

**Pull request closed without merging**
