### PR TITLE
docs: fix the `dune cache trim` documentation

### PR DESCRIPTION
**Pull request by anmonteiro**
- `--size` is the final size
- `--trimmed-size` is how many bytes to remove

cc @ygrek

### CODE REVIEW

**Comment by rgrinberg** [comment]
Could you fix the `cache-man.t` tests?

**Comment by Alizter** [comment]
Just build `@doc/runtest`.

**Comment by anmonteiro** [comment]
> Could you fix the `cache-man.t` tests?

Done.



> Just build `@doc/runtest`.

This had no effect. I ran `./dune.exe build @test/cache-man --auto-promote`

**Comment by Alizter** [comment]
Oh sorry I misunderstood the error, I thought you were trying to update the manpages.

**Review by Alizter — APPROVED** [review]

**Pull request merged**
