### PR TITLE
Refactor handling of link time deps

### LINKED ISSUE #2789: dune build fails for discover.exe in bytecode-only target
With commit c5679280 in bytecode-only targets some packages fail to build:
````
[   49s] File "src/config/dune", line 2, characters 8-16:
[   49s] 2 |   (name discover)
[   49s]             ^^^^^^^^
[   49s] Error: File unavailable:
````
Looks like everything with some sort of discover.exe fails, packages without discover like `result` and `ppx_derivers` succeed.

This log is from ocaml-num:
````
[   49s] + dune installed-libraries
[   49s] bigarray                       (version: [distributed with Ocaml])
[   49s] bytes                          (version: [distributed with OCaml 4.02 or above])
[   49s] compiler-libs                  (version: [distributed with Ocaml])
[   49s] compiler-libs.bytecomp         (version: [distributed with Ocaml])
[   49s] compiler-libs.common           (version: [distributed with Ocaml])
[   49s] compiler-libs.toplevel         (version: [distributed with Ocaml])
[   49s] dune-action-plugin             (version: n/a)
[   49s] dune-build-info                (version: n/a)
[   49s] dune-configurator              (version: n/a)
[   49s] dune-glob                      (version: n/a)
[   49s] dune-private-libs.caml         (version: n/a)
[   49s] dune-private-libs.dune-lang    (version: n/a)
[   49s] dune-private-libs.dune_re      (version: n/a)
[   49s] dune-private-libs.ocaml-config (version: n/a)
[   49s] dune-private-libs.stdune       (version: n/a)
[   49s] dune.configurator              (version: n/a)
[   49s] dynlink                        (version: [distributed with Ocaml])
[   49s] graphics                       (version: [distributed with Ocaml])
[   49s] ocamldoc                       (version: [distributed with Ocaml])
[   49s] result                         (version: [distributed with Ocaml])
[   49s] seq                            (version: [distributed with Ocaml])
[   49s] stdlib                         (version: [distributed with Ocaml])
[   49s] str                            (version: [distributed with Ocaml])
[   49s] threads                        (version: [distributed with Ocaml])
[   49s] threads.none                   (version: [internal])
[   49s] threads.posix                  (version: [internal])
[   49s] threads.vm                     (version: [internal])
[   49s] uchar                          (version: [distributed with Ocaml])
[   49s] unix                           (version: [distributed with Ocaml])
[   49s] + dune external-lib-deps @install
[   49s] These are the external library dependencies in the default context:
[   49s] - compiler-libs
[   49s] - dune.configurator
[   49s] + dune external-lib-deps @runtest
[   49s] These are the external library dependencies in the default context:
[   49s] - dune.configurator
[   49s] + dune build --verbose @install
[   49s] # Workspace root: /home/abuild/rpmbuild/BUILD/ocaml-num-1.2
[   49s] Running[0]: /usr/bin/nproc > /tmp/dune954810.output 2> /dev/null
[   49s] # Auto-detected concurrency: 12
[   49s] Running[1]: /usr/bin/ocamlc -config > /tmp/dune72d940.output
[   49s] # Dune context:
[   49s] #  { name = "default"
[   49s] #  ; kind = "default"
[   49s] #  ; profile = Dyn
[   49s] #  ; merlin = true
[   49s] #  ; for_host = None
[   49s] #  ; build_dir = "default"
[   49s] #  ; toplevel_path = None
[   49s] #  ; ocaml_bin = External "/usr/bin"
[   49s] #  ; ocaml = External "/usr/bin/ocaml"
[   49s] #  ; ocamlc = External "/usr/bin/ocamlc"
[   49s] #  ; ocamlopt = None
[   49s] #  ; ocamldep = External "/usr/bin/ocamldep"
[   49s] #  ; ocamlmklib = External "/usr/bin/ocamlmklib"
[   49s] #  ;
[   49s] #  env =
[   49s] #    map
[   49s] #      {
[   49s] #      "CAML_LD_LIBRARY_PATH" :
[   49s] #        "/home/abuild/rpmbuild/BUILD/ocaml-num-1.2/_build/install/default/lib/stublibs"
[   49s] #      ; "DUNE_CONFIGURATOR" : "/usr/bin/ocamlc"
[   49s] #      ; "INSIDE_DUNE" : "1"
[   49s] #      ;
[   49s] #      "OCAMLFIND_IGNORE_DUPS_IN" :
[   49s] #        "/home/abuild/rpmbuild/BUILD/ocaml-num-1.2/_build/install/default/lib"
[   49s] #      ;
[   49s] #      "OCAMLPATH" :
[   49s] #        "/home/abuild/rpmbuild/BUILD/ocaml-num-1.2/_build/install/default/lib"
[   49s] #      }
[   49s] #  ; findlib_path = [ External "/usr/lib64/ocaml" ]
[   49s] #  ; arch_sixtyfour = true
[   49s] #  ; natdynlink_supported = false
[   49s] #  ; supports_shared_libraries = true
[   49s] #  ; opam_vars = map {}
[   49s] #  ;
[   49s] #  ocaml_config =
[   49s] #    { version = "4.08.1"
[   49s] #    ; standard_library_default = "/usr/lib64/ocaml"
[   49s] #    ; standard_library = "/usr/lib64/ocaml"
[   49s] #    ; standard_runtime = "the_standard_runtime_variable_was_deleted"
[   49s] #    ; ccomp_type = "cc"
[   49s] #    ; c_compiler = "/usr/bin/gcc"
[   49s] #    ; ocamlc_cflags = [ "-O2"; "-fno-strict-aliasing"; "-fwrapv"; "-fPIC" ]
[   49s] #    ; ocamlopt_cflags = [ "-O2"; "-fno-strict-aliasing"; "-fwrapv" ]
[   49s] #    ;
[   49s] #    bytecomp_c_compiler =
[   49s] #      [ "/usr/bin/gcc"
[   49s] #      ; "-O2"
[   49s] #      ; "-fno-strict-aliasing"
[   49s] #      ; "-fwrapv"
[   49s] #      ; "-fPIC"
[   49s] #      ; "-D_FILE_OFFSET_BITS=64"
[   49s] #      ; "-D_REENTRANT"
[   49s] #      ]
[   49s] #    ; bytecomp_c_libraries = [ "-lm"; "-ldl"; "-lpthread" ]
[   49s] #    ;
[   49s] #    native_c_compiler =
[   49s] #      [ "/usr/bin/gcc"
[   49s] #      ; "-O2"
[   49s] #      ; "-fno-strict-aliasing"
[   49s] #      ; "-fwrapv"
[   49s] #      ; "-D_FILE_OFFSET_BITS=64"
[   49s] #      ; "-D_REENTRANT"
[   49s] #      ]
[   49s] #    ; native_c_libraries = [ "-lm"; "-ldl" ]
[   49s] #    ; cc_profile = [ "-pg" ]
[   49s] #    ; architecture = "amd64"
[   49s] #    ; model = "default"
[   49s] #    ; int_size = 63
[   49s] #    ; word_size = 64
[   49s] #    ; system = "linux"
[   49s] #    ; asm = [ "/usr/bin/as" ]
[   49s] #    ; asm_cfi_supported = true
[   49s] #    ; with_frame_pointers = false
[   49s] #    ; ext_exe = ""
[   49s] #    ; ext_obj = ".o"
[   49s] #    ; ext_asm = ".s"
[   49s] #    ; ext_lib = ".a"
[   49s] #    ; ext_dll = ".so"
[   49s] #    ; os_type = "Unix"
[   49s] #    ; default_executable_name = "a.out"
[   49s] #    ; systhread_supported = true
[   49s] #    ; host = "x86_64-suse-linux-gnu"
[   49s] #    ; target = "x86_64-suse-linux-gnu"
[   49s] #    ; profiling = true
[   49s] #    ; flambda = false
[   49s] #    ; spacetime = false
[   49s] #    ; safe_string = false
[   49s] #    ; exec_magic_number = "Caml1999X025"
[   49s] #    ; cmi_magic_number = "Caml1999I025"
[   49s] #    ; cmo_magic_number = "Caml1999O025"
[   49s] #    ; cma_magic_number = "Caml1999A025"
[   49s] #    ; cmx_magic_number = "Caml1999Y025"
[   49s] #    ; cmxa_magic_number = "Caml1999Z025"
[   49s] #    ; ast_impl_magic_number = "Caml1999M025"
[   49s] #    ; ast_intf_magic_number = "Caml1999N025"
[   49s] #    ; cmxs_magic_number = "Caml1999D025"
[   49s] #    ; cmt_magic_number = "Caml1999T025"
[   49s] #    ; natdynlink_supported = false
[   49s] #    ; supports_shared_libraries = true
[   49s] #    ; windows_unicode = false
[   49s] #    }
[   49s] #  ;
[   49s] #  which =
[   49s] #    map
[   49s] #      { "ocaml" : Some External "/usr/bin/ocaml"
[   49s] #      ; "ocamlc" : Some External "/usr/bin/ocamlc"
[   49s] #      ; "ocamlobjinfo" : Some External "/usr/bin/ocamlobjinfo"
[   49s] #      }
[   49s] #  }
[   49s] # Actual targets:
[   49s] # - recursive alias @./install
[   49s] Running[2]: (cd _build/default && /usr/bin/ocamldep -modules -intf src/arith_flags.mli) > _build/default/src/.num.objs/arith_flags.mli.d
[   49s] Running[3]: (cd _build/default && /usr/bin/ocamldep -modules -impl src/arith_flags.ml) > _build/default/src/.num.objs/arith_flags.ml.d
[   49s] Running[4]: (cd _build/default && /usr/bin/ocamldep -modules -intf src/arith_status.mli) > _build/default/src/.num.objs/arith_status.mli.d
[   49s] Running[5]: (cd _build/default && /usr/bin/ocamldep -modules -impl src/arith_status.ml) > _build/default/src/.num.objs/arith_status.ml.d
[   49s] Running[6]: (cd _build/default && /usr/bin/ocamldep -modules -intf src/big_int.mli) > _build/default/src/.num.objs/big_int.mli.d
[   49s] Running[7]: (cd _build/default && /usr/bin/ocamldep -modules -impl src/big_int.ml) > _build/default/src/.num.objs/big_int.ml.d
[   49s] Running[8]: (cd _build/default && /usr/bin/ocamldep -modules -intf src/int_misc.mli) > _build/default/src/.num.objs/int_misc.mli.d
[   49s] Running[9]: (cd _build/default && /usr/bin/ocamldep -modules -impl src/int_misc.ml) > _build/default/src/.num.objs/int_misc.ml.d
[   49s] File "src/config/dune", line 2, characters 8-16:
[   49s] 2 |   (name discover)
[   49s]             ^^^^^^^^
[   49s] Error: File unavailable:
[   49s] /usr/lib64/ocaml/dune-private-libs/stdune/dllstdune_stubs.so
[   49s] Running[10]: (cd _build/default && /usr/bin/ocamldep -modules -impl src/config/discover.ml) > _build/default/src/config/.discover.eobjs/discover.ml.d
[   49s] Running[11]: (cd _build/default/src && /usr/bin/touch bng_generic.c)
[   49s] Running[12]: (cd _build/default && /usr/bin/ocamldep -modules -intf src/nat.mli) > _build/default/src/.num.objs/nat.mli.d
[   49s] Running[13]: (cd _build/default && /usr/bin/ocamldep -modules -impl src/nat.ml) > _build/default/src/.num.objs/nat.ml.d
[   49s] Running[14]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -no-alias-deps -opaque -o src/.num.objs/byte/arith_flags.cmi -c -intf src/arith_flags.mli)
[   49s] Running[15]: (cd _build/default && /usr/bin/ocamldep -modules -intf src/num.mli) > _build/default/src/.num.objs/num.mli.d
[   49s] Running[16]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -no-alias-deps -opaque -o src/.num.objs/byte/arith_status.cmi -c -intf src/arith_status.mli)
[   49s] Running[17]: (cd _build/default && /usr/bin/ocamldep -modules -impl src/num.ml) > _build/default/src/.num.objs/num.ml.d
[   49s] Running[18]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -no-alias-deps -opaque -o src/.num.objs/byte/int_misc.cmi -c -intf src/int_misc.mli)
[   49s] Running[19]: (cd _build/default && /usr/bin/ocamldep -modules -intf src/ratio.mli) > _build/default/src/.num.objs/ratio.mli.d
[   49s] Running[20]: (cd _build/default && /usr/bin/ocamldep -modules -impl src/ratio.ml) > _build/default/src/.num.objs/ratio.ml.d
[   49s] Running[21]: (cd _build/default && /usr/bin/ocamldep -modules -intf toplevel/num_top.mli) > _build/default/toplevel/.num_top.objs/num_top.mli.d
[   49s] Running[22]: (cd _build/default && /usr/bin/ocamldep -modules -impl toplevel/num_top.ml) > _build/default/toplevel/.num_top.objs/num_top.ml.d
[   49s] Running[23]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -no-alias-deps -opaque -o src/.num.objs/byte/nat.cmi -c -intf src/nat.mli)
[   49s] Running[24]: (cd _build/default && /usr/bin/ocamldep -modules -intf toplevel/num_top_printers.mli) > _build/default/toplevel/.num_top.objs/num_top_printers.mli.d
[   49s] Running[25]: (cd _build/default && /usr/bin/ocamldep -modules -impl toplevel/num_top_printers.ml) > _build/default/toplevel/.num_top.objs/num_top_printers.ml.d
[   49s] Running[26]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -intf-suffix .ml -no-alias-deps -opaque -o src/.num.objs/byte/arith_flags.cmo -c -impl src/arith_flags.ml)
[   49s] Running[27]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -intf-suffix .ml -no-alias-deps -opaque -o src/.num.objs/byte/arith_status.cmo -c -impl src/arith_status.ml)
[   49s] Running[28]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -intf-suffix .ml -no-alias-deps -opaque -o src/.num.objs/byte/int_misc.cmo -c -impl src/int_misc.ml)
[   49s] Running[29]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -intf-suffix .ml -no-alias-deps -opaque -o src/.num.objs/byte/nat.cmo -c -impl src/nat.ml)
[   49s] Running[30]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -no-alias-deps -opaque -o src/.num.objs/byte/big_int.cmi -c -intf src/big_int.mli)
[   49s] Running[31]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -intf-suffix .ml -no-alias-deps -opaque -o src/.num.objs/byte/big_int.cmo -c -impl src/big_int.ml)
[   49s] Running[32]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -no-alias-deps -opaque -o src/.num.objs/byte/ratio.cmi -c -intf src/ratio.mli)
[   49s] Running[33]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -no-alias-deps -opaque -o src/.num.objs/byte/num.cmi -c -intf src/num.mli)
[   49s] Running[34]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -intf-suffix .ml -no-alias-deps -opaque -o src/.num.objs/byte/ratio.cmo -c -impl src/ratio.ml)
[   49s] Running[35]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence -strict-formats -g -bin-annot -I toplevel/.num_top.objs/byte -I /usr/lib64/ocaml/compiler-libs -I src/.num.objs/byte -I src/.num.objs/native -no-alias-deps -opaque -o toplevel/.num_top.objs/byte/num_top_printers.cmi -c -intf toplevel/num_top_printers.mli)
[   49s] Running[36]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence -strict-formats -g -bin-annot -I toplevel/.num_top.objs/byte -I /usr/lib64/ocaml/compiler-libs -I src/.num.objs/byte -I src/.num.objs/native -no-alias-deps -opaque -o toplevel/.num_top.objs/byte/num_top.cmi -c -intf toplevel/num_top.mli)
[   49s] Running[37]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -bin-annot -I src/.num.objs/byte -intf-suffix .ml -no-alias-deps -opaque -o src/.num.objs/byte/num.cmo -c -impl src/num.ml)
[   50s] Running[38]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence -strict-formats -g -bin-annot -I toplevel/.num_top.objs/byte -I /usr/lib64/ocaml/compiler-libs -I src/.num.objs/byte -I src/.num.objs/native -intf-suffix .ml -no-alias-deps -opaque -o toplevel/.num_top.objs/byte/num_top.cmo -c -impl toplevel/num_top.ml)
[   50s] Running[39]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence -strict-formats -g -bin-annot -I toplevel/.num_top.objs/byte -I /usr/lib64/ocaml/compiler-libs -I src/.num.objs/byte -I src/.num.objs/native -intf-suffix .ml -no-alias-deps -opaque -o toplevel/.num_top.objs/byte/num_top_printers.cmo -c -impl toplevel/num_top_printers.ml)
[   50s] Running[40]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -safe-string -strict-sequence -strict-formats -g -a -o toplevel/num_top.cma toplevel/.num_top.objs/byte/num_top_printers.cmo toplevel/.num_top.objs/byte/num_top.cmo)
[   50s] Running[41]: (cd _build/default && /usr/bin/ocamlc -w +a-4-9-41-42-44-45-48 -warn-error A -bin-annot -g -safe-string -strict-sequence -strict-formats -g -a -o src/num.cma -dllib -lnum_stubs -cclib -lnum_stubs src/.num.objs/byte/arith_flags.cmo src/.num.objs/byte/int_misc.cmo src/.num.objs/byte/nat.cmo src/.num.objs/byte/big_int.cmo src/.num.objs/byte/ratio.cmo src/.num.objs/byte/num.cmo src/.num.objs/byte/arith_status.cmo)
[   50s] error: Bad exit status from /var/tmp/rpm-tmp.GZalQn (%build)
````

### PR DESCRIPTION
**Pull request by diml**
Fixes #2789

Signed-off-by: Jeremie Dimino <jeremie@dimino.org>

### CODE REVIEW

**Comment by rgrinberg** [comment]
Looks good overall. However, why do we still have this `Lib_config.t` being passed explicitly everywhere? We are passing it whenever we create `Lib.t` values, so we should extract whatever is information is indeed from there.

**Comment by diml** [comment]
I'm having a look at this

**Comment by diml** [comment]
I tried to store it in `Lib_info.t`. It allows to remove the the `~link_config` flag of `Lib.L.compile_and_link_flags` but not `Lib.Lib_or_module.L.link_flags`. The latter is a bit more annoying, we need to add the lib config to the `Module` case which is a bit odd.

**Comment by rgrinberg** [comment]
I suppose it can always be added to the argument of `Module`. Anyway, it's not so important for this PR.

**Comment by diml** [comment]
I unbroke the parsing of `dune-package` files and updated the tests, so this should be good to go now.

**Comment by aalekseyev** [comment]
FWIW, I don't understand this PR. You say refactor, but at the same time it's supposed to fix a bug? 

Why do we need to change the dune_package format and why is it a good idea to treat the "native" archives differently from "foreign" ones?

**Comment by diml** [comment]
Previously, they were things in `foreign_archives` there were not foreign archives such as the .a file containing the natively compiled OCaml code, the `std_exit.{cmx,o.cmo}` files for the stdlib or the .so for the stubs. In a way, the `foreign_archives` field had become a dump-all field for various things. Additionally, the dependencies when linking a bytecode executable with `-output-complete-exe` (the new name for `-custom`) where not right.

So I extract the things that were not supposed to be in `foreign_archives` into separate fields, namely:
- `foreign_dll_files` for the .so files for the stubs
- `native_archives` for the .a containing the natively compiled OCaml code
- `exit_mode` for the `Std_exit` module of the stdlib

Then, when computing the link flags we decide what to depend on depending on what we are doing. 

After this split, `foreign_archives` no longer needed to be a dictionary given that the foreign archives are the same for byte/native mode. That's why the `dune-package` format changed.

**Comment by aalekseyev** [comment]
@diml, thanks. We talked in person about the specifics of the bugfix and this is the way I understood it:

- previous versions of dune didn't track dependencies of bytecode compilation on .so files (which is a bug)
- we recently fixed that, but the fix didn't work when the .so comes from an installed library (the path to .so file was not computed correctly)
- this PR removes the tracking of dependencies on .so files that come from the installed libraries. This partially re-introduces the original issue, but for installed libraries it's much more benign.

**Pull request merged**
