### PR TITLE
Move display config to scheduler

### PR DESCRIPTION
**Pull request by rgrinberg**
This breaks the dependency between dune_config and process

### CODE REVIEW

**Comment by rgrinberg** [comment]
Now dune_config no longer even needs to be in dune_engine, but I don't know where else to put it.

**Review by jeremiedimino — APPROVED** [review]
Looks good

**Comment by jeremiedimino** [comment]
Maybe in its own library?

**Comment by rgrinberg** [comment]
Yeah, why not. Now it's in its own library.

**Comment by jeremiedimino** [comment]
BTW, splitting things in libraries is nice as the relationships between the various components is more obvious. But soon we are going to need to check that the library dependencies written in Dune files are still all used, so that we can remove stale ones and ensure we can get as much parallelism as possible. That should be easy to do by looking at the imports in the output of `ocamlobjinfo`.

**Pull request merged**
