### PR TITLE
Fix #3026

### LINKED ISSUE #3026: dune cache writes merlin files to source tree with wrong umask
With dune 2.1.1 and `DUNE_CACHE=enabled`, the `.merlin` files written to the source tree end up with the following permissions:

```
 % ls -la cli/.merlin 
-rw-r--r--  1 avsm  staff  3424 12 Jan 19:49 cli/.merlin
```

This subsequently results in dune segfaulting on a second build, since it fails the write to the .merlin file as it doesn't have write permissions for the user:

```
Error: exception Sys_error("cli/.merlin: Permission denied")
Backtrace:
Raised by primitive operation at file "stdlib.ml", line 324, characters 29-55
Called from file "src/stdune/io.ml", line 184, characters 8-126
Re-raised at file "src/stdune/io.ml", line 189, characters 8-23
Called from file "src/dune/artifact_substitution.ml", line 383, characters 15-48
Called from file "src/fiber/fiber.ml", line 229, characters 16-19
Called from file "src/dune/build_system.ml", line 1637, characters 8-1023
Called from file "src/fiber/fiber.ml", line 114, characters 10-15
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters 33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
```

This doesn't happen with DUNE_CACHE disabled as the merlin files have a more permissive umask.  This may be because the daemonisation of the dune daemon called `(Unix.umask 0)` so that the `~/.cache/dune` files are read-only, but this also ends up propagating to the `.merlin` files promoted to the source tree and causes a difference in behaviour with the dune cache disabled.

### PR DESCRIPTION
**Pull request by ghost**
Mark the files promoted to the source tree as writable by the user.

### CODE REVIEW

**Comment by mefyl** [comment]
Well, so far we used the exact opposite approach : since the files can be shared between build trees (think hardlinks), we explicitely REMOVE the write permissions when promoting them. We discussed and documented that altering produced files was probably a bad idea anyway as the build should be a computational graph.

IMO I don't think we should do this, or maybe only in copy mode (as opposed to hardlink).

In any case, if we want those write permissions, we should not remove them when caching rather that re-adding them when pulling, and redocument it correctly.

**Review by mefyl — COMMENTED** [review]
Well, so far we used the exact opposite approach : since the files can be shared between build trees (think hardlinks), we explicitely REMOVE the write permissions when promoting them. We discussed and documented that altering produced files was probably a bad idea anyway as the build should be a computational graph.

IMO I don't think we should do this, or maybe only in copy mode (as opposed to hardlink).

In any case, if we want those write permissions, we should not remove them when caching rather that re-adding them when pulling, and redocument it correctly.

**Comment by diml** [comment]
Yes, for promotion to the shared cache removing write permissions is the right thing to do. Here, it is for promotion to the source tree, i.e. when we have a rule with `(mode promote)` and dune copies the targets to the source tree after building them. In such case, we don't use hardlinks and always do a plain copy instead. In this case, explicitly setting write permissions seems fine to me.

Another option to avoid #3043 would be to make dune delete the files before doing a promotion. But in any case it feels like whether we are using the shared cache or not shouldn't affect the read-only status of files copied to the source tree.

**Comment by mefyl** [comment]
Oh, absolutely then, sorry didn't notice this was about the "other" promotion. Maybe we should call the cache operation "caching a file" instead of promoting to avoid such confusion.

**Review by mefyl — APPROVED** [review]
LGTM

**Comment by diml** [comment]
Indeed, that's a good idea!

**Pull request merged**
