### PR TITLE
Cache file contents in action builder by name.

### PR DESCRIPTION
**Pull request by dkalinichenko-js**
Improve overall performance in builds by removing redundant reads. Previously, Dune was caching file contents only by callsites.

### CODE REVIEW

**Review by snowleopard — APPROVED** [review]
Thanks! Please sign your commit, by adding a line like this (but with your name/email) into the commit message:

```
Signed-off-by: Andrey Mokhov <amokhov@janestreet.com>
```

**Comment by snowleopard** [comment]
It's worth adding that in our monorepo, this change sped up null builds by the factor of 2.6x! We were reading every file 6 times on average. 

@ejgallego Could you check if this change makes Coq null builds noticeably faster?

**Comment by dkalinichenko-js** [comment]
> Thanks! Please sign your commit, by adding a line line this (but with your name/email) into the commit message:
> 
> ```
> Signed-off-by: Andrey Mokhov <amokhov@janestreet.com>
> ```

Oops, done.

**Comment by Alizter** [comment]
@snowleopard our monorepo coq-universe needs some work since we are updating the Coq version, but I'll make a note to test ASAP.

**Comment by dkalinichenko-js** [comment]
> @dkalinichenko-js There is a little benchmark in [perf.sh](https://github.com/ocaml/dune/blob/main/bench/perf.sh). Could you run it and show the results?

Unfortunately can't get the benchmark to compile on my machine, but I don't expect much improvement outside of Jane due to different build rules. Merging anyway.

**Comment by snowleopard** [comment]
> @snowleopard our monorepo coq-universe needs some work since we are updating the Coq version, but I'll make a note to test ASAP when it is functional again.

Thanks, please share the results!

**Pull request merged**
