### PR TITLE
Reproduction case for #6106.

### PR DESCRIPTION
**Pull request by rlepigre**
See #6106.

### CODE REVIEW

**Comment by rgrinberg** [comment]
This is expected and there's already a test case for this. The preprocessor needs to run from root to report errors relative to the root.

**Comment by rlepigre** [comment]
I thought you agreed there was a bug [here](https://github.com/ocaml/dune/issues/6106#issuecomment-1442179706) @rgrinberg. Have you changed your mind?

The problem is that your workspace root may not coincide with your project root in compositional builds. So, for me there still is a bug in that it should not matter whether you have a single dune project (and the workspace root is the project root) or if you have several (and the workspace root does not coincide with that of the project using ppx preprocessing).

**Comment by rlepigre** [comment]
Actually, looking at the reproduction case in this MR, it does not demonstrate the right issue, so let's just close this indeed.

**Comment by rgrinberg** [comment]
It's indeed an issue, but there's already a test for it. See `pp-cwd.t`.

**Pull request closed without merging**
