### PR TITLE
refactor: generic source tree (#7115

### PR DESCRIPTION
**Pull request by rgrinberg**
Make the source tree generic in [Load_rules]

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Review by snowleopard — APPROVED** [review]
Thanks, looks good! I don't have a good understanding of OCaml performance around first-class modules: do you know if this change might have a performance impact?

**Comment by rgrinberg** [comment]
Using first class modules is exactly equivalent to passing records of functions (and values). We lose out on inlining opportunities, but in this situation, they're not really relevant performance wise.

**Comment by rgrinberg** [comment]
Using first class modules is exactly equivalent to passing records of functions (and values). We lose out on inlining opportunities, but in this situation, they're not really relevant performance wise.

**Comment by snowleopard** [comment]
Got it, makes sense.

**Pull request merged**
