### PR TITLE
doc: remove %{first-dep} in quick-start.rst

### PR DESCRIPTION
**Pull request by cedlemo**
https://discuss.ocaml.org/t/jbuilder-to-dune-what-is-first-dep/2356/3

### CODE REVIEW

**Comment by rgrinberg** [comment]
Please read https://github.com/ocaml/dune/blob/master/CONTRIBUTING.md and sign your commit before it can be considered for merging.

**Comment by cedlemo** [comment]
@rgrinberg,

done

**Comment by rgrinberg** [comment]
Hmm, the way you signed things seems fine but the bot expects your github handle for some reason.

I'll defer to @avsm and @diml on how to handle this.

**Comment by diml** [comment]
I merged anyway, thanks for the PR

**Pull request merged**
