### PR TITLE
refactor(tui): move initialization to UI thread

### PR DESCRIPTION
**Pull request by rgrinberg**
Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Comment by Alizter** [comment]
How does making the setup lazy ensure that the UI thread will pick it up when it is evaluated?

**Comment by rgrinberg** [comment]
All of those thunks will only be forced in the UI thread.

**Review by Alizter — COMMENTED** [review]
OK, I think I get what is happening now. Another question was about the removal of the thunk on the Tui module, does this affect anything:

**Review by Alizter — APPROVED** [review]

**Comment by rgrinberg** [comment]
The generative functor argument? No, it shouldn't affect anything because there are no longer any module side effects.

**Pull request merged**
