### PR TITLE
Construct Dir.t values without a tree

### PR DESCRIPTION
**Pull request by rgrinberg**
All the work is in `File_tree.Contents`. `Readdir.of_path` will need to be memoized and some of the functions in `Contents`. Some things will need to be re-organized to make use of memoization better.

cc @aalekseyev

### CODE REVIEW

**Comment by rgrinberg** [comment]
Also, I've removed the extra flag that was used to warn about jbuild files. I think it will be simpler if we simply emit the warning every time and have a mechanism that will filter out emitted warnings.

**Comment by diml** [comment]
It seems that some commits are missing. The flag for warning about jbuild files is still present for instance.

**Comment by aalekseyev** [comment]
I forget what it's about and I'm assuming it's not ready for review. I'm removing myself from reviewing set.

**Comment by rgrinberg** [comment]
There's a more recent PR attempting to do the same thing.

**Pull request closed without merging**
