### PR TITLE
Windows watch mode: fix a small race condition, re-enable tests

### PR DESCRIPTION
**Pull request by nojb**
This PR contains a small fix for the Windows watch mode #7010 that can result in some notifications being lost when they arrive immediately after the watched directory is added. It also re-enables a unit test for this watcher backend.

### CODE REVIEW

**Comment by rgrinberg** [comment]
@MisterDA could you take a look?

**Comment by nojb** [comment]
Description of the changes for the prospective reviewer:
1) when adding a new directory, the OCaml thread sends a message to the native thread to do the actual addition. This means that there is a delay between calling `Fswatch_win.add` and the actual start of the monitoring. This can cause some events to be missed if the events arrive very quickly after calling `Fswatch_win.add` (this was the case in the unit test). To fix this, we make sure that `Fswatch_win.add` does not return until monitoring is actually started in the other thread. We communicate this fact using an event object (`afterAdd`).
2) For the same reason, it is not a good idea to pass relative paths to `Fswatch_win.add` (as the current directory could change between the call to `Fswatch_win.add` and the actual point in time when monitoring starts). Of course with 1) this should not happen, but for extra safety I enforce that directories passed to `Fswatch_win.add` be absolute (this is the case in current Dune codebase).

**Comment by jonahbeckford** [comment]
Just saw this. Will have a review tomorrow.

**Comment by nojb** [comment]
@emillon this one can go in 3.7.1.

**Pull request merged**
