### PR TITLE
Add dune-merlin-ppx_expect test

### PR DESCRIPTION
**Pull request by jberdine**
Test case for interop between dune and merlin when ppx_expect is used.

### CODE REVIEW

**Comment by voodoos** [comment]
Added a `run.t` file to actiavate the test.
It is failing because it needs Merlin master.

**Comment by jberdine** [comment]
The test output has timing stats in it, which makes this test, as an expect test, not useful. Is there an better way to do this that avoids time stats?

**Comment by voodoos** [comment]
You can filter-out Merlin's output with `jq`: 
`ocamlmerlin ....... | jq '.value'`

And if we add that test to the suite we should to add `conf-jq` to the test-deps in  the Makefile.

**Comment by rgrinberg** [comment]
Please re-open if this is still relevant

**Pull request closed without merging**
