### PR TITLE
Block strings + remove block/sexp comments

### PR DESCRIPTION
**Pull request by diml**
This PR proposes two changes in the syntax of dune files. The syntax of jbuild files is untouched.

### 1. Remove block/sexp comments

These were pretty much never used and they make the lexical conventions of the language more complicated. I think end of line comments are enough.

### 2. Add block strings

It is currently painful to write blocks of text in dune files as there is no syntax for raw strings where things don't need to be escaped. I find the usual syntax used in programming languages for raw strings quite painful as it's impossible to indent blocks of text properly. This PR proposes a syntax for *block* or *end of line* strings which solves this problem.

The syntax is as follow: everything that appears after a `"\|` on a line is a string. If the next line starts with spaces and `"\|` again, it is the continuation of the string. For readability, we require that this delimiter is either followed by a newline or one space that is ignored. Escape sequences are still interpreted interpreted, however it is possible to disable this behavior on a line by line basis by using `"\>` rather than `"\|`. In the end, a block of text looks like this:

```(alias
 ((name new)
  (action (echo "\| ARFLAGS=rsc
                "\| CXX=g++
                "\| CXXFLAGS="-Wall -O3 -g -pthread"
                "\| if ! ${ARCH_SIXTYFOUR}; then
                "\|   CXX="$CXX -m32"
                "\| fi
                "\| ${MAKE} -s -C libre2 clean
                "\| ${MAKE} -s -C libre2 \
                "\|   ARFLAGS="$ARFLAGS" \
                "\|   CXX="$CXX" \
                "\|   CXXFLAGS="$CXXFLAGS" \
                "\|   obj/libre2.a obj/so/libre2.so
                "\| cp libre2/obj/libre2.a libre2_c_stubs.a
                "\| cp libre2/obj/so/libre2.so dllre2_c_stubs.so
                "\| ${MAKE} -s -C libre2 clean
))))
```

Which IMO is much nicer that what we had to write previously:

```
(alias
 ((name old)
  (action (echo "\
ARFLAGS=rsc
CXX=g++
CXXFLAGS=\"-Wall -O3 -g -pthread\"
if ! ${ARCH_SIXTYFOUR}; then
  CXX=\"$CXX -m32\"
fi
${MAKE} -s -C libre2 clean
${MAKE} -s -C libre2 \
  ARFLAGS=\"$ARFLAGS\" \
  CXX=\"$CXX\" \
  CXXFLAGS=\"$CXXFLAGS\" \
  obj/libre2.a obj/so/libre2.so
cp libre2/obj/libre2.a libre2_c_stubs.a
cp libre2/obj/so/libre2.so dllre2_c_stubs.so
${MAKE} -s -C libre2 clean
"))))
```

I chose this syntax since it doesn't reserve another character.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Is it ok to allow mixing `"\>` and `"\|` in the same block comment? this seems to be allowed in the current implementation.

**Comment by diml** [comment]
Yes, that's was my intention. It seems to me that there is no reason to force the whole block to be the same and allowing to mix can be useful.

**Comment by diml** [comment]
I thought the regexp would be similar to the one for comments. @/cc Chris00

I'll update the manual to document the new syntax.

**Comment by diml** [comment]
I rewrote the documentation for the syntax. I removed the references to OCaml and fully explained the language instead.

**Comment by Chris00** [comment]
> emacs highlighting can't really handle this escaping scheme because of their primitive regex based highlighting

I think it will be necessary to use [syntax properties](https://www.gnu.org/software/emacs/manual/html_node/elisp/Syntax-Properties.html) to support these “one line strings” but that should be doable.

**Comment by diml** [comment]
Ok, good to know it should be doable. I'm merging this then. We'll need to have another pass on the manual before the 1.0.0, we can tweak the doc more at this point if needed.

**Pull request merged**
