### PR TITLE
[dunerpc] use log notification for errors

### PR DESCRIPTION
**Pull request by rgrinberg**
report errors that aren't request specific using the log notification

Perhaps this notification should be switched to "error"?

### CODE REVIEW

**Comment by jeremiedimino** [comment]
What errors are we talking about here?

**Comment by rgrinberg** [comment]
> What errors are we talking about here?

There's some examples in this PR. The gist of it is errors that are related to invalid notifications. For example:

* Invalid notification method names
* Notifications being sent before a version is negotiated with the initialization request

What these have in common is that there's no request id we can attach the error to.

**Comment by jeremiedimino** [comment]
So IIRC, these are errors related to the RPC machinery. For instance because one side of the connection is not respecting the protocol. Is that correct? What do we do in such a case? I'd expect that the other side logs and error and immediately closes the connection. No point continuing a software-to-software communication if the two softwares don't agree on how to talk to each other.

**Comment by rgrinberg** [comment]
> So IIRC, these are errors related to the RPC machinery. For instance because one side of the connection is not respecting the protocol. Is that correct? What do we do in such a case? I'd expect that the other side logs and error and immediately closes the connection. No point continuing a software-to-software communication if the two softwares don't agree on how to talk to each other.

Sure, I could add that. I suppose we could rename the callback to `fatal_error` or something?

I still think that a logging notification that the server can send to the client is useful.

**Comment by jeremiedimino** [comment]
> Sure, I could add that. I suppose we could rename the callback to `fatal_error` or something?

Sounds good.

> I still think that a logging notification that the server can send to the client is useful.

Agreed.

**Comment by jeremiedimino** [comment]
So in the end, we are thinking: the server observes a fatal error, it sends an error to the client and closes the connection. Is that correct?

Should we still call such a message a "log" or just an "abort" message?

**Comment by rgrinberg** [comment]
> So in the end, we are thinking: the server observes a fatal error, it sends an error to the client and closes the connection. Is that correct?

Yes.

> Should we still call such a message a "log" or just an "abort" message?

`abort` sounds like a better way. I'll add the following callback `abort:(message:string -> payload:Sexp.t option -> unit Fiber.t)` for the fatal error.

**Comment by rgrinberg** [comment]
I added an abort notification.

**Review by jeremiedimino — APPROVED** [review]

**Pull request merged**
