### PR TITLE
feature: allow using bigarray in bootstrap

### PR DESCRIPTION
**Pull request by rgrinberg**
this is in preparation for the source fetching PR

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Review by nojb — COMMENTED** [review]
Does this work in recent versions of OCaml (where `bigarray` does not exist anymore)?

**Comment by rgrinberg** [comment]
Good point. Fixed for 5.0

**Review by nojb — COMMENTED** [review]
The `Bigarray` module was moved to the standard library in 4.07. Dune requires 4.08 and later. Do we need the `bigarray` library at all?

**Comment by rgrinberg** [comment]
Oh, I guess not.

**Pull request closed without merging**
