### PR TITLE
Allow stanzas in dune-project file

### PR DESCRIPTION
**Pull request by diml**
This PR makes it possible to write normal stanzas such as `library` or `executable` in the `dune-project` file. This way, one can merge the `dune` and `dune-project` files at the root of the repository. This avoids the proliferation of dune configuration files at the root of the project.

A necessary step was to allow to have multiple dune files per directory. In particular, this PR allows to have both a `jbuild` and `dune` file in the same directory.

I merged the `dune` and `dune-project` files in a few tests, this should be enough to test this feature.

### CODE REVIEW

**Comment by rgrinberg** [comment]
The feature looks fine. Why do we need multiple file per directory? AFAIK, people are mostly asking for the opposite feature here. A single dune file that covers multiple directories.

**Comment by diml** [comment]
It's for when we automatically create the dune-project file. If the user starts by writing a dune file and then dune creates the dune-project file, then we end up with two dune files in the same directory. One possibility would be to copy thr contents of the dune file in the dune-project file and delete the dune file. But that might be a bit surprising

**Comment by diml** [comment]
Alternatively we could disallow a dune-project file with stanzas and a dune file. so you'd be allowed both as long as the dune-project file doesn't have stanzas. That seems better actually

**Comment by emillon** [comment]
It seems weird to me to mix these two kind of files. If it's not possible to add stanzas, each file has a clear role. If `dune-project` can contain stanzas, the situation is less clear:
- `dune-project` can contain more things than `dune`, so it's impossible to rename or copy `dune-project` to `dune` (when extracting a library for example)
- it's impossible to have two `dune-project` files in the same project, so one has to learn how to properly use multiple `dune` files.

So, in a lot of cases it seems that one will have to manipulate both kind of files and in addition also need to understand the exceptions where you can put stanzas in `dune-project`. That seems confusing to me.

That being said, I agree that it would be great to have a single kind of file but that seems difficult without scanning all the `dune` files.

**Comment by diml** [comment]
I hadn't considered these. It's true that it's a bit confusing.

> That being said, I agree that it would be great to have a single kind of file but that seems difficult without scanning all the dune files.

We discussed this quickly at some point, but there are several issues with having only one kind of files. For instance we couldn't identify projects just by looking at the FS, we'd indeed need to read and interpret `dune` files, which is not great. My feeling is that it's better for dune and other tools if the boundaries of a project are simple to figure out. Additionally, many things are scoped at the level of projects in order to allow vendoring, and IMO it's clearer if the scopes appear in the file-system.

Another option here would be to allow explicitly *embedding* a dune file in a dune-project. For instance via a separator:

```
(lang dune 1.0)
(using menhir 1.0)

--dune--

(library ...)
```

**Comment by diml** [comment]
I'm closing this PR for now

**Pull request closed without merging**
