### PR TITLE
    Add tests for (lint)

### PR DESCRIPTION
**Pull request by emillon**
Linters are ppx rewriters that can be used in two ways:

- there is a `@lint` alias that will run these and discard the output. Warnings from their standard output will be displayed.
- when using ppxlib, there is a rewrite feature that is integrated with `dune promote`.

### CODE REVIEW

**Comment by emillon** [comment]
This is now ready.

**Comment by diml** [comment]
BTW, the ppxlib feature works even when used as a preprocessor.

**Comment by emillon** [comment]
Yes, that did not seem to be in the spirit of ppxlib. In particular, I wasn't able to use `~lint_impl` because it emits a preprocessor warning instead. Is there a more idiomatic way to demonstrate `.lint-corrected`?

**Comment by diml** [comment]
I suppose you could use ~lint_impl and return an empty list of errors. One usage of generating correction in the preprocessing phase is `[@@deriving_inline]`. For instance if you write:

```
type t = X [@@deriving_inline sexp]
[@@@end]
```

then ppxlib will generate a corrected file with the generated code for `[@@deriving sexp]` in between the two attributes. This is useful either as a linting step (to avoid dependency on the ppx rewriter) or during normal preprocessing to debug errors coming from the code generated by ppx rewriters.

**Comment by emillon** [comment]
Thanks! I'm merging this for now, I might add tests for ppx corrections later.

**Pull request merged**
