### PR TITLE
Move the window of supported OCaml version forward

### PR DESCRIPTION
**Pull request by diml**
- drop support for 4.06
- do the CI testing with 4.09

Cleaned up a bit the code after dropping support for 4.06:
- we can now rely on the existence of `Stdlib` so we no longer need `Dune_caml`
- use `Stdlib` instead of undeprecating `Pervasives`
- cleanup a few other compat stuff, such as the Filename module

Signed-off-by: Jeremie Dimino <jeremie@dimino.org>

### CODE REVIEW

**Comment by rgrinberg** [comment]
Can we disable CI for 4.09 for now? odoc isn't yet ported.

**Comment by diml** [comment]
Hmm, that's odd. I have it installed on my system with 4.09. There are quite a few errors with building the doc though.

Anyway, merlin not being available for 4.09 is a blocker to move the development to 4.09. So let's wait for merlin first.

**Comment by diml** [comment]
Merlin and odoc seems supported now, so we can move forward with this!

**Comment by diml** [comment]
I don't understand what's going on with odoc. I can install it just fine with 4.09 on my machine but the CI is refusing to do the same. /cc @dra27 in case you have an idea what's going on

**Comment by dra27** [comment]
Travis installs a specific version of odoc specified in the `ODOC` variable - it still had 1.4.1 specified. I've changed it to `odoc` and added a comment above - it seems better to install the latest version by default and only specify a specific version if we have a problem with the latest and need to unblock CI. However, it's not clear to me why it was necessary to force installation of latest odoc in 0e4278b, @rgrinberg?

**Comment by dra27** [comment]
SPECTRUM IS GREEN!

**Comment by diml** [comment]
Awesome, thanks @dra27! I didn't know about the `ODOC` variabe. I guess the intent is to prevent the CI from installing an old version which would return a different set of errors/warnings. Does opam allow `opam install odoc>=1.4.2`?

**Comment by diml** [comment]
Just tested and that seems to work, I propose to do that then

**Comment by diml** [comment]
Just pushed a commit to do that

**Pull request merged**
