### PR TITLE
Use a formally verified incremental cycle detection algorithm

### PR DESCRIPTION
**Pull request by Armael**
This PR proposes to replace the current implementation of the incremental cycle detection algorithm implemented in dune (described in https://dl.acm.org/citation.cfm?doid=2846106.2756553).

This is joint work with @jhjourdan, @charguer and @fpottier.
Our new OCaml implementation has been formally verified using Coq, including both its *functional correctness* and *asymptotic complexity*. It is described in the following [blog-post](http://gallium.inria.fr/blog/incremental-cycle-detection/) (shortly) and [article](http://gallium.inria.fr/~fpottier/publis/gueneau-jourdan-chargueraud-pottier-2019.pdf) (in greater details).

The verified OCaml code and Coq proofs are [available online](https://gitlab.inria.fr/agueneau/incremental-cycles), this PR is simply vendoring the code into dune and implementing a thin plumbing layer on top of it.

Interestingly, the verified code is also faster (due to one algorithmic improvement as well as generally more cautious code). Replaying the trace produced by building [ocaml-platform](https://github.com/avsm/platform) shows a [7x performance improvement](https://gist.github.com/Armael/966bb2d0b2ab8e5fa693c922b05f81d1)!
Note that, while this is nice, it won't impact too much dune's running time in practice, since the algorithm takes only a fraction of dune's running time (around 10% with the current one).

------

Technical matters: 

I'm currently stuck with the vendoring setup, because it seems the `dag` library in `src/dag` does not see the `incremental_cycles` library in `vendor/incremental-cycles`. 
Is this supposed to work? If not, what should I do?

### CODE REVIEW

**Comment by diml** [comment]
Ah, it's because of the bootstrap. The bootstrap step doesn't read dune files, there is a micro build system in `bootstrap.ml`. There are several solutions, however looking at the code in vendor/incremental-cycles, I'm not sure I understand why this is needed. Maybe it's only useful in the upstream repository but not when vendored inside dune? In this case, I suggest to do code generation when vendoring the project and just commit the result.

**Comment by Armael** [comment]
Ah, I see. The weird build rules are workarounds for limitations in our verification tool. We're not really able to verify the code as an ocaml functor, even though this is how we want to distribute it.
Verification is done on the code without the functor, and then the custom rule "packages" it by wrapping the code with `module Make (...) = struct ... end`.

Indeed, it is also fine to do the code generation at vendoring time, and commit the result.

**Comment by Armael** [comment]
I think this is good for review now.

**Comment by diml** [comment]
Ok. Could you rebase your PR? There was a bug in the travis script causing failures to be hidden. Rebasing should fix it and we should see the proper failure.

BTW, the argument of the functor in dag.ml looks pretty generic. Do we really need a functor in `Incremental_cycles`?

**Comment by Armael** [comment]
Rebased. I'm confused because the tests all pass on my computer...

> BTW, the argument of the functor in dag.ml looks pretty generic. Do we really need a functor in Incremental_cycles?

The algorithm is currently published as a functor because we really did the verification against an abstract graph interface: we really wanted to make the algorithm reusable on any kind of (possibly pre-existing) graph users might have. Also, I think they are always various trade-offs when choosing a particular graph implementation, so it's hard to come up and provide a one-size-fits-all implementation.

Here, I agree the instantiation is not particularly interesting. I also agree there would be some value in publishing pre-instantiated versions of the algorithm on specific graph implementations for convenience. But I'd like to do it without resorting to more sed-like macros -- maybe this could be done another time?

**Comment by diml** [comment]
Sure, that seems fine. For the test, it seems to be a printing problem, I'm observing the issue on my computer as well. Not sure why the behaviour is different on your computer :/

Could you revert the change to `test/unit-tests/tests.mlt`? I'll merge after that

**Comment by Armael** [comment]
Thanks! I just reverted the change.

**Comment by diml** [comment]
Merged, thanks again for this!

**Comment by Armael** [comment]
Great! Thanks!

**Comment by avsm** [comment]
a 7x speedup in the cycle detection on large codebases? That's amazing :-) Nice work!

**Pull request merged**
