### PR TITLE
Reproduction case for #2228

### PR DESCRIPTION
**Pull request by rgrinberg**
@aalekseyev from a brief glance, this looks related to some of the changes you've made.

### CODE REVIEW

**Comment by rgrinberg** [comment]
This case also reveals a small flaw in opam-installer. It will install partial packages. That seems undesirable to me.

**Comment by aalekseyev** [comment]
I'll have a look, thanks for the reproduction.

**Comment by aalekseyev** [comment]
This must be the stale artifact deletion.
Building `@runtest` ends up deleting the entire `_build/install/default/lib/foobar` directory.
I think that happens because the rules for that directory aren't forced, so the directory isn't added to `build_dirs_to_keep`, so it's removed when generating rules for `_build/install/default/lib`.

**Comment by aalekseyev** [comment]
I'm going to have a look at making the list of buildable subdirectories computed deterministically instead of relying on the side-effect.

**Comment by rgrinberg** [comment]
@aalekseyev shall we merge this test case or are you planning to push to this branch?

**Pull request merged**
