### PR TITLE
Add doc for coqdoc support

### PR DESCRIPTION
**Pull request by Alizter**
This is the doc for #5695 <s>and relies on #5755 so draft for now.</s>

### CODE REVIEW

**Review by christinerose — CHANGES_REQUESTED** [review]

**Review by ejgallego — APPROVED** [review]
Great, thanks.

We need to investigate if that works OK for `coq-universe`

**Comment by ejgallego** [comment]
Another question is opam integration.

**Comment by ejgallego** [comment]
Needs rebase.

**Comment by Alizter** [comment]
@ejgallego Done.

**Pull request merged**
