### PR TITLE
[2.9] Bump dune lang to 2.9 and fix build and tests on 4.12

### PR DESCRIPTION
**Pull request by voodoos**
This is needed for some Dune main backports such as #4480 

@jeremiedimino: I don't remember, do I need to update the opam file and Dune's dune-project ?

### CODE REVIEW

**Comment by voodoos** [comment]
I also updated ocamlformat to match main branch.

**Comment by rgrinberg** [comment]
> I don't remember, do I need to update the opam file and Dune's dune-project ?

Not sure what you mean here.

**Comment by ejgallego** [comment]
I think @voodoos means the line:
```lisp
(lang dune 2.8)
```
in dune's own dune-project; I guess this applies to tests so yes.

Pity tho, as currently I can use opam dune to build dune's `main` branch, which is very useful as for some reason `merlin` is broken in my setup if I do use the bootstrap dune instead [likely worth reporting and investigating]

**Comment by rgrinberg** [comment]
> in dune's own dune-project; I guess this applies to tests so yes.

I see. If you need to use 2.9 for tests, then it's fine to bump it.

> Pity tho, as currently I can use opam dune to build dune's main branch, which is very useful as for some reason merlin is broken in my setup if I do use the bootstrap dune instead [likely worth reporting and investigating]

Yes, we absolutely need to investigate. It would be a much bigger misfortune if 2.9 shipped with broken merlin support.

**Comment by ejgallego** [comment]
> Yes, we absolutely need to investigate. It would be a much bigger misfortune if 2.9 shipped with broken merlin support.

My guess is that merlin is calling dune in opam which doesn't work if I built dune with the bootstrap one; I'll file a bug report.

But indeed it would be cool if we could keep tests a bit more separate so the version in `dune-project` would the actual one needed to build dune [or maybe that's a bad idea, I dunno, not an expert on compiler boostrappign]

**Comment by voodoos** [comment]
> Pity tho, as currently I can use opam dune to build dune's `main` branch, which is very useful as for some reason `merlin` is broken in my setup if I do use the bootstrap dune instead [likely worth reporting and investigating]

Can you check that you are using the lastest released dune in your switch? (2.8.5)

The marshalled data-structure changed in 2.8.4 so Merlin configuration generated by dune < 2.8.4 are not readable by dune main and vice-versa. This is usually not an issue except for Dune devs who use a different version (`dune.exe`)  to build the project and the dune from their switch to read the config.

**Comment by ejgallego** [comment]
> The marshalled data-structure changed in 2.8.4 so Merlin configuration generated by dune < 2.8.4 are not readable by dune main and vice-versa.

Oh that was it, thanks a lot and sorry for the noise.

**Pull request merged**
