### PR TITLE
Make foreign archives rules more robust

### PR DESCRIPTION
**Pull request by snowleopard**
Previously the foreign archives rule would fail on platforms where dynamic linking is not supported, even if the dynamic library wasn't required by any other build rules (which would likely be the case).

This patch decouples building of static foreign libraries from dynamic foreign libraries, at the cost of running `ocamlmklib` twice where both libraries are required.

### CODE REVIEW

**Comment by rgrinberg** [comment]
> Previously the foreign archives rule would fail on platforms where dynamic linking is not supported

Is it possible to just detect this case using `ocaml -config` and the `supports_shared_libraries` variable?

**Comment by rgrinberg** [comment]
Actually, do we have some numbers for how useful this optimization is in practice? If the gains are not significant enough, then we might as well just drop it and simplify our code to boot.

**Comment by snowleopard** [comment]
> Is it possible to just detect this case using `ocaml -config` and the `supports_shared_libraries` variable?

I guess we could, but not sure it's worth it -- the only benefit is the ability to give an error message earlier, before the corresponding rule fails? Or did you have something else in mind?

> Actually, do we have some numbers for how useful this optimization is in practice? If the gains are not significant enough, then we might as well just drop it and simplify our code to boot.

Which optimisation are you referring to? Here is the current one:

https://github.com/ocaml/dune/blob/80c43b976b54de86cad542c13285661d92ca20f2/src/dune/lib_rules.ml#L241-L256

It doesn't cost us much in terms of complexity, but does make the common case (building OCaml libraries) fast.

However, the additional optimisation mentioned in the comment of this PR will only speed up the uncommon case of foreign libraries, and will most likely require changing the internals of Dune (to allow for "optional targets"), and it may indeed be too costly complexity-wise.

**Comment by snowleopard** [comment]
> > Is it possible to just detect this case using `ocaml -config` and the `supports_shared_libraries` variable?

> I guess we could, but not sure it's worth it -- the only benefit is the ability to give an error message earlier, before the corresponding rule fails? Or did you have something else in mind?

Answering my own question: I guess we could also use this information to set `build_targets_together` to true in the foreign libraries case. Given that this is an uncommon case, not sure it's worth doing it in this PR.

**Comment by aalekseyev** [comment]
I think the current state is reasonable:
- for the library case we're not changing behavior because it's tricky to think about platforms that we don't even know how to test as the risk of breaking something is high
- for the foreign_library case we're introducing something that's relatively simple and yet should be robust; the fact that it does not depend on ocaml config seems good to me.

**Comment by ygrek** [comment]
ftr there are cases when ocaml supports dynamic libraries, but the foreign code doesn't due to some stupid internal reasons. It is good to be able to specify this explicitly when needed

**Comment by snowleopard** [comment]
@ygrek Feel free to create an issue, including more details so we could try to reproduce.

**Comment by ygrek** [comment]
but I understand the proposed behaviour was implemented, I am just expressing my support for it. Anyway I first need to upgrade to 2.0.0 to experience it :)

**Comment by snowleopard** [comment]
I see, I hope 2.0 will work well for you! If not, don't hesitate to ping us.

**Pull request merged**
