### PR TITLE
Remove `files_to_install` argument from gen_rules

### PR DESCRIPTION
**Pull request by gridbugs**
It appears that all the dependencies that would be added by this function
are already added by the `define_all_alias` function.

Signed-off-by: Stephen Sherratt <stephen@sherra.tt>

### CODE REVIEW

**Comment by gridbugs** [comment]
I'm trying to figure out if I've missed something. The generated <package>.install file will depend on all the files to 
be installed already, and this file gets picked up by `define_all_rules` when generating the dependencies for the `all` alias, so it already depends on all installed files without needing to add them explicitly.

**Comment by rgrinberg** [comment]
The following test case might demonstrate the difference in behavior:

```
$ cat >dune-project <<EOF
> (lang dune 3.0)
> (package (name foo))
> EOF
$ cat >sub/dune <<EOF
> (install
>  (section share)
>  (files ../foo))
> EOF
$ dune build @sub/all`
```

The last build command would not build `foo` i believe.

**Comment by gridbugs** [comment]
Ah yep, this was a case that I missed. Thanks!

**Comment by rgrinberg** [comment]
Could you submit a test case for this? This behaviour is a bit subtle, so it would be good to have it recorded in the tests

**Comment by rgrinberg** [comment]
@gridbugs did you have a chance to look at the test?

**Comment by gridbugs** [comment]
Oh I missed this comment. I'll take a look now!

**Comment by gridbugs** [comment]
There's already this test: https://github.com/ocaml/dune/tree/main/test/blackbox-tests/test-cases/all-alias/install-stanza.t
It exercises that the `subdir/@all` target depends on files listed in the install stanza in `subdir/dune`. Is that sufficient? Does it matter that the install stanza doesn't list files located in the parent directory?

**Pull request closed without merging**
