### PR TITLE
Upgrade to OCamlformat 0.26.1

### PR DESCRIPTION
**Pull request by Julow**
The aim of this preview is to gather feedback.

This is a bug-fix release and is compatible with the slightly changed let-binding syntax in OCaml 5.1. Changelog can be found here: https://github.com/ocaml-ppx/ocamlformat/blob/main/CHANGES.md

The diffs are intended changes made to the janestreet profile.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Thanks. Does this include all the JS patches? Or is there still more to come?

**Comment by Julow** [comment]
OCamlformat has been released a week ago. This is ready to be merged.

**Comment by Alizter** [comment]
@Julow does the ocamlformat releases so I would assume yes.

**Comment by Alizter** [comment]
Once ocmalformat has been added to nixpkgs you can update the flake with `nix flake update` and the format job should work. Since it takes some time for nixpkgs to catch up you can point our build input for nixpkgs directly to your nixpkgs PR.

**Comment by Julow** [comment]
I should have done that sooner! Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/257454
I'll update once this is merged.

**Comment by emillon** [comment]
Great! Please open a PR updating just the necessary input and we can get this one merged. Thanks

**Comment by Alizter** [comment]
@emillon The PR updating nix will have to be this one since the format job uses that version of ocamlformat.

**Comment by emillon** [comment]
I don't think that's correct? For #8064 I extracted #8311 first.

**Comment by Julow** [comment]
OCamlformat has been merged in nixpkgs last week, I updated this PR.

**Comment by emillon** [comment]
Thanks!

**Pull request merged**
