### PR TITLE
[rpc] Introduce end to end tests for dune_rpc

### PR DESCRIPTION
**Pull request by rgrinberg**
I chose to implement the tests in Lwt for a few reasons:

* This is a common library used by end users. It would be good to make sure that
  everything works with Lwt.
  
* Lwt library is mature enough to organize the process handling required to test
  this. 
  
* Implementing tests like this in cram is much less practical than I thought.
  Shell scripting isn't sufficient to write complex tests. This is one reason
  why don't yet have tests for watch mode for example. It's much easier to write
  complex tests like this in OCaml.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Actually, perhaps we should move the `Lwt` based `Fiber` into a library that users can use. We'll keep it private, so if users want to use it they should vendor it, but I think it would still be useful. Providing the fiber implementation isn't trivial as we can see from my implementation.

**Comment by rgrinberg** [comment]
@cwong-ocaml you might be interested in this as well. It should be straightforward to port the code here to Async.

**Comment by jeremiedimino** [comment]
> Actually, perhaps we should move the Lwt based Fiber into a library that users can use. We'll keep it private, so if users want to use it they should vendor it, but I think it would still be useful. Providing the fiber implementation isn't trivial as we can see from my implementation.

The functor that takes the different fiber implem is public right? In that case, we could make the Lwt version public as well. We should provide it as a separate package, so that we don't add a hard-dependency on Lwt.

**Comment by jeremiedimino** [comment]
I've swapped the reviewer from me to @cwong-ocaml. @cwong-ocaml given that you are working with the RPC, it'd be good for you to familiarise yourself with the whole stack.

**Comment by rgrinberg** [comment]
> The functor that takes the different fiber implem is public right? In that case, we could make the Lwt version public as well. We should provide it as a separate package, so that we don't add a hard-dependency on Lwt.

I hesitated to do it because I knew it would require an ungodly amount of signature copy pasting. I ended up doing it anyway, as the benefits to users is definitely non trivial.

**Comment by rgrinberg** [comment]
@cwong-ocaml the code is ready for review.

@jeremiedimino this PR creates a bit of an issue in CI. Since we're now testing watch mode, dune is trying to spawn `fswatch` which does not exist in CI. I see a couple workarounds for this:
* Install fswatch/inotifywait in CI.
* Create a fake fswatch/inotifywait and an option in dune to point to it.

**Review by cwong-ocaml — APPROVED** [review]
No objections here

**Comment by jeremiedimino** [comment]
@rgrinberg what would the fake fswatch/inotifywait tool do?

**Comment by rgrinberg** [comment]
>  what would the fake fswatch/inotifywait tool do?

Nothing much really. For the purposes of this test at least, there's no need restart the build if the sources change.

**Comment by jeremiedimino** [comment]
I see. The fake watcher seems like a good idea then, as we will have more control over it, which is good for tests.

> an option in dune to point to it.

You could also have a special value for this option to mean "no file watcher". Then you don't even need to implement the fake watcher.

**Pull request merged**
