### PR TITLE
chore(Source_tree): remove dead code

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Review by snowleopard — APPROVED** [review]
👍

**Review by snowleopard — CHANGES_REQUESTED** [review]
Actually, hang on. I found a use-use internally. Could we instead add a comment to the `mli` saying that the function is used internally at Jane Street?

**Comment by rgrinberg** [comment]
What about you guys just move the implementation to your own codebase? As far as I can tell, it relies on only public API's.

**Comment by snowleopard** [comment]
> What about you guys just move the implementation to your own codebase? As far as I can tell, it relies on only public API's.

We could do that but importing upstream changes has been quite painful recently, so I'd prefer to keep our patch small. Also, leaving this function in the API with a "please don't change" comment might catch some internal changes that would break our implementation (e.g. imagine the type of `sub_dirs` changing).

**Comment by rgrinberg** [comment]
We discussed this in the meeting. I'll re-phrase what I said there:

I'm really sympathetic to the issue of staying up to date with dune, and I'm happy to keep temporary workarounds to make it easier for you. But at the end of the day, leaving fortune cookies marking what's used at janestreet isn't going to work long term. We should instead strive for a long term stable API and then be very careful with changing it.

**Comment by snowleopard** [comment]
> leaving fortune cookies marking what's used at janestreet isn't going to work long term

Why not? It's not like we have dozens of such "currently used only at JS" functions, so it doesn't seem like a big deal to me. 

> We should instead strive for a long term stable API and then be very careful with changing it.

Sounds good. How do I declare this function as part of this stable API?

**Comment by rgrinberg** [comment]
> Why not? It's not like we have dozens of such "currently used only at JS" functions, so it doesn't seem like a big deal to me.

Sure, but isn't the goal is to reduce the amount of work it takes you to update dune inside janestreet? I'm sure there are plenty of things that you rely on that end up changing frequently just because of unrelated changes to the rest of dune.

 > Sounds good. How do I declare this function as part of this stable API?

I guess now is a good time to ask what you think of the goal in [this ticket](https://github.com/ocaml/dune/issues/3571) and what should follow after its completion. In my mind, once we finish the public API, it would be completely written down in `dune_engine.mli`. Then, changes to this API wouldn't be something that we'd do lightly and we'd have some system in place (specifics are TBD) for breaking changes.  For example, we wouldn't just remove things, but perhaps deprecate them first.

I suppose that one good property I'd like our public API to have is minimalism. In other words, if something can be reasonably implemented on top of our API - without performance penalties, loss of abstraction, approximately the same amount of code, etc, then it likely does not belong in the public API. So I'd prefer if there was no way to mark a function that is only used at janestreet as part of the stable API if it's possible to maintain it outside of the engine without obvious downsides.

**Pull request closed without merging**
