### PR TITLE
line edits for goals.rst

### PR DESCRIPTION
**Pull request by christinerose**
Signed-off-by: Christine Rose <professor.rose@gmail.com>

Mostly line edits and tightening syntax with active verbs. Changed "friend communities" to "functional language communities," as friend communities sounded awkward to my ears. Perhaps friendly communities if functional language communities aren't accurate. 

Hope my suggestions help!

### CODE REVIEW

**Comment by rgrinberg** [comment]
We probably want to include communities such as mirage as well. In which case "functional language communities" isn't quite precise. I'm unable to come up with better suggestions at the moment.

**Comment by christinerose** [comment]
Understood! I'll change it back to 'friendly'

**Comment by rgrinberg** [comment]
> or how about "associate communities" or "associated communities"?

Perhaps "neighbouring communities"? In any case, I'll accept any word at this point. Just let me know when you think this is ready and I'll merge.

**Comment by christinerose** [comment]
Okay! Done!
Changed it to 'neighboring communities'

**Comment by rgrinberg** [comment]
Merged. Thanks

**Pull request closed without merging**
