### PR TITLE
foreign libs: protect against undefined symbols by placing last on th…

### LINKED ISSUE #3640: Linking order: foreign libraries should be passed as late as possible on the command-line
I have a stanza of the form
```
(executable
 (name fastmath_unit_test)
 (foreign_archives ../intel/intelmath
                   fastmath)
 (foreign_stubs
  (language c)
  (include_dirs ../bindings)
  (names fastmath-caml))
 (modules fastmath fastmath_unit_test))
```
where `fastmath-caml` contains references to functions defined in one of the foreign libraries, `fastmath`. The linking step fails due to undefined references to these functions (under Linux). As far as I can see it is due because in the linking step, `libfastmath.a` appears before than `fastmath-caml.o` in the command-line and the GNU linker discards any symbol from `libfastmath.a` that is not needed *when it sees the archive*.

To avoid this problem, I think it would be a good idea to pass foreign libraries as late as possible in the command line. The relevant code seems to be https://github.com/ocaml/dune/blob/a58aa6ea03f7e157694f5e46e588771503c58f46/src/dune/exe.ml#L155-L176
(where the foreign libraries are passed in `link_args` and the foreign stubs in `o_files`).

cc @snowleopard

### PR DESCRIPTION
**Pull request by nojb**
Fixes #3640 cc @snowleopard 

This places foreign libraries (contained in the `link_args` argument) last on the command-line to try to guard against the GNU linker's propensity to discarding symbols which are deemed unnecessary when processing libraries. This works in simple examples (eg the included test), but am not 100% sure that this may not have other side-effects, so careful review is encouraged :)

### CODE REVIEW

**Comment by snowleopard** [comment]
@nojb Thanks for the fix! We discussed this today and two questions came up:

* @jeremiedimino asks: can we currently build any projects depending on `re2`? It seems their linking may be affected by this issue too. It would be nice to confirm this and check if this fix works for `re2` too.
* @aalekseyev notes that it's not ideal that foreign stubs can't declare explicit dependencies on foreign archives. In the test you added, it would have been nice to declare the dependency, e.g.:
    ````
    (executable
      (name main)
      (foreign_archives lib)
      (foreign_stubs (language c) (names stubs) (link_deps lib)))
    ````
    With this approach, one could ensure the right ordering between foreign archives too (if they have some mutual dependencies). Of course, this doesn't need to be implemented right in this fix, but this may be something to think about in the long term. An alternative could be to assume that all foreign stubs depend on all libraries that appear in `foreign_archives` declarations in the same stanza, and use this to determine the right order. This seems nice because it doesn't require `link_deps` but may be a bit more limiting.

**Comment by nojb** [comment]
Thanks for the comments. I tried to make a small test with `re2` but I can't get it to build with the latest versions of its dependencies and 4.09. I'm getting this error, in case it rings a bell:
```
File "re2/src/regex.ml", line 121, characters 8-42:
121 | include Binable.Of_stringable_without_uuid [@alert "-legacy"] (T)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module Binable.Of_stringable_without_uuid
File "re2/src/re2_options_cinaps/re2_options_cinaps.ml", line 49, characters 8-14:
49 |       [%string
             ^^^^^^
Error: Uninterpreted extension 'string'.
```

**Comment by aalekseyev** [comment]
@nojb, sounds like you're using the version of re2 that's out of sync with its dependencies (core, ppx_jane).

Anyway, I think re2 works around this issue like this:

It's split in two libraries: `re2` and `re2_c` where `re2` depends on `re2_c`. We link in the library archive as a part of `re2_c` and we link the stubs as a part of `re2`. The library dependency probably makes sure the archives are ordered correctly.

**Comment by nojb** [comment]
> @nojb, sounds like you're using the version of re2 that's out of sync with its dependencies (core, ppx_jane).

I grabbed `master` from https://github.com/janestreet/re2

> Anyway, I think re2 works around this issue like this:
> 
> It's split in two libraries: `re2` and `re2_c` where `re2` depends on `re2_c`. We link in the library archive as a part of `re2_c` and we link the stubs as a part of `re2`. The library dependency probably makes sure the archives are ordered correctly.

This was my impression as well from taking a quick glance, but was trying to confirm it.

**Comment by nojb** [comment]
> > Anyway, I think re2 works around this issue like this:
> > It's split in two libraries: `re2` and `re2_c` where `re2` depends on `re2_c`. We link in the library archive as a part of `re2_c` and we link the stubs as a part of `re2`. The library dependency probably makes sure the archives are ordered correctly.
> 
> This was my impression as well from taking a quick glance, but was trying to confirm it.

OK, I managed to build it; and I confirm that this is the case :)

**Comment by snowleopard** [comment]
> OK, I managed to build it; and I confirm that this is the case :)

@nojb Great, thanks! I've approved the PR as it seems to be a clear improvement on what we have today but I think we might want to come up with a more systematic way of ordering the link arguments. 

Could you add a comment explaining why `link_args` should go last and that there is scope for further improvement?

**Comment by nojb** [comment]
> @nojb Great, thanks! I've approved the PR as it seems to be a clear improvement on what we have today but I think we might want to come up with a more systematic way of ordering the link arguments.

Thanks!

> Could you add a comment explaining why `link_args` should go last and that there is scope for further improvement?

Done.

**Comment by snowleopard** [comment]
@nojb That's perfect, many thanks!

**Comment by nojb** [comment]
Merged, thanks!

**Pull request merged**
