### PR TITLE
Treat *.ml* in Linguist as OCaml and *.t as undetectable

### PR DESCRIPTION
**Pull request by kevinji**
Linguist is marking some *.ml{i} files as SML instead of OCaml; this should fix the statistics.

### CODE REVIEW

**Comment by Alizter** [comment]
Cool I didn't know that you could do this. We should also do the same for `*.t` cram tests since they are being marked as Perl files.

**Comment by kevinji** [comment]
Seems like Cram tests are not in the [list of Linguist languages](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml); should they just be marked as undetectable to remove them from the stats?

**Comment by Alizter** [comment]
@kevinji I suppose marking them as undetectable is the next best thing. If you could do that, that would be great. We could probably support syntax highlighting for cram tests since OCaml Platform has it and the syntax (i.e. the lexer) is very simple. However, this is not currently a priority.

**Comment by emillon** [comment]
Marking as undetectable seems fine.

It's a nice side project to add cram test support to linguist to get better support on github but it's a bit more involved, IIRC it requires a TM grammar.

**Comment by kevinji** [comment]
Just pushed a change to mark `*.t` as undetectable.

**Review by Alizter — APPROVED** [review]

**Pull request merged**
