### PR TITLE
Disable archives for virtual libraries

### PR DESCRIPTION
**Pull request by rgrinberg**
Building virtual libraries and implementations complicates the build 2 folds:

* Virtual libraries cannot construct archives
* Implementations will also come with external .o files that will need to be linked (from stubs)

Also, I suggest that we disable `build_self_stubs` for virtual libraries as in my comment in the source.

### CODE REVIEW

**Comment by rgrinberg** [comment]
CI issues are spurious.

**Comment by diml** [comment]
Why should we disable it for virtual libraries? Note that while we can't have .cma/.cmxa files for virtual libraries, we can have .a files, since the C linker doesn't require things to be in dependency order.

**Comment by rgrinberg** [comment]
I see. Thanks for clarifying. I've removed the incorrect message and enabled stub archive building for virtual libraries.

**Comment by rgrinberg** [comment]
@diml this is ready

**Pull request merged**
