### PR TITLE
Cosmetic changes for default package entry point.

### PR DESCRIPTION
**Pull request by rgrinberg**
@trefis how about this version of #653? I've added the missing newlines that Anton wanted.

### CODE REVIEW

**Comment by trefis** [comment]
I don't really like the newline in the "The entry point of this library is the module ..." case, but I guess that's a matter of taste.
For the other cases, the `\n` before the `{!modules}` construct used to be unnecessary; that might have change in @aantron new version, I don't know.
When you say "Anton wanted", I think I missed that discussion, did he explain why?

As for the changes to the implementation itself, they seem like nice improvements to me.

**Comment by aantron** [comment]
https://github.com/ocaml/dune/pull/367#issuecomment-352209790

https://github.com/ocaml/dune/commit/eb05f4f64362653690fffb25b9fda5e1e2fab8d4

https://github.com/ocaml/dune/pull/659

**Comment by aantron** [comment]
In summary, not enforcing the newline makes people try to put module lists inside sentences.

**Comment by aantron** [comment]
And, luckily, "enforcing" the newline is easier for the new odoc parser than being loose about it, which would require extra code.

**Comment by rgrinberg** [comment]
@trefis ping. This is the only PR that is holding up the release.

**Comment by trefis** [comment]
Yep yep, fine by me.

**Pull request merged**
