### PR TITLE
Set the target's PATH when cross compiling

### LINKED ISSUE #625: Modify PATH for cross compilation
This should include the host's rather than the targets' path. Extracted from the discussion in #623 

I'd like the bisect implementation to be more fleshed out before touching this. As this might not be so useful for bisect.

### PR DESCRIPTION
**Pull request by rgrinberg**
Fix #625 

I'm not sure if my approach or the much simpler one where we simply we t.env is the right one. It feels a bit yicky to just throw away the old PATH so I did the slightly more complicated thing.

### CODE REVIEW

**Comment by diml** [comment]
I think it's simpler if the environment of `jbuilder exec` and the one of the build matches. Currently when you write `(run foo)`, `foo` will resolve to the host binary, which to me indicates that the PATH should be set to point to the host PATH.

**Comment by rgrinberg** [comment]
@diml done

**Comment by diml** [comment]
Why not set the `PATH` directly in the `env` field?

**Comment by rgrinberg** [comment]
Yeah, that was the first option I was contemplating. Only because we are
discarding the old PATH, it's fine I guess

**Comment by diml** [comment]
Yh, I think it's simpler to have only one `PATH`. At least we'll get the right thing in the log.

**Comment by rgrinberg** [comment]
ok @diml I've just updated the context's path. I'm being really careful to make sure the PATH is removed if it isn't present at all in the host context. That's probably overkill since a PATH must always be present. But given all the edge cases that we've hit recently, maybe it doesn't hurt.

**Comment by diml** [comment]
Sure, seems fine

**Pull request merged**
