### PR TITLE
Upgrade to Coq 8.11.1 in Travis

### PR DESCRIPTION
**Pull request by diml**
@snowleopard @ejgallego I believe this should unbreak travis. Looking at the log, it seems that it's because an opam command is trying to upgrade coq and doesn't go through the `keep_travis_happy`.

We might need a more general solution moving forward though.

### CODE REVIEW

**Comment by snowleopard** [comment]
Strange, it still tries to do the upgrade:

```
The following actions will be performed:
  ↗ upgrade coq 8.11.0 to 8.11.1
```

**Comment by diml** [comment]
Alright, let's just try to keep travis happy while doing the `opam upgrade`

**Comment by diml** [comment]
It worked \o/

**Comment by snowleopard** [comment]
Cool, thanks! :tada:

**Comment by ejgallego** [comment]
Thanks a lot for taking care of this.

**Pull request merged**
