### PR TITLE
Install both ml & mli

### PR DESCRIPTION
**Pull request by hhugo**
So that the following works with installed libraries:
- jump to definition using merlin
- sourcemap support in js_of_ocaml

### CODE REVIEW

**Comment by hhugo** [comment]
fix https://github.com/janestreet/base/issues/36

**Comment by rgrinberg** [comment]
Thanks @hhugo this is cherry-picked in master along with a little test. It always made more sense to me to install all the sources.

**Comment by jpdeplaix** [comment]
> jump to definition using merlin

Aren't cmti files made for that so that we don't have to install the sources ?
I'm not sure it's a good default behaviour (or else I didn't fully understand what the PR does)

**Comment by hhugo** [comment]
You need the source in order to to jump to it.
I don't understand you comment. What default behaviour are you talking about ?

**Comment by jpdeplaix** [comment]
Is jumping to the mli file not enough ? I'm just not sure it is a good idea to install implementations by default.

**Comment by rgrinberg** [comment]
The mli doesn't always exist. Also, viewing the implementation is just as
useful. Why should this be avoided on purpose?

**Comment by yminsky** [comment]
Strong agree. Another improvement that could be made would be to install .merlin files for libraries as well, so that once you locate something in the source, you can continue to jump from there to other places, and look up types.

**Comment by yminsky** [comment]
Strong agree. Another improvement that could be made would be to install .merlin files for libraries as well, so that once you locate something in the source, you can continue to jump from there to other places, and look up types.

**Comment by diml** [comment]
This might require some changes in merlin, I'm not sure. Basically we wouldn't be able to generate absolute paths in installed merlin files, since we don't know the installation directories beforehand.

BTW, the tendency seems to be to have less .merlin files rather than more: https://github.com/ocaml/merlin/issues/737

**Pull request closed without merging**
