### PR TITLE
Refactor action handling

### PR DESCRIPTION
**Pull request by rgrinberg**
* Make resolved actions private
* Make the target/dep inference private
* Share code between expansion phases

### CODE REVIEW

**Comment by diml** [comment]
Should we move the rest of `Super_context.Action.run` to `Action_unexpanded.run`? Just to shed a bit more weight from `Super_context`.

**Comment by rgrinberg** [comment]
It's possible to move this bit:

```ocaml
    Path.Build.Set.iter action.targets ~f:(fun target ->
        if Path.Build.( <> ) (Path.Build.parent_exn target) targets_dir then
          User_error.raise ~loc
            [ Pp.text
                "This action has targets in a different directory than the \
                 current one, this is not allowed by dune at the moment:"
            ; Pp.enumerate (Path.Build.Set.to_list action.targets)
                ~f:(fun target ->
                  Pp.text (Dpath.describe_path (Path.build target)))
            ]);
```

I guess I'll do that.

But it's not possible to move this one:

```ocaml
      let foreign_flags ~dir =
        get_node sctx.env_tree ~dir |> Env_node.foreign_flags
      in
      Action_unexpanded.expand t ~map_exe ~dep_kind ~deps_written_by_user
        ~targets:targets_written_by_user ~expander ~foreign_flags
```

Because of the circular dependency that will be introduced. First we'd need to factor out env_tree.

**Comment by diml** [comment]
That makes sense

**Comment by snowleopard** [comment]
@rgrinberg While you remember what's going on, please add some comments, at least a brief top-level overview of the overall design. This code is far from trivial, and we want as many people as possible to contribute.

**Pull request merged**
