### PR TITLE
bc-for-jsoo: use -noautolink, do not depend on stublibs

### PR DESCRIPTION
**Pull request by nojb**
Typically the ocaml bytecode compiler checks that all native shared objects in library dependencies are present when linking a bytecode executable `.bc`. However, in the case of `.bc-for-jsoo` this is not necessary since we will not actually execute the file with the bytecode interpreter.

This PR implements a small optimization in this case:

- passes `-noautolink` when building `.bc-for-jsoo` to disable the compiler check,
- modifies the JSOO rules so as to no longer depend on the foreign shared objects of the dependent libraries.

### CODE REVIEW

**Comment by nojb** [comment]
xref #5282

**Comment by hhugo** [comment]
LGTM

**Comment by rgrinberg** [comment]
@hhugo i added you as a formal reviewer to approve

**Comment by nojb** [comment]
@hhugo do you mind formally approving the PR? Thanks!

**Review by hhugo — APPROVED** [review]

**Comment by nojb** [comment]
Thanks

**Pull request merged**
