### PR TITLE
chore(nix): use nix-overlays for the slim devShell

### PR DESCRIPTION
**Pull request by anmonteiro**
I noticed a few problems with the regular shell:

- every time the source tree changes, opam2nix does full resolution again and rebuilds everything
- somehow, using the `nixpkgs` input doesn't give me editor completion on the slim shell, but using `nix-overlays` as the input fixes it for me

Steps to reproduce:

```shell
$ nix develop .#slim -c zsh
$ make clean && make dev

# In another tmux window, for me
$ nix develop .#slim -c nvim
```

Signed-off-by: Antonio Nuno Monteiro <anmonteiro@gmail.com>

### CODE REVIEW

**Comment by anmonteiro** [comment]
Another note: I don't know if anyone else is using the slim shell other than myself (added in https://github.com/ocaml/dune/pull/6327).

**Comment by Alizter** [comment]
>every time the source tree changes, opam2nix does full resolution again and rebuilds everything

This is (unfortunately) intentional since we need to build dev deps with the new dune in case we break how things are installed. Dune has done this in the past.

**Comment by Alizter** [comment]
I think that is fine to have and is essentially what we have for Coq today too.

**Review by rgrinberg — APPROVED** [review]
Looks OK, just needs a rebase.

Note that running opam2nix is the cause of the slowdown. The issue is that every change to the source requires to rebuild the downstream packages. What would be nice is to have a middle ground environment that uses the dune from opam to build all the dev deps.

**Comment by anmonteiro** [comment]
Rebased

**Pull request merged**
