### PR TITLE
test(win): use bash instead of system when needed

### PR DESCRIPTION
**Pull request by emillon**
On Windows, `(system)` uses `cmd` and fails on these commands.
Using `(bash)` ensures that it is used even on Windows.

### CODE REVIEW

**Review by maiste — COMMENTED** [review]
In the `blackbox-tests/test-cases` directory, it seems that `system` is used at many places. Is there a reason why you targeted these three files in particular and not the other ones?

**Comment by emillon** [comment]
Yes: these are the ones I saw fail with "invalid syntax" in #10655. There's a bunch of cases that are valid uses of `(system)`, and maybe there will be more cases to fix as we fix more things.

**Review by maiste — APPROVED** [review]
Maybe other fixes should land on another PR and this one can be merged?

**Comment by rgrinberg** [comment]
These tests deserve a `%{bin:bash}` dependency as well

**Pull request merged**
