### PR TITLE
Cleanup js_of_ocaml rules 

### PR DESCRIPTION
**Pull request by hhugo**
Js_of_ocaml changes are on master but not yet part of an official release.

How do you imagine pushing such change ? do you want to keep compatibility with older version of js_of_ocaml ?

### CODE REVIEW

**Comment by nojb** [comment]
For info, this PR follows https://github.com/ocsigen/js_of_ocaml/issues/966 / https://github.com/ocsigen/js_of_ocaml/pull/978 .

**Comment by diml** [comment]
Will the next version of jsoo introduces some big breaking changes or drop compat with older compilers? If not, we don't need to consider keeping compatibility with older jsoo versions.

More precisely, the only justification for keeping compat with older jsoo versions would be if not keeping compat would prevent users from upgrading dune.

**Comment by hhugo** [comment]
I don't think we have any big breaking changes in the next release but I would not be surprised to see few project requiring some update with the new release.
I propose to hold onto this change for a while and collect feedback from jsoo users with the upcoming jsoo release.

**Comment by diml** [comment]
That seems good to me

**Comment by rgrinberg** [comment]
> How do you imagine pushing such change ? do you want to keep compatibility with older version of js_of_ocaml ?

One easy way is to add a conflict with older versions of jsoo. This is what we've been doing with odoc for now.

**Comment by rgrinberg** [comment]
@hhugo I think this needs a CHANGES entry.

**Comment by hhugo** [comment]
I've added a CHANGES entry and rebased the PR

**Comment by rgrinberg** [comment]
Thanks. I merged manually.

**Pull request closed without merging**
