### PR TITLE
Explicit build api

### PR DESCRIPTION
**Pull request by cwong-ocaml**
Inserts an explicit `build_api` library between `dune_engine` and `dune_rules`, and adjusts consumers of `dune_engine` to use `build_api` instead.

This API is not minimal, but rather generated somewhat mechanically as an aggregate of all `.mli` files that are referred to by `dune_rules` and `bin`, then curated by hand. I almost certainly missed some opportunities to prune unnecessary functions.

Suggestions (especially for naming -- `build_api` doesn't feel right to me, but `dune_api` feels worse) appreciated.

See also #3703 .

### CODE REVIEW

**Review by rgrinberg — CHANGES_REQUESTED** [review]
I'm all for the idea of having an explicit build api, but adding 4000 lines of boilerplate does not seem like the way go. I'm imagining the amount of extra overhead it would take from the rest of the maintainers to maintain this massive mli, and the cost just seems prohibitive.

Didn't we have efforts to reduce the api and modularize the engine? That kind of work is far less intrusive, and can be done incrementally.

**Comment by cwong-ocaml** [comment]
> adding 4000 lines of boilerplate does not seem like the way go

To be entirely honest, I'm in complete agreement. This 4000-line mli is super unwieldy and I don't particularly relish the idea of messing with it much more.

Currently, the closest thing to "an API" we have is the set of mlis in `src/dune_engine`, but that mixes up two notions of the interface -- one that engine modules use to refer to each other, and one that is intended to be consumed by the rules. The goal behind this insane mli was to decouple the two by explicitly specifying, separately, the "external" API, so that we can have `dune_rules` depend on `build_api` but not `dune_engine`.

My initial draft split the huge `api.mli` file into several different modules, which only re-exported the underlying `Dune_engine` types. The core problem with that, however, is that implementing those interfaces was more complex than simply re-exporting `Dune_engine.Foo` as `Build_api.Foo` -- if `Foo` refers to some engine module `Bar`, the typechecker won't know that `Build_api.Bar` and `Dune_engine.Bar` are the same module (this fact is hidden behind the mli, and we can't export it because that defeats the point of the decoupling), and so fails. Putting it together into one gigantic module "fixes" this issue, because now all the implementors are aware of each other.

When I discussed this issue with @jeremiedimino , he suggested that we take this course of action, but I don't think any of us foresaw just how ridiculous the result would be. Jeremie, maybe you have some other thoughts for this draft?

**Comment by jeremiedimino** [comment]
My expectation was that the initial version would be quite big, but it would be a starting point and by looking at it there would be quite a few obvious thing we can do to shrink it. First of all, as @aalekseyev pointed out the other day there are quite a few modules in there that don't need to be part of the build API and for which we will share not only the interface but also the implementation between Dune and Jenga. For instance `Opam_file` or `Package`. There might also be modules for which we will want a different implementation but we can easily extract from the main mli files.

It seems worth to me doing a first pass over the list of modules and submitting a few PRs to move these things around. For instance creating a new library that will contain the modules for which we want to share the impl between Jenga and Dune and are referred in the build API. After that, the main mli in this PR might start looking more reasonable.

**Comment by rgrinberg** [comment]
I think this can be closed since we've found a less intrusive approach.

**Pull request closed without merging**
