### PR TITLE
Remove trailing zero's when writing json

### LINKED ISSUE #4569: Don't drop trailing zeroes for dune-bench
## Desired Behavior

This is for current-bench. The dune benches currently drop the trailing zeroes making the json invalid for parsing. 

## Example

{"results":[{"name":"clean_build","metrics":{"time":242.}},{"name":"zero_build","metrics":{"time":[4.,2.,2.,3.,2.]}},{"name":"dune_size","metrics":{"size":13093864}}]}

### PR DESCRIPTION
**Pull request by rgrinberg**
Fix #4569

### CODE REVIEW

**Review by aalekseyev — APPROVED** [review]
I guess you remove a trailing dot, not a trailing zero (which was absent, in the first place), but looks good.

**Comment by aalekseyev** [comment]
Maybe need to update tests

**Comment by rgrinberg** [comment]
Indeed. Thanks for noticing.

**Comment by rgrinberg** [comment]
I clarified  the commit message as well.

**Pull request merged**
