### PR TITLE
better integration with vscode

### PR DESCRIPTION
**Pull request by bobzhang**
- For watch mode, vscode needs a begin pattern, end pattern pair
- For error exits, it would be nice to have an indicator

### CODE REVIEW

**Comment by avsm** [comment]
Are these configurable in vscode? The error markers in this PR are kind of shouty and not in the normal dune style.

**Comment by Khady** [comment]
Yes, it is possible to create a tasks.json file to specify the patterns for beginning and end. In my current setup it looks like this (works only because I call dune from a makefile).

```
            "beginsPattern": "dune build .*",
            "endsPattern": "make\\[1\\]: Leaving directory '.*"
```

**Comment by rgrinberg** [comment]
The above isn't all that great either. `$ dune runtest` isn't picked up by this for example.

**Comment by diml** [comment]
Can we detect if we are being run by vscode?

**Comment by bobzhang** [comment]
Would it do any harm to have a clear delimiter in general? Currently the dune output is verbose, without a decent integration with editor, you have to search pages to find the location..
Note you can pick a nicer message.

**Comment by diml** [comment]
The capital letter are a bit loud, so if it only works in vscode, it seems better to use them only when running under vscode.

Could you try passing `--display progress` to dune when running under vscode and see if it improves the output? `progress` is the best output mode: it's quiet but still shows progression. However, it only works if the output is a terminal or when running inside emacs. If it works under vscode as well, then we can enable it when running inside vscode.

**Comment by bobzhang** [comment]
see https://github.com/ocaml/dune/issues/1733

**Comment by diml** [comment]
?

**Pull request closed without merging**
