### PR TITLE
Turn on incremental memo by default

### PR DESCRIPTION
**Pull request by rgrinberg**
For some reason this breaks error reporting with RPC (it now reports stale errors). Investigating as to what the cause is.

### CODE REVIEW

**Comment by jeremiedimino** [comment]
It seems that fsevents supports a "flush" operation that does the same as the inotify sync mechanism: https://developer.apple.com/documentation/coreservices/1445629-fseventstreamflushsync?language=objc

**Comment by rgrinberg** [comment]
Yeah, that looks useful but it would require us to abandon fswatch on MacOS and switch to fsvents directly.

**Comment by jeremiedimino** [comment]
Indeed. In the long run that seems inevitable if we want proper fine grained file watching. fswatch/inotifywait were an easy way to bootstrap the system but they don't give us much control. For instance, we can't dynamically add watches with fswatch, so we can't watch external files and directories while we can by using the inotify or fsevents API directly.

**Comment by jeremiedimino** [comment]
@rgrinberg can you disable the offending tests on OSX for now and merge this PR? And while you are at it, delete the environment variable and the old mode entirely.

The new mode is usable enough now and there is going to be a fair amount of polishing to do before it's ready for release. So we might as well make the new mode the new reality ASAP.

**Comment by rgrinberg** [comment]
Is there a way to do enabled_if on inline tests? I'm not sure how to disable tests on OSX.

**Comment by jeremiedimino** [comment]
Putting it on the whole library stanza should work. I'm trying that.

**Review by jeremiedimino — APPROVED** [review]

**Pull request merged**
