### PR TITLE
Add Fiber.Result module

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by rgrinberg** [comment]
Yes, this is being used in LSP which vendors fiber. Thanks you for the review!

**Comment by jeremiedimino** [comment]
So, we have this for `Deferred` in `Async` and its usage is not unanimous. It's like marmite, some love it some hate it. @rgrinberg if this is only used in LSP, I'd rather that this code lives in LSP. It doesn't need to be part of the `Fiber` module.

**Comment by rgrinberg** [comment]
Alright, I reverted.

**Comment by snowleopard** [comment]
Presumably, if we want to discourage the use of `Result.t Fiber.t` for error handling, we should also remove `fold_errors` and `collect_errors`, which are currently provided by the interface but appear to be unused in Dune.

I personally don't feel strongly one way or another, but if we want to stick to `with_error_handler` as the idiomatic way of handling errors, we can replace `collect_errors` with something like:

```ocaml
val with_all_errors_handler :
  (unit -> 'a t) -> on_error:(Exn_with_backtrace.t list -> unit) -> 'a t
```

P.S.: In a parallel discussion with @jeremiedimino, we also thought that it would be useful to make `with_error_handler` deterministic, i.e. return not the earliest error (like now), but the first error in the order of parallel branches.

**Comment by rgrinberg** [comment]
>  In a parallel discussion with @jeremiedimino, we also thought that it would be useful to make with_error_handler deterministic, i.e. return not the earliest error (like now), but the first error in the order of parallel branches.

Sounds like a good idea. Shall we make an issue for this at least?

**Comment by snowleopard** [comment]
@rgrinberg Done: #3439.

**Pull request merged**
