### PR TITLE
Enable watch mode tests on MacOS

### PR DESCRIPTION
**Pull request by rgrinberg**
install fsevents using homebrew

### CODE REVIEW

**Comment by rgrinberg** [comment]
@aalekseyev I pushed a fix for macos.

**Comment by aalekseyev** [comment]
The test doesn't pass, which highlights the fact that I'm an idiot.

When I made the "@_build" change for inotifywatch, I did that for a reason: because otherwise the notification for `_build/dune-inotify-sync` was being filtered out.

Guess what, the same issue exists with fswatch.

I even thought of a solution then: we can try using `--include` before `--exclude`. Relevant quote from the man page:

> The user can specify multiple filter
> expression in any order and the first matching expression wins.

Let me try to fix that...

**Comment by rgrinberg** [comment]
> The test doesn't pass, which highlights the fact that I'm an idiot.

Strangely, the tests seem to pass on my mac even with the old order of flags.

**Comment by aalekseyev** [comment]
Oh well, the test still doesn't pass.
Sorry, I won't invest any more time into this for now.
If you can get it working, great. If not, we should revisit it at some later time, maybe using a native backend instead of fswatch.

**Comment by rgrinberg** [comment]
Alright well I'll disable on macos but keep the changes as it least it works for me locally.

**Pull request merged**
