### PR TITLE
doc: allow for downloads of pdf and epub of documentation

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by emillon** [comment]
Where can the result be downloaded?

**Comment by Alizter** [comment]
In the select version menu in the bottom left corner.

**Comment by Alizter** [comment]
Well at least according to https://docs.readthedocs.io/en/latest/tutorial/index.html#enabling-pdf-and-epub-builds but it didn't seem to work.

**Comment by emillon** [comment]
that might only works on "releases" (including `/latest`). do you have a local copy? if it does not look too awful we can enable that.

**Comment by Alizter** [comment]
It doesn't show locally since that menu is javascript. I think readthedocs just generates the artifacts as you said for each release. It appears they even have download statistics.

**Comment by emillon** [comment]
I mean, if you run sphinx-build in epub or pdf mode, how does it look?

**Review by emillon — APPROVED** [review]

**Comment by emillon** [comment]
Looks good. These backends are not a priority for me but this gives a low-effort way of downloading the docs.

**Pull request merged**
