### PR TITLE
Emacs dune mode

### PR DESCRIPTION
**Pull request by Chris00**
Fixes to be able to publish it on MELPA.

### CODE REVIEW

**Comment by Chris00** [comment]
The [MELPA PR](https://github.com/melpa/melpa/pull/6000) will fix https://github.com/ocaml/dune/issues/1710

**Comment by Chris00** [comment]
Note that, in the referenced PR, they asked the following:

> Please consider putting the elisp libraries in a separate repository. That makes it easier for people who want to install dune using a system package but install emacs packages by cloning git repositories. (I do that sort of thing using borg.) A separate repository would also make it easier to mirror the package on the Emacsmirror. And finally it might make it a bit more likely that users contribute to the package.
>
> I think caml-mode used to be part of the ocaml repository but was recently moved out. It would be nice if that could be done across all repositories of the ocaml organisation.

Let me know what you think of it.

**Comment by rgrinberg** [comment]
I'm sympathetic to those needs but I think that ultimately it makes maintenance more difficult for us. In the end, our plan is to use generation to make the various editor integration a lot more seamless. Not to mention the fact that we don't have to worry about supporting old versions of dune with the mode.

I think that if the dune repo grows huge like the OCaml one, the argument will have more weight, but for now I'm against this.

**Comment by tarsius** [comment]
Okay, I understand. As long as you keep the elisp in a dedicated directory I can extract it with `git subtree` for the Emacsmirror.

**Pull request merged**
