### PR TITLE
Add native object directories to generated .merlin files

### PR DESCRIPTION
**Pull request by mrmr1993**
Only `.cmti` files are present in the byte object directory for libraries built in native mode. This PR adds the native object directories to the `.merlin` file, so that merlin can locate definitions in these libraries, not just declarations.

See ocaml/merlin#1202 for the related merlin issue.

### CODE REVIEW

**Comment by voodoos** [comment]
Your fix looks correct to me (appart from the tests that need to be updated), however I am puzzled about the original issue: 
Using Dune 2.7.1 with an example project I do have the `.cmt` in the `byte` object sub-dir, when building in native (or in byte) mode.

Can you provide a small project that would help us reproduce the issue ?

**Comment by mrmr1993** [comment]
> Can you provide a small project that would help us reproduce the issue ?

I've been using 4.07.1 with dune 2.7.0. The project I used to test this has:
`subdir/dune`:
```
(executable
 (name subdir)
 (libraries test))
```
`subdir/subdir.ml`:
```
let () = Format.eprintf "%i@." (Test.f 15)
```
`test/dune`:
```ocaml
(library
 (name test))
```
`test/intf.ml`:
```ocaml
module type S = sig
  val f : int -> int
end
```
`test/test.ml`:
```ocaml
let f x = x
```
`test/test.mli`:
```ocaml
include Intf.S
```

Deleting `_build` and running `dune build subdir/subdir.exe` generates
```
$ ls _build/default/test/.test.objs/byte/test.*
_build/default/test/.test.objs/byte/test.cmi  _build/default/test/.test.objs/byte/test.cmti
$ ls _build/default/test/.test.objs/native/test.*
_build/default/test/.test.objs/native/test.cmt  _build/default/test/.test.objs/native/test.cmx  _build/default/test/.test.objs/native/test.o
```

Without this patch, running `:MerlinLocate` from vim on `Test.f` in `subdir/subdir.ml` jumps to `val f` in `test/intf.ml`. With it, it respects my implementation preference and jumps to `test/test.ml` via the `.cmt` file in the native objs directory.

> tests that need to be updated

I will try to get around to fixing these these later today.

**Comment by mrmr1993** [comment]
> > tests that need to be updated

> I will try to get around to fixing these these later today.

Done, found a couple of mins while waiting for a compile.

**Comment by mrmr1993** [comment]
There's an additional annoying issue where the `.cmt` file is deleted by a subsequent build. This means that merlin only operates correctly exactly when the module whose `.cmt` file it needs to reference was dirty (ie. needed a recompile) at the last compile involving that module.

I can investigate and fix this, either as part of this PR or as a separate issue/PR, whichever is preferable. I am unlikely to get to this today.

**Comment by rgrinberg** [comment]
Note that we're aware of this issue and we decided against complicating our rules to support tooling for native targets. See the discussion here https://github.com/ocaml/dune/pull/3758

Are you building the `@check` target? This is the target we provide to the user to build all files required for tooling.

> There's an additional annoying issue where the .cmt file is deleted by a subsequent build. This means that merlin only operates correctly exactly when the module whose .cmt file it needs to reference was dirty (ie. needed a recompile) at the last compile involving that module.

The bug here is that we are adding the `-bin-annot` flag even if we aren't expecting `.cmt` targets.

**Comment by mrmr1993** [comment]
> Note that we're aware of this issue and we decided against complicating our rules to support tooling for native targets. See the discussion here #3758

Most of the discussion there seems to be centred around the disabling of bytecode and how this is undesirable. I wholeheartedly agree. I can't see any discussion of there being value in not generating `.cmt`s where we are already generating them.

> Are you building the `@check` target?

No, I am not. I can add this to the makefiles of the projects I work on, but this appears to be papering over the cracks in dune rather than dealing with the actual issue, and adds more complexity to something that could easily be a basic feature of dune.

> The bug here is that we are adding the `-bin-annot` flag even if we aren't expecting `.cmt` targets.

I think I disagree here: the `-bin-annot` flag is fairly cheap (just dump the typedtree once it is generated), and provides value to users by making tools work immediately with their code once it has compiled. To expand on the options a little, from a user perspective:

* We could stop deleting the `.cmt` files generated by `-bin-annot` builds
  - This would make dune 'just work' for users: when they see a compile error, they can jump into their code and use merlin to navigate around etc. immediately.
  - Incrementally editing code is a 2-step process: build, edit
  - If always dumping the typetree is an issue (speeding up builds, perhaps?) then it should probably be a flag/configurable. Default on is naturally the best developer experience.
  - This is simple (just acknowledge the additional target) and adds essentially 0 overhead to the current behaviour.
* We could stop adding the `-bin-annot` flag
  - This adds complexity (sometimes we want it, e.g. `@check`, other times we don't)
  - This breaks dune compatibility with merlin for novice users:
    + building with dune doesn't allow them to use merlin by default
    + `@check` is not very discoverable
    + novice users will have to waste time learning this dune-ism instead of being producting
  - This will be an annoyance for more experienced users:
    + debugging a compile error or editing compiled code requires a recompile (actually re-typecheck, but this difference isn't relevant to users)
    + `-bin-annot` artifacts are likely to fall out of date with the latest compiled version if `@check` isn't run with each build. This comes with the additional mental burden of tracking whether these artifacts are up-to-date, in addition to the regular build ones.
    + time is wasted explaining to novice users that they need to do a special `@check` build to make dune work
  - This adds a burden to (sympathetic) project maintainers: they will likely want to update some or all of their build rules to do the relevant `@check` to help newer contributors, or will each have to document this dune quirk and the workaround
  - I haven't looked into it, but `@check` seems broader in scope than a specific compile target
    + Doing the naive `@check` build may typecheck targets that are not relevant to what the developer is working on, wasting time
    + Compiling only the relevant targets adds complexity, or is maybe impossible (if e.g. 2 libraries/executables cohabit in a directory, but only one is relevant).

I feel strongly that the solution is: where we pass the `-bin-annot` flag, the rule should add a `.cmt` target.

**Comment by rgrinberg** [comment]
> Most of the discussion there seems to be centred around the disabling of bytecode and how this is undesirable. I wholeheartedly agree. I can't see any discussion of there being value in not generating .cmts where we are already generating them.

I'm just making sure you haven't disabled bytecode builds.

> I feel strongly that the solution is: where we pass the -bin-annot flag, the rule should add a .cmt target.

I whole heartedly agree. If dune is creating a rule that produces a file, then there should be a corresponding target. Anything otherwise is a bug.

**Comment by mrmr1993** [comment]
> I wanted to make sure you haven't disabled bytecode builds. The discussion also contains a proposal that tries to put an end to all of this madness around cmt/cmti's: modify the compiler to make it possible to produce `.cmt` targets after typing, and allow code bytecode and native compilation to resume from this stage. Would this be satisfactory to you long term?

I haven't done anything as yet, I've only poked around a little to see which rules are the ones that generate the `.cmt`, so that I can add it as a target to them.

The resumable compile is a really nice idea, and the compiler is the right place to do it IMO. I'm sure you've considered that this will be useful for tooling, better for workflows that compile both bytecode and native, and (I think) should let post-typechecking phases be completely parallelisable; I'll mention them anyway because they're all good improvements and I'm a big fan!

> So do you suggest that we generate cmt targets for all native targets? [..] Note that this still wouldn't be very clean as `$ dune install` and `$ dune build @check` would still favor the cmt's derived from the bytecode.

I think this would be the best developer experience, yes. For the preferences of `install` and `@check`, I think this is fine as long as it is documented somewhere, since the decision has to be made one way or another regardless.

> If dune is creating a rule that produces a file, then there should be a corresponding target. Anything otherwise is a bug.

Great, I'll finish tracking down the rule and add the `.cmt` target.

As an aside, it would be nice if there was a way for dune to dump the rules for a dune file/target/directory, along with where they came from (including code locations for 'internal' rules). I haven't been enjoying `grep`ing/adding `printf`s to try and track it down, and I know I've longed for this kind of information in other situations too. Apologies in advance if this already exists and I've just missed it.

**Comment by mrmr1993** [comment]
> I'll finish tracking down the rule and add the `.cmt` target.

I worked out why I couldn't find the rule: I have `CAMLPARAM="_,bin-annot=1` set in my `.bashrc`. Classic user error.

Instead I've implemented your workaround of generating `.cmt` files for native builds, respecting the `bin_annot` option from the compilation context to match the bytecode builds. This works perfectly for what I wanted.

-------

@rgrinberg it seems like ideally dune should know about the `CAMLPARAM` env var, and that rules that call into the OCaml compiler should have an implicit dependency on it (or on the data dune might extract from it). I'm not particularly interested in implementing this myself, but I can open an issue for it if it is worth considering.

**Pull request closed without merging**
