### PR TITLE
Fix sites installation with opam

### PR DESCRIPTION
**Pull request by bobot**
Cherrypick from 2.9 (wrong way sorry)  #4645

### CODE REVIEW

**Comment by jeremiedimino** [comment]
We already have `--promote-install-files`. Can we have `--promote-install-files=no` instead of `--no-promote-install-files`? We already have a lot of options, so it seems better to augment existing ones rather than add new similar ones.

FTR, we patched cmdliner in https://github.com/ocaml/dune/pull/4718 to support "optional parameters" properly. i.e. you can change `--promote-install-files` to take an optional parameter, and in this case you have to write `--promote-install-files=<value>` if you want to pass a parameter, so that there is no ambiguity.

**Comment by ejgallego** [comment]
> > Can we have --promote-install-files=no instead of --no-promote-install-files?
> 
> Good idea, I will do it. @ejgallego I will have an additional little commit for 2.9. Is it okay?

No problem, thanks!

**Comment by jeremiedimino** [comment]
Hmm, removing command line options is difficult since the cli is not versioned. We shouldn't introduce an option that we know we are going to remove.

> In any case allowing every boolean option to be overridden using --no- is useful and common (e.g wget). We can have that as a general rule (and automatic for every flag).

Optional parameters seems better to me. We started using them for other options such as `--watch` and it is working pretty well. I don't understand why it wouldn't work here. Plus optional parameters are more versatile since they allows more states than just `yes` or `no`.

**Comment by jeremiedimino** [comment]
> is it okay to modify our version before the modification is accepted in Cmdliner?

Yes, we have already cross that bridge. However, we have https://github.com/ocaml-dune/cmdliner. @rgrinberg, have you been pushing patches to the ocaml-dune/cmdliner fork and then updating the copy in vendor?

**Comment by ejgallego** [comment]
I'm adding the 2.9 milestone because I understand bits of this will have to be backported too.

**Comment by rgrinberg** [comment]
>  have you been pushing patches to the ocaml-dune/cmdliner fork and then updating the copy in vendor?

Yes. Patches to cmdliner should be pushed there and then updated in this repo.

**Comment by jeremiedimino** [comment]
Ack. I pushed the small patch added in #4678 to github.com/ocaml-dune/cmdliner (/cc @aalekseyev).

**Pull request merged**
