### PR TITLE
Add memo benchmarks

### PR DESCRIPTION
**Pull request by jeremiedimino**
Add micro benchmarks for `Memo`. These were written by Arseniy inside Jane Street, I just copied and adapted them.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Can we incorporate all these benchmarks into the CI we setup earlier?

**Review by snowleopard — APPROVED** [review]
Nice, thanks for doing this! 

These benchmarks look a bit quirky outside the context of the Tenacious library, but it's better than nothing :)

**Comment by jeremiedimino** [comment]
Agreed

**Comment by rgrinberg** [comment]
> I was thinking that as well, that would be really awesome. core_bench supports sexp output (via -sexp), so it shouldn't be too difficult to incorporate.

Yes that's what I had in mind.

**Pull request merged**
