### PR TITLE
chore: move melange rules to melange dir

### PR DESCRIPTION
**Pull request by Alizter**
Signed-off-by: Ali Caglayan <alizter@gmail.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
I'll wait until the all the wip melange PR's are merging this.

**Comment by rgrinberg** [comment]
Can you rebase this?

**Comment by Alizter** [comment]
@rgrinberg Rebased.

**Comment by snowleopard** [comment]
This code reorganisation makes perfect sense but it's breaking the build of Dune internally for us. I wonder if you could revert this for now, or, alternatively, turn these new subdirectories into proper libraries?

**Comment by snowleopard** [comment]
(The same applies to the other new subdirectories, it's just the first build error I got was about Melange rules.)

**Comment by snowleopard** [comment]
Alternatively, we can probably also just delete all Dune rules code internally...

**Comment by snowleopard** [comment]
@rgrinberg and I discussed this and decided to create a branch for Jane Street's version of Dune, which will have a flat directory structure.

**Pull request merged**
