### PR TITLE
build: needs CoreFoundation instead of Foundation

### PR DESCRIPTION
**Pull request by Et7f3**
Found while reviewing https://github.com/NixOS/nixpkgs/pull/208957#pullrequestreview-1236361465

Signed-off-by: Élie BRAMI <cadeaudeelie@gmail.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
Thanks. Can you sign off with your real name? I apologize for asking, but it's needed for a valid DCO.

**Comment by anmonteiro** [comment]
Can we get some more information about why this change is needed? I don't understand what this would fix

**Comment by Et7f3** [comment]
> Thanks. Can you sign off with your real name? I apologize for asking, but it's needed for a valid DCO.

done

> Can we get some more information about why this change is needed? I don't understand what this would fix

We just get more precise on what is needed to build dune. Headers use CoreFoundation so we should link again CoreFoundation not a framework that use it. Also in nix pr adding Foundation allowed to not specify CoreServices so it goes agains strict deps.

**Comment by anmonteiro** [comment]
> We just get more precise on what is needed to build dune. Headers use CoreFoundation so we should link again CoreFoundation not a framework that use it.

Thanks, makes sense and I agree

**Review by anmonteiro — APPROVED** [review]

**Comment by rgrinberg** [comment]
Thanks.

Now I'm curious how `nix develop` picks up these dependencies on macos. I'm using opam-nix, so the deps should come from the opam file, and those say nothing about these macos deps.

**Comment by Et7f3** [comment]
```
$ nix develop
error: builder for '/nix/store/jr6ivj853biby0ihll6dqkdmi5fplrva-ocaml-config-2.drv' failed with exit code 1;
       last 5 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/4d0ix5djms3n2jnjdc58l916cwack1rp-empty-directory
       > source root is empty-directory
       > patching sources
       > /nix/store/f9ldh0bv3vrxfksfxjm1p2q9m2ii5nna-stdenv-darwin/setup: line 120: /dev/stderr: Operation not permitted
       For full logs, run 'nix log /nix/store/jr6ivj853biby0ihll6dqkdmi5fplrva-ocaml-config-2.drv'.
error: 1 dependencies of derivation '/nix/store/8j1yzkhs27247wsky38i783lh6mrlrkn-ocaml-4.14.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8r828jl0agkkgwybi4nypx7ld1dwr41r-nix-shell-env.drv' failed to build
```

**Comment by rgrinberg** [comment]
No idea where's that coming from It seems to work fine for me.

**Comment by Et7f3** [comment]
It was sandbox mode, without sandbox mode it take from here:
/nix/store/smkbczxw43s09bv81h23fr86mj79zx4a-apple-framework-CoreFoundation/Library/Frameworks
/nix/store/9g1xgzh8bg2kmprzrrrbcf32ykg50cm2-apple-framework-CoreServices/Library/Frameworks

(clang --verbose file.c)
Ok now I have re-enabled sandbox it still take the path from the same place and without the error

**Comment by Et7f3** [comment]
> Thanks. Can you sign off with your real name? I apologize for asking, but it's needed for a valid DCO.

gnark gnark gnark 😈 I have a GitHub username for the signoff https://github.com/ocaml/dune/pull/3772/commits/104565517a35ca643390daf1b45ecb9bb5cb9ebb (my first merged PR) I hope it won't cause issue ?

**Pull request merged**
