### PR TITLE
Make blackbox tests independent from dune language version

### PR DESCRIPTION
**Pull request by NathanReb**
Bumping the language version won't break any test after this PR is merged, we'll need to carefully review new tests so that they are future proof as well though.

There is two kind of fixes here:
1. when relevant, add a dune-project (or generate it depending on how the test was written)
2. when the dune-project generation is part of the test or when we `cat` files that contain the language version, pipe the command through a `sed` to replace the version with `<version>`.

Having to copy the sed command around isn't great so we could maybe extract it to a tiny script somewhere but I'm not sure how much better it would look.

Let me know what you think.

### CODE REVIEW

**Comment by diml** [comment]
> Having to copy the sed command around isn't great so we could maybe extract it to a tiny script somewhere but I'm not sure how much better it would look.

That should be quite easy to do actually: we could add a bunch of scripts in `test/blackbox-tests/bin` and then add them to the PATH via `(env (_ (binaries ...)))` in `test/blackbox-tests/dune`

**Comment by diml** [comment]
And instead of a script, we could make it an OCaml program with several sub-commands, that'd be even better and portable.

**Comment by NathanReb** [comment]
That sound good indeed, should I do this as part of this PR?

**Comment by diml** [comment]
Doing it separately seems best to me

**Comment by NathanReb** [comment]
Great, let's merge then!

**Pull request merged**
