### PR TITLE
test(fsevents): reproducible test

### PR DESCRIPTION
**Pull request by rgrinberg**
Another attempt.

### CODE REVIEW

**Comment by rgrinberg** [comment]
ping @jeremiedimino

**Comment by jeremiedimino** [comment]
The CI still looks all broken :/

**Comment by jeremiedimino** [comment]
Looks like it's formatting

**Review by jeremiedimino — APPROVED** [review]
The changes look reasonable to me.

**Comment by rgrinberg** [comment]
@nojb could you look over the C changes?

**Pull request merged**
