### PR TITLE
fix: man dir for contexts

### PR DESCRIPTION
**Pull request by rgrinberg**
it was set to bin/ accidentally

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Review by anmonteiro — APPROVED** [review]

**Comment by anmonteiro** [comment]
Wait, is this the source of the nix problem?!

**Comment by rgrinberg** [comment]
Which nix problem?

**Comment by anmonteiro** [comment]
https://github.com/NixOS/nixpkgs/pull/211748

**Comment by rgrinberg** [comment]
Probably not. This fix only affects commands like `$ dune exec -- man foo`

**Pull request merged**
