### PR TITLE
Add stats to dune's rpc server

### PR DESCRIPTION
**Pull request by rgrinberg**
Generic stat tracking of:

- [x] Sessions created & destroyed
- [x] Requests & notifications being handled

### CODE REVIEW

**Comment by rgrinberg** [comment]
gentle ping @aalekseyev

**Comment by rgrinberg** [comment]
I added @cwong-ocaml or @jeremiedimino as alternative reviewers if you guys have time.

**Comment by jeremiedimino** [comment]
Let's consider that you and @cwong-ocaml are responsible for the RPC on the Dune side.

**Comment by rgrinberg** [comment]
ping @cwong-ocaml

**Review by cwong-ocaml — APPROVED** [review]

**Comment by cwong-ocaml** [comment]
Seems unambiguously good to me

**Pull request merged**
