### PR TITLE
Pass the linkall flag to jsoo in whole program compilation as well

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
The CI seems to be broken on master already. Failures here don't seem related to this PR

**Comment by Leonidas-from-XIV** [comment]
The local switch failure was fixed by #10938, so when you rebase it should disappear.

**Comment by rgrinberg** [comment]
CHANGES entry please

**Comment by hhugo** [comment]
> CHANGES entry please

done

**Comment by rgrinberg** [comment]
Is this failure relevant?
```
--- a/_build/.sandbox/baffd0df3e27b507f69e0a94ea33d889/default/test/blackbox-tests/test-cases/jsoo/inline-tests.t/run.t
+++ b/_build/.sandbox/baffd0df3e27b507f69e0a94ea33d889/default/test/blackbox-tests/test-cases/jsoo/inline-tests.t/run.t.corrected
@@ -16,6 +16,7 @@ Run inline tests using node js
   inline tests (JS)
 
   $ dune runtest --profile release
+  Warning: your program contains effect handlers; you should probably run js_of_ocaml with option '--enable=effects'
```

**Comment by hhugo** [comment]
> Is this failure relevant?
> 
> ```
> --- a/_build/.sandbox/baffd0df3e27b507f69e0a94ea33d889/default/test/blackbox-tests/test-cases/jsoo/inline-tests.t/run.t
> +++ b/_build/.sandbox/baffd0df3e27b507f69e0a94ea33d889/default/test/blackbox-tests/test-cases/jsoo/inline-tests.t/run.t.corrected
> @@ -16,6 +16,7 @@ Run inline tests using node js
>    inline tests (JS)
>  
>    $ dune runtest --profile release
> +  Warning: your program contains effect handlers; you should probably run js_of_ocaml with option '--enable=effects'
> ```

Yes, I've committed the change

**Comment by hhugo** [comment]
The behavior between whole program compilation and separate compilation is now the same.

**Pull request merged**
