### PR TITLE
(library (extra_objects)): avoid double linking

### LINKED ISSUE #10785: Error building library with indirect dependency on object file
There seems to be a problem when building libraries with indirect dependencies to object files. That is, when calc.ml depends on dep.c which in turn depends on add.o.

I get the following error:
```
/usr/bin/ld: lib/add.o: in function `add':
add.c:(.text+0x0): multiple definition of `add'; lib/libc_test_stubs.a(add.o):add.c:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```

The issue is also discussed at [discuss.ocaml.org](https://discuss.ocaml.org/t/build-error-when-using-c-stubs-and-external-object-file/15041).

## Reproduction

- PR with a reproducing test: [pull request](https://github.com/ocaml/dune/pull/10784)

## Specifications

- Version of `dune`: 3.16.0
- Version of `ocaml`: 5.2.0

## Additional information 

- Link to gist with verbose output (run `dune` with the `--verbose` flag): [dune verbose output](https://gist.github.com/Hsodergren/ed2d33f921fdc6ab5cc1382fdba122a5)

### PR DESCRIPTION
**Pull request by nojb**
Fixes https://discuss.ocaml.org/t/build-error-when-using-c-stubs-and-external-object-file/15041/7
Fixes #10785

### CODE REVIEW

**Comment by nojb** [comment]
I don't quite understand why https://github.com/ocaml/dune/blob/81877e57662749faf78315b318e4fcc18cd1fe06/test/blackbox-tests/test-cases/extra-objects/extra-objects-lib.t#L78-L95 did not detect this issue...

**Comment by nojb** [comment]
> > I don't quite understand why
> 
> I guess because that library does not have foreign stubs. I will add a test for this case.

This is now done (I adapted the existing test).

**Review by emillon — APPROVED** [review]

**Comment by emillon** [comment]
Looks good; what do you want to do about tests? pick the one from #10784 or keep the new one from this PR?

**Comment by nojb** [comment]
> Looks good; what do you want to do about tests? pick the one from #10784 or keep the new one from this PR?

I'll cherry-pick the one from #10784 and revert the modification to the existing test.

**Comment by nojb** [comment]
CI failure looks unrelated. Merging!

**Pull request merged**
