### PR TITLE
chore: use ocamlformat 0.25.1

### PR DESCRIPTION
**Pull request by emillon**

### CODE REVIEW

**Comment by emillon** [comment]
These look ok to me, mostly fixes with indent inside parentheses.

**Review by Alizter — APPROVED** [review]
Shame about the git history. Or did I misunderstand, are you able to ignore them?

**Comment by emillon** [comment]
we are able to ignore them. the reason this PR is failing is because the corresponding ocamlformat version is not availble on nix, though.

**Comment by Alizter** [comment]
25 was merged last week so if you update the nixpkgs version in the flake with `nix flake update` it should work.

**Comment by emillon** [comment]
OK I just did that (for just the `nixpkgs` input)

**Comment by Alizter** [comment]
Looks good to go now.

**Pull request merged**
