### PR TITLE
fix(melange): merlin support for melange only libs

### PR DESCRIPTION
**Pull request by rgrinberg**
If a library is defined only for melange, we tell merlin to use the
melange object dir to lookup cmi's

### CODE REVIEW

**Review by anmonteiro — APPROVED** [review]
looks correct. My understanding:

- if building a library solely in "melange" mode (i.e. both OCaml modes are missing), we use the Melange object directory for Merlin, otherwise, we'll use the bytecode directory

**Review by jchavarri — APPROVED** [review]
Looks great.

Two questions:
- Would it make sense to write a test to validate the assumptions added in this test? (in case we change them later, we integrate melange and ocaml cmis, etc)
- Besides this diff, do you think there are other steps to take to support Melange in `vscode-ocaml-platform`?

**Comment by rgrinberg** [comment]
> Would it make sense to write a test to validate the assumptions added in this test? (in case we change them later, we integrate melange and ocaml cmis, etc)

Done. The tests revealed a few bugs that I've now fixed.

> Besides this diff, do you think there are other steps to take to support Melange in vscode-ocaml-platform?

AFAIK it should be enough. However, the way support the melange stdlibs is a bit hacky as we just pretend it's an OCaml lib.

**Comment by anmonteiro** [comment]
> However, the way support the melange stdlibs is a bit hacky as we just pretend it's an OCaml lib.

Can't we just add `opam var melange:install` to the Merlin binary search path?

**Comment by rgrinberg** [comment]
> Can't we just add opam var melange:lib to the Merlin binary search path? Or is that what you mean by "pretend it's an OCaml lib"?

Yes, that's possible but also a hack. This would be the best way to make it work:

1. Add first class support for installed libraries
2. Define builtin melange libraries using the standard library stanza in dune
3. Take advantage of 1. and 2. to provide merlin support.

**Pull request merged**
