### PR TITLE
Add a platform independent output mode for Process

### PR DESCRIPTION
**Pull request by rgrinberg**
@diml looks like this is insufficient to replace sanitize, as we also need to
sanitize the output of .install and dune-package files. Perhaps we could
introduce a command like `$ dune internal-sanitize` to do this instead?

### CODE REVIEW

**Comment by diml** [comment]
How would `dune internal-sanitize` work? Would it do the same as what `cram` does now? i.e. search and replace a specific regexp

**Comment by rgrinberg** [comment]
That's how it would work. I don't see another way unfortunately.

**Comment by diml** [comment]
Should we just apply this filter systematically on the output of dune? Just so that we don't have to modify the code everywhere to rewrite the extensions. Looking at the diff, there are quite a few more places to update.

**Comment by rgrinberg** [comment]
> Should we just apply this filter systematically on the output of dune? Just so that we don't have to modify the code everywhere to rewrite the extensions. Looking at the diff, there are quite a few more places to update.

I don't think it's enough. There are some tests that inspect the output of artifacts produced by dune (with cat).

**Pull request closed without merging**
