### PR TITLE
Add support for cinaps

### PR DESCRIPTION
**Pull request by diml**
[Cinaps](https://github.com/janestreet/cinaps) is a small tool that allows to auto-generate parts of ml or other source files and keep them in sync. This PR adds integration into dune to make it easier to use it in dune projects.

I still need to write the doc, however this is ready for testing. /cc @ceastlund

### CODE REVIEW

**Comment by rgrinberg** [comment]
Some thing that is a bit weird to me: We developed the entire subsystem feature to stop hard coding integrations with external tools like ppx_inline_test. And yet here we are hard coding cinaps anyway. In this particular case, this tool seems like a simple preprocessor that also edits your source files. Seems like this is something that users should easily write.

This also needs some tests btw.

**Comment by diml** [comment]
Ah yh, I forget to commit the tests.

Yh, I don't disagree for the hardcoded part. Thinking about it, it almost fit in the "inline_tests" system, except that you can't have both inline tests and cinaps snipet at the same time. Additionnally, cinaps can be used on other files than ml files.

But maybe we can use the same idea to have a general stanza and cinaps be just one backend.

**Comment by rgrinberg** [comment]
Okay, well I don't think these concerns should block the feature. However, I think that it would be better if the stanza had to be enabled in the dune-project file until it wasn't so cinaps specific.

**Comment by diml** [comment]
Yh, that makes sense, I'll add that.

**Comment by diml** [comment]
I made it an extension

**Pull request merged**
