### PR TITLE
Make ``dune describe`` correctly handle Reason files

### PR DESCRIPTION
**Pull request by esope**

### CODE REVIEW

**Comment by esope** [comment]
@rgrinberg : should I add a test for reason files ? This would create a dependency to the reason toolchain...

**Comment by rgrinberg** [comment]
You can just add a dummy `refmt` binary and then make it available with `(env (_ (binaries ..)))`

**Comment by esope** [comment]
Thanks. Done in last commit.

**Comment by rgrinberg** [comment]
Thanks

**Pull request closed without merging**
