### PR TITLE
add sandboxing to ocamldep, lint, dialect, pp

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by rgrinberg** [comment]
Thanks Etienne. I'll drop the sandboxing on ocamldep as it's a fairly safe command.

I'd like to keep sandboxing on preprocessing even if it there is a small penalty. It's an issue of correctness for user rules so it's worth making sure these are actually solid.

**Comment by emillon** [comment]
I tried to retime this but TBH the numbers are all over the place with my measuring setup so I don't think we rely on them too much.

**Comment by rgrinberg** [comment]
Let me do some tests as well then.

**Comment by nojb** [comment]
Just now I did some _informal_ tests under Windows doing a build from scratch of the LexiFi codebase, but the difference seems to be noise:

This PR: 4m39 4m29 4m30
3.1.1: 4m35 4m34 4m25

**Comment by Alizter** [comment]
Would it perhaps be more noticeable if we restrict to a single job? `-j1`?

**Pull request merged**
