### PR TITLE
Allow `enabled_if` in executable(s) stanza

### LINKED ISSUE #1690: [question] enabled_if in executable stanza?
Would it make sense to add the `optional` / `enabled_if` field to the executable stanza?

The context is that in the default build of Coq, we may want to skip building some optional binaries [such as CoqIDE] if the right libraries are not present. Note that we are working on a composed build thus this seems like the simplest approach.

### PR DESCRIPTION
**Pull request by voodoos**
Fix #1690 

This PR add support for `enabled_if` in executable(s) stanza.

Any attempt to build an executable whose `enable_if` field evaluates to false will raise a "Don't know how to build" error.

I am unsure whether or not that behaviour is the correct one. Other options are: 
- do nothing 
- warn the user that the `enable_if` field is not satisfied.

### CODE REVIEW

**Comment by rgrinberg** [comment]
> Any attempt to build an executable whose enable_if field evaluates to false will raise a "Don't know how to build" error.

Isn't this the same for libraries with `enabled_if` that evaluates to false?

**Comment by voodoos** [comment]
Yes it is indeed the case.

Current behaviour is: nothing for aliases, "don't know" for rules and libraries, and a more precise error when depending on a disabled library.

```
This alias is disabled, building it should do nothing:
  $ dune build @x

This one is enabled:
  $ dune build @y
  Building alias y

This rule is disabled, trying to build a should fail:
  $ dune build a
  Error: Don't know how to build a
  Hint: did you mean b?
  [1]

This one is enabled:
  $ dune build b
  Building file b

Test the enabled_if field for libraries:

  $ dune build main.exe
  File "dune", line 33, characters 12-15:
  33 |  (libraries foo))
                   ^^^
  Error: Library "foo" in _build/default is hidden (unsatisfied 'enabled_if').
  Hint: try: dune external-lib-deps --missing main.exe
  [1]
```

**Comment by rgrinberg** [comment]
i think this is sufficient for now. thanks.

**Comment by diml** [comment]
Did you check what happens if the executable is public? From a quick glance over the path, it seems to me that Dune would try to build the executable and fail.

**Comment by voodoos** [comment]
I can confirm that attempting to `build @install` a project including disabled public executables will trigger a `don't know how to build error`.

What do you think should be the correct behaviour ?

**Comment by diml** [comment]
I think we should exclude executables with unsatified `enabled_if` clauses from installation. And while reading this code I found a very embarrassing bug: https://github.com/ocaml/dune/pull/3163

Bascially, you should interpret the `enabled_if` in the `keep_if` function that this function modifies.

**Pull request merged**
