### PR TITLE
Byte_complete is an installable mode ?

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by AltGr** [comment]
This doesn't seem to be enough to fix the issue, as dune will still look for  `.bc` instead of `.bc.exe` files afterwards

**Comment by rgrinberg** [comment]
> This doesn't seem to be enough to fix the issue

Could you describe the issue a bit more?

**Comment by AltGr** [comment]
Yes, sorry. If I have an exe with only `modes: byte_complete`, dune won't let me use it for installation with `public_name`. So for example [here](https://github.com/ocaml-sf/learn-ocaml/pull/408/files#diff-bb37305a4fcd08ae553bde364006478a72895d5608c2617cfecfc631c8025425R25) I had to remove `public_name` and define my `install` action manually. The error I get otherwise is:
```
Error: No installable mode found for this executable.
When public_name is set, one of the following modes is required:
- exe
- native
- byte
```

**Comment by rgrinberg** [comment]
Sorry for the (year long) delay. Your diagnosis is correct but the fix is a little more complex. I've updated the PR accordingly.

**Pull request merged**
