### PR TITLE
let%map syntax, but without ppx

### PR DESCRIPTION
**Pull request by diml**
This PR allows us to use the `let%map` syntax in dune, in order to help writing applicative parsers.

## Motivation

The motivation is to turn `Of_sexp.t` which is currently a monadic parser into an applicative parser. Doing so will unlock many features:

- generation of grammars from `Of_sexp.t` values, allowing to easily provide better editor support
- automatic upgraders for jbuild/dune files
- better pretty printers without too much work: we can easily turn a `Usexp.t` value into a richer data type that encodes what is a record, a constructor, etc...

However, writing applicative code without a special let-syntax is a huge pain as one has to do positional matching of arguments.

## Feature description

This PR adds a small preprocessor that turns this:

```ocaml
let%map p1 = e1
and p2 = e2
in
e
```

into:

```
let x1 = e1
and x2 = e2
in
Let_syntax.(fun f -> const f $ x1 $ x2) @@ fun p1 p2 -> e
```

## Implementation

I think it's clear that we don't want to use ppx in dune: too many compatibility issues that require heavy machinery to workaround. Instead this is implemented as a pure text preprocessor. As a result:

- it is a lot faster
- we have the guarantee that it is compatible with all versions of OCaml

The preprocessor generates line directives to ensure that errors are reported at the right place. The only limitation is that it is currently quite rigid regarding the syntax. For instance the above code is not accepted:

```ocaml
let%map p1 = e1 and p2 = e1 in
e
```

and must be written:

```ocaml
let%map p1 = e1
and p2 = e2
in
e
```

or:

```ocaml
let%map p1 = e1
and p2 = e2 in
e
```

With more work on the preprocessor it would be possible to support the first version.

### CODE REVIEW

**Comment by diml** [comment]
This PR also rewrites `bin/main.ml` to use the `let%map` syntax. IMO the result is a lot nicer.

**Comment by diml** [comment]
It's simpler to enable it for everything. It's fast anyway

**Comment by diml** [comment]
Agreed. @gasche do you know if a syntax like this could be added to OCaml directly? It's really painful to write applicative code without it and using ppx is still a difficult choice for many projects.

**Comment by gasche** [comment]
We have had discussions in the past about adding monadic syntax, and they were inconclusive, but maybe we could restart them now. If you have a proposal that also includes applicative syntax in a fluent way, and they work well together, I think you could give it a go. Of course, as you know, these things are always long to build consensus for...

**Comment by emillon** [comment]
In the context of dune, is there a way to make merlin aware of this syntax?

**Comment by diml** [comment]
Hmm, I don't think merlin supports plain preprocessors (/cc @trefis @let-def). For now we'll have to live without merlin support. I think the benefits of the `let%map` syntax still justify it

Given that this preprocessor generates correct line directives, we could actually wrap it with a tool pp-to-ppx that would convert a pp to a ppx. So one possibility would be to write this pp-to-ppx tool.

On the other hand, if we can get something into OCaml directly, then the problem becomes much simpler as we'd only need a compatibility ppx for a fixed set of older OCaml versions. So we could replace this pp by a compatiblity ppx for older OCaml compilers.

I'm personally more interested in the latter solution as it would benefit many more projects.

**Comment by samoht** [comment]
Merlin has a branch to support plain pre-processors: https://github.com/ocaml/merlin/tree/pp it allows to add `-pp '...'` in the `FLG` lines.

**Comment by let-def** [comment]
We plan to merge it in a few days, I would be happy to have a few more testers before :).

**Comment by let-def** [comment]
They are enabled with `FLG -pp command`.
The filename that is passed to the binary is a temporary one and in `# file line` directives, the filename is ignored (only the buffer name of the editor is considered)

**Comment by diml** [comment]
Great! Happy to try that.

> The filename that is passed to the binary is a temporary one and in # file line directives, the filename is ignored (only the buffer name of the editor is considered)

The preprocessor in this PR does the following: if it is given file "foo.ml" as input, it generates line directives of the form:

- for portions of code copied from the foo.ml: `# 42 "foo.ml"`
- for generated code blocks: `# 42 "foo.ml.generated"`

is that compatible with what merlin expects?

**Comment by rgrinberg** [comment]
Silly question, but would merlin preprocess the file again internally? I know that this probably doesn't matter for fast pp's like this one, but if that's the case then the design of this feature seems odds. dune already provides the unpreprocessed and preprocessed versions of the source, why should merlin do its own pp'ing again?

**Comment by let-def** [comment]
Because the file is not on the disk but in the editor.

**Comment by let-def** [comment]
@diml If it works with ocaml, it should be fine for Merlin.

**Pull request merged**
