### PR TITLE
Update the vendored incremental-cycles

### PR DESCRIPTION
**Pull request by Armael**
This PR updates the `incremental_cycles` vendored library to its last version.

I want to get this PR in before we start touching `incremental_cycles` as discussed in #2959 . 

This update comes with a minor API change for the [raw_add_edge] function, so I updated dag.ml accordingly. I wanted to make sure that the API change is properly accounted for, as it could be easily overseen.

### CODE REVIEW

**Comment by Armael** [comment]
To be clear: the PR was crafted by simply updating the hash in the vendoring script, running the script, and updating `dag.ml` manually.

**Comment by ejgallego** [comment]
Thanks @Armael , I'll rebase #2959 on top of this.

**Comment by ejgallego** [comment]
@Armael the signed-off-by is missing from the commit; also, maybe you want to add a changelog entry?

**Comment by Armael** [comment]
Thanks, I just added the signed-off. Not sure this needs a change entry though.

**Comment by ejgallego** [comment]
> Not sure this needs a change entry though.

I guess adding a summary of what's changed upstream [either in the commit message or in CHANGES] would help dune devs to understand what's new in the lib in case some problem pops up.

**Comment by diml** [comment]
Let's keep it simple. The update script has the commit hash, so we can always look at the git log between the two commits.

**Comment by diml** [comment]
Thanks for the PR!

**Comment by Armael** [comment]
To be clear: the code should be observationally equivalent. I think the changes were mostly this small refactoring, and documentation/cleanups.

**Pull request merged**
