### PR TITLE
doc: split stanza documentation in several files

### PR DESCRIPTION
**Pull request by emillon**
The HTML output is identical (this is like a preprocessor include) but this makes the source file a lot smaller.

### CODE REVIEW

**Review by rgrinberg — APPROVED** [review]
Thanks. I assume there's no changes to the documentation text itself here.

**Comment by emillon** [comment]
No. There's just a minor change: `js_of_ocaml` was between `executable` and `executables` since #6824 but this also fixes it.

**Comment by esope** [comment]
Well, `js_of_ocaml` is not a stanza: rather, it is an option of `executable` and `library`. It used to belong to the doc of `library`, but I moved it to `executable` because `executable` moved before `library`.
Should `js_of_ocaml` have its dedicated file in spite of not being a stanza?

**Comment by rgrinberg** [comment]
We have a whole separate doc page for jsoo, don't we? I suppose we should keep the doc there and link to it from the appropriate stanzas?

**Pull request merged**
