### PR TITLE
tui: add more interactions

### PR DESCRIPTION
**Pull request by Alizter**
We add some more features to the `--display tui` mode.

Waiting for #7663 

Features:
- Messages to the user a separated with a rule and include a numbering together with total number of messages.
- Horizontal and vertical scroll bars which can be controlled using the arrow keys, `j` and `k` or by interacting with the mouse including scrolling and clicking. (Horizontal scrolling is done with Meta (alt) + Scroll.
- Help screen activated with `h` or `?` explaining what keys do what.
- Debug features:
  - Pressing 'd' will output some debug info about the state of the UI.
  - Pressing Meta + `l` will make dune output a lorem ipsum, allowing to quickly test any issues with scrolling. (I want to keep this in as it is harmless and out of the way).

#### How to test:
Just run
```console
./dune.exe build @install
_build/install/bin/dune build @check -w --display tui
```

#### Compatibility
- Linux
  - [x] Alacritty, works fine, this is in the screenshots
  - [x] xterm, works but meta + l is sometimes ignored
  - [x] gnome console, works fine
- [ ] macos
- [ ] windows
  - [ ] cmd
  - [ ] wsl

#### Issues
- [ ] Exceptions are not printed when in tui mode. We need to have a fallback display. For example, running two watch mode tui's will cause the second one to crash silently and return to the prompt since Dune will complain about the _build lock. We should probably add a way internal exceptions can be displayed or printed nicely.
- [x] Needs to look good on light terminals, the colors used are somewhat ad-hoc. We need to make them more configurable and then adapt based on terminal colors chosen.

### CODE REVIEW

**Comment by rgrinberg** [comment]
do we really need a confirmation? to me this is something more annoying than useful

**Comment by Alizter** [comment]
@rgrinberg Sure I can remove it no problem. Its good to demonstrate extra state tracking for the UI though.

**Comment by rgrinberg** [comment]
Can you extract resizing into a separate PR?

**Comment by Alizter** [comment]
@rgrinberg It's not working completely for me, I will make a separate PR when I get it to work.

**Comment by Alizter** [comment]
Here is a screenshot of the latest features:
image
Here you can see:
- The help screen
- The horizontal and vertical scrollbars (controlled with scroll and meta (alt) + scroll)
- Message separation with numbering

This needs:
- more testing, especially on edge cases.
- update help page for more info (debug and scroll)
- mouse interaction with scroll bars?

**Comment by Alizter** [comment]
This is being worked on at the moment but will come as a different PR.

**Pull request closed without merging**
