### PR TITLE
Some GC stats were missing

### PR DESCRIPTION
**Pull request by rgrinberg**
This adds some useful stats to the catapult counters. @emillon was there a reason why most stats were omitted?

### CODE REVIEW

**Comment by emillon** [comment]
The main reason I omitted them is that it makes a crowded output (so I wanted to limit to only useful ones if possible), but we can add all of them.

**Comment by rgrinberg** [comment]
@emillon note that one weakness in the current catapult API is that there's no way to output float counters. I've added a hack for this, do you think it's worth making an issue?

**Comment by emillon** [comment]
Regarding float counters, this solution is fine. If we need to emit a float counter from the rest of the code, we can either expose a float version, or emit all counters as floats.

**Comment by diml** [comment]
BTW, these counters will always be integer values, so we can simply emit the integer part.

**Pull request merged**
