### PR TITLE
Remove all invalid_arg from codebase

### PR DESCRIPTION
**Pull request by rgrinberg**
Exn.code_error should be used everywhere

Signed-off-by: Rudi Grinberg <rudi.grinberg@gmail.com>

### CODE REVIEW

**Comment by aalekseyev** [comment]
I guess it's not actually "much" worse when the sexp is rendered for human consumption:

`("Invalid text in unquoted template" ("s" "x%{"))`

vs

`("Invalid text in unquoted template" "x%{")`

But still.

**Comment by rgrinberg** [comment]
> A lot of exceptions look much worse now, such as:

It's only in the toplevel. Where we don't seem to install proper exception printers. In fact, if you ever get such exceptions when running dune they will look much better.

> maybe the answer is that we want all errors to be in sexp format, which is fair enough)

It's just that it's easier to provide info in a code error. You immediately see the value of relevant variable. With `invalid_arg`, the variables and the message are mixed.

> Why does code error need to have such a rigid sexp structure? Can't we have this as a sexp?

I'm not against this. I think that this could possibly be an improvement. This is how base does it, right?

**Comment by aalekseyev** [comment]
> With invalid_arg, the variables and the message are mixed

Fair enough, seems good.

> This is how base does it, right?

In base there is no concept of "code error". The closest related thing is `Error.t`, which, yeah, you basically always construct directly from a sexp (`val create_s : Sexp.t -> Error.t`).

**Comment by rgrinberg** [comment]
> In base there is no concept of "code error". The closest related thing is Error.t, which, yeah, you basically always construct directly from a sexp (val create_s : Sexp.t -> Error.t).

What I had in mind is `raise_s`.

**Comment by aalekseyev** [comment]
Oh, yeah.

**Pull request merged**
