### PR TITLE
Initial Camlp5 support 

### PR DESCRIPTION
**Pull request by Kakadu**
This is my progress on issue https://github.com/ocaml/dune/issues/4193 The initial version to collect feedback about implementation, @rgrinberg 

- [x] Test
    The test build a camlp5 preprocessor and a library that uses this preprocessor
- [x] Camlp5 subsystem
    It was easier to me to implement it in the same manner as PPX (having PPX rewriter subsystem as an example)
- [ ] Fix dune-package file for Camlp5
    For now I have a desired dune-package fie in examples, it not yet added into camlp5 repo. It requries a symlink for the test example to pass (see README in the tests directory)
- [ ] Get rid of `dune-package` file for Camlp5 and parse all possible information from META file
     Right now this feature is postponed. It seems that dune can't parse information even about PPX rewriters from META, so I don't yet have a nice example which I should use as base. 
- [ ] The file `preprocessing.ml` requires some refactoring. 
     For now I copy pasted some functions from PPX. Don't know yet have to refactor it in the most desirable way
- [ ] Decide what to do with sorting of dependencies. 
     Packages with camlp5-based rewriter do not have a 100% correct order, so it should be controlled by end-user. Moreover, repeating the same package twice makes a sense. Dune by default sorts all dependencies alphabetically before computing digest. I disabled it, no idea what implications will be. Can you help?
- [ ] Loading camlp5 packages to utop is not yet implemented

### CODE REVIEW

**Comment by jeremiedimino** [comment]
Hi @Kakadu,

Happy to give you some pointers to hack on Dune, but just to be clear at this point there is no agreement in principle that this PR will be accepted.

Have you considered alternatives? Such as using camlp5 via `(pps (action ...))`, and if so what are the limitations?

**Comment by Kakadu** [comment]
> Happy to give you some pointers to hack on Dune, but just to be clear at this point there is no agreement in principle that this PR will be accepted.

I hope that PR will make you reach an agreement faster. Maybe It will make you reconsider adding plugin support to dune to push burden of support about this to others. At least, if it will make you add more comments about what subsystem concept means, it would be great. I'm not 100% sure that I understand it right.

> Have you considered alternatives? Such as using camlp5 via `(pps (action ...))`, and if so what are the limitations?
Yes, currently I'm using exactly that. But I'm worrying that is is not a clean solution
* I need to manually support META file because dune can't generate camlp5 information and I can't use templates because ocamlfind can't merge subpackages as I want. 
* This external rewriter relies on `mkcaml5` tool which relies on ocamlfind's package. I don't know how it will work in case of vendored repositories. (It think it won't).

**Comment by jeremiedimino** [comment]
> I hope that PR will make you reach an agreement faster. Maybe It will make you reconsider adding plugin support to dune to push burden of support about this to others. At least, if it will make you add more comments about what subsystem concept means, it would be great. I'm not 100% sure that I understand it right.

Being extensible is one of the goals of Dune: https://dune.readthedocs.io/en/stable/goals.html

However, we are also very mindful about backward compatibility, and right now our APIs are simply not mature enough to be publicised. Once they are, we will happily make Dune extensible. The good news is that we are doing a lot of work on the core of Dune, and as a result the core APIs are getting more love. So we are getting there, slowly but surely.

Now, even once Dune will be extensible, we still want the features that are the most important to the community to be part of Dune. If support for camlp5 was such as feature, then it would make sense to add support for it in Dune. So happy to discuss here whether it is or not.

In any case, one option is for your to maintain a fork of Dune until it is extensible. FTR, that's what we started doing inside Jane Street given that the current Dune language is not enough for Jane Street needs. But just a heads up that the core of Dune has been changing quite a lot recently, and I expect this to continue for a few more months until it stabilises. 

> - I need to manually support META file because dune can't generate camlp5 information and I can't use templates because ocamlfind can't merge subpackages as I want.

You lost me there.

> - This external rewriter relies on mkcaml5 tool which relies on ocamlfind's package. I don't know how it will work in case of vendored repositories. (It think it won't).

You can call `ocamlfind` inside Dune rules, as long as you declare the right dependencies. For instance, we call `ocamlfind` in cram tests in the Dune testsuite. If you declare a dependency on `(package x)`, then `ocamlfind ... -package x` will work inside the rule. It works with vendored repositories. The only pitfall is that `(package x)` is likely a big sur-approximation of what you need, and so the build might be a bit slower than it could be. But depending on the size of your repository, that might be acceptable.

**Comment by bikallem** [comment]
@chetmurthy could be of interest to you.

**Comment by Kakadu** [comment]
> > * I need to manually support META file because dune can't generate camlp5 information and I can't use templates because ocamlfind can't merge subpackages as I want.
> 
> You lost me there.

Let's say that we need to generate package `P.A` , `P.B` and `P.camlp5_rewriter`. let's say dune can generate META for `P.A` and `P.B`. The package `P.camlp5_rewriter` should have camlp5-specific lines in META, and before my patch dune can't generate right META, the only way to have right META installed for `P.camlp5_rewriter` is to write this META by hand. So we could try the following contents of `META.P.template`.

```text 
% dune-generate code goes above %
package "P" {
  package "camlp5_rewriter" {
     stuff
  }
}
```

but it will not work because the final META file will have two lines `package "P" {` and ocamlfind will complain about package P declared twice. So, the only way I see is to writer entire META by hands or patch ocamlfind somehow

> > * This external rewriter relies on mkcaml5 tool which relies on ocamlfind's package. I don't know how it will work in case of vendored repositories. (It think it won't).
> 
> You can call `ocamlfind` inside Dune rules, as long as you declare the right dependencies. For instance, we call `ocamlfind` in cram tests in the Dune testsuite. If you declare a dependency on `(package x)`, then `ocamlfind ... -package x` will work inside the rule. It works with vendored repositories. The only pitfall is that `(package x)` is likely a big sur-approximation of what you need, and so the build might be a bit slower than it could be. But depending on the size of your repository, that might be acceptable.

It sounds too good to be true, I need to do some experiments....

**Comment by jeremiedimino** [comment]
I was thinking about this again yesterday evening and it occurred to me that Dune's ppx support should be generic enough to support camlp5. For instance, Dune's doesn't know about ppxlib. Instead, [ppxlib declares itself as a driver](https://github.com/ocaml-ppx/ppxlib/blob/4112b163b8850e900e62613b7f730826ebe21538/src/dune#L9). So declaring such a driver for camlp5 should be enough.

The idea would be to write a small library as follow:

```
(library
 (name camlp5_driver)
 (libraries camlp5)
 (ppx.driver
  (main Camlp5_main.main)))
```

(I made up the `Camlp5_main.main` name, I don't know how the entry point of Camlp5 is called)

and then the following should work:

```
(library
 (name mylib)
 (preprocess (pps camlp5_driver pa_foo pa_bar ...)))
```

Modulo some details:
- the various cma/cmxa files for the `pa_xxx` plugins must be compiled with `-linkall`. FTR, adding `(kind ppx_rewriter)` to a library causes it to be linked with `-linkall`. If that's not the case at the moment, for the sake of the experiment you can pass `~link_args:(Action_builder.return (Command.Args.A "-linkall"))` to the call to `Exe.build_and_link` in `src/dune_rules/preprocessing.ml`
- Dune assumes that the ppx driver accepts the arguments `--impl`/`--intf`, while camlp5 accepts `-impl`/`-intf`. You can change these in `src/dune_rules/command.ml` (function `ppx_driver_arg`)

If this is successful, we can then add all that properly to Dune. For instance:
- we could make the `--impl`/`--intf` flags configurable via the `ppx.driver` field
- calling `camlp5` a ppx driver might be a bit odd, so we could generalise the terminology:
  + `(ppx.driver ...)` --> `(pp.driver ...)`
  + `(kind ppx_rewriter)` --> `(kind preprocessor)`
- add an encoding of `pp.driver` in META files, so that camlp5 can declare itself as a driver without having to switch to Dune

**Comment by bikallem** [comment]
@Kakadu Interesting discussion here. Just out of curiosity and slightly off tangent. Will using camlp5 as a ppx also work with `ocamlformat` and `merlin/ocaml-lsp`? Referencing your post from the forum, it seems not - at least with merlin 'https://discuss.ocaml.org/t/using-merlin-with-camlp5/7082 - right? I also want to explore using camlp5 but wasn't sure how it interacted with other ocaml tools in the ecosystem.

**Comment by jeremiedimino** [comment]
Well, for merlin and ocamlformat you have another issue: camlp5 allows you to extend the OCaml syntax. If you do that, then `ocamlformat` and `merlin` won't able to parse the file. That being said, I remember that some support for generic preprocessors was added to merlin, so there might be a way to make it work, but I'm not 100% sure. /cc @voodoos

If you use camlp5 without changing the syntax, for instance to rewrite some extension points, then there is no reason it wouldn't work with ocamlformat and merlin. You'd just need to add one feature to camlp5 to make it work, and that is the ability to be invoked as a ppx rewriter. i.e. something like this:

```
$ camlp5_driver.exe -as-ppx <flags> <input-file> <output-file>
```

where:
- `<input-file>` is the name of a file containing the marshaled AST to rewrite
- `<output-file>` is the name of the file the processed AST should be marshaled to

**Comment by Kakadu** [comment]
> @Kakadu Interesting discussion here. Just out of curiosity and slightly off tangent. Will using camlp5 as a ppx also work with `ocamlformat` and `merlin/ocaml-lsp`? Referencing your post from the forum, it seems not - at least with merlin 'https://discuss.ocaml.org/t/using-merlin-with-camlp5/7082 - right? I also want to explore using camlp5 but wasn't sure how it interacted with other ocaml tools in the ecosystem.

The current merlin issue is here: https://github.com/ocaml/dune/issues/4169

**Comment by Kakadu** [comment]
> Modulo some details:
> 
>     * the various cma/cmxa files for the `pa_xxx` plugins must be compiled with `-linkall`. FTR, adding `(kind ppx_rewriter)` to a library causes it to be linked with `-linkall`. If that's not the case at the moment, for the sake of the experiment you can pass `~link_args:(Action_builder.return (Command.Args.A "-linkall"))` to the call to `Exe.build_and_link` in `src/dune_rules/preprocessing.ml`
>     * Dune assumes that the ppx driver accepts the arguments `--impl`/`--intf`, while camlp5 accepts `-impl`/`-intf`. You can change these in `src/dune_rules/command.ml` (function `ppx_driver_arg`)

Currently, camlp5 syntax packages should not be reordered automatically (I made some changes in the module that computes digest) and should be loaded more then once if they appear in the packages list more then once. @jeremiedimino, can this peculiarities somehow affect the design you proposed?

**Comment by chetmurthy** [comment]
I haven't been following any of this, but: it's not clear to me how this can work.  Camlp5's input is always OCaml -source-, not serialized OCaml AST.  Camlp5 can emit either OCaml source or serialized OCaml AST, though.  Is that a problem?

Adding options to camlp5's driver as you propose shouldn't be problematic (though I haven't looked closely).

**Comment by jeremiedimino** [comment]
@Kakadu, Dune should be conservative regarding the order, unless libraries are written in the wrong dependency order. Regarding loading the same package more than once, that won't work unfortunately. Does camlp5 rely on (private) dynamic linking to make that work? AFAIK, it is not possible to statically link the same OCaml compilation twice and Dune links drivers statically.

@chetmurthy that's fine, Dune passes the source file to the ppx driver. For reference, [here](https://github.com/ocaml/dune/issues/4284#issuecomment-786061032) are some diagrams showing Dune's compilation pipeline.

**Comment by Kakadu** [comment]
> @Kakadu, Dune should be conservative regarding the order, unless libraries are written in the wrong dependency order.

@jeremiedimino, Here https://github.com/ocaml/dune/blob/main/src/dune_rules/preprocessing.ml#L51 dune sorts dependencies in the  alphabetical order. I believe it's called *not* being conservative

> Does camlp5 rely on (private) dynamic linking to make that work? AFAIK, it is not possible to statically link the same OCaml compilation twice and Dune links drivers statically.

AFAIU, yes, but @chetmurthy knows better.

**Comment by Kakadu** [comment]
Maybe in the place where preprocessing subsystem will be declared we can have a new switch which 
1) either tells that `ppx.exe` should be built by dune (is it is happening now)
2) or it should be outsourced to a tool called 'mkcamlp5' (or something)  which will take packages that should be linked together as an input.

**Comment by chetmurthy** [comment]
Regarding loading libraries:

(1) camlp5 loads .cmo files given on the commandline, and can also look in directories specified on the commandline.  E.g. something like `camlp5 -I <dir1> -I <dir2> a.cmo b.cmo ....`

(2) This behaviour can be invoked directly by passing arguments to camlp5, but when used with ocamlfind, typically ocamlfind is given packages with preprocessor speciications, and those specs are what add .dmo files to the camlp5 cmdline.

(3) So you specify a findlib package like `pa_ppx.deriving_plugins.std` and this causes various .cmo files to be added to the camlp5 cmdline.

**Comment by jeremiedimino** [comment]
> @jeremiedimino, Here https://github.com/ocaml/dune/blob/main/src/dune_rules/preprocessing.ml#L51 dune sorts dependencies in the alphabetical order. I believe it's called not being conservative

Indeed, I forgot that part. We had an issue the past with ocaml-migrate-parsetree re-ordering passes to minimise the number of AST migrations. We ended up adding a `position:int` argument to the function that registers a ppx rewriter with the ocaml-migrate-parsetree driver so that rewriters could be re-ordered at runtime. Could something similar be done for camlp5?

> or it should be outsourced to a tool called 'mkcamlp5' (or something) which will take packages that should be linked together as an input.

By packages, do you mean `.cma` and `.cmo` files or actually passing `-package <name>` to `mkcamlp5`? With the latter, we would have to make sure that `mkcamlp5` and Dune resolve the package names in the same way, and that is not currently supported for private libraries.

But from @chetmurthy's last answer, it seems to me that we can reason at the level of .cm files here and not involve ocamlfind package names, which simplifies thing as we can let Dune do the name resolution logic once and for all, as we do in the rest of the code base.

Now, regarding calling `mkcamlp5` rather than doing the linking manually with `ocamlc`/`ocamlopt`, that could be done but that's also an additional code path to test and maintain. It would be better if we could do the same for ppx and camlp5. What does `mkcamlp5` do?

**Comment by Kakadu** [comment]
> Now, regarding calling `mkcamlp5` rather than doing the linking manually with `ocamlc`/`ocamlopt`, that could be done but that's also an additional code path to test and maintain. It would be better if we could do the same for ppx and camlp5. What does `mkcamlp5` do?

```
➜  /tmp mkcamlp5 -syntax camlp5 -package camlp5.pa_o,camlp5.pr_o,camlp5.extend,camlp5.extfold,camlp5.quotations -verbose
ocamlfind ocamlc -predicates syntax,preprocessor,byte -package camlp5,camlp5.pa_o,camlp5.pr_o,camlp5.extend,camlp5.extfold,camlp5.quotations -verbose -linkall -linkpkg link25270.ml -syntax camlp5 odyl.cmo
ocamlfind: [WARNING] Package `camlp5.extend': camlp5.extend SHOULD NOT be used with camlp5.pa_o
Effective set of preprocessor predicates: preprocessor,syntax,camlp5
Effective set of compiler predicates: pkg_camlp5,pkg_camlp5.pa_o,pkg_camlp5.pr_o,pkg_camlp5.extend,pkg_camlp5.extfold,pkg_camlp5.quotations,syntax,autolink,byte,syntax,preprocessor,byte
+ ocamlc.opt -verbose -linkall -I /home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5 \
      -pp "camlp5 -nolib \
        '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' \
        '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' \
        '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' \
        'odyl.cma' 'camlp5.cma' 'pa_o.cmo' 'pr_o.cmo' 'pr_op.cmo' 'pa_extend.cmo' 'pa_extfold.cmo' 'q_MLast.cmo'      " \
    /home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5/odyl.cma 
    /home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5/camlp5.cma /home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5/pa_o.cmo /home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5/pr_o.cmo /home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5/pr_op.cmo /home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5/pa_extend.cmo /home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5/pa_extfold.cmo /home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5/q_MLast.cmo \
    link25270.ml odyl.cmo
+ camlp5 -nolib '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' '-I' '/home/kakadu/.opam/4.10.1+fp+flambda/lib/camlp5' \
    'odyl.cma' 'camlp5.cma' 'pa_o.cmo' 'pr_o.cmo' 'pr_op.cmo' 'pa_extend.cmo' 'pa_extfold.cmo' 'q_MLast.cmo' \
    'link25270.ml' > /tmp/ocamlpp41c440
```
And generated file `linkXXXXX.ml` contains `Dynlink.set_allowed_units [  something..... ] `. @chetmurthy  should know better

**Comment by jeremiedimino** [comment]
@chetmurthy, what is the purpose of the `linkXXXXX.ml` file?

**Comment by chetmurthy** [comment]
The file is generated here: https://github.com/camlp5/camlp5/blob/fa6dfa4d238c18669fcfa5f52c000a8a40302023/etc/mkcamlp5.pl#L68
(1) mkcamlp5 generates an executable
(2) but that executable, when invoked, can of course be passed more .cmo files on the cmdline.
(3) the generated file specifies which interfaces are made visible to those to-be-dynamically-linked files.
(4) So probably, it's safe to make it empty.

Sadly, I didn't document this (and I don't know where the old camlp5 7.xx documentation is).  This needs to be fixed.  I'll get that done.

**Comment by Kakadu** [comment]
> The file is generated here: https://github.com/camlp5/camlp5/blob/fa6dfa4d238c18669fcfa5f52c000a8a40302023/etc/mkcamlp5.pl#L68
> (1) mkcamlp5 generates an executable
> (2) but that executable, when invoked, can of course be passed more .cmo files on the cmdline.
> (3) the generated file specifies which interfaces are made visible to those to-be-dynamically-linked files.
> (4) So probably, it's safe to make it empty.
> 
> Sadly, I didn't document this (and I don't know where the old camlp5 7.xx documentation is). This needs to be fixed. I'll get that done.

Do I understand that right: if we replace mkcamlp5 by `ocamlfind c -linkall` it will still be able to generate valid rewriter but it will not be possible to pass extra `cmo`'s to the final rewriter (which is not needed in the case of dune)?
Do the same happens for `mkcamlp5.opt`? (I heard somewhere that dynlinking in native code doesn't work or is at least tricky)

**Comment by jeremiedimino** [comment]
@chetmurthy thanks for the explanation.

@Kakadu my understanding is that if you replace `mkcamlp5` by `ocamlfind c -linkall` (or `ocamlc -linkall`), then you will still be able to pass extra cmo's, however these cmo's will be able to reference more modules than they would be able to if they were loaded in a program produced by `mkcamlp5`. `Dynlink.set_allowed_units` restricts what dynamically loaded modules can reference. Without this call, there are no restrictions.

**Comment by rgrinberg** [comment]
Please re-open if you're going to work on this.

**Pull request closed without merging**
