### PR TITLE
Split csexp_rpc from rpc

### PR DESCRIPTION
**Pull request by rgrinberg**
As requested by @jeremiedimino

### CODE REVIEW

**Comment by rgrinberg** [comment]
@jeremiedimino there is another disadvantage to merging create + {connect,serve}: we can no longer call `close` before successfully connecting to the socket.

**Comment by jeremiedimino** [comment]
Do we need that?

**Comment by rgrinberg** [comment]
We could rewrite the code with this signature:

```
val create : .. -> (t * Session.t Fiber.Stream.In.t) Fiber.t
```

But then the call to `Scheduler.Rpc.stop` will be more complicated and will have to do the same state management.

So I guess it's just a matter of choosing where this state management should live.

**Comment by jeremiedimino** [comment]
Alright, let's keep it as it. As mentioned in the other PR, we could use `Unix.sockaddr` for this (low-level) API rather than a custom `Address.t` type. That's up to you.

**Review by jeremiedimino — APPROVED** [review]
LGTM

**Pull request merged**
