### PR TITLE
refactor(merlin): remove `Ocaml_flags.common` and use `Lib_mode.t` ac…

### PR DESCRIPTION
**Pull request by anmonteiro**
…ross the board

Addresses the comments in this thread: https://github.com/ocaml/dune/pull/7398#discussion_r1147238233

### CODE REVIEW

**Comment by rgrinberg** [comment]
@voodoos is adding `-g` to the merlin flags to OK?

**Comment by anmonteiro** [comment]
Looks like merlin has at least some handling for it https://github.com/ocaml/merlin/blob/85ad3a6b09edbf54685eb8e962e82c209f409951/src/ocaml/parsing/ast_mapper.ml#L911

**Review by jchavarri — APPROVED** [review]
Thanks!

**Comment by voodoos** [comment]
> @voodoos is adding `-g` to the merlin flags to OK?

Merlin ignores the flags and the value is always passed as `false` to the vendored parser/typer.

**Pull request merged**
