### PR TITLE
Add DUNE_WORKSPACE env var

### LINKED ISSUE #1053: Customize workspace via environment variable
# Problem

It's quite useful to be able to customize builds opam builds in bulk without having to edit build scripts.

# Proposal

We already have a mechanism for making build customization that are never part of a release build and hence can always be inserted. This mechanism is the workspace file which can now be used to select the profile, change standard compiler flags, among other things. Being able to specify this workspace file more easily would open to door to adding a flag to an entire opam switch without changing a single build script.

There are 2 possibilities to implement this future. One is to allow users to specify the workspace contents in the env var. The other possibility is to have the user input a filename. Both are almost interchangeable and have their own minor adjustments. I don't have a particular preference towards either one.

### PR DESCRIPTION
**Pull request by rgrinberg**
This variable is equivalent to setting --workspace.

Fix #1053

### CODE REVIEW

**Comment by andreypopp** [comment]
Had a discussion about this feature with @rgrinberg.

Some background: when calling `dune` from inside esy environment we want all invocations to have the following arguments passed:

- `--only-packages $cur__name` where `$cur__name` is the name of the package currently being built, so `dune` builds only the current package and won't try to build others (others are provided by esy via ocamlfind config).
- `--root .` so `dune` won't try to climb up

This is not just about an invocation to build a package in release mode (`dune build -p $cur__name` is fine). In dev mode we want
```
esy dune build --only-packages $cur__name --root .
```
and then for any other dune `COMMAND` we want
```
esy dune COMMAND --only-packages $cur__name --root .
```
We really don't want to make users specify this long command lines.

@rgrinberg suggested that `DUNE_WORKSPACE` could help with that if it would allow to configure those two things above. Thus the feature request — could dune make `--root` and `--only-packages` configurable via dune-workspace?

If `DUNE_WORKSPACE` would be useful for esy then we want to generate it and supply to build env. In this case it would be more ergonomically if we could put the actual config value inside `DUNE_WORKSPACE` not the filename of the file which contains the config value. Just not to deal with on-the-fly generated files.

**Comment by diml** [comment]
> Thus the feature request — could dune make --root and --only-packages configurable via dune-workspace?

Making `--root` configurable via the `dune-workspace` file might be a bit annoying as we decide what root is quite early. We could add an environment variable for it though. Allowing `--only-packages` in the `dune-workspace` file might work.

> If DUNE_WORKSPACE would be useful for esy then we want to generate it and supply to build env. In this case it would be more ergonomically if we could put the actual config value inside DUNE_WORKSPACE not the filename of the file which contains the config value. Just not to deal with on-the-fly generated files.

That seems fine to me.

**Comment by rgrinberg** [comment]
Not having `--root` configurable via the workspace file seems fine to me. @andreypopp are you ok with:

* Have `DUNE_WORKSPACE` take an sexp value. I think we can also allow users to provide paths if they prefix the value with `@`. I.e. `DUNE_WORKSPACE=@/path/to/dune.workspace`.

* Have `--root` configurable only via the command line.

**Comment by rgrinberg** [comment]
@andreypopp Is it correct to say that you don't really need this feature and don't plan on relying on it in esy?

**Comment by rgrinberg** [comment]
In which case I will revert the feature to its original design. Taking a file path is more symmetric with how the command line works anyway.

**Comment by rgrinberg** [comment]
I'm including this PR as it was designed originally. To be honest, even if esy needs this feature we'd be better if they just generated a file. As mentioned before, the error messages will be better.

**Pull request merged**
