### PR TITLE
Stop installing the ocaml-syntax-shims binary

### PR DESCRIPTION
**Pull request by ghost**
Instead, I created a separate repository for this project. The advantages are:

- once we stop using it in dune itself we won't need to maintain it anymore
- the project can evolve on its own and become more complex. In particular, I'd like to re-implement it more cleanly by copying the whole OCaml parser, provide it as a library so that it can be used in conjunction with other ppx rewriters, etc...

### CODE REVIEW

**Review by rgrinberg — APPROVED** [review]

**Comment by rgrinberg** [comment]
Should we fix the opam package generation to add this dependency whenever it finds it?

**Comment by diml** [comment]
Yh, that seems like a good feature, but at the same time it feels like quite a bit of work for something that is not used that often.

**Comment by avsm** [comment]
This (I think) breaks dune 1.11 projects using it:

```
#=== ERROR while compiling duniverse.1.0.0+dune ===============================#
423    # context              2.0.5 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(git+https://github.com/avsm/duniverse.git#d691b892)
424    # path                 ~/.opam/4.07/.opam-switch/build/duniverse.1.0.0+dune
425    # command              ~/.opam/4.07/bin/dune build -p duniverse -j 71 @install
426    # exit-code            1
427    # env-file             ~/.opam/log/duniverse-18366-968dd0.env
428    # output-file          ~/.opam/log/duniverse-18366-968dd0.out
429    ### output ###
430    # File "stdune/dune", line 4, characters 13-26:
431    # 4 |  (preprocess future_syntax)
432    #                  ^^^^^^^^^^^^^
433    # Error: Program ocaml-syntax-shims not found in the tree or in PATH
434    #  (context: default)
435    
436 
```

If this is rarely used to be a breaking dune 1.0 -> 2.0 change that's fine; just thought I'd flag this up.

**Comment by diml** [comment]
Indeed. I grepped the dune-universe and couldn't any package using this feature. Otherwise we could do the same as for the dune-configurator split: https://github.com/ocaml/opam-repository/pull/14851

**Pull request merged**
