### PR TITLE
refactor: better path maps and sets

### PR DESCRIPTION
**Pull request by rgrinberg**
Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Review by snowleopard — COMMENTED** [review]
That's... a lot of duplicated code. Do you at least get good results in benchmarks?

**Comment by snowleopard** [comment]
> That's... a lot of duplicated code. 

Can we get rid of some code duplication using functors? I feel like it's going to be hard to maintain this in the long run: people will be making changes to sets/maps and forgetting to update the corresponding code for paths.

**Comment by rgrinberg** [comment]
Yeah, it's definitely not optimal. Let me see if this change is at all useful first. Then I can work on removing some duplication.

**Comment by snowleopard** [comment]
Oh, we're getting pretty nice figures from the benchmark bot!

**Comment by Alizter** [comment]
@snowleopard The figures in the benchmark bot have been mostly garbage, I think its best to ignore it for now. Even doc PRs were getting wild numbers.

**Comment by snowleopard** [comment]
> @snowleopard The figures in the benchmark bot have been mostly garbage, I think its best to ignore it for now. Even doc PRs were getting wild numbers. Hopefully it will be turned off soon.

Oh, that's sad.

> (It actually has started posting as a table).

Yay! :)

**Comment by rgrinberg** [comment]
@snowleopard This PR does seem to give a significant drop to major collections for clean builds. Could you send it through a round of benchmarks internally? If the results are promising, I can clean it up and remove some of the duplication.

**Comment by snowleopard** [comment]
@rgrinberg Could you import it internally? I'll kick off some benchmarks!

**Comment by rgrinberg** [comment]
@snowleopard IIRC you benched this and didn't get a positive change, right?

**Comment by snowleopard** [comment]
> @snowleopard IIRC you benched this and didn't get a positive change, right?

It's a positive change, particular for small builds (for some reason?). But larger builds, it's below 1% speed up, and no savings in memory. Given the size of the diff, not sure it's really worth it.

**Comment by snowleopard** [comment]
Maybe we should try a different approach, and try to eradicate `Path.Map`s altogether, and instead keep multiple different maps where that's necessary?

**Comment by rgrinberg** [comment]
> Maybe we should try a different approach, and try to eradicate Path.Maps altogether, and instead keep multiple different maps where that's necessary?

I fear that we'll end up having to keep just as much as code, but without the abstraction to help us. Also, the other problem is that I don't know where this change is necessary - if at all. Before writing this PR, I imagined it would be helpful everywhere and this representation is strictly superior almost everywhere. But judging by the benchmarks, the improvement seems rather underwhelming.

By the way, now that we have unboxed option, we could make empty sets/maps be 1 word. That would truly make this PR strictly superior. Although again i'm not sure if it will at all matter.

I was much more interested in seeing reduction in memory, and that didn't work out at all. I'll let you judge if the performance benefits are worth it. For the kind of workspaces I'm working with, it doesn't seem like it's worth it. Closing until there's further interest in such tiny speed-ups.

**Comment by snowleopard** [comment]
I think we should come back to this at some point in future when we start to put more effort into optimisation.

**Comment by snowleopard** [comment]
Thanks for the experiment! We did learn something new, so it wasn't a waste of time.

**Pull request closed without merging**
