### PR TITLE
fix(coq): fix duplicate dir targets being detected before theories

### PR DESCRIPTION
**Pull request by Alizter**
Signed-off-by: Ali Caglayan <alizter@gmail.com>

### CODE REVIEW

**Review by ejgallego — APPROVED** [review]
Nice !

**Comment by rgrinberg** [comment]
This PR needs to be reverted because it's loading the coq scope for projects where coq isn't enabled. This is a performance penalty for all dune projects which is a no-no.

**Comment by ejgallego** [comment]
This is strange, how is the code called if there is not `coq.theory` stanza in your development?

Code after #9149 seems to do the same, right?

**Comment by ejgallego** [comment]
Never mind, got to see the other PRs

**Pull request merged**
