### PR TITLE
fix: correctly handle absolute paths in dune ocaml top-module

### LINKED ISSUE #7370: dune ocaml top-module crashes when given an absolute path
Reproduction case in #7369.

### PR DESCRIPTION
**Pull request by Alizter**
- fix #7370

### CODE REVIEW

**Comment by rgrinberg** [comment]
Instead of disallowing them, you could just strip the initial PWD and look for corresponding source file

**Comment by Alizter** [comment]
@rgrinberg What if the prefix isn't shared? I'll have to add some logic making sure its a prefix etc.

**Comment by rgrinberg** [comment]
If the prefix isn't shared, then the path is outside the workspace and there's very little we can do for the user.

**Comment by Alizter** [comment]
Also I'm not sure the initial PWD is the correct thing to choose. You can imagine a project `a/b/...` where you call `dune ocaml top-module` inside `b` using the absolute path for a module inside `a`. I think we rather need the project root.

**Comment by rgrinberg** [comment]
Okay sure, you can use the workspace root.

**Comment by Alizter** [comment]
@rgrinberg I've implemented the prefix handling logic. There is some refactoring we should do in the future: `Workspace_root` should work with `Path.t` rather than `string`.

**Comment by rgrinberg** [comment]
I ran into this annoying issue and took the liberty to revive this PR.

**Pull request merged**
