### PR TITLE
chore(ci): disable flaky tests

### PR DESCRIPTION
**Pull request by rgrinberg**
I need to think about how to make them more reliable

### CODE REVIEW

**Comment by rgrinberg** [comment]
@snowleopard any idea where this mac error is coming from:

```
File "test/blackbox-tests/test-cases/directory-targets/copy-files.t", line 1, characters 0-0:
454
/usr/local/bin/git --no-pager diff --no-index --color=always -u _build/.sandbox/1d39977388197da1223d672136617e28/default/test/blackbox-tests/test-cases/directory-targets/copy-files.t _build/.sandbox/1d39977388197da1223d672136617e28/default/test/blackbox-tests/test-cases/directory-targets/copy-files.t.corrected
455
diff --git a/_build/.sandbox/1d39977388197da1223d672136617e28/default/test/blackbox-tests/test-cases/directory-targets/copy-files.t b/_build/.sandbox/1d39977388197da1223d672136617e28/default/test/blackbox-tests/test-cases/directory-targets/copy-files.t.corrected
456
index 53160f8..c3f8232 100644
457
--- a/_build/.sandbox/1d39977388197da1223d672136617e28/default/test/blackbox-tests/test-cases/directory-targets/copy-files.t
458
+++ b/_build/.sandbox/1d39977388197da1223d672136617e28/default/test/blackbox-tests/test-cases/directory-targets/copy-files.t.corrected
459
@@ -49,5 +49,5 @@ Copy from a generated directory somewhere else
460
   [1]
461
 
462
   $ ls _build/default/b
463
-  ls: cannot access '_build/default/b': No such file or directory
464
-  [2]
465
+  ls: _build/default/b: No such file or directory
466
+  [1]
```

**Comment by snowleopard** [comment]
> @snowleopard any idea where this mac error is coming from:

I think this may be caused by this recently merged PR: #5335. We should check file existence in a more portable way instead of doing `ls _build/default/b`.

**Comment by rgrinberg** [comment]
I see. Well in this case this PR is ready then.

**Review by snowleopard — APPROVED** [review]
Looks good but I had a really hard time parsing the added condition. It would be great to add a comment explaining the intent.

**Comment by Et7f3** [comment]
Is using stat an option ? It has format field.

**Comment by rgrinberg** [comment]
> Is using stat an option ? It has format field.

Would you like to give this a try?

**Comment by rgrinberg** [comment]
done in #5367

**Comment by Et7f3** [comment]
Ok shell construct should be more portable.

**Pull request merged**
