### PR TITLE
[WIP] Ocaml ll

### PR DESCRIPTION
**Pull request by bobot**
Preliminary implementation of [library linking support](https://github.com/dbuenzli/RFCs/blob/master/rfcs/ocamlib.md#ocaml-library-install-support) in dune using @dbuenzli [implementation](https://github.com/dbuenzli/RFCs/blob/master/rfcs/ocamlib.md#ocaml-status).

### CODE REVIEW

**Comment by diml** [comment]
I initially read the title as "OCaml 2" :smile:

**Comment by dbuenzli** [comment]
Thanks @bobot ! Note that acad37b's commit message is misleading it should read "Add `--require` for archive creation".

**Comment by rgrinberg** [comment]
This proposal is (permanently?) blocked by upstream. Does this PR still makes sense then?

**Comment by dbuenzli** [comment]
I don't think so. It's also not up-to-date with the latest version of the proposal.

**Pull request closed without merging**
