### PR TITLE
[Scheduler] Shutdown when standing by

### PR DESCRIPTION
**Pull request by rgrinberg**
When standing by, the normal shut down mechanism deadlocks. This is easily
reproduced by running in passive mode and shutting down without building
anything.

To fix, we force the shutdown by sending a signal.

In addition, we make sure the Waiting_for_inotify_sync state also
terminates properly.

This fix feels a bit dirty. I don't quite like how I am pretending we received a
signal. Should we introduce a new event?

### CODE REVIEW

**Comment by aalekseyev** [comment]
This signal business does feel weird.
It was always confusing to me to have two different shutdown mechanisms (signal and shutdown rpc). 
Let's try to clarify why they are different.

The difference seems to be that signals terminate the scheduler without running any more fibers, while Shutdown finishes all fiber computations and processes scheduler events normally.

One reason might be that we want the "shutdown" rpc itself to finish cleanly? (dune closing the connection etc.)
If that's indeed the reason, then going through the signal handling code path seems wrong.

I guess if we're doing an orderly shutdown, then maybe `get_build_request` in `poll_passive` should return a "shutdown" variant (or raise an exception), too?

For that, we'd need to make `Dune_rpc_impl.Server.pending_build_action` raise an exception on shutdown.

For that, I guess we'd want to "close" the Job_queue in src/dune_rpc_impl/server.ml?

All of that sounds complicated and starting with a "signal-like" treatment is probably better than nothing.

**Comment by aalekseyev** [comment]
If the "unclean" completion of the shutdown RPC is not an issue, can you please add a comment to the `Event.Queue.send_signal` explaining the trade-off?

**Comment by rgrinberg** [comment]
I'd prefer a clean shutdown mechanism, but given that I can't come up with tangible benefits, and our clean mechanism requires constant maintenance to make sure it works, I agree we should probably switch to the signal based approach.

**Review by aalekseyev — APPROVED** [review]
The simplification looks really good. I hope this doesn't bite us later.

**Comment by rgrinberg** [comment]
Yeah. I hope so too.

> One reason might be that we want the "shutdown" rpc itself to finish cleanly? (dune closing the connection etc.)
If that's indeed the reason, then going through the signal handling code path seems wrong.

To address this issue (if it ever comes up), perhaps a better mechanism to allow callers to add shutdown finalizers? It would not be possible to do much from these finalizers - no rpc, no worker threads, processes, or anything else that relies on the scheduler. But it should be enough for the user to handle clean ups and fill some ivars if it's necessary.

**Pull request merged**
