### PR TITLE
test: demonstrate a dependency cycle between modules field and rule

### PR DESCRIPTION
**Pull request by anmonteiro**
this might be the "rules in the same dir" / masking limitation thing that prevents us from generating melange js in the same directory, but I'm not sure?

### CODE REVIEW

**Comment by rgrinberg** [comment]
Yes, you should move the `rule` stanza to a different directory and then copy the file into your desired directory with a copy rule.

**Comment by jchavarri** [comment]
Should this change be consolidated with `eif-library-cycle.t`?

**Comment by rgrinberg** [comment]
Btw, I think we need to refine the repro further still. Roughly, what we need is:

1. libraries `x` and `y` in the same dir.
2. library `x` needs a dynamic list of modules. The dynamic list should exist in some separate directory to avoid the issue Etienne mentioned.
3. the dynamic list of modules needs to be generated by resolving `y` somehow. E.g. by running an executable that uses `y`

**Comment by anmonteiro** [comment]
@rgrinberg I think the test now illustrates the case you described. Could you check again, please?

**Review by rgrinberg — APPROVED** [review]

**Pull request merged**
