### PR TITLE
chore: update nix

### PR DESCRIPTION
**Pull request by rgrinberg**
Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

ps-id: 608375b2-a289-45b0-b659-dba64ba8ab60

### CODE REVIEW

**Comment by Alizter** [comment]
I wanted to ask about this. How come we are tied to ocaml-lsp's flake lock?

**Comment by rgrinberg** [comment]
Because flake inputs are downloaded recursively. This PR changes the inputs in the ocamllsp flake to use the dependencies we're already using for dune.

Rudi.

**Comment by Alizter** [comment]
I'm getting:
```
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
trace: warning: [opam-nix] Using `null' as a version in a query is deprecated, because it is unintuitive to the user. Use `"*"' instead.
```
we should change all those nulls in devPackages to `"*"`.

**Comment by Alizter** [comment]
Other than the warnings, works fine.

**Pull request merged**
