### PR TITLE
Split executable & test rules out of Gen_rules

### PR DESCRIPTION
**Pull request by emillon**
`Gen_rules` is a bit difficult to navigate. My plan is to extract the different parts into different files and ultimately replace then `Gen` functor by plain functions. Does that sound like a good plan to you?

### CODE REVIEW

**Comment by rgrinberg** [comment]
The functors don't really bother me, so I'll have to see what the improvement is there. But I support splitting the executable rules into its own module. For consistency with Lib_rules, Simple_rules, etc. we should name the module as `Exe_rules`.

**Comment by emillon** [comment]
OK, thanks! My only gripe with the functor is that it makes it a bit harder to move inner functions because there can be some setup code that depends on the functor parameter, but in that case it does not seem too bad. The functor will naturally disappear once all the parts are extracted. What I'm really after is making this file shrink :)

**Comment by emillon** [comment]
Done. I refactored the stanza loop as well.

**Comment by diml** [comment]
Thanks, could you open `No_io` in the various new files? It's a protection to make sure we don't read files directly. It was useful to catch bugs in the past.

**Comment by diml** [comment]
It's only needed in files using the build arrow, we do need to read files directly in other places, such as the build system itself.

**Comment by emillon** [comment]
OK, makes sense!

**Pull request merged**
