### PR TITLE
fix: update digest and incremental db versions

### PR DESCRIPTION
**Pull request by rgrinberg**
https://github.com/ocaml/dune/pull/8052 updated the representation for
these, but didn't bump the version.

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Review by Alizter — APPROVED** [review]

**Review by snowleopard — APPROVED** [review]
Oops, thanks. Did you find it because the change broke something?

**Comment by Alizter** [comment]
I got a few segfaults that disappeared after cleaning today, but I was tweaking rpc yesterday too so it might be unrelated.

**Comment by snowleopard** [comment]
> I got a few segfaults that disappeared after cleaning today, but I was tweaking rpc yesterday too so it might be unrelated.

@Alizter I see, thanks!

@rgrinberg Could you also add a test to prevent such breakage in future? We should basically make the format change observable somewhere, forcing us to update the version when needed.

**Comment by rgrinberg** [comment]
> Could you also add a test to prevent such breakage in future? We should basically make the format change observable somewhere, forcing us to update the version when needed.

Coming up soon

**Pull request merged**
