### PR TITLE
Fix `@all` alias should only build enabled libraries

### LINKED ISSUE #2272: `@all` doesn't work with enabled_if on libraries
[This project](https://github.com/vsiles/dune-enabled-if) shows an example where dune should only build one of the libraries with `@all`.

cc @vsiles

### PR DESCRIPTION
**Pull request by bobot**
Fixes #2272

### CODE REVIEW

**Comment by rgrinberg** [comment]
Oh yeah, I remember now. @diml I think this is a fairly good reason why `@all` can't just be building all the targets in all directories recursively. We know optional targets are allowed to fail in advance, there's no reason to include them in `@all`.

**Comment by diml** [comment]
Indeed, yeah

**Comment by rgrinberg** [comment]
This PR alters the behavior of merlin generation and also for detecting which modules belong to which stanzas. That doesn't seem right to me. Can we add some tests for these changes?

**Comment by diml** [comment]
> A better option would be to be able to remove these target from the globing but not from the graph.

That would be really nice! And maybe not that difficult to implement. For instance, we could flag such rules with a special marker. When collecting the list of targets in a directory, we would always skip such targets, but trying to build such a target would lead to the better error message.

**Comment by diml** [comment]
We just talked about this with @rgrinberg. We decided to go for @bobot's versoin for 2.0.0, and keep the improvement discussed here for the future.

**Comment by rgrinberg** [comment]
I'll clarify my last comment purely for reference here:

* Currently, libraries that aren't buildable will still be included in the .merlin file. That means merlin will still be able to jump to their sources if possible. Now this is no longer the case.

* I no longer understand how the stanza <-> module relationship is affected by this PR.

**Comment by diml** [comment]
> Currently, libraries that aren't buildable will still be included in the .merlin file. That means merlin will still be able to jump to their sources if possible. Now this is no longer the case.

That seems fine. It is not possible to build against an unavailable library, so we should never need to jump to the sources of an unavailable library.

> I no longer understand how the stanza <-> module relationship is affected by this PR.

The module<->stanza assignment is done before that and once and for all in `Dir_contents`, before we know what is available and what is not, so this PR shouldn't affect it. In a distant past, we were doing that as we went using mutable state, and the old code would have indeed be broken by this PR, but the current one is fine.

**Pull request merged**
