### PR TITLE
dsexp --> galach

### PR DESCRIPTION
**Pull request by diml**
I find the names `sexp` and `dsexp` too close. I suggest to rename `dsexp` to `galach` to make the distinction clearer. Galach is the main language in the Dune universe, so it seems appropriate.

### CODE REVIEW

**Comment by rgrinberg** [comment]
It would also be nice to rename the To_sexp and Of_sexp modules then. Something like `To` and `Of` should be enough.

**Comment by emillon** [comment]
I'm not sure about this one, that might be pushing the theme a bit fat. The s-expression part is already pretty complicated, and it does not help newcomers if they have to guess what a "galach" is. Plus, that sounds a bit like the name of a gun. I welcome a clarification, but what about something more neutral, like `Dune_sexp`?

**Comment by diml** [comment]
Indeed. I'll do that in another PR. @emillon, are you happy with this renaming as well?

**Comment by rgrinberg** [comment]
I don't think that our language is sexp based is relevant here, which is why `Dune_sexp` is non ideal. If there were no cute names like `Galach`, I'd pick a name like `Dlang` or `Dune_lang`. I have a soft spot for the cute naming schemes myself though.

**Comment by rgrinberg** [comment]
> Indeed. I'll do that in another PR. @emillon, are you happy with this renaming as well?

Would you mind just pushing this change without code review? I have a couple of PR's that I need to rebase on top of this so it would be helpful to me to speed this along.

**Comment by rgrinberg** [comment]
One thing that I like about `Dlang` over `Dune_lang` is that it's symmetric with `Blang`. I don't have preferences for the submodule names, but i can thro in my own suggestions: `Dump` and `Gen`.

Anyways, diml I think we've given you enough feedback. You can just pick something and merge.

**Comment by diml** [comment]
Let's try with `Dune_lang` and `Encoder/Decoder`. I did a couple of other renamings:

- dsexp --> dune_lang
- Of_sexp --> Decoder
- To_sexp --> Encoder
- Sexpable --> Conv
- dparse --> decode
- dgen --> encode

FTR, this is the script I used:

```
#!/bin/bash

repl=dune_lang
Repl=Dune_lang

sed -i.bak "s/dsexp/$repl/g;\
            s/Dsexp/$Repl/g;\
            s/Of_sexp/Decoder/g;\
            s/To_sexp/Encoder/g;\
            s/Sexpable/Conv/g;\
            s/dparse/decode/g;\
            s/dgen/encode/g" \
    `ag -il '(sexp|dgen|dparse)'`
find . -name '*.bak' -delete

for depth in 1 2 3 4 5; do
    files=$(find . -name *dsexp* -maxdepth $depth)
    for i in $files; do
        git mv $i ${i/dsexp/$repl}
    done
    let "depth++"
done

git checkout vendor
git add .
```

**Pull request closed without merging**
