### PR TITLE
fix(pkg): better lock cleanup

### PR DESCRIPTION
**Pull request by rgrinberg**
* We write the pid to the lock file
* We delete the lock file before release the lock to avoid a race

### CODE REVIEW

**Review by Leonidas-from-XIV — APPROVED** [review]
Looks good, however what is the point of the PID in the lock file? To be able to trace who holds it, if anyone?

Good point on deleting the lock file before releasing the FD, otherwise it would indeed be possible to remove the lockfile of another process (or fail doing exactly that) I would probably solve this by not deleting the lockfile at all, which is avoids the problem just as well.

**Comment by Alizter** [comment]
@Leonidas-from-XIV We add the pid to the dune lock file during a build, which allows us to report which pid has locked the build directory allowing the user to manually kill it or delete the lock as necessary. Writing the pid helps disambiguate between a running process having locked it, and a lock file being left over.

**Comment by Leonidas-from-XIV** [comment]
@Alizter However which PID has the lock can also be retrieved from `lsof`, which is somewhat more authoritative as the process with the original PID can terminate and process ids wrap around etc.

**Comment by Alizter** [comment]
We could do that, but we would also have to make sure the solution is cross-platform. Windows probably has a similar capability since by default you cannot delete "open" files.

**Comment by Leonidas-from-XIV** [comment]
We set `O_SHARE_DELETE` on all locks I think :)

**Comment by Alizter** [comment]
@Leonidas-from-XIV Sorry, I didn't mean that it was a problem on Windows, just that it should be possible to find an `lsof` equivalent.

**Comment by Leonidas-from-XIV** [comment]
Ah yeah, you're right — fair enough.

**Comment by Leonidas-from-XIV** [comment]
I think an error message mentioning the PID would be a good addition, but that can be added later as well.

**Pull request merged**
