### PR TITLE
test: use cmdliner in dune_cmd

### PR DESCRIPTION
**Pull request by emillon**
Now that cmdliner supports subcommands it's easier to use this in `dune_cmd` and remove the custom abstraction.

### CODE REVIEW

**Review by rgrinberg — APPROVED** [review]

**Review by Alizter — APPROVED** [review]

**Comment by rgrinberg** [comment]
By the way, this should add cmdliner to the list of test dependencies.

**Comment by Alizter** [comment]
@rgrinberg Why? Isn't cmdliner vendored by us?

**Comment by rgrinberg** [comment]
The vendored version is only to build dune itself

**Comment by emillon** [comment]
I'll add this, thanks. There's a small gotcha I hadn't thought of: this is going to be linked against our fork when building dune (and in CI), but against the upstream cmdliner for users that run tests on opam. So we should restrict ourselved to the common subset of features.

**Comment by emillon** [comment]
I agree. Should we close this then?

**Comment by rgrinberg** [comment]
I think the change is fine. It would just be preferable if cmdliner was sourced from where we source all external deps for the tests But if it can't be done due to some limitation in dune, it's acceptable to even use the vendored cmdliner.

**Comment by emillon** [comment]
I prefer closing that for now and revisit that when we have a better system for vendoring our test deps. Probably once dune is better at package management.

**Pull request closed without merging**
