### PR TITLE
Revert "feature: Eager watch mode for exec (#6507)"

### PR DESCRIPTION
**Pull request by gridbugs**
This reverts commit 5ff9a4fb0be075a26379b537677e15398113f14a.

This was causing occasional segfaults on macos when running `dune exec` so reverting this until we figure out what's causing that.

### CODE REVIEW

**Comment by rgrinberg** [comment]
How about you just disable the feature for now? I.e. just remove the flag that enables it. I don't mind reverting it, but I think you're just going to create more work for yourself long term if someone edits this file and creates conflicts for this change.

**Comment by gridbugs** [comment]
We see the segfault on macos even when running `dune exec` not in watch mode.

**Comment by gridbugs** [comment]
I can semi-reliably reproduce this on a mac by running:
```
while make clean && dune build @test/dependency-external; do date; done
```
Usually within a few iterations it fails with a seg fault.

As an experiment I tried replacing the call to `Scheduler.go_with_rpc_server_and_console_status_reporting` with `Scheduler.go` and after a few hours I haven't got a seg fault. I let it run overnight and if there is still no seg fault I'll investigate further into why this change caused the problem to go away.

**Comment by rgrinberg** [comment]
Btw, can you upload the stacktrace from the core dump?

**Comment by gridbugs** [comment]
```
$ lldb --core /cores/core.2223
(lldb) target create --core "/cores/core.2223"
Core file '/cores/core.2223' (x86_64) was loaded.
(lldb) bt
* thread #1
  * frame #0: 0x00007ff806f3b3ea libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007ff806f75a6f libsystem_pthread.dylib`_pthread_cond_wait + 1249
    frame #2: 0x00000001038da262 main.exe`caml_thread_leave_blocking_section [inlined] st_masterlock_acquire(m=<unavailable>) at st_posix.h:137:5 [opt]
    frame #3: 0x00000001038da224 main.exe`caml_thread_leave_blocking_section at st_stubs.c:244:3 [opt]
    frame #4: 0x00000001038e5d63 main.exe`caml_leave_blocking_section at signals.c:175:3 [opt]
    frame #5: 0x00000001038e2d23 main.exe`unix_unlink(path=<unavailable>) at unlink.c:33:3 [opt]
    frame #6: 0x000000010385d2c4 main.exe`camlStdune__Fpath__unlink_no_err_758 + 36
    frame #7: 0x0000000103881afb main.exe`camlStdlib__new_exit_481 + 59
    frame #8: 0x0000000103881b73 main.exe`camlStdlib__exit_488 + 35
    frame #9: 0x00000001035cef85 main.exe`camlDune__exe__Main__entry + 1781
    frame #10: 0x00000001035c7789 main.exe`caml_program + 8265
    frame #11: 0x000000010390cf55 main.exe`caml_start_program + 73
    frame #12: 0x00000001038e43a6 main.exe`caml_startup_common(argv=0x00007ff7bc93e1a0, pooling=<unavailable>) at startup_nat.c:160:9 [opt]
    frame #13: 0x00000001038e441b main.exe`caml_main [inlined] caml_startup_exn(argv=<unavailable>) at startup_nat.c:167:10 [opt]
    frame #14: 0x00000001038e4414 main.exe`caml_main [inlined] caml_startup(argv=<unavailable>) at startup_nat.c:172:15 [opt]
    frame #15: 0x00000001038e4414 main.exe`caml_main(argv=<unavailable>) at startup_nat.c:179:3 [opt]
    frame #16: 0x00000001038e448c main.exe`main(argc=<unavailable>, argv=<unavailable>) at main.c:37:3 [opt]
    frame #17: 0x0000000105e2952e dyld`start + 462

```

**Comment by rgrinberg** [comment]
Looks mysterious. @nojb any chance you might know?

**Comment by gridbugs** [comment]
Out of curiosity I tried instrumenting `Fpath.unlink` to print out the file it's unlinking (though I now doubt that's related) and now I don't get a seg fault.

**Comment by nojb** [comment]
> Looks mysterious. @nojb any chance you might know?

No idea. Is this with OCaml 5? Can it be reproduced with 4.14?

**Comment by gridbugs** [comment]
This was with 4.14

**Pull request merged**
