### PR TITLE
Fix test 1395 on osx

### PR DESCRIPTION
**Pull request by rgrinberg**
We really need to fix our blackbox tests on Windows.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Hmm, looks like this is a divergence between my local machine and CI. Anyone else is getting this failure on OSX?

**Comment by nojb** [comment]
Yes, I think the C compiler on `OS X` is `cc`, the CI tests on Linux, where it is `gcc`.

**Comment by diml** [comment]
What about removing the `--display=short`? We can just do `dune exec ./main.exe` in this test to make sure everything is built as it should.

**Comment by nojb** [comment]
Was about to suggest the same.

**Comment by rgrinberg** [comment]
Good call. Note that I think that the output-obj also suffers from this problem.

**Pull request closed without merging**
