### PR TITLE
use tags from package stanza in dune-file

### PR DESCRIPTION
**Pull request by anuragsoni**
Signed-off-by: Anurag Soni <anurag@sonianurag.com>

### CODE REVIEW

**Comment by anuragsoni** [comment]
@bobot I noticed this when using dune to generate the opam file for one of my packages. Looking at the opam generation implementation inside dune i couldn't see the tags field being used anywhere.

I'll rebase this PR and update later today. Thanks for reviewing!

**Comment by anuragsoni** [comment]
@bobot  this is now rebased and synchronized with the master branch

**Comment by rgrinberg** [comment]
@diml should we do this formatting change only after 2.0? Otherwise this is going to change opam files even if the dune language isn't altered.

**Comment by diml** [comment]
Yes, we do indeed.

**Comment by anuragsoni** [comment]
@rgrinberg Thanks!

**Pull request merged**
