### PR TITLE
Add support for `flags` field

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
This implements the simplest missing field from the proposal #7059: `flags` that writes the OPAM field `flags`.

I am not sure I am doing things correctly here - in particular the way `ident` in the Dune sexp parser is probably not right but I am not sure how to parse `:keywords` - `keyword` seems to expect a specific keyword and not return one.

### CODE REVIEW

**Comment by Leonidas-from-XIV** [comment]
It kind of depends on the flag, e.g. what how we plan to handle OPAM plugins (which are currently the 100% of packages that are using `.opam.template` files to write `flags` fields). Should we expose similar functionality to OPAM plugins, e.g. `dune opam <plugin-name>`?

**Comment by Leonidas-from-XIV** [comment]
> Any other features that are provided with flags that we should consider?

I don't think there's any more in practical use.

* `compiler` is only interesting for `opam switch` and so far there are no compilers that build with dune anyway.
* `avoid-version`/`deprecated` is theoretically interesting to publish prereleases or mark problematic versions, but I can't see that useful for people developing a package and more for `opam-repository` maintainers.

**Comment by rgrinberg** [comment]
> compiler is only interesting for opam switch and so far there are no compilers that build with dune anyway.

Note that we'll be able to build the compiler with dune just fine. We'll simply execute the command listed in the opam file. I don't see why we need to mark a package as a "compiler" however.

> avoid-version/deprecated is theoretically interesting to publish prereleases or mark problematic versions, but I can't see that useful for people developing a package and more for opam-repository maintainers.

Sounds right to me.

**Comment by Leonidas-from-XIV** [comment]
> I don't see why we need to mark a package as a "compiler" however.

That's only for the thing to show up in `opam switch list-available`, which is not particularly relevant for us indeed.

**Comment by Leonidas-from-XIV** [comment]
I think with the conclusions from #7059 we can close this for now. If we do decide to implement it, this can be reopened later after all, no need to clutter the list of open PRs.

**Pull request closed without merging**
