### PR TITLE
[refactor] Simplify our 0install vendor to remove unused features

### PR DESCRIPTION
**Pull request by ElectreAAS**
Our vendored dependency, `opam-0install`, is our only interface with `0install` and doesn't use `command`s or 'machine groups' at all. Here I remove them entirely, without any feature loss.

The goal is to simplify the codebase such that future modifications are easier to make. In particular, looking at things like #10987, #10838, maybe even help with #10837.

### CODE REVIEW

**Comment by ElectreAAS** [comment]
Note the this PR includes two commits that run ocamlformat on both the 0install-solver and the opam-0install codebases. Working with a formatted file is a lot easier.
We might want to add those to `.git-blame-ignore-revs` afterwards.
I could also remove the commits if we deem them unnecessary.

**Comment by rgrinberg** [comment]
Thanks for getting started on this. To properly fork these projects and develop them as internal dune libraries, I suggest we take the following preliminary steps:

1. Move them from vendor to src
2. Remove the import scripts
3. Run ocamlformat

Once those 3 are done, the removal of dead code should commence as it will be a lot easier to tell what is being deleted. You followed the same steps but in a different order, which makes review a little bit harder. It's not a big deal though, as the changes are still simple. However, it would be helpful to push our changes after preliminary work

**Comment by ElectreAAS** [comment]
Thanks for the pointers @rgrinberg, I'll work on cleaning up my butchery after stabilizing my changes, I have other ideas still

Relatedly, my last commit pretty much solves #10987, although in a very opiniated way.
I'll look into patching that on its own though

**Comment by ElectreAAS** [comment]
My above comment is now outdated, this PR is ready for review. The commit solving the weird errors is in another PR.

**Pull request merged**
