### PR TITLE
Add CLI and config file configuration for the cache.

### LINKED ISSUE #2830: Put cache parameters in the config file
Put the various cache parameters such as the trimming period or the limits in the user configuration file.

### PR DESCRIPTION
**Pull request by mefyl**
Fix #2830.

### CODE REVIEW

**Comment by mefyl** [comment]
I used "transport" to describe whether we go through the daemon or we use direct filesystem access. Feel free to challenge the options naming.

**Comment by rgrinberg** [comment]
Do you mind updating the config tests with these 2 parameters by the way? We don't need anything fancy, just make sure that these values can actually be read.

**Comment by diml** [comment]
I'm not sure about the name `transport` either, but I don't have a better suggestion. Let's ask on the channel

**Comment by diml** [comment]
I'm not sure about the name `transport` either, but I don't have a better suggestion. Let's ask on the channel

**Pull request merged**
