### PR TITLE
chore: bump Dune version to 3.8

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Review by christinerose — APPROVED** [review]

**Comment by yawaramin** [comment]
I just tried bumping dune version on my personal project to 3.8 and got this error:

```
dune build
File "dune-project", line 1, characters 11-14:
1 | (lang dune 3.8)
               ^^^
Error: Version 3.8 of the dune language is not supported.
Supported versions of this extension in version 3.8 of the dune language:
- 1.0 to 1.12
- 2.0 to 2.9
- 3.0 to 3.7
```

My `dune --version`: `3.7.1`.

Should this be reverted?

**Comment by anmonteiro** [comment]
No, you should install Dune 3.8.

**Comment by yawaramin** [comment]
Latest release is 3.7.1 https://ocaml.org/p/dune/latest

**Comment by anmonteiro** [comment]
I don't understand what you're asking. `(lang dune 3.8)` is available since version 3.8 of Dune. If you'd like to use it, you need to install that version. It should be available once this is merged: https://github.com/ocaml/opam-repository/pull/23814

**Comment by yawaramin** [comment]
I'm saying that until dune 3.8 is available to the general public from opam repository, it should not be the `lang` version mentioned in the docs. Because when people Try it out right now, they will immediately get an error because the latest version they will have is 3.7.1.

**Comment by yawaramin** [comment]
Alternatively, the docs could take advantage of ReadTheDocs' versioning feature to specify version numbers that match with the docs version, e.g. it's fine to mention 3.7 on https://dune.readthedocs.io/en/3.8/

But not on https://dune.readthedocs.io/en/stable/ because that is currently 3.7

**Comment by rgrinberg** [comment]
I think you might be missing the point that it's possible to use the latest version of dune without opam. For example, dune 3.8 is probably already available in the ArchLinux AUR.

**Comment by yawaramin** [comment]
Sure, it's _possible_ in some distros. But the _official_ way to install dune is with opam: https://dune.build/install . That's also how macOS and Windows users will do it.

- We have the `opam install dune` command on the landing page which installs 3.7.1 now
- We have `(lang dune 3.8)` in the docs (since February)

Anyone following this sequence will immediately get a build error. This is an unnecessary UX pitfall. It can be resolved fairly easily by updating the `(lang dune VERSION)` in the docs after the opam repository merge.

**Comment by emillon** [comment]
In the meantime you can use

    opam pin add dune.3.8.0 https://github.com/ocaml/dune/releases/download/3.8.0/dune-3.8.0.tbz

This is a transient state due to unusual load on the CI machines; we don't need to change the release process for this.

**Comment by yawaramin** [comment]
This PR was merged in February. Haven't we been in this state since then?

**Comment by emillon** [comment]
No. We've been in that state (https://dune.readthedocs.io/ mentions 3.8) since 3.8.0 got released on github, last week.

**Comment by yawaramin** [comment]
Oh I see, so the RTD page is only updated when the release is tagged and done on GH. Thanks for the clarification.

**Pull request merged**
