### PR TITLE
test: repro #10301

### PR DESCRIPTION
**Pull request by anmonteiro**
reproes #10301

### CODE REVIEW

**Comment by anmonteiro** [comment]
at least for the ocamllex case it's easy to see why the target is expected to be in the same dir as the dune file: https://github.com/ocaml/dune/blob/main/src/dune_rules/stanzas/rule_conf.ml#L215-L220

**Comment by anmonteiro** [comment]
and for menhir:

https://github.com/ocaml/dune/blob/2a4a5bf6b904549dccd580904bff52e49a8ec8f2/src/dune_rules/menhir/menhir_rules.ml#L100-L103

**Review by emillon — COMMENTED** [review]
thanks for the repro. 2 remarks:
- can you add a pointer to #10301?
- if these are 2 separate issues, can you create 2 separate tests?
thanks!

**Comment by anmonteiro** [comment]
@emillon changed this to be just about menhir, and renamed the test case to point to #10301.

**Comment by anmonteiro** [comment]
ping @emillon

**Review by emillon — APPROVED** [review]

**Pull request merged**
