### PR TITLE
Add a reproduction case for #5122

### PR DESCRIPTION
**Pull request by bobot**
The issues:
 - The first installation doesn't detect any problems of dependencies in `dune-project`
 - Putting a dependency locally (`cp -r a b/a`) breaks the compilation: dune detects the dependency problem
 - All the transitive dependencies (`cat`, and `story`) needs to be added instead of just the first level `cat`.

### CODE REVIEW

**Comment by jeremiedimino** [comment]
Do we still have false positives? We shouldn't ask people to fix their code if it's correct.

**Comment by jeremiedimino** [comment]
Well, it's definitely a cleaner default, but compiler devs are not going to be too happy about it.

**Comment by kit-ty-kate** [comment]
> Moreover it has the benefit to push people to `(implicit_transitive_deps false)`. Which is good, no?

As long as issues such as the type aliases issues[*] are not resolved, I firmly don’t think `(implicit_transitive_deps false)` is a good default. It will result in a worse experience for OCaml developers.

[*]: e.g.

module A (using the `result` library):
```
val f : unit -> (unit, unit) Result.t
```
the user project:
```
match A.f () with
| Ok () -> ()
| Error () -> ()
```
will fail because `Result.t` is abstract. The user does not use `result` explicitly and now HAS to add it to make it work.

This is an extremely common pattern among others in the same vein and are a pain to deal with, especially when testing several versions of the A library (one might depend on `result` and some other version not, even depending on dependencies of it.. through Lwt_result for example)

**Comment by rgrinberg** [comment]
Please re-open if this is still relevant

**Pull request closed without merging**
