### PR TITLE
feature: blake3

### PR DESCRIPTION
**Pull request by rgrinberg**
Still not completely ready yet, but worth examining this early for benchmarking

### CODE REVIEW

**Comment by snowleopard** [comment]
Where is the implementation coming from? It doesn't seem to have any license.

> but worth examining this early for benchmarking

Have you done any benchmarks?

**Comment by rgrinberg** [comment]
> Where is the implementation coming from? It doesn't seem to have any license.

It's taken from from cryptokit.

> Have you done any benchmarks?

Yes. In my benchmarks, this digest is around 30% faster on average than md5.

**Comment by snowleopard** [comment]
Nice! Not particularly spectacular but still a good win. 

How fair was the comparison? I imagine performance depends quite a lot on the bindings/IO implementation itself, not just on the underlying algorithm, so is the 30% speed-up a consequence just of switching from MD5 to Blake3, or is there anything else going on?

**Comment by rgrinberg** [comment]
> so is the 30% speed-up a consequence just of switching from MD5 to Blake3, or is there anything else going on?

For strings in memory, it's around a 30% speed up across the board.

For digesting very small files, the difference is between smaller-than-30% to barely-measurable. For somewhat larger files (10kb+), the difference is around 30% again.

**Pull request closed without merging**
