### PR TITLE
List only public modules in generated index

### LINKED ISSUE #2008: documentation target and private_modules
When I use `private_modules` in a dune file, and run the `dune build @doc` target, the documentation is nicely generated, but the resulting index page includes the list of private modules.

This is with dune 1.8.2 and odoc 1.4.0

The generated html page (for https://github.com/mirleft/ocaml-x509/pull/112) contains:
```
<p>This library exposes the following toplevel modules:</p><ul class="modules"><li><code>Asn_grammars</code></li><li><code>Registry</code></li><li><a href="X509/index.html"><code>X509</code></a></li><li><code>X509_authenticator</code></li><li><code>X509_ca</code></li><li><code>X509_certificate</code></li><li><code>X509_common</code></li><li><code>X509_crl</code></li><li><code>X509_crl_types</code></li><li><code>X509_encoding</code></li><li><code>X509_extension</code></li><li><code>X509_extension_types</code></li><li><code>X509_pem</code></li><li><code>X509_request_types</code></li><li><code>X509_types</code></li></ul>
```

I'm not sure whether this is an issue in odoc or dune (or am I missing some magic?).

### PR DESCRIPTION
**Pull request by rgrinberg**
Fix #2008. cc @hannesm

I would like to @jonludlam as a reviewer but he's not available, @avsm could you ad him?

### CODE REVIEW

**Comment by diml** [comment]
I just added him

**Comment by hannesm** [comment]
I tested this PR, and it fixes my problem. Thanks!

**Comment by rgrinberg** [comment]
@diml i'm afraid he still doesn't show up on the reviewer list

**Comment by diml** [comment]
I sent the invite but I think the person has to accept it before they show up

**Review by aantron — COMMENTED** [review]
No objection from me.

**Pull request merged**
