### PR TITLE
Factor out common handling of Action for lint/pp

### PR DESCRIPTION
**Pull request by rgrinberg**
The previous code had a bit of duplication between Linting and preprocessing. Also, I removed the `Build.action_dyn` wrapping, @diml was it necessary?

### CODE REVIEW

**Comment by diml** [comment]
The `action_dyn` was to declare the target. It wasn't very clear though, another way would be to add `Build.with_stdout_to` which would do it for the caller. Could you diff the output of `dune rules -r @install` with `dune` at base and tip of this PR? Just to check this PR doesn't affect the generated rules.

**Comment by rgrinberg** [comment]
As luck would have it `$ dune rules -m -r @install` causes an infinite loop on master. Can anyone confirm that's the case for them as well?

**Comment by diml** [comment]
Yep, I can confirm that as well :/ We need to debug that, but for this PR let's just use any file that is preprocessed with an action, for instance `dune rules src/build.pp.ml`

**Comment by rgrinberg** [comment]
Indeed it was necessary. I just brought it back and now the rules are setup exactly the same way.

**Pull request merged**
