### PR TITLE
Add 4.04 and 4.05 to test matrix

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by rgrinberg** [comment]
I somehow got the minimum versions for -no-{approx,code} wrong twice. Hopefully this PR fixes things for good.

**Comment by rgrinberg** [comment]
I'm a bit stumped on how to make tests run on 4.05. Does anyone have an idea what might be going on?

**Comment by diml** [comment]
BTW, the title of this PR and the versions in the travis file don't match (4.02&4.05 vs 4.04&4.05)

**Comment by diml** [comment]
`opam info ocaml` doesn't mention 4.05.1, just 4.05.0. Maybe that's the issue?

**Comment by diml** [comment]
(the travis log shows that it's trying to download ocaml 4.05.1)

**Comment by rgrinberg** [comment]
Good call. I fixed things. Originally, I tried getting the tests to pass on 4.02 but it quickly proved to be a massive task.

**Pull request merged**
