### PR TITLE
Add a ppx rewriter example for the generated install file

### PR DESCRIPTION
**Pull request by rgrinberg**
The example should work with dune and jbuild files.

### CODE REVIEW

**Comment by rgrinberg** [comment]
@diml so you're saying this is supported, right? If so, I get an error with this test on your branch:

```
+|  Error: No ppx driver found.
+|  It seems that these ppx rewriters are not compatible with jbuilder.
+|  -> required by (pps (foo.ppx_rewriter_dune))
```

**Comment by diml** [comment]
Thanks for the test. I'm going to debug this.

**Comment by diml** [comment]
Ah, it's simply that the driver is looked up in the transitive closure of the lib. If the lib has no dependency and is not a driver itself, then it is clearly not compatible with the new method.

I changed the test in my PR to make the library a driver, otherwise it's going to be painful for us to run the tests.

**Comment by diml** [comment]
I'm going to add a hint as well, because it is indeed quite cryptic.

**Pull request merged**
