### PR TITLE
Use 4.06 to run the testsuite in travis

### PR DESCRIPTION
**Pull request by diml**
Signed-off-by: Jeremie Dimino <jeremie@dimino.org>

### CODE REVIEW

**Comment by diml** [comment]
@dra27 it seems that the travis script is trying to rebuild opam and fails, could you have a look? (You wrote the travis script and I don't understand everything it's doing)

**Comment by kodek16** [comment]
Maybe we could install `bubblewrap` like this? https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-container-based-infrastructure

**Comment by dra27** [comment]
Possibly - it's not immediately clear if you can use a custom ppa with containers (I'd kinda hope not!). There's no particular need for sandboxing anyhow.

**Comment by kodek16** [comment]
Apparently there's a whitelist at https://github.com/travis-ci/apt-source-whitelist, but this PPA isn't there. It's in the main Ubuntu repos from 17.10 onwards though, so when Travis moves from 14.04, it'll become possible to use bwrap without sudo :).

**Comment by diml** [comment]
Ok, it seems to be working now. Thanks @dra27

**Pull request merged**
