### PR TITLE
nix: add quick coq dev shell

### PR DESCRIPTION
**Pull request by Alizter**
The findlib package is needed for some reason for the Coq ocaml libraries to be visible to Dune. This is not correct, but convenient for testing.

### CODE REVIEW

**Comment by ejgallego** [comment]
What do you mean by "not correct"?

**Review by rgrinberg — APPROVED** [review]

**Comment by Alizter** [comment]
@ejgallego the correct thing would be to build Coq with the bootstrapped version of Dune, not the latest released version as done here.

**Comment by Alizter** [comment]
@ejgallego the correct thing would be to build Coq with the bootstrapped version of Dune, not the latest released version as done here.

**Comment by ejgallego** [comment]
> @ejgallego the correct thing would be to build Coq with the bootstrapped version of Dune, not the latest released version as done here.

Why would that be correct?

Note that we do the same with menhir, odoc, and quite a few other tools.

**Comment by Alizter** [comment]
For most things it will work as expected. In the rare case we change the behavior of Dune (say something about how things are installed), then those libraries we install need to be installed using the new version of Dune and not the old. This flake will use the latest Dune 3 to build and install Coq.

In order to "correct" this, we would need to use the bootstrapped version of Dune to build and install Coq which is entirely possible but not useful for a development flake. Not using the bootstrapped version also has the advantage of having Nix cache the compiled files making setting up the flake faster.

In any case, it doesn't matter for our users and is entirely an aid for me (and perhaps other devs) to quickly setup Coq for Dune development.

**Comment by ejgallego** [comment]
> For most things it will work as expected. In the rare case we change the behavior of Dune (say something about how things are installed), then those libraries we install need to be installed using the new version of Dune and not the old. This flake will use the latest Dune 3 to build and install Coq.

I don't see how that problem would be Coq-specific, would Dune do that (which I doubt), it would affect many other things.

Anyways, I don't see any support to the claim that what we do now is "not correct".

**Comment by rgrinberg** [comment]
> would Dune do that (which I doubt), it would affect many other things.

Not only has dune done this in the past, but we reserve the right to do it in the future. We don't guarantee backwards compat of generated artifacts because the expectation is that users will rebuild packages of dune is updated.

**Pull request merged**
