### PR TITLE
Recursive module instead of let rec

### PR DESCRIPTION
**Pull request by aalekseyev**
This PR tries to use recursive modules to clean up the big [let rec] in build_system.ml

I also notice that recursive modules give us a nice style of writing recursive memoized functions.

```
module rec Rec : sig
  val f : a -> b
  val g : a -> c
end = struct
  open Rec

  let f_impl = ...
  let g_impl = ...

  let f = ...memoize boilerplate ... f_impl
  let g = ...memoize boilerplate ... g_impl
end
```

The advantages are:

- You can see the type of the function explicitly. I like this because I can't easily extract the type from the "memoize boilerplate" at a glance
- You don't end up using Fdecl at all, which seems great.
- You have less alternation of value-level code (instead of "boilerplate; impl; boilerplate" you get "signature; impl; boilerplate", and signature seems easier to think about and start your program with) 

On top of that, I split the functions up a bit and moved the Load_dir memoization to top-level.

I want to make the same change (using recursive modules) to all occurrences of Memo as well.

### CODE REVIEW

**Comment by aalekseyev** [comment]
In 69b35fbe29e50 I get rid of all uses of `Memo.create ... None`, using recursive modules instead.
In some cases it gets awkward, like the one in `Dir_status.make`. I guess we could revert that one.

But actually it seems not too bad. I personally would keep it that way.

**Comment by diml** [comment]
Agreed. It seems better to me to have only one way of defining recursive memoised functions.

**Comment by aalekseyev** [comment]
@diml, by revert I meant use an explicit call to `Fdecl`, not delaying the change in `Memo.create`.

**Comment by diml** [comment]
Ok. That seems OK for `Dir_status`. I guess in the future we'll probably change the API to be just `Dir_status.get : Path.Build.t -> status` and get rid of the `DB` module anyway. It took me a bit of time to understand why we needed the `Rec` and `To_open` modules in build_system.ml BTW.  I guess we could avoid it by moving a couple more functions inside the recursive module.

**Comment by aalekseyev** [comment]
I added code comments about those two things and I'm merging this PR.

**Pull request merged**
