### PR TITLE
Use Toploop.add_directive

### LINKED ISSUE #4830: deprecated alert when using ocaml syntax in dune files with ocaml 4.13~alpha2
dune version : 2.9.0
dune file : https://github.com/ocsigen/js_of_ocaml/blob/master/lib/lwt/graphics/dune

```
Alert deprecated: Toploop.directive_table
File "_build/.dune/default/lib/lwt/graphics/dune.ml", line 28, characters 14-37:
28 |   Hashtbl.add Toploop.directive_table "require"
```

It seems that `dune.ml` is generated by dune itself

### PR DESCRIPTION
**Pull request by nojb**
Fixes #4830 

cc @hhugo

### CODE REVIEW

**Review by rgrinberg — APPROVED** [review]
Needs a CHANGES entry.

**Comment by nojb** [comment]
> Needs a CHANGES entry.

Done (sorry for the lag). Will merge once CI passes.

**Comment by nojb** [comment]
By the way if there is another 2.9 release this can go in it.

**Comment by hhugo** [comment]
When should I expect this to land in an official release ?

**Comment by nojb** [comment]
This will be in 3.0 but it is probably worth doing a 2.9 maintenance release with this fix as well. cc @rgrinberg @ejgallego

**Comment by ejgallego** [comment]
Why is this needed in the 2.9 series? As far as I understand, this is just a harmless warning.

**Comment by nojb** [comment]
> Ok, the fix seems minor but we can add it to 2.9.2

Yes, the warning is a bit annoying because it triggers whenever you use "OCaml syntax" with 4.13.

**Comment by ejgallego** [comment]
Sure, I didn't have time to backport this, please feel free to submit a backported PR targetting the 2.9 branch [and don't forget to adjust the changelog in `master` too]

**Pull request merged**
