### PR TITLE
Add --disable-promotion option

### LINKED ISSUE #2568: Feature request: CLI flag or env var to disable .merlin generation
This has been raised a few times before (e.g #257) and it seems that it's been rejected due to better ways to solve the root problem in each case.

My root problem: outside of the ocaml community, it's fairly common to build outside of the source directory, and this should not modify the source directory at all; for example, this is the default expectation of debian's package building scripts

Example workflow:

```
$ cd $SOURCE_DIR
$ DUNE_NO_MERLIN=true DUNE_BUILD_DIR="$(mktemp -d)" dune build foo.exe
$ git status --ignored
Current behavior: lots of .merlin files added
Desired behavior: absolutely no changes to SOURCE_DIR, even ones ignored by source control system
$
```

People actively working on the project would presumably want the .merlin files, but packaging builds do not; this means that committing a change to the configuration files is not a suitable option.

### PR DESCRIPTION
**Pull request by rgrinberg**
Add an option to disable all promotion. This option is enabled via `--disable-promotion` or `DUNE_PROMOTION_DISABLED` env var.

Fix #2568

### CODE REVIEW

**Comment by aalekseyev** [comment]
The change looks good (except for the `ls .merlin` command portability; I remember we solved exactly the same problem before, but I forget how).

**Review by aalekseyev — CHANGES_REQUESTED** [review]
Maybe the trick is `ls -1 . | grep merlin`

**Review by aalekseyev — APPROVED** [review]

**Comment by rgrinberg** [comment]
> Maybe the trick is ls -1 . | grep merlin

That doesn't seem to work with hidden files. I've tried something similar with `test -f`

**Comment by rgrinberg** [comment]
The output is probably not the same. This complicates our expect tests.

Anyway, I think using test and echo gives us predictable output everywhere.

**Pull request merged**
