### PR TITLE
ci: use nix for coq job

### PR DESCRIPTION
**Pull request by emillon**
We have to override the nixpkgs definition to get `coq-native`.

### CODE REVIEW

**Comment by emillon** [comment]
Before:  11m 21s
Now:  8m 46s

**Comment by ejgallego** [comment]
Great, thanks!

**Comment by ejgallego** [comment]
Indeed Nix provides very good build times for Coq, it is used heavily in some Coq projects.

**Comment by emillon** [comment]
Thanks. Do you know if some projects use nix to build coq-native? I had to define it in here so it's not cached at the moment.

**Comment by emillon** [comment]
Not ideal but an improvement already so I'm going for it.
cc @Alizter - if you know of a way to use coq-native from nix we can use it.

**Comment by Alizter** [comment]
@emillon Unfortunately there is no way to use Coq native from nixpkgs. The way you've done it seems fine to me.

**Pull request merged**
