### PR TITLE
Vendor and use spawn to replace Unix.create_process

### PR DESCRIPTION
**Pull request by jeremiedimino**
On big workspaces, Dune can use a lot of memory. When this happens, `Unix.create_process` becomes super slow to the point where Dune runs about one process per minute. This is because `Unix.create_process` uses fork+exec, and fork is very slow when the process uses a lot of memory.

We experienced this while trying to build Jane Street repository with Dune.

To fix this, this PR vendors and uses the [spawn](https://github.com/janestreet/spawn) library, which uses `vfork` rather than `fork`. `vfork` doesn't suffer from the same issue as `fork`.

We could also use `posix_spawn`, which would be less C code. However, `posix_spawn` doesn't support setting the cwd, while `spawn` does.

### CODE REVIEW

**Review by aalekseyev — APPROVED** [review]
Looks good!

**Comment by rgrinberg** [comment]
Awesome! This is such a nice change, that I wonder if we should make a point release with it

**Comment by jeremiedimino** [comment]
First we need to debug the OSX failure.

**Comment by jeremiedimino** [comment]
I've enabled github actions for the spawn repo to test on OSX. Let's see what comes out of it.

**Comment by jeremiedimino** [comment]
Seems like `chdir`/`fchdir` doesn't work after `vfork` under OSX. However, OSX has `pthread_chdir`/`pthread_fchdir`, so I'm trying that instead.

**Comment by rgrinberg** [comment]
@jeremiedimino silly question, but why don't we just `chdir` before `vfork` and avoid the issue altogether? I don't think dune care what the cwd is anyway.

**Comment by aalekseyev** [comment]
@rgrinberg, dune cares a lot what the cwd is because I think most filesystem operations are made on relative paths.

**Comment by jeremiedimino** [comment]
Yeah, that's a general problem with multi-threaded programs. If one threads happens to call `open_in "a/b.txt"` at the same time as another thread is doing a temporary `chdir`, then the `a/b.txt` filename will be interpreted relative to the chdired directory, which is probably not what the programmer who wrote the `open_in` expected.

This would work if there was a way to change the cwd of only the current thread. However, there is no such system call on Unix. Funnily enough, OSX does support this; it has `pthread_chdir` and `pthread_fchdir`.

**Comment by ejgallego** [comment]
@jeremiedimino , note the 2.8.6. milestone here, so we either need to cherry pick this for 2.9 [and adjust changes], or move the milestone to 3.0 , for now I'm setting 2.9 based on the discussion.

**Comment by jeremiedimino** [comment]
I tried backporting this PR but there are a lot of conflicts. Let's leave it for 3.0.

**Pull request merged**
