### PR TITLE
Use -output-complete-exe if available

### PR DESCRIPTION
**Pull request by nojb**
See ocaml/ocaml#8872.

Not tested yet.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM!

**Comment by nojb** [comment]
Tested with current OCaml trunk.

**Comment by rgrinberg** [comment]
@nojb I believe this needs a CHANGES entry.

**Comment by nojb** [comment]
> @nojb I believe this needs a CHANGES entry.

Done in #2709

**Pull request merged**
