### PR TITLE
melange: add test for inter-module deps

### PR DESCRIPTION
**Pull request by jchavarri**
It seems that when generating rules for `.js` targets, we don't generate rules for the modules that these `.js` files depend upon.

This PR adds a test that shows the failure.

### CODE REVIEW

**Comment by jchavarri** [comment]
@rgrinberg I tried fixing this but to get the inter-module dependencies one has to call `Compilation_context.dep_graphs`, which requires the compilation context, but `setup_emit_js_rules` doesn't receive it. I am trying to figure out if there's a way to pass it through in `gen_rules`, but I'm not sure if I'm looking at the problem from the wrong side.

**Comment by Alizter** [comment]
@jchavarri I had a similar issue trying to inspect the module deps in https://github.com/ocaml/dune/pull/6489. I'm not sure Compilation_context.dep_graphs really needs the entire context but I didn't investigate further.

**Comment by anmonteiro** [comment]
Your test has empty entries so they don’t get compiled.

**Comment by jchavarri** [comment]
> Your test has empty entries so they don’t get compiled.

@anmonteiro I don't think that matters. The `melange.emit` can have no modules and still depend in the library `a` (which would have both modules as `modules`).

But it was possible to simplify the test, did so in https://github.com/ocaml/dune/pull/7261/commits/0f0d46c6cc88e4f7b6c41837813f43345cd59501.

**Comment by jchavarri** [comment]
> I still think this is on purpose, they should be produced if you add the alias

@rgrinberg suggested the idea of targeting a specific `.js` file to be able to build subsets of some Melange project without having to add multiple `melange.emit` stanzas or introduce new ones like discussed in #7017. So I was testing this and realized it won't work as the dep rules are defined right now.

**Comment by rgrinberg** [comment]
This PR demonstrates expected behavior. When you do `dune build x`, dune will only build `x` and its dependencies. Other things such as runtime dependencies are not expected to build. This is why we introduced the alias to the melange.emit stanza

**Comment by jchavarri** [comment]
@rgrinberg Right. Maybe I misinterpreted you when you said (on DM):

> I’m also not sure that multiple emit stanzas is the solution. I wonder if it would be enough to be able to specify the subset of targets that are related to a library inside a melange.emit

Weren't you referring to targeting an individual `js` file?

**Comment by jchavarri** [comment]
> Other things such as runtime dependencies are not expected to build.

I am not sure I get the semantics of what runtime deps means. To me, dependencies between resulting js files generated by melange are just regular deps. In this case, the behavior might be correct but it does not look consistent: if dune builds the dependencies of a cmj when targeting it, why doesn't it build the dependencies of a js target?

**Comment by rgrinberg** [comment]
> Weren't you referring to targeting an individual js file?

My idea was to have multiple aliases. A separate alias for every app.

> I am not sure I get the semantics of what runtime deps means. To me, dependencies between resulting js files generated by melange are just regular deps. In this case, the behavior might be correct but it does not look consistent: if dune builds the dependencies of a cmj when targeting it, why doesn't it build the dependencies of a js target?

You're right, runtime deps isn't a well defined term. Dune has the nice property of only building the minimum to satisfy a build request. So for dune, dependencies are things that are needed to generate the action, or to execute it. Here, the other .js files you've pointed out fall into neither category. So they will not be built

**Comment by jchavarri** [comment]
> My idea was to have multiple aliases. A separate alias for every app.

But this means multiple `melange.emit` stanzas right? Or is there a way to tie a specific subset of libraries under an alias using a single `melange.emit` that I'm missing?

**Comment by rgrinberg** [comment]
> My idea was to have multiple aliases. A separate alias for every app.

But this means multiple melange.emit stanzas right? Or is there a way to tie a specific subset of libraries under an alias using a single melange.emit that I'm missing?

We can make it work with a single emit stanza. There's currently no mechanism to do this, but we could add one.

**Comment by jchavarri** [comment]
> We can make it work with a single emit stanza. There's currently no mechanism to do this, but we could add one.

Something like this?

```
(melange.emit
 (alias all_apps)
 (target es6)
 (libraries
  (library
   (name app1)
   (alias app1))
  (library
   (name app2)
   (alias app2))
  (library
   (name app3)
   (alias app3)))
 (module_systems es6))
```

Then, users can build everything with `dune build @all_apps` or specific subsets with `dune build @appX`.

**Comment by rgrinberg** [comment]
Looks fine to me. Although I would lean towards a new field instead:

```
(alias
 (name app1)
 (libraries app1)
(alias
 (name app2
 (libraries app2)
...
```

**Comment by jchavarri** [comment]
@rgrinberg I added a ticket to define the changes required: https://github.com/ocaml/dune/issues/7339

I think this PR is still valuable as it reflects current behavior when targeting `.js` files. Please lmk if anything is missing to get it merged, thanks!

**Pull request closed without merging**
