### PR TITLE
chore: odoc CHANGES

### PR DESCRIPTION
**Pull request by rgrinberg**
@jonludlam @lubegasimon does the minimum version of odoc need to change?

### CODE REVIEW

**Comment by lubegasimon** [comment]
> @jonludlam @lubegasimon does the minimum version of odoc need to change?

I am not sure, perhaps @jonludlam knows!

**Comment by rgrinberg** [comment]
@lubegasimon could you investigate what it should be? Otherwise it will break things for users when we release 3.0

**Comment by lubegasimon** [comment]
> @lubegasimon could you investigate what it should be? Otherwise it will break things for users when we release 3.0

Sure, let me do that!

**Comment by jonludlam** [comment]
It's already 2.0.1 as of https://github.com/ocaml/dune/pull/5252/ - that's certainly sufficient for the new rules to work. Is there anywhere else it might have to change?

**Comment by jonludlam** [comment]
Oh I see, that's just the Makefile for the tests. We'll need it to be `>=2.0.0` in the opam file.

**Comment by rgrinberg** [comment]
Thanks. I updated dune's opam file to reflect the conflict.

**Comment by jonludlam** [comment]
Looks good to me!

**Pull request merged**
