### PR TITLE
fix a bug in configurator String.take

### PR DESCRIPTION
**Pull request by aalekseyev**
Signed-off-by: Arseniy Alekseyev <aalekseyev@janestreet.com>

### CODE REVIEW

**Comment by aalekseyev** [comment]
@rgrinberg, not sure what the impact of this bug is, but effectively configurator API doesn't work at all, it seems, since 357fc63727.

**Review by rgrinberg — APPROVED** [review]
That's embarrassing. I suppose we deserve this for copy pasting so much code into configurator instead of using stdune (which does not have this bug)

**Comment by rgrinberg** [comment]
This also needs a CHANGES entry

**Comment by aalekseyev** [comment]
Did we actually release a stable version of configurator with the bug?

**Comment by rgrinberg** [comment]
As far as I can see, the offending commit you've pointed out is present in tags: `2.7.1  2.7.0 2.6.2 2.6.1 2.6.0`.

**Comment by aalekseyev** [comment]
Maybe that code path just ~never gets executed. I believe it only runs if INSIDE_DUNE is unset.

**Comment by rgrinberg** [comment]
That explains why this wasn’t observed by users. INSIDE_DUNE is only set when running the dune tests.

**Comment by aalekseyev** [comment]
I'm very confused by what you said. (sounds like you're implying the only thing our users do is running dune tests)
But it's probably not worth getting me unconfused.

**Pull request merged**
