### PR TITLE
Treat environment variables with empty values same as undefined

### LINKED ISSUE #3959: %{env:FOO=bar} should treat empty FOO same as undefined?
I would like to propose that `%{env:FOO=var}` treat an *empty* environment variable `FOO` the same as if it were undefined. This would simplify cross-system portability (on Windows, there is no difference between an undefined variable and an empty one).

### PR DESCRIPTION
**Pull request by nojb**
Fixes #3959 

PR for discussion.

### CODE REVIEW

**Comment by rgrinberg** [comment]
I'm for fixing #3959, but I'm not sure `Stdune` is the right place to do it. That `Env` module is supposed to be general purpose and may be used in dune cache for example. I think it would be much less surprising if this behavior was strictly limited to dune builds

**Comment by nojb** [comment]
> I'm for fixing #3959, but I'm not sure `Stdune` is the right place to do it. That `Env` module is supposed to be general purpose and may be used in dune cache for example. I think it would be much less surprising if this behavior was strictly limited to dune builds

Actually, wouldn't it be better to adopt the same behaviour everywhere?

I couldn't think of a case where it would be useful to differentiate empty from undefined variables... but would be happy to learn of one :)

**Comment by rgrinberg** [comment]
> I couldn't think of a case where it would be useful to differentiate empty from undefined variables... but would be happy to learn of one :)

Admittedly, I cannot think of any such situation, but I still find the proposed change to stdune sketchy. Let's see what @aalekseyev has to say about it.

**Comment by aalekseyev** [comment]
I'm used to treating environment the way I would treat `string option` in OCaml: `None` can very much be used to convey a different information from `Some ""`.

For variables interpreted by dune itself, I think it's probably OK to treat `None` the same as `Some ""`, although that wouldn't necessarily be my expectation.

For variables interpreted by programs other than dune (e.g. for env forwarding), I think dune should *definitely* distinguish `None` from `Some ""` because it's common for programs to behave differently in the two cases.

I agree with Rudi that hardcoding `None = Some ""` in stdune seems surprising.

**Comment by nojb** [comment]
> I'm used to treating environment the way I would treat `string option` in OCaml: `None` can very much be used to convey a different information from `Some ""`.

I agree, but only on Unix :)

> For variables interpreted by programs other than dune (e.g. for env forwarding), I think dune should _definitely_ distinguish `None` from `Some ""` because it's common for programs to behave differently in the two cases.

In theory, I agree with this opinion, but in practice, I can't think of any useful such case. Out of curiosity, do you have any in mind?

> I agree with Rudi that hardcoding `None = Some ""` in stdune seems surprising.

OK, I'll see if I can rework the PR without too much trouble in a more localized manner.

**Comment by aalekseyev** [comment]
> do you have any in mind?

I know we have had many examples in various scripts in Jane Street over time, and I can't remember individual examples, but here's one from a public package:

If a program that uses `Async` is run with `ASYNC_CONFIG=''` then it exits printing a help page instead of using a default config.

A more common idiom is to use [ -v foo ] in bash (or `Option.is_some (Core.Sys.getenv "FOO")`) so that the users can pass .
I don't know if ppx module timer is public-released, but `PPX_MODULE_TIMER=''` is such an example.

**Comment by aalekseyev** [comment]
> only on Unix

Oh, I didn't know it was different on Windows.

**Comment by nojb** [comment]
> > only on Unix
> 
> Oh, I didn't know it was different on Windows.

Yes, on Windows "empty" and "undefined" are equivalent. Which is why it is a debatable choice to interpret these two notions differently in code (at least if you expect your code to be used under Windows).

**Comment by nojb** [comment]
This was discussed during the developer's meeting and it was agreed that there wasn't enough of a rationale to change the way that the environment of the underlying system is exposed through the `dune` APIs.

**Pull request closed without merging**
