### PR TITLE
doc: only use "toplevel" in the OCaml sense

### LINKED ISSUE #308: Project layout doc page: meaning of 'toplevel'
It would be great to clarify exactly what is meant by 'toplevel' in the following text at the beginning of the page ( http://jbuilder.readthedocs.io/en/latest/project-layout-specification.html ):

> A typical jbuilder project will have one or more `<package>.opam` file at toplevel....

The term 'toplevel' already has meaning in the OCaml world, so maybe we can instead use 'project root' since 'root' is already defined in the terminology page ( http://jbuilder.readthedocs.io/en/latest/terminology.html ) and for good measure, we can even link the terms to their definitions for maximum clarity.

### PR DESCRIPTION
**Pull request by emillon**
Instead, rephrase using "repository root".

Closes #308

### CODE REVIEW

**Comment by rgrinberg** [comment]
What about project or workspace instead of repository? repository is a VCS term and we don't really have a hard dependency on any VCS.

**Comment by emillon** [comment]
I considered that, but "project" and "workspace" have well-designed semantics in dune, and it's not the same (there could be a dune project under `/src/` but a `/Makefile`, for example.

In most cases "toplevel" meant "the root directory when I'm unpacking or closing this thing".

Would just "root" work?

**Comment by rgrinberg** [comment]
I think `root` would work better

**Comment by emillon** [comment]
Just did that!

**Comment by emillon** [comment]
Thanks!

**Pull request merged**
