### PR TITLE
test: promote for new jsoo

### PR DESCRIPTION
**Pull request by rgrinberg**
the new jsoo compiler is outputting another command

### CODE REVIEW

**Review by hhugo — APPROVED** [review]

**Comment by rgrinberg** [comment]
@bobot the test mentioned in #5406 is failing here

**Comment by snowleopard** [comment]
@rgrinberg The lines you added here make CI unhappy (and also break locally for me). See #5418.

**Comment by snowleopard** [comment]
Oh wait, I think I got confused: the CI failure I saw was going the other way, so it was agreeing with the changes made here. 

Locally, however, `main` still fails for me, asking to undo changes made in this PR. What should I do?

**Comment by rgrinberg** [comment]
You should update to the latest js of ocaml.

**Comment by snowleopard** [comment]
@rgrinberg Thanks, it worked!

**Pull request merged**
