### PR TITLE
refactor(console): split Dune_console.Backend (#7000

### PR DESCRIPTION
**Pull request by rgrinberg**
Move the dumb and progress backends to their own files.

Move flushing/composition to a [Combinators] module

Finally, [Console.Backend.progress] is now flushing. Previously, it
wouldn't flush and was therefore buggy. This didn't affect dune, as we
only used [progress_threaded].

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
@snowleopard After this change, you're free to use `Console.Backend.progress` internally and get rid of the threading if you don't need it.

**Review by Alizter — APPROVED** [review]

**Comment by snowleopard** [comment]
It's pretty hard to review PRs that conflate refactorings with behaviour changes. I see lots of code moves, but where is the actual change? Might you factor it into a separate commit/PR?

**Comment by rgrinberg** [comment]
Okay, I removed the fix to the unthreaded backend. This is all refactoring now.

**Review by snowleopard — APPROVED** [review]
OK, I glanced through this PR very briefly but it looks fine.

**Pull request merged**
