### PR TITLE
Add support for response files

### PR DESCRIPTION
**Pull request by ghost**
This PR adds support for passing arguments to the OCaml compiler via a response file when the list of arguments is too long. This is to bypass the low command line length limit of Windows.

## Implementation

This PR adds global registry indicating whether programs support response files. It is filled while creating the context. It's not the cleanest way to do it, but it is a simple way to cut through all the layers and make sure the response file is used consistently.

A possible improve would be to add a type `Program.t` that would store the program path and whether it supports a response file, and then use this type instead of `Path.t` in the various places.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Appveyor complains:

```
File "src\\process.ml", line 244, characters 12-29:
Error: Unbound module Response_file
```

**Comment by rgrinberg** [comment]
Let's also add a CHANGES entry.

**Review by rgrinberg — APPROVED** [review]
Looks good to me. Can we get a round of testing from @jordwalke or @bryphe

**Comment by bryphe** [comment]
Awesome! Thanks @diml and @rgrinberg . I'll test it out on `esy`'s build and report back.

**Review by emillon — APPROVED** [review]

**Comment by diml** [comment]
I tested this feature this morning on a WIndows machine by lowering the limit and it seems to work well. We can assume that this PR is correct.

**Comment by bryphe** [comment]
Thanks @diml for your work on this!

**Comment by diml** [comment]
No problem, happy to help improve Windows support!

**Pull request merged**
