### PR TITLE
Specify length of git hash prefix used in build info version

### LINKED ISSUE #4855: git hash in build-info version is not as stable as it could be
## Expected Behavior

`Build_info.V1.version` returns the same string when the same commit is checked out, no matter the other state of the clone.

## Actual Behavior

The number of characters in the git commit hash component of `Build_info.V1.version` can vary.

## Reproduction

I do not know a reliable way to reproduce this. The root cause of this issue is that the `git describe --always --dirty` command that dune invokes internally to populate the build info version depends on the state of the clone. In particular, git automatically includes more than 7 characters in order to make the hash prefix unique. This seems to take into consideration local commits, stashes, to-be-gced commits, etc. It would be more robust to explicitly specify the desired length using the `--abbrev=<n>` flag for some n that is uniform at least across versions of the build info library.

## Specifications

- Version of `dune` (output of `dune --version`): 2.9.0
- Version of `ocaml` (output of `ocamlc --version`): 4.12.0
- Operating system (distribution and version): linux and macos

### PR DESCRIPTION
**Pull request by jberdine**
fix #4855

### CODE REVIEW

**Comment by jberdine** [comment]
BTW, `make dev-switch` failed for me, with an error about not finding an acceptable version of stdune-unstable. I had to instead `opam switch create . --empty; opam pin add stdune-unstable .; make dev-switch`. User error?

**Comment by rgrinberg** [comment]
> BTW, make dev-switch failed for me, with an error about not finding an acceptable version of stdune-unstable. I had to instead opam switch create . --empty; opam pin add stdune-unstable .; make dev-switch. User error?

No idea. Sorry.

Please add a CHANGES entry though.

**Comment by rgrinberg** [comment]
Thanks.

**Comment by jvillard** [comment]
Hi @ejgallego, would it be possible to include this PR in a future 2.9.2 dune release? This issue is causing some pain for infer users/hackers at the moment wrt ocamlformat checking its version and complaining that it's not the same just because `git describe` gives different results on different machines without this patch.

**Pull request merged**
