### PR TITLE
self_build_stubs_archive: do not ignore argument

### LINKED ISSUE #1393: The argument of `self_build_stubs_archive` is ignored
The argument of the `self_build_stubs_archive` is completely ignored, which doesn't seem right. It should be the name of the C library built by the user.

### PR DESCRIPTION
**Pull request by nojb**
Closes #1393

### CODE REVIEW

**Comment by diml** [comment]
`Library.{stubs_archive,dll}` need updating as well. BTW, it's probably worth adding a test for this.

**Comment by nojb** [comment]
I will add a test.

**Comment by nojb** [comment]
Test added.

**Review by ghost — APPROVED** [review]

**Comment by diml** [comment]
Thanks

**Review by emillon — COMMENTED** [review]
Thanks! Can you add "Closes #1393" in one of the commit messages so that the resolution is linked?

**Comment by nojb** [comment]
Sure, I did that by putting the comment in the PR description.

**Pull request merged**
