### PR TITLE
JS targets still build in dune 2.0 by default

### PR DESCRIPTION
**Pull request by rgrinberg**
The dune init tests can be modified to reproduce the js targets still
being included in @all even if the language is version 2.0

### CODE REVIEW

**Comment by rgrinberg** [comment]
@nojb do you have time to look at this one

**Comment by nojb** [comment]
Yes, will do (probably not today though).

**Comment by nojb** [comment]
I tried with a fresh checkout, but could not reproduce (on macOS) ... can you double-check ?

**Comment by nojb** [comment]
> I tried with a fresh checkout, but could not reproduce (on macOS) ... can you double-check ?

Sorry, I had made a mistake; I can reproduce, I will investigate. Thanks!

**Comment by nojb** [comment]
I forced-pushed the fix directly to your branch, which I also rebased on master. Ready to merge!

**Pull request merged**
