### PR TITLE
Use Exe to generate ppx executable

### LINKED ISSUE #3336: dune-build-info transitively used from ppx rewriter
(note: I am not sure the use case below is supposed to be supported, as the documentation states that build info can be embedded in executables, but does not explicitly mention whether it can be embedded in libraries.)

## Expected Behavior
Define a library depending on `dune-build-info` and have a ppx rewriter depending on said library.

## Actual Behavior
Dune fails with:
```
File ".ppx/98cd9c27bc47def1a842c7a721af4e6b/_ppx.ml", line 1:
Error: No implementations provided for the following modules:
         Build_info__Build_info_data referenced from /Users/xclerc/.opam/4.10.0/lib/dune-build-info/build_info.cmxa(Build_info)
```

## Reproduction

[repro.zip](https://github.com/ocaml/dune/files/4440231/repro.zip)

## Specifications

- Version of `dune` (output of `dune --version`): 2.4.0
- Version of `ocaml` (output of `ocamlc --version`): 4.10.0
- Operating system (distribution and version): macOS

### PR DESCRIPTION
**Pull request by rgrinberg**
Before this PR, we'd have two paths for generating executables
- Preprocessing: generate ppx exe's
- Exe: all other exe's

This PR replaces the build rules with Exe. As a consequence, one can use the
build info library in ppx rewriters now.

Fixes #3336

Once #3847 is merged, the `.d` files will disappear. It's also a bit annoying that the bytecode compiler is used to build the cmi's here.

Another point that needs to be addressed are the extra compilation steps to generate cmi's.

### CODE REVIEW

**Comment by rgrinberg** [comment]
This PR is now ready. It's unfortunate that this PR adds an extra step to building a ppx executable - first we must build the cmi. But I feel that fixing this bug is more important, and if this optimization is so important, we should just apply it across the board for all executables (inline tests, cinaps, user defined exes).

**Review by aalekseyev — APPROVED** [review]
I don't understand why you extracted Pp_spec in a separate module, I think its interface is very confusing without docs, and probably will be a pretty confusing abstraction even with docs.

Also, keeping it in a separate commit would have saved me a bit of time.

Anyway, the change overall seems reasonable and I don't want to hold up the merge of this feature.

If you can think you can add any docs to Pp_spec before (or after) merging, that would be appreciated.

**Comment by rgrinberg** [comment]
>  don't understand why you extracted Pp_spec in a separate module, I think its interface is very confusing without docs, and probably will be a pretty confusing abstraction even with docs.

It's done to break a dependency cycle. We want `Preprocessing` to use `Compilation_context`, but previously `Compilation_context` used `Preprocessing.t` (moved to `Pp_spec`) to pass the preprocessor specification.

**Comment by aalekseyev** [comment]
Ok, makes sense.

**Pull request merged**
