### PR TITLE
Improve error message about missing inotifywait and fswatch

### PR DESCRIPTION
**Pull request by diml**

### CODE REVIEW

**Comment by TyOverby** [comment]
Consider explicitly stating that inotifywait is preferred.

**Comment by rgrinberg** [comment]
> If you are using Linux, please install inotifywait. Indeed, inotifywait
is preferred as we observed that it works better than fswatch on Linux.

Since we can detect if the user is using Linux, what about just saying:

```
Please install inotifywait to enable watch mode. If inotifywait is unavailable, fswtach may also be used but will result in a worse experience.
```

**Comment by diml** [comment]
How do we detect that actually?

**Comment by rgrinberg** [comment]
> How do we detect that actually?

`uname -s`. At least this is enough to detect `Darwin` and just immediately recommend `fswatch`.

**Comment by diml** [comment]
Looking at `man 2 uname`, we can actually read this from `/proc/sys/kernel/ostype` so I did that.

**Comment by rgrinberg** [comment]
I’m not sure this is available on Mac OS unfortunately. I’ll test it out

**Comment by diml** [comment]
Yh but it doesn't matter too much here since we only want to detect Linux. We can always bind the `uname` system call later.

**Pull request merged**
