### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by rgrinberg** [comment]
Please sign your commit

**Comment by Alizter** [comment]
@rgrinberg Done

**Comment by rgrinberg** [comment]
I don't see the `sign-off` line in  the commit. Perhaps you forgot to push?

**Review by christinerose — APPROVED** [review]

**Comment by Alizter** [comment]
@rgrinberg I must be confused what you meant. Did you not ask me to GPG sign it?

**Comment by nojb** [comment]
> @rgrinberg I must be confused what you meant. Did you not ask me to GPG sign it?

No, just a simple "git" sign-off (obtained by using `git commit -s`).

**Comment by Alizter** [comment]
OK, I will do `-s` instead of `-S` next time

**Pull request merged**
