### PR TITLE
refactor: name some lazy cells

### PR DESCRIPTION
**Pull request by rgrinberg**
makes debugging cycles easier

### CODE REVIEW

**Review by jeremiedimino — APPROVED** [review]
Looks good.

Maybe we should make the `~name` argument of `Memo.lazy_` mandatory. WDYT? /cc @snowleopard

**Review by snowleopard — APPROVED** [review]
Nice!

**Comment by snowleopard** [comment]
> Maybe we should make the `~name` argument of `Memo.lazy_` mandatory. WDYT? /cc @snowleopard

@jeremiedimino Agreed, let's make it mandatory if it's not too annoying.

**Comment by rgrinberg** [comment]
Tbh, I'd kind of prefer to pass `__POS__` over a name. The names are a little artificial and are only good for grepping the source anyway.

**Comment by jeremiedimino** [comment]
Names would be better for #5053 though.

**Pull request merged**
