### PR TITLE
Fix bad interaction between env stanza and vendored projects

### PR DESCRIPTION
**Pull request by diml**
When a vendored project didn't have its own `env` stanza,  the `env` stanza from the enclosing project was in effect. This patch fixes this.

I added a test for this case in the `env` test and also refactored a bit to make it easier to understand. The patch also moves the filling of the env table in `Super_context.t` from `Super_context.create` to `Super_context.Env.get`. The code is a bit more straightforward and lazy this way.

### CODE REVIEW

**Comment by dra27** [comment]
@avsm - I have a feeling this may break the platform build, or at least its propagation of warnings flags?

**Comment by diml** [comment]
I suppose we could add a way to make it clear that the default will cross-project boundaries, such as a `cross_project_env` stanza.

**Comment by diml** [comment]
In the meantime, this PR fixes an inconsistency between projects that have a top-level env stanzas and those that don't, so it should be merged.

**Comment by avsm** [comment]
yes agree this should be merged -- however it would be good to highlight the change in backwards compatibility prominently as it could cause surprising side-effects as vendored projects shift to using `dune-project` files from `jbuilder` (since presumably the flag will stop being propagated now when the `dune-project` file shows up).

**Comment by diml** [comment]
I opened #1419 to discuss alternative possibilities.

**Pull request merged**
