### PR TITLE
chore: add a docker dev file for development

### PR DESCRIPTION
**Pull request by rgrinberg**
Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

ps-id: a84f5801-0c44-412e-af23-69561bb805d5

### CODE REVIEW

**Comment by Alizter** [comment]
How does it work?

**Comment by rgrinberg** [comment]
First, you build the image:

```
$ docker build -f dev.Dockerfile -t dune .
```

Then you run it:

```
$ docker run --rm -it -v $PWD:/source dune bash
```

**Review by Alizter — APPROVED** [review]
Ah so this is so we can quickly check the ocamlformat version in the CI?

**Comment by rgrinberg** [comment]
I just use it to test errors that only appear in CI. Nothing to do with ocamlformat

**Comment by rgrinberg** [comment]
@Alizter did you test?

**Pull request merged**
