### PR TITLE
Allow to customize javascript runner

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by rgrinberg** [comment]
ping @hhugo . you asked or help with this PR but did not specify the kind of help or even what is being implemented here.

**Comment by hhugo** [comment]
I've managed to unlock myself and fix the build.
I suspect the current approach is not quite correct and would welcome comments.
In particular, the `runner` currently expand itself "inside" the _build directory context and makes referencing custom binary awkward, see   https://github.com/ocaml/dune/pull/5303/commits/42debe244c448d26389997d6e44397f1bdc521c5

**Comment by rgrinberg** [comment]
Could you describe the motivation for this feature a little more? As you know, it's already possible to customize the runner by writing your own inline tests backend. What other forms of customization do you need?

**Comment by rgrinberg** [comment]
And of course you can customize the runner locally by overriding the `node` binary as well with `env`.

**Comment by hhugo** [comment]
What I want is orthogonal to inline-tests backend.
Dune current hardcode the fact that node is used to run JavaScript tests. I want to be able to customize that. You can imagine passing flags to node or use another JS vm. My use case is that I need a node wrapper to preload values before executing the JS file.

**Comment by hhugo** [comment]
I think I can do what I want by using a combination of
```
(env
  (_
    (binaries (my_wrapper.exe as node))
  )
)
```
and
```
(env
  (_
    (env-vars ("NY_WRAPPER_ARGS" "BLAH"))
  )
)
```

**Pull request closed without merging**
