### PR TITLE
feature(pkg): thread monad through 0install solver

### PR DESCRIPTION
**Pull request by rgrinberg**
This is a rather dumb translation that does not try to take advantage of any concurrency. It should be enough for our needs however.

### CODE REVIEW

**Review by Leonidas-from-XIV — APPROVED** [review]
I assume this is this the same code that you pushed in #8950? That seems to be working fine and I looked through it as part of that PR.

**Comment by Alizter** [comment]
Does this allow for eager error messages during solving?

**Comment by rgrinberg** [comment]
What are eager error messages?

**Comment by rgrinberg** [comment]
> I assume this is this the same code that you pushed in #8950? That seems to be working fine and I looked through it as part of that PR.

Yes, it's the exact same stuff but cleaned up and isolated.

**Pull request merged**
