### PR TITLE
Add explicit mode for -output-complete-exe

### PR DESCRIPTION
**Pull request by ghost**
Add a `byte_complete` mode for executables. With this mode, the executbale is built with the extension `.bc` and is self-contained (as per the `-output-complete-exe` option of the compiler).

This PR also refactorsa bit the code handling modes:
- it removes the `loc` field from `Link_mode.t` and stores a `Loc.t Link_mode.Map.t` instead of a `Link_mode.Set.t`
- it makes the overlap checks more generic

TODO:
- [x] add test
- [x] update the doc

### CODE REVIEW

**Comment by ygrek** [comment]
Thanks for working on this!
Regardless .bc file extension - it seems inconsistent with current choice (as described in [doc](https://dune.readthedocs.io/en/stable/dune-files.html#linking-modes)) : 
```
Note that when (byte exe) is specified but neither (best exe) nor (native exe) are specified, Dune still knows how to build an executable with the extension .exe. In such case, the .exe version is the same as the .bc one except that it is linked with the -custom option of the compiler. You should always use the .exe rather that the .bc inside build rules.
```

Also, probably unrelated, but is the next sentence in the doc true? 
```
Lastly, note that .bc executables cannot contain C stubs. If your executable contains C stubs you may want to use (modes exe).
```

**Comment by diml** [comment]
> Regarding .bc file extension - it seems inconsistent with current choice (as described in doc) :

Indeed, I was thinking to update the doc, but maybe we should use a different extension indeed. This way you could build the normal and complete bytecode at the same time. I'll do that.

> Also, probably unrelated, but is the next sentence in the doc true?

Yes. Well,  maybe it could be clearer. Basically, a bytecode executable can depend on libraries that have C stubs. However, dune also allow to have stubs attached directly to an executable rather than a library. In that case, you can't build and use the `.bc` as the stubs attached to the executble wouldn't be packaged into a `.so`.

**Comment by diml** [comment]
Alright, this is ready for review. I used the extension `.bc.exe` for `byte_complete` given that it is bytecode packages into a real executable.

**Comment by ygrek** [comment]
works, thank you!

**Pull request merged**
