### PR TITLE
refactor(melange): share visible_cmi branch

### PR DESCRIPTION
**Pull request by rgrinberg**
Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

ps-id: 8ddb7982-5094-48e8-ad0f-ecd86f157032

### CODE REVIEW

**Review by anmonteiro — APPROVED** [review]
Looks correct

**Comment by rgrinberg** [comment]
I guess I'm not accounting for `MELANGELIB` yet so this isn't quite correct.

**Comment by anmonteiro** [comment]
That doesn't need to be passed in as an include path. Melange includes it automatically. Am I missing something?

**Comment by rgrinberg** [comment]
The following two commands output something different, right?

```
$ melc --where
$ MELANGELIB=foo melc --where
```

In which case dune must know that `melc --where` reads this variable to recompute the rules if it changes.

**Comment by anmonteiro** [comment]
They do produce different outputs.

**Comment by rgrinberg** [comment]
It's not 100% needed here I should note. I'm not setting up a rule for running `melc --where` so we'll be recomputing it on every fresh run. But just in case we switch this to a rule, it will be useful

**Comment by rgrinberg** [comment]
Okay, I've now added a branch for when `MELANGELIB` is set. When it's set, we might as well skip running the binary altogether.

**Comment by rgrinberg** [comment]
I just realized that my comments were made in the wrong PR. Sorry for the confusion.

**Comment by anmonteiro** [comment]
I was just coming to realize that. thanks for clarifying

**Comment by rgrinberg** [comment]
To re-iterate, this PR is a trivial refactoring that has nothing to do with the recomputation of anything.

**Pull request merged**
