### PR TITLE
nix: upgrade to patch that track `doc` section

### PR DESCRIPTION
**Pull request by anmonteiro**
This PR showcases how https://github.com/NixOS/nixpkgs/pull/220592 allows dune's cinaps tests to be run.

example of setup:

```shell
$ nix develop .#slim -c $SHELL

$ ./dune.exe build @test/blackbox-tests/test-cases/cinaps/runtest
```

### CODE REVIEW

**Comment by anmonteiro** [comment]
cc @Alizter does this make cinaps tests work for you in the slim shell?

**Comment by anmonteiro** [comment]
(btw, this is a regular flake update, since I included the patch in the overlays, so it can be merged)

**Comment by Alizter** [comment]
nix develop is broken:
```
$ nix develop
error: builder for '/nix/store/gcziwjr9j3lhnh3f4l7pba6dsyc2ly4r-nix-shell-env.drv' failed with exit code 1;
       last 10 log lines:
       > findlib: [WARNING] Package ppxlib has multiple definitions in /nix/store/p8ih9wxmzkh02360qwmm8plmvj8p853z-ppxlib-0.28.0/lib/ocaml/4.14.0/site-lib/ppxlib/META, /nix/store/yzgflsspi3s2426pw2wpkchifqad7n6r-ocaml4.14.1-ppxlib-0.28.0/lib/ocaml/4.14.1/site-lib/ppxlib/META
       > findlib: [WARNING] Package ocaml-compiler-libs has multiple definitions in /nix/store/npsb8kyxwnc99viadiblkgf2dnqs1hy2-ocaml-compiler-libs-v0.12.4/lib/ocaml/4.14.0/site-lib/ocaml-compiler-libs/META, /nix/store/v9jrf8a8ksc79m5dliwm8pjjkavjrmj4-ocaml4.14.1-ocaml-compiler-libs-0.12.4/lib/ocaml/4.14.1/site-lib/ocaml-compiler-libs/META
       > findlib: [WARNING] Package stdlib-shims has multiple definitions in /nix/store/l91al9r3ig3vzf8jk2082smknal0wkym-stdlib-shims-0.3.0/lib/ocaml/4.14.0/site-lib/stdlib-shims/META, /nix/store/nyq94bn8nwbgdqq18jivhf6g521di6z6-ocaml4.14.1-stdlib-shims-0.3.0/lib/ocaml/4.14.1/site-lib/stdlib-shims/META
       > findlib: [WARNING] Package sexplib0 has multiple definitions in /nix/store/cqf3l1sbqanibs5lxp2jsxsxwjs3fdrp-sexplib0-v0.15.1/lib/ocaml/4.14.0/site-lib/sexplib0/META, /nix/store/d9j4ih45z666ky92k9f9ccpjyfsrrwx1-ocaml4.14.1-sexplib0-0.15.1/lib/ocaml/4.14.1/site-lib/sexplib0/META
       > findlib: [WARNING] Package base has multiple definitions in /nix/store/ba2inxni4b7lxn5sxhzrbzr6853n648x-base-v0.15.1/lib/ocaml/4.14.0/site-lib/base/META, /nix/store/9h4rk01fjmhlr8hd7wvxm521l76lndws-ocaml4.14.1-base-0.15.1/lib/ocaml/4.14.1/site-lib/base/META
       > findlib: [WARNING] Package ppx_derivers has multiple definitions in /nix/store/6vxv18dpmh2ls1612qc2rybp72694byj-ppx_derivers-1.2.1/lib/ocaml/4.14.0/site-lib/ppx_derivers/META, /nix/store/cbp0sdgzhy27hh3282nmhcnpvygbh894-ocaml4.14.1-ppx_derivers-1.2.1/lib/ocaml/4.14.1/site-lib/ppx_derivers/META
       > findlib: [WARNING] Package ppx_sexp_conv has multiple definitions in /nix/store/2rcjpqz02j3d3v731svkbwj4wp8nclsw-ppx_sexp_conv-v0.15.1/lib/ocaml/4.14.0/site-lib/ppx_sexp_conv/META, /nix/store/86k25a5ff0fbl5i65bjm766lj0af65an-ocaml4.14.1-ppx_sexp_conv-0.15.1/lib/ocaml/4.14.1/site-lib/ppx_sexp_conv/META
       > findlib: [WARNING] Package ppx_assert has multiple definitions in /nix/store/1573gpr6yl165ds6vswpn8pyi25zj7fq-ppx_assert-v0.15.0/lib/ocaml/4.14.0/site-lib/ppx_assert/META, /nix/store/2fk1s3jg360vknpjj9jxpsx62mg2fm1r-ocaml4.14.1-ppx_assert-0.15.0/lib/ocaml/4.14.1/site-lib/ppx_assert/META
       > findlib: [WARNING] Package seq has multiple definitions in /nix/store/xsv09g085cgi7mr8wixxv6hwmh5319j2-seq-base/lib/ocaml/4.14.0/site-lib/seq/META, /nix/store/pci9lpvaing39dm1p8b95pqxq5l5c3pi-ocaml4.14.1-seq-0.1/lib/ocaml/4.14.1/site-lib/seq/META
       > findlib: [WARNING] Package re has multiple definitions in /nix/store/vhxdjjsn5hpgyr9nzrkr2jjmp46hr5h7-re-1.10.4/lib/ocaml/4.14.0/site-lib/re/META, /nix/store/rx9w0kpms0447l6pnkjpvd2y6hw4n0gs-ocaml4.14.1-re-1.10.4/lib/ocaml/4.14.1/site-lib/re/META
       For full logs, run 'nix log /nix/store/gcziwjr9j3lhnh3f4l7pba6dsyc2ly4r-nix-shell-env.drv'.
```

**Comment by Alizter** [comment]
> cc @Alizter does this make cinaps tests work for you in the slim shell?

Yes! :))

**Comment by anmonteiro** [comment]
closing this after #7279

**Comment by Alizter** [comment]
Also upstream has been merged so we can just update nixpkgs.

**Pull request closed without merging**
