### PR TITLE
Use stdune's temp module when possible

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by voodoos** [comment]
It look like the Bootstrap needs an update.

**Comment by rgrinberg** [comment]
Thanks. Should be fixed.

**Review by snowleopard — APPROVED** [review]
Looks good to me. I assume nothing else relied on the names of these temporary files since you appear to be renaming them.

**Comment by rgrinberg** [comment]
yeah, we certainly don't keep the names of temporary files stable.

**Pull request merged**
