### PR TITLE
fix(doc): use sphinx < 6

### LINKED ISSUE #7107: docs: `Uncaught ReferenceError: jQuery is not defined` error
Opening

https://dune.readthedocs.io/en/stable/search.html?q=variables&check_keywords=yes&area=default

The page never ends loading, and the following error is shown in console:
```
Uncaught ReferenceError: jQuery is not defined
```

Yesterday it was working fine.

### PR DESCRIPTION
**Pull request by emillon**
Fixes #7107

### CODE REVIEW

**Comment by Alizter** [comment]
So do we wait till the extensions also support sphinx 6 before removing the limit?

**Comment by emillon** [comment]
Yeah, I'm not sure what's the path forward. There's a sphinxcontrib-jquery.3.0.0 that embeds jquery, which be a solution too, but at least sphinx < 6 is consistent with what we have in nix ATM so I think that's good to adopt for now.

**Comment by emillon** [comment]
@jchavarri this should fix the `/latest/` page but `/stable/` is going to be broken until the next release.

**Comment by Alizter** [comment]
@emillon Can we not forcefully fix the stable page?

**Comment by emillon** [comment]
I don't know how to do that. It's fairly possible that we're going to have a point release for 3.7, and there's the option of using `/latest` so that doesn't seem too bad but if you know how to make a commit a `stable` one we can give it a go.

**Comment by Alizter** [comment]
If you are in the stable page, you cannot switch to latest since the javascript doesn't work.

**Comment by Alizter** [comment]
Macos seems to be failing. We recently had to add `pkg-config` to our macos runners so maybe that is related.

**Review by christinerose — APPROVED** [review]

**Comment by emillon** [comment]
Let's merge this and talk separately about fixing `/stable/`.

**Pull request merged**
