### PR TITLE
Add support for `.dune-fs` files

### PR DESCRIPTION
**Pull request by diml**
To replace `jbuild-ignore` files

### CODE REVIEW

**Comment by diml** [comment]
indeed, i'll add tests.

Thinking about this again, i don't know why not just use an fs stanza in dune files. That would get rid of one kind of files

**Comment by diml** [comment]
I tried that. I still need to update the documentation, but I think it's better this way

**Comment by rgrinberg** [comment]
Jérémie Dimino <notifications@github.com> writes:

> I tried that. I still need to update the documentation, but I think it's better this way

+1 - one less file.

**Comment by diml** [comment]
Indeed. BTW while adding the test, I realised that there is something a bit odd: you can use a `fs` stanza to ignore for instance `*.x`. But this setting is not sticky. In particular, when marking a sub-tree as `raw_data`, then the default settings are assumed inside this sub-tree. This limitation is a bit odd, and we might end up having to extend this feature in the future.

In the end, I'm wondering if we shouldn't have only `(ignored_subdirs (a b c))` for now. Since #732, all pending fs issues have been solved and there have been no request for something more advanced than ignoring sub-trees.

**Comment by diml** [comment]
Superseeded by #767

**Pull request closed without merging**
