### PR TITLE
WIP: Extend PKG_CONFIG_PATH in configurator

### PR DESCRIPTION
**Pull request by emillon**
This cleans up how `PKG_CONFIG_PATH` is set, and extends it to include `$OPAM_SWITCH_PREFIX/lib/pkgconfig`.

I have a couple questions:
- this approach works with opam 2, but is not as generic as the one outlined in #1492. But I'm not sure how to access the list of library directories from configurator, so this seems better.
- how to test this? I thought of using a fake `pkg-config` binary in the workspace, but configurator does not know about this. Would setting `PATH` to a directory with a shell script be acceptable?
- would it be OK to add an optional `?static:bool` option to handle `--static` as in #1492, or is this a breaking change?

Thanks!

### CODE REVIEW

**Comment by emillon** [comment]
One last remark: we build command lines like `env PKG_CONFIG_PATH=a:b:$PKG_CONFIG_PATH`. For other variables like `PATH`, this can cause problems because if the variable is initially unset, this expands to `a:b:`. For `PATH`, this is equivalent to `a:b:.` which can cause security issues. `pkg-config` does not seem to be affected by this, but still, it would probably be better to read the environment and expand it from within configurator. What do you think about this?

**Comment by rgrinberg** [comment]
> how to test this? I thought of using a fake pkg-config binary in the workspace, but configurator does not know about this. Would setting PATH to a directory with a shell script be acceptable?

Did you try using the new `binaries` field in the env stanza?

> would it be OK to add an optional ?static:bool option to handle --static as in #1492, or is this a breaking change?

I don't think it's a breaking change but I'm not convinced that it's necessary either. Toggling static vs non static by the library itself does not seem correct to me. It seems like this is something that the user should be able to set globally.

Also, adding a mechanism to add general flags to pkg-config seems better than just extending it one flag at a time. I'm not even sure if this flag needs to be passed at link time vs compile time btw.

**Comment by rgrinberg** [comment]
> One last remark: we build command lines like env PKG_CONFIG_PATH=a:b:$PKG_CONFIG_PATH. For other variables like PATH, this can cause problems because if the variable is initially unset, this expands to a:b:. For PATH, this is equivalent to a:b:. which can cause security issues. pkg-config does not seem to be affected by this, but still, it would probably be better to read the environment and expand it from within configurator. What do you think about this?

That seems good. I think in general all of our path manipulations should be done via the Env module which should support safe ways of modifying the environment.

**Comment by diml** [comment]
> Did you try using the new binaries field in the env stanza?

plus `%{bin:pkg-config}` in the `(deps ...)` field

> this approach works with opam 2, but is not as generic as the one outlined in #1492. But I'm not sure how to access the list of library directories from configurator, so this seems better.

We could pass it from Dune via an environment variable. Although, I don't even know if that's where other systems will put the .pc files, so it's probably not worth spending time on this right now.

**Comment by emillon** [comment]
> Curious why it isn't made so opam sets `$PKG_CONFIG_PATH` instead (as described in [#1492 (comment)](https://github.com/ocaml/dune/issues/1492#issuecomment-432724543)).

Ah, right. I initially discarded that idea because I thought that it would mean shelling out to opam from configurator, but the opam environment is already defined. I'll try to fix that on the opam side. (I'm leaving this open because we'll probably have something to do for `--static`).

**Comment by emillon** [comment]
I don't think we'll need that thanks to mirage/mirage#969 by @thelortex, so I'm closing this. Thanks!

**Comment by avsm** [comment]
Isn't this still useful as a way to find stuff in macOS _vs_ Unix and so on?

**Comment by emillon** [comment]
That PR is in particular about exposing .pc files installed by opam. As far as I know, only mirage does this. Configurator still uses the system pkgconfig directories, where the system installs .pc files.

**Pull request closed without merging**
