### PR TITLE
[coq] [fix] Install .glob files

### PR DESCRIPTION
**Pull request by ejgallego**
This seems like an omission from the beginning, I'm surprised this wasn't a problem for anyone until now.

### CODE REVIEW

**Comment by Alizter** [comment]
These were added as targets back here:
- https://github.com/ocaml/dune/pull/3721

**Comment by ejgallego** [comment]
Thanks for finding out about that PR @Alizter , indeed it was mostly an accident as it can be seen from the discussion; the plan was to install `.glob` files when we added coqdoc support, however we did forget.

**Comment by JasonGross** [comment]
> I'm surprised this wasn't a problem for anyone until now.

I guess nobody had tried to use coqbot to minimize a development that both (a) relied on dune, and (b) did not qualify project-local imports.  (The minimizer is fairly robust to missing .glob files, in that it will attempt to reconstruct the .glob file via coqc, even for installed files, using the same flags that are used to compile the development being minimized.  Thus only projects that rely on binding their own files with `-R` instead of `-Q` fail to have .glob files remade.)

**Comment by ejgallego** [comment]
Indeed @JasonGross , actually I noted because I did implement jump to definition in coq-lsp and I was like "where are the glob files) !

**Pull request merged**
