### PR TITLE
Bump dune-project to 2.5

### PR DESCRIPTION
**Pull request by snowleopard**
It looks like the Dune's `dune-project` file has fallen behind, and some useful features (like #3092) are not enabled leading to problems like those discussed in #3376.

Let's bump the version to `2.5`. 

Shall we do any other adjustments to `dune-project` to safely transition to the new version?

### CODE REVIEW

**Comment by rgrinberg** [comment]
This PR should have regenerated the opam files in the dune repository. @snowleopard I pushed the regenerated opam files this time, but next time it should be done in the same commit.

**Comment by snowleopard** [comment]
@rgrinberg Sorry for messing this up and thanks for the fix! 

How do you regenerate the opam files? I think it's useful to record this in `dune-project` in a comment.

**Comment by rgrinberg** [comment]
Any build command should regenerate it. So, dune build, dune build @check, dune build @all should all work.

Leaving a comment in the dune-project file is a good idea too.

**Comment by snowleopard** [comment]
Thanks @rgrinberg, done in #3406.

**Pull request merged**
