### PR TITLE
[RFC/WIP] Threadless scheduler

### PR DESCRIPTION
**Pull request by stedolan**
Dune doesn't build on multicore at the moment because (ironically enough) multicore doesn't support stock OCaml's systhreads (although it will eventually).

To fix this, I changed the scheduler to use `Unix.select` to handle process termination, signals and file changed notifications instead of using systhreads. Is this something the dune maintainers would be interested in having upstreamed?

In any case, there are a few more things this patch needs before it can be merged:

  - [ ] file watcher debouncing
  - [ ] windows support
  - [ ] docs for the new `Ev_select` interface
  - [ ] unit tests for the new `Ev_select` interface

(I'm happy to implement these, but I won't bother unless there's interest in merging this patch, so I'm asking for comments now)

### CODE REVIEW

**Comment by ejgallego** [comment]
Oh, @stedolan I just stumbled upon this recently when trying to compile Coq using the multicore branch. Fortunately I could use the make-based system to continue.

But indeed, then running Coq was hard again as the toplevel is using `Thread` and so it was broken. I don't mind so much as I have a branch of Coq that doesn't use it, but I dunno how hard adding `Thread` emulation would be, but certainly that would ease things for many projects.

[Another problem I hit in Coq was the new reserved keywords]

**Comment by stedolan** [comment]
Implementing `Thread` as actual multicore threads wouldn't be very hard. However, preserving the stock OCaml behaviour that "threads" run sequentially is trickier, and some programs rely on this. (See ocamllabs/ocaml-multicore#100)

**Comment by diml** [comment]
My only reservation is that making all this portable will be quite a lot of work. That's the reason I used threads the for the scheduler: they provides a cheap way to multiplex events that works on all platforms.

I don't believe we make the assumption that threads run sequentially in Dune, so plain multicore threads would work for us. Maybe it would be possible to isolate the assumption we make about threads in a dedicated module and provide an alternative implementation of this module for multicore OCaml?

**Comment by ejgallego** [comment]
@stedolan , I tried to build this, however it hangs forever:
```
'/home/egallego/.opam/4.06.1+multicore/bin/ocamldep.opt' -modules src/wp/wp.boot.ml > boot-depends.txt
'/home/egallego/.opam/4.06.1+multicore/bin/ocamldep.opt' -modules src/xdg/xdg.ml > boot-depends.txt
'/home/egallego/.opam/4.06.1+multicore/bin/ocamllex.opt' -q src/let-syntax/lexer.mll
'/home/egallego/.opam/4.06.1+multicore/bin/ocamlc.opt' -g -w -40 -o boot.exe unix.cma threads.cma -I +threads boot.ml
./boot.exe
```
using the opam package which seems to point to `master`.

**Comment by stedolan** [comment]
@ejgallego That's because, even with this patch, `dune` still links against `threads.cmxa` which doesn't work in multicore. (In this case, what's going wrong is that our `Unix.fork` runs inside a blocking section, which plays poorly with the global runtime lock in `threads.cmxa`). It should work fine in multicore once I remove threads from dune's build flags.

**Comment by stedolan** [comment]
> It should work fine in multicore once I remove threads from dune's build flags.

Unusually, the thing that "should work fine" actually did work fine, and this branch builds on multicore now.

**Comment by ejgallego** [comment]
> Unusually, the thing that "should work fine" actually did work fine, and this branch builds on multicore now.

Confirmed, thanks a lot @stedolan , running the test suite I got a few:
```
Error: exception Invalid_argument("Signal events already enabled for signal -6")
```
Unfortunately trying to do a Coq build I got the same problem [in a dune exec call], but I could workaround that and the build completed [didn't try to run yet as it needs a few tweakings]

**Comment by diml** [comment]
@stedolan and @ejgallego, I feel like there will be a lot more development and debugging required before this feature is fully working, portable and production ready. Before committing to it, let's consider alternative approaches.

What else can we do to make dune compatible with multicore? To start with, if we wanted to change dune to be only compatible with OCaml multicore, what would be the easiest way?

**Comment by ejgallego** [comment]
It works now @stedolan , thanks!

**Comment by stedolan** [comment]
@ejgallego This is because I had removed lazy initialisation from the signal handling code. It's back now. (I didn't realise there were code paths that actually ran initialisation twice)

@diml I don't think the portability issue is terrible severe - I think the only portability concern is that I need to re-add the 1kHz process polling hack for Windows that dune currently uses. I do understand being reluctant to to merge this, though, since it's a relatively large change.

Eventually, multicore will support systhreads for compatibility, so the lowest-effort route is to leave dune as is. I'll use my patch for development while multicore doesn't have working systhreads, and eventually stock dune will work on multicore as well. I'd prefer to avoid maintaining a fork, though.

Another option is to use real threads (`Domain.t`) in dune (@dra27 has a patch in this direction). This is a bit inelegant, though, since dune doesn't actually use any parallelism so it seems a bit of a waste to introduce domains.

**Comment by diml** [comment]
There is another issue on Windows: you cannot read from or write to a pipe in non-blocking mode. In particular if you pass a pipe to select then you will never be notified. The only workaround I know is to perform IOs on pipes in separate threads. That's what Lwt does on Windows for instance. But if we can't use threads, then how is that going to work?

**Comment by diml** [comment]
BTW, I didn't mention it, but the version of OCaml used to build dune and the version of OCaml used to build applications do not need to match. i.e. you could build a `dune` with a regular compiler and use it to build applications using ocaml-multicore.

That might require a bit of fiddling with the build process to make that work smoothly with opam, but it is much simpler that rewriting the scheduler entirely.

**Comment by diml** [comment]
To conclude this discussion: we are looking forward OCaml multicore and are happy to help the effort how we can with Dune. However, completely rewriting the Dune scheduler from scratch doesn't feel like the right way to solve the problem at hand. In particular, since `Threads` will have to be ported to multicore eventually, simply waiting for it to be ported it seems like the path with the optimal usage of developers time. In particular I suggest to do that first. Indeed, not only it will unblock Dune for multicore, but it will also unblock a lot of other important packages such as Lwt or Core.

Considering this, I am closing this PR.

**Comment by stedolan** [comment]
Sorry I haven't found time to look at this for a while!

I agree that closing this PR is probably the best choice for dune. The existence of this patch unblocks us for testing software that depends on dune using multicore, and the best route forwards is probably for us to use this patch and for upstream dune to wait until multicore's `Threads` module works as expected. Your suggestion of using a non-multicore dune to build multicore software also sounds good (it will require minor hacking for us, though, not because of dune but because of OPAM).

---

In case I or anyone else wants to resurrect this patch in future, here's my notes on getting the approach to work on Windows. I think there's only an hour or two's work here, but I have neither the motivation nor the Windows machine needed to do it at the moment (and waiting for appveyor builds after each edit is not fun).

Pipes and `Unix.select` work fine under Windows. The Windows `select` function does not support pipes, but thanks to some heroics in OCaml's `win32unix/select.c`, the `Unix.select` function emulates such support. (The emulation amounts to a thread pool polling pipes and waking up `select` if any become readable).

However, the self-pipe trick (a signal handler writes to a pipe to wake up `select`) does not work, but this is because of how signals work under Windows, not pipes. OCaml signal handlers, under Windows, simply call `caml_record_signal`, which sets a flag polled at every allocation and every `caml_{enter/leave}_blocking_section`.

The `Unix.select` function under Windows has no analogue of Unix's `EINTR` - the arrival of a signal will not cause `Unix.select` to return early. Since `Unix.select` takes place in a blocking section, this means that nothing happens after `Ctrl-C` due to the following cycle:

  - `Unix.select` will not return until the pipe is readable
  - The pipe will not be readable until the signal handler writes to it
  - The signal handler will not run until `Unix.select` returns

A second thread breaks this cycle, by giving the signal handler somewhere to run before `select` returns. However, this cycle can also be broken by having a short timeout on `select`: once `select` times out, the signal handler will be run, the pipe becomes readable, and a future `select` will return immediately.

Forcing a short timeout on select seems inefficient - replacing `select` with a polling loop. However, due to limitations of the `Unix.wait` API on Windows, dune already has a 1kHz polling loop on Windows, for child process termination. So, if all of the `select` calls have short timeouts, signal handling should work fine, and be about as efficient as the current polling loop.

There's a secondary issue, which is that pipes on Windows do not support non-blocking mode. This patch uses non-blocking mode on Unix to handle an obscure failure case: what if >PIPE_BUF signals arrive between two `select`s? (e.g. someone holds down ctrl-C while dune is doing a lot of `stat`s to a very slow filesystem). Without non-blocking mode, the pipe can fill up and dune can get wedged in a signal handler that's blocking to write to a pipe that cannot empty until the signal handler returns. (I think on Windows the only thing to do is to ignore the issue and leave the pipe in blocking mode. You can hack around this with creative use of PeekNamedPipe, but not from the API that OCaml exposes).

**Comment by nojb** [comment]
Not directly relevant, but related: https://github.com/ocaml/ocaml/issues/7935

**Comment by alainfrisch** [comment]
> dune already has a 1kHz polling loop on Windows,

Is that https://github.com/ocaml/dune/blob/882fcfc494f844678da469e7ec8dc3d789ceb552/src/scheduler.ml#L420?

As discussed in the ticket linked by @nojb , this would likely result in more like a 64 Hz polling loop, unless special care is applied to request higher frequency clock in Dune's code base, or another running process on the machine does it.

**Comment by diml** [comment]
@alainfrisch yes, that's it. Maybe we should just start one thread per job on Windows. The polling code dates from before we were using threads in Dune, but now that we are using them it seems fine to do that.

**Pull request closed without merging**
