### PR TITLE
Memoize mkdir_p

### PR DESCRIPTION
**Pull request by rgrinberg**
Previously, this was done manually

Signed-off-by: Rudi Grinberg <rudi.grinberg@gmail.com>

### CODE REVIEW

**Comment by aalekseyev** [comment]
You're effectively adding a few `is_managed` checks. I don't know why they were done selectively before, but you're not saying why that should change either. 

It looks plausible to me that this is effectively a no-op change though. (all the directories in question already happen to be managed)

**Comment by rgrinberg** [comment]
> You're effectively adding a few is_managed checks. I don't know why they were done selectively before, but you're not saying why that should change either.

That's right. It seems wrong to me to ever create directories that aren't managed. These are external directories, the build system should never touch them.

**Comment by rgrinberg** [comment]
@aalekseyev I've added an exception when we try to mkdir an external directory.

**Comment by aalekseyev** [comment]
Sounds good.

**Pull request merged**
