### PR TITLE
chore(nix): support build for experimental feature

### PR DESCRIPTION
**Pull request by maiste**
Following the merge of #10724, I have written this PR so we are able to build the executable using _Nix Flake_. I'm far from being a Nix expert, so if someone with a better expertise is able to reduce the amount of code, it would be happy to change the code :smile: 

__EDIT__: Replace my solution with @gridbugs' one, as it is simpler and more elegant one. It consists in adding a function to the package default that could take some flags.

### CODE REVIEW

**Comment by gridbugs** [comment]
Heads up that I pushed a commit that fixes the failing nix test.

**Comment by gridbugs** [comment]
I pushed another change to remove the duplication of the experimental flags.

**Comment by emillon** [comment]
I think it's simpler and more idiomatic to use `overrideAttrs` to update the `configureFlags` of an existing derivation, I'll try something

**Comment by maiste** [comment]
On @gridbugs and my computer, the produced binary works as expected:
- No need to add some flags to get the compiler installed (no error about Ocaml when doing the `dune pkg lock` command)
- It displays the packages installed nicely when running `dune  build`

**Comment by gridbugs** [comment]
Nice work @emillon, I didn't know about `overrideAttrs`. I gave this a test on both macos-aarch64 and linux-x86_64 and both binaries have the features I expected.

**Comment by maiste** [comment]
I have rebased and cleaned the history. If the tests pass, I think it's ok to merge it :+1:

**Comment by emillon** [comment]
> Nice work @emillon, I didn't know about `overrideAttrs`

The part that made it click for me is [this comment](https://www.reddit.com/r/NixOS/comments/cn6nt4/comment/ew7bjhz/) - derivations are `mkDerivation` calls and `overrideAttrs` changes the input of this function.

```nix
{ stdenv, bar, baz }: # this part gets overriden by `override`
stdenv.mkDerivation { # This part gets overriden by overrideAttrs
  pname = "test";
  version = "0.0.1";
  buildInputs = [bar baz];
  phases = ["installPhase"];
  installPhase = "touch $out";
}
```

**Review by emillon — APPROVED** [review]

**Comment by maiste** [comment]
@gridbugs @emillon, I don't have the merge right: can I gently ask one of you to do the merge? :)

**Pull request merged**
