### PR TITLE
Document the interaction between `@all` and (optional)

### PR DESCRIPTION
**Pull request by diml**
`dune build @all` tries to build optional libraries that are not available, which is not great.

### CODE REVIEW

**Comment by diml** [comment]
To fix this, we should at least not generate the various archive files for the library. We could also generate no rules at all for such libraries.

The only disadvantage of doing so is that if the user really wants to build the library, they will get an error about a rule not found, which is not great.

**Comment by rgrinberg** [comment]
> tries to build optional libraries that are not available, which is not great.

It seems like `@all` is acting as intended to me here. I wouldn't expect it to skip any targets.

If had logical targets however, we could have a more sophisticated target:

```
$ dune build all:required
```

For example.

**Comment by rgrinberg** [comment]
> It's not really "required" though, it's more "buildable"

Perhaps we can switch it to enabled once that works: `$ dune build all:enabled`.

> It's a bit odd that @all tries to build things that we know are not buildable.

On the other hand, it's also odd that building `@all` doesn't actually build everything. The problem that we had with `@install` as the default target is that it left some repositories in an untested state for too long because many targets weren't exercised as often as they should. I think if we changed the semantic of `@all` to be `@all-enabled`, we'd sort of reintroduce the problem (on a much smaller scale, but still).

**Comment by diml** [comment]
Hmm, yh that's true. Something like `all:enabled` seems good. Any objection to merging this PR to document the current behavior?

**Pull request merged**
