### PR TITLE
Doc refresh - 2

### PR DESCRIPTION
**Pull request by nojb**
From #2521 : 

- Rename the section "dune files" to "Stanzas" (maybe "Stanza reference" would be better); this section has three subsection, one for each of `dune`, `dune-project` and `dune-workspace`.
- Documented most of `dune-project` stanzas in the corresponding subsection
- Moved `dune-workspace` documentation to corresponding subsection (used to be in "Usage")
- Moved "Common items" to top-level and renamed it "Concepts".

As a general rule I think it would be nice to limit the TOC depth to 2 instead of 3 as it currently is to avoid deep nesting, but that would require lifting the sections for `dune`, `dune-project` and `dune-workspace` to the toplevel. We can think about this later.

### CODE REVIEW

**Comment by nojb** [comment]
By the way, the idea behind the "stanzas" section is that that's the section where people will find what they are looking for 85% of the time: which stanzas are available in each file and the precise syntax with a brief explanation. Links are provided to other sections and subsections where specific topics are developed.

**Comment by rgrinberg** [comment]
How about "Dune language" rather than the general sounding "Concepts". Concepts seems a bit too high level

**Comment by nojb** [comment]
> How about "Dune language" rather than the general sounding "Concepts". Concepts seems a bit too high level

I don't have a strong preference for a precise title at the moment; "Dune language" is OK I guess. What about "Common concepts" ?

**Comment by nojb** [comment]
Thanks, I renamed "Concepts" into "General concepts" so that it is a little less "high-level" and "Stanzas" into "Stanza reference" which I think is clearer. We can always refine it later.

**Pull request merged**
