### PR TITLE
Extract Process.Temp

### PR DESCRIPTION
**Pull request by NathanReb**
This is a first step towards #3432 and is required to move forward with #3392.

### CODE REVIEW

**Comment by NathanReb** [comment]
You're right, this bit could actually be moved to stdune. I didn't put it there because the remaining points in #3432 seem a bit specific to dune. Either way works for me!

**Comment by NathanReb** [comment]
We could have `Stdune.Temp` and `Dune_temp` modules, the latter using the former.

**Comment by nojb** [comment]
> We could have `Stdune.Temp` and `Dune_temp` modules, the latter using the former.

Sounds OK to me, but just in case a second opinion would be nice.

**Comment by jeremiedimino** [comment]
To be fair, putting all temporary files into a single temporary directory seems like a good practice to me. So having a single module that lives in `Stdune` seems fine to me.

**Comment by NathanReb** [comment]
Yeah makes sense, I'll move it!

**Comment by NathanReb** [comment]
Done!

**Comment by NathanReb** [comment]
Can I go ahead and merge this despite the CI error?

**Comment by rgrinberg** [comment]
@NathanReb yeah, this is good to merge. The error is unrelated.

**Pull request merged**
