### PR TITLE
Fixes #366 - Escape backslashes .merlin FLG lines

### LINKED ISSUE #366: On Windows, generated .merlin ppx path incorrectly uses backslashes
I have a `jbuild`:

```lisp
(jbuild_version 1)

(executables
 ((names        (example))
  (flags (:standard -short-paths))
  (preprocess (pps (ppx_jane)))))
```

with `example.ml`:

```ocaml
open Base

let f = [%compare.equal: int]
```

This builds just fine. However, the generated .merlin has the following line:

    FLG -ppx "C:\Users\levim\src\ppx-example\_build/default/.ppx/ppx_jane/ppx.exe --as-ppx"

This results in merlin trying and failing to find the ppx at:

    C:.\\Userslevimsrcppx-example_build\\default\\.ppx\\ppx_jane\\ppx.exe

This apparently can be fixed by manually modifying the `\` in the generated .merlin either to `/` or `\\`.

Related to #201.

### PR DESCRIPTION
**Pull request by mlasson**
It is necessary to escape/or use forward slashes in the path to
the ppx executable provided to merlin to avoid messing with merlin's
implementation of unescaping FLG lines in .merlin files.

### CODE REVIEW

**Comment by trefis** [comment]
Let's ask @let-def .

**Comment by mlasson** [comment]
Ok, my bad.

This replacement is not valid when using "UNC" path, so maybe we should use escaping "\\" actually or we would probably break merlin users that build on a network disk. 

Eg. "\\.\C:\Users\mlasson\dune/_build" -> "\\\\.\\C:\\Users\\mlasson\\dune/_build"

what a mess.

**Comment by let-def** [comment]
Merlin unescaping tries to follow shell conventions. Should we do something else?

**Comment by mlasson** [comment]
Ideally, a user may expect to copy past the FLG line from the .merlin and pass it directly to ocaml using his shell, but that seems hard to achieve. I think, current merlin escaping is fine and dune should try to follow merlin's convention so that after merlin unescaping the thing is parsable by cmd.exe (or Sys.command).

**Comment by diml** [comment]
Should we just escape `\` characters in dune then?

**Comment by dra27** [comment]
It feels like a good first step that Dune escape the backslashes, yes. Trying to translate between forward and backslashes in a shell-consistent way is notoriously hard, but what is useful (IIRC) is that `C:\\` and `C:\` are definitely the same path (unlike `/` and `//` on Unix)

**Comment by mlasson** [comment]
Note that this PR now simply quote the backslashes.

**Comment by diml** [comment]
Indeed, patch looks good, thanks!

**Pull request merged**
