### PR TITLE
Introduce dune.result library

### PR DESCRIPTION
**Pull request by rgrinberg**
This library is equivalent to the result library for 4.02 compatibility.

@ejgallego you will need to rebase your PR once this is merged

### CODE REVIEW

**Comment by rgrinberg** [comment]
Okay, I fixed bootstrap

**Comment by diml** [comment]
Actually, should we call it `dune._result` like other internal libraries? So that we can easily remove it in the future. If it is not marked as internal, we can't really remove it without a deprecation cycle.

**Comment by rgrinberg** [comment]
Well we are explicitly making it available via configurator, so it seems like this library is no longer private. I think we might as well just drop this library when we drop 4.02. Would that need a deprecation cycle as well?

**Comment by diml** [comment]
What if some user refers to `dune.result` or `Dune_result`? Deleting this library without notice would break their code.

**Comment by emillon** [comment]
I think it's ok to make it public API at least for the rest of dune 1.x releases. If we drop 4.02 for dune 2, this can be dropped as well.

**Comment by rgrinberg** [comment]
I made it private

**Pull request merged**
