### PR TITLE
test: missing opam file now causes build failure

### PR DESCRIPTION
**Pull request by emillon**
Since #8518, we fail in the case where `(generate_opam_files)` is true but the generated file is not part of the release tarball.

### CODE REVIEW

**Comment by emillon** [comment]
@rgrinberg this is technically a regression introduced by #8518 (there are 94 failures in the alpha1 run related to that). I think we can argue that these packages have an issue, but I wonder if we can do better than just failing.

**Comment by rgrinberg** [comment]
I suppose we could guard the check behind a project version. Although it makes the fix sort of useless because upstream maintainers don't want to upgrade the dune language in every single package to make the builds reproducible.

**Comment by emillon** [comment]
I agree it doesn't seem ideal. Removing duplicates, it's 17 releases (12 unique packages) so it's something we can easily communicate and patch.

**Comment by emillon** [comment]
I think we can set bounds + send patches upstream but this can be discussed at the next team meeting.

**Comment by rgrinberg** [comment]
Upstream patches that allows for this PR to work https://github.com/ocaml/dune/pull/8512 would be welcome as well.

It's the same issue just with different rules.

**Comment by rgrinberg** [comment]
Now that I think about it, we could adjust the feature as following:

Instead of ignoring the rule completely, we could make it a normal instead of a promote rule.

**Comment by emillon** [comment]
I'll merge this as a regression test and open an issue to track this idea.

**Pull request merged**
