### PR TITLE
dune formatting: style tweaks

### PR DESCRIPTION
**Pull request by nojb**
This PR tweaks the formatting style for `dune` files in two small ways:

- reduces to one (from two) the number of spaces when indenting certain nested lists. I assume this was unintended because it seems incoherent with the one-space indent for top-level lists.

- uses an `hv` box rather than an `hov` box for these lists. The rationale is that if you have long lists in your `dune` files the "wrapped" style produced using `hov` boxes is unreadable, `diff`-unfriendly, etc.

I realize that the specific formatting style is not versioned, so am not sure how to go about with this change.

### CODE REVIEW

**Review by rgrinberg — APPROVED** [review]
Since this is a one line change, I took the liberty of taking this from @snowleopard 's plate and reviewing.

@nojb what about moving the formatter to `Pp`? It's a little irksome that we still have instances of formatting strings in the codebase.

**Comment by nojb** [comment]
> @nojb what about moving the formatter to `Pp`? It's a little irksome that we still have instances of formatting strings in the codebase.

Done! By the way, I hadn't looked at `Pp` before -- it is nice!

**Comment by rgrinberg** [comment]
Awesome. Thanks.

**Review by snowleopard — COMMENTED** [review]
Looks good to me, thanks, and sorry for the delay!

**Comment by nojb** [comment]
> Looks good to me, thanks, and sorry for the delay!

No problem, thanks! I went ahead and merged on the basis of @rgrinberg's approval.

**Comment by snowleopard** [comment]
Sure, that's fine! Thanks @rgrinberg :)

**Comment by rgrinberg** [comment]
@nojb I tihnk this change needs to be versioned. Sorry, I just remembered this.

**Comment by nojb** [comment]
> @nojb I tihnk this change needs to be versioned. Sorry, I just remembered this.

Fair enough, see #3946

**Pull request merged**
