### PR TITLE
Add a test-case to showcase a change in promotion's behaviour in 2.0

### PR DESCRIPTION
**Pull request by NathanReb**
This is a MWE of the bug mentioned in #2958 !

I'm happy to look into a fix as well if need be!

### CODE REVIEW

**Comment by NathanReb** [comment]
Just realized that this test is likely break due to race conditions :/

**Comment by NathanReb** [comment]
It seems that this change was introduced in 77b8fc031b00ac7c8722f6fdb01d08fcb87da0b8. I'll take a look!

**Comment by diml** [comment]
Thanks for bisecting and the reproduction case! Racy tests are not great indeed. I guess we should merge the test as part of the fix.

**Comment by NathanReb** [comment]
We've been looking into it with @voodoos and hope to come up with a fix. It might take a bit of time though as we need to familiarize with Fiber and parts of dune I'm not accustomed to yet!

**Comment by diml** [comment]
This should be deterministic as we run the tests with -j1. I have an idea of what could be the cause, I'm having a quick look

**Pull request merged**
