### PR TITLE
dune_file_watcher: do not exclude _opam and _esy systematically

### PR DESCRIPTION
**Pull request by nojb**
As discussed in the thread starting at https://github.com/ocaml/dune/pull/7010#issuecomment-1430313703, it seems that it is not right to systematically exclude `_opam` (and `_esy`) from the file notification watchers, since these directories may be added explicitly to the Dune build (eg by using `(vendored_dirs ...)`).

cc @jonahbeckford @rgrinberg

### CODE REVIEW

**Comment by jonahbeckford** [comment]
Could we just have a command line option / dune-project config item / environment variable for “don’t use default exclusion rules”? I think that Boolean would be simplest.

But perhaps we can let the user specify the exact exclusion rules as a list of strings (ex. semicolon separated list of rules) instead. Maybe I’m the only one in the world, but I have huge node_modules/ directories inside my source tree when I get Dune to generate JS. And large Conda (Python) environments when I mix OCaml with Sphinx.

**Comment by rgrinberg** [comment]
I also think that removing _opam and _esy from the default list should be opt-in. Many users have a local switch in _opam so it doesn't make sense to inconvenience the majority. A command line option or a workspace option to remove the default paths would make more sense.

**Comment by jonahbeckford** [comment]
I don't know my way around the dune codebase. This could be something I can take over though if someone could point me to an example in the code of using a workspace option.

**Comment by nojb** [comment]
Being able to customize the set of exclusion patterns seems the better way to go, so I'll close this one.

**Pull request closed without merging**
