### PR TITLE
Add some automated tests for dune watching mode

### PR DESCRIPTION
**Pull request by aalekseyev**

### CODE REVIEW

**Comment by rgrinberg** [comment]
The flags being added here seem fairly specialized. Instead of adding them, did you consider perhaps adding rpc requests to control watch mode instead?

**Comment by aalekseyev** [comment]
I considered it, but I don't understand the RPC interface enough to know offhand how to do it. Since the RPC was not merged in yet I didn't want to rock that boat.

We thought that it's OK to add a simple flag for now and think about integration with the RPC mechanism later.

**Comment by aalekseyev** [comment]
@rgrinberg, my understanding of RPC did not improve very much since then, but I rebased this PR and I'd like to push it forward, since the subject of testing watch mode came up again. 
Do you mind giving me some pointers how you think it would be reasonable to integrate file watching notifications with RPC, if you had a chance to think about it?

**Comment by rgrinberg** [comment]
>  my understanding of RPC did not improve very much since then

RPC is certainly ready enough to be usable in tests, but it's not clear to me how exactly it should be used here. It's definitely possible to write the automation harness over RPC instead of a cli, but i'm not sure of what the advantage would be. Another idea brought up in another issue would be to send file notification events over RPC instead of running an external file watcher. That makes it easier to write tests, but then the tests themselves become less useful.

In any case, I don't have any fully fledged ideas so there's no reason to block this PR. I'd just mention somewhere that these CLI options aren't stable so that users don't rely on them.

**Comment by aalekseyev** [comment]
Thanks.
We had a small brainstorm with Jeremie of what RPC interface is most useful for these tests.
As you say, delivering file modification events manually makes the tests much less useful so I'd like to avoid that.
One idea is to start Dune in a mode where it's passively watching for changes, and control it with an RPC that makes it act upon those changes (do a build).

So the tests could look something like:

```
dune build goal1 -w --passive &
dune rpc build
modify-some-files
dune rpc build
modify-more-files
dune rpc build
```
I plan to look at implementing something like that.

**Pull request closed without merging**
