### PR TITLE
test: rename directory targets tests

### PR DESCRIPTION
**Pull request by rgrinberg**
allows to include additional tests in the same directory.

### CODE REVIEW

**Comment by rgrinberg** [comment]
@snowleopard I would have expected this to work properly.

**Comment by snowleopard** [comment]
@rgrinberg Right now, depending on a directory only works if that directory is a target of a rule but I agree that depending on source directories seems like a natural next step. 

In general, the story of directory dependencies needs more work, with the first step adding the `(dir foo)` syntax to express such dependencies, mirroring the syntax used in target specification.

**Comment by rgrinberg** [comment]
Okay, then I believe the test in this PR is useful.

**Review by snowleopard — APPROVED** [review]
Looks good but please expand the comment in the doc, clarifying that the current behaviour isn't ideal and we in fact plan to change it.

**Pull request merged**
