### PR TITLE
Port more functions to use Path.Build.t

### PR DESCRIPTION
**Pull request by rgrinberg**
List of public functions modified:

* C.Sources.objects
* Coq_module.obj_file
* Format_rules.gen_rules
* Format_rules.gen_rules_output
* Preprocessing.make
* Super_context.add_rule
* Super_context.add_rule_get_targets
* Super_context.add_rules
* Super_context.add_alias_action
* Super_context.Action.run
* Virtual_rules.setup_copy_rules_for_impl
* Utop.setup
* Utop.is_utop_dir
* Odoc.gen_rules
* Js_of_ocaml_rules.build_cm
* Js_of_ocaml_rules.build_exe
* Lib_archives.make
* Expander.dir
* Expander.set_dir
* Expander.c_flags
* Dune_file.Library.stubs
* Dune_file.Library.stubs_archive
* Dune_file.Library.dll
* Dune_file.Library.archive

I believe I can start porting Action, Build

### CODE REVIEW

**Comment by aalekseyev** [comment]
I guess we should be looking at `Path.Build.{to_string/of_string}` more closely than I realized. When you remove or add `Build.` you're changing the semantics. In particular, `Path.Build.of_string` in `src/coq_rules.ml` looks suspicious.

**Comment by aalekseyev** [comment]
I pushed a fix.

**Comment by rgrinberg** [comment]
> I guess we should be looking at Path.Build.{to_string/of_string} more closely than I realized. When you remove or add Build. you're changing the semantics. In particular, Path.Build.of_string in src/coq_rules.ml looks suspicious.

Thanks, I try to be careful here but there's quite a bit of stuff to port. I think that we should probably make `Path.to_string`, `Path.Build.to_string`, `Path.Source.to_string`, all return the same string. Otherwise it's too easy to change the semantics in an unintended way.

**Comment by aalekseyev** [comment]
Path.to_string and Path.Source.to_string already return the same string (I hope).

For Path.Build.to_string I don't like that it would depend on the configurable build directory root. Maybe we should just remove this function? :-)

**Comment by aalekseyev** [comment]
Actually Path.to_string already depends on that thing. OK, I'm fine with making Path.Build's string representation have "build_" in front.

**Comment by rgrinberg** [comment]
Ok. I'll make that change separately.

**Comment by rgrinberg** [comment]
Now that I've rebased the commit, it seems to introduce some (innocent looking) re-ordering of build commands. I think this is probably fine, but it would be nice to know what is causing it.

I also added a commit to remove an instance of polyrmorphic comparison of paths.

**Comment by aalekseyev** [comment]
What is it specifically that you're running to observe reordering? I do expect the 

I do expect #2189 (the thing you're rebasing onto) to introduce some re-ordering, but I don't expect anything in this PR to do so

**Comment by aalekseyev** [comment]
Actually I found what caused the reordering and reverted it. It looks like using `Mode.compiled_lib_ext Native` instead of `ctx.ext_lib` makes a difference.

**Pull request merged**
