### PR TITLE
Refactor [Foreign]

### PR DESCRIPTION
**Pull request by cwong-ocaml**
In the same vein as my other recent PRs.

This started as a refactoring of "definitely backend" modules that used `Lib_name`, but I noticed that `Foreign` was also mostly things that don't need to be in the engine.

I'm generally less satisfied with this one (see my rant in `foreign_langage.mli`), but I think it's a step in the right direction -- `foreign` feels like a front-end module, so we should move towards moving all of that infrastructure into the frontend.

Would appreciate other thoughts.

Signed-off-by: Cameron Wong <cwong@janestreet.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
I agree that this refactoring seems off to me. Stepping back a bit, I don't see why `Copy_line_add_directive` needs to care about foreign extensions at all. What makes more sense to me is to interpret whether we need this additional line directive when we expand the action.

Let's see if @aalekseyev has an opinion on this perhaps.

**Comment by aalekseyev** [comment]
FWIW, I think splitting Foreign_language out in a separate file is probably a small improvement regardless of the backend/frontend stuff.

I agree with Rudi: we can check the file extension earlier and change the constructor to something along these lines:

```
module Line_directive_style = struct
  type t = | C | Ocaml
end

type Action.t =
...
    | Copy_and_add_line_directive of path * target * Line_directive_style.t
...
```

**Comment by aalekseyev** [comment]
Given what I said about split of Foreign_language being a good thing, I don't see why we shouldn't merge this PR as is if it makes things simpler and make the `Line_directive_improvement` improvement separately. @rgrinberg, do you agree?

**Comment by rgrinberg** [comment]
This change indeed looks good to me. I should clarify that my earlier reservation was about this work trying to work around a dependency edge that shouldn't be there in the first place. I don't mind at all flattening our module hierarchy if it doesn't leak any implementation details. Hence this PR LGTM

**Review by aalekseyev — APPROVED** [review]

**Pull request merged**
