### PR TITLE
feature(fiber): introduce package

### PR DESCRIPTION
**Pull request by rgrinberg**
and mark API is unstable

cc @anuragsoni

### CODE REVIEW

**Comment by rgrinberg** [comment]
@jeremiedimino I moved configurator to its own project. I think it's the easiest way to make it not inherit dune's toplevel `env` options. This is needed because configurator still needs to build with ancient versions of OCaml that don't support the alert flag in the command line.

**Comment by jeremiedimino** [comment]
Couldn't we do `:standard \ -alert=-unstable` for configurator? But a separate dune-project file seems fine as well.

**Review by jeremiedimino — APPROVED** [review]
LGTM

**Comment by rgrinberg** [comment]
Merged with jeremie's workaround instead.

**Pull request closed without merging**
