### PR TITLE
get rid of alias stamp files and compute alias expansions

### PR DESCRIPTION
**Pull request by aalekseyev**
Signed-off-by: Arseniy Alekseyev <aalekseyev@janestreet.com>

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good.

We discussed this PR offline. The only thing missing is that `dune rules` doesn't expand aliases completely, but we can change that later.

**Comment by aalekseyev** [comment]
I ran a benchmark of `git clean -Xdf; time make test` in dune, and saw it take ~50 seconds at the base and ~60 seconds at the tip of this PR for me.

Some slowdown is expected because we're putting more things in the sandbox. To be honest I'm relieved the slowdown is not worse, but of course losing 10 seconds is not great either.

**Comment by jeremiedimino** [comment]
Indeed, let's make a note to look into this for Dune 3.0. If we can't find a good solution, one option is to make this behaviour conditional. BTW, right now `OCAMLPATH` allows to escape the sandbox, so that's another thing to fix.

**Comment by ejgallego** [comment]
Thanks all, couple of questions:
- should https://github.com/ocaml/dune/issues/3415 be closed?
- could this be candidate for a 2.9 ?

**Comment by aalekseyev** [comment]
I don't know what the plan for 2.9 is. If that release is done the way releases are usually done, then this change will make it to 2.9 because it's unconditional (does not depend on language version).

**Pull request merged**
