### PR TITLE
fix(sendfile): Flush the out_channel used in the fallback path

### LINKED ISSUE #8284: Dune upgrades to 3.9.2 but fails to build other packages (Mint, ecryptfs)
## Expected Behavior

`opam upgrade -v` successfully upgrades my packages.

## Actual Behavior

The build of packages using Dune fails.

## Reproduction

`opam update -v`

I can still revert to the previous opam state, which has Dune 3.7.1.

## Specifications

OCaml 5, Dune 3.9.2, Linux Mint 21.2, Linux kernel 5.15.0-78-generic, ecryptfs

## Additional information 

This is the output of the `opam upgrade -v` command, there are a lot of errors that are hard for me to make sense of: https://gist.github.com/alan-j-hu/7bf8fcc6ede90c6ebe604af38745334b

This is probably still related to https://github.com/ocaml/dune/issues/8041 and https://github.com/ocaml/dune/issues/8210.

### PR DESCRIPTION
**Pull request by alan-j-hu**
Fixes #8284

### CODE REVIEW

**Comment by alan-j-hu** [comment]
This code is a little ugly. Because the `| exception Unix.Unix_error (EINVAL, "sendfile", _) ->` case has separate cleanup rules, I can't use `Exn.protect` to close the `src` and `dst` descriptors. I'm trying to see if there's a cleaner way to write the code.

**Comment by alan-j-hu** [comment]
Made the code cleaner and made the diff smaller by adding an explicit `flush oc` instead of having two different cleanup paths.

**Comment by alan-j-hu** [comment]
Added a code comment explaining why the explicit flush is necessary.

**Comment by rgrinberg** [comment]
Thanks for the fix. I tweaked a little to always close with the channel api when using channels. I think that's a little safer and makes sure that all of the channel's invariants are respected.

**Comment by emillon** [comment]
Nice detective work! The fix is a bit complicated but so is the problem so I'd say that's ok. I'd feel safer with a test so I added one in #8292, to merge before this PR. Thanks!
(did you manage to test that it fixes your other opam installation issues?)

**Comment by emillon** [comment]
I rebased and top of the fix and it's all good to me.

**Comment by alan-j-hu** [comment]
@rgrinberg Did you see the review comments I left? I'm pretty sure that the exception was forgotten to be reraised.

**Comment by rgrinberg** [comment]
Nope. I didn't see them. Maybe you forgot to submit the comments? Will fix though.

**Comment by alan-j-hu** [comment]
[Holy moly, "Pending" is such misleading UI. If not for today, I would not have realized that just commenting on a piece of code in review doesn't submit it.](https://github.com/orgs/community/discussions/10369)

**Comment by alan-j-hu** [comment]
I can confirm that my installation issues are fixed when I pinned the dune package to the Git repo.

**Pull request merged**
