### PR TITLE
Benchmark Support

### PR DESCRIPTION
**Pull request by rgrinberg**
- [x] alias to build benchmarks
- [ ] build an executable that will run the benchmarks after setting the env appropriately.
- [ ] add tests.

### CODE REVIEW

**Comment by diml** [comment]
What does this alias means BTW? Is it just building the benchmarks or running them?

**Comment by rgrinberg** [comment]
analogous to `@runtest` so running benchmarks. Perhaps we should name it `@runbench` as well?

But thinking about it a little more, I'm not sure how well this would work in practice. We'd like the benchmarks to run serially, and we'd also prefer that we aren't doing any compilation meanwhile. So I suppose it could only work well with `-j1`?

**Comment by diml** [comment]
> But thinking about it a little more, I'm not sure how well this would work in practice. We'd like the benchmarks to run serially, and we'd also prefer that we aren't doing any compilation meanwhile. So I suppose it could only work well with -j1?

Yes, in fact at Jane Street we never run benchmarks through the build system. People always run individual benchmarks manually and make sure to run them on an idle machine. What our jenga rules do is generate an `inline_benchmark_runner.sh` script that call the benchmark runner and user call this script.

I guess we could slightly change core_bench so that we don't need a wrapper script, and then users would just do:

```
$ jbuilder exec ./inline_benchmark_runner.exe ...
```

**Comment by diml** [comment]
That said, we might still want an alias to build these runners

**Comment by rgrinberg** [comment]
Yeah. In that case the `@bench` alias makes sense. Should we generate such a runner script as well perhaps? What does it look like?

**Comment by diml** [comment]
It looks like [this](https://github.com/diml/memory-access-bench/blob/master/runner.sh):

```sh
#!/usr/bin/env sh
export BENCHMARKS_RUNNER=TRUE
export BENCH_LIB=mem_bench
exec ./_build/default/main.exe -run-without-cross-library-inlining "$@"
```

If we generate a script, we have to handle windows as well. However, what this script is doing could be easily supported by generating a .ml file instead. For the `BENCHMARKS_RUNNER=true`, we could use library variants instead or in the meantime use the same solution as ppx_inline_test.

**Comment by rgrinberg** [comment]
> Yes, in fact at Jane Street we never run benchmarks through the build system. People always run individual benchmarks manually and make sure to run them on an idle machine. What our jenga rules do is generate an `inline_benchmark_runner.sh` script that call the benchmark runner and user call this script.

For our own benchmarks in dune, we're actually running the benchmarks via dune:

```
#!/usr/bin/env sh
export BENCHMARKS_RUNNER=TRUE
export BENCH_LIB=dune_bench
exec dune exec -- ./main.exe -fork -run-without-cross-library-inlining "$@"

```

Another question about this: We're setting `BENCH_LIB=dune_bench` above, but the runner executable already sets the library name:

```
Inline_benchmarks_public.Runner.main ~libname:"dune_bench"
```

Is this redundancy intended?

Also, rather than generating a shell script, would it be possible to just include all the pre-amble in the benchmark binary instead? If we're calling `Inline_benchmarks_public.Runner.main` directly, then `BENCHMARKS_RUNNER=TRUE` should be obvious.

**Comment by diml** [comment]
I'm not sure, that seems better to me as well, but I'm not very familiar with the code of core_bench. /cc @sliquister in case he knows or knows someone who would know.

**Pull request closed without merging**
