### PR TITLE
Add test for using (include_subdirs unqualified) + (preprocess (action ...))

### PR DESCRIPTION
**Pull request by nojb**
Test case for #1624

### CODE REVIEW

**Comment by rgrinberg** [comment]
Did you forget to push the `run.t` file?

**Comment by nojb** [comment]
Indeed. I pushed a dummy entry for this test; it but will need to be amended when the test passes.

**Comment by rgrinberg** [comment]
Feel free to promote it. We can commit tests that fail (as long as they do so in a reproducible way).

**Comment by nojb** [comment]
OK, done.

**Comment by rgrinberg** [comment]
I pushed a fix. @nojb does this fix things for you in your original repo?

**Comment by nojb** [comment]
Yes, it does. Thanks!

**Pull request merged**
