### PR TITLE
Add cxx extension for C++ stubs

### PR DESCRIPTION
**Pull request by rgrinberg**
This feature would be nice to add, but I'm wondering if we should version it.

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by diml** [comment]
By version it, do you mean only consider `.cxx` files if the dune language is >= 1.8?

**Comment by rgrinberg** [comment]
Exactly

**Comment by diml** [comment]
That does put us on the safe side at minimal cost, so I'm for it.

**Comment by rgrinberg** [comment]
I've pushed a commit that does it, but I'm not sure how minimal this cost it.

**Comment by rgrinberg** [comment]
@diml would you mind looking over the changes to make this 1.8+ only? It's quite intrusive, so I'm wondering if there's an easier way

**Comment by diml** [comment]
I can't think of a simpler way. BTW, it's worth printing  a warning when seeing a `.cxx` file with <=1.7, otherwise users might be confused why their .cxx files are ignored.

**Comment by rgrinberg** [comment]
I added such a warning.

**Review by ghost — APPROVED** [review]

**Pull request merged**
