### PR TITLE
[CI] enable cache for Unix jobs

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by Alizter** [comment]
This looks to be more trouble than it is worth unfortunately.

**Comment by emillon** [comment]
I tried to set `DUNE_CACHE=disabled` for the rest of the run but it was still causing problems. I think there's an issue with dune's test suite itself when the cache is enabled.

**Comment by emillon** [comment]
@Alizter disabling the dune cache for tests through `(env)` seems to work  (I'll submit that in a separate PR)` but coq is still not cached. [The opam file for coq 8.16.0 still overrides COQ_USE_DUNE](https://github.com/ocaml/opam-repository/blob/a1fdc2d1a3d7ea17ad27253d882a8dbbce22279e/packages/coq/coq.8.16.0/opam#L46) and so [it continues to use the make-based build](https://github.com/coq/coq/blob/V8.16.0/Makefile). Do you know why that's the case?

**Comment by Alizter** [comment]
@emillon The 8.16 makefile just calls dune under the hood so it shouldn't be an issue.

**Comment by emillon** [comment]
> @emillon The 8.16 makefile just calls dune under the hood so it shouldn't be an issue. We are generating the build rules ourselves since Dune is unable to generate and execute at the same time. AFAIK if DUNE_CACHE=enabled then it should work. Have a look at Makefile.dune.

I understand that it's the intent, but this does not correspond to what is in the tarball that's being used by opam:
- [here's the opam file as present in opam-repository](https://github.com/ocaml/opam-repository/blob/a1fdc2d1a3d7ea17ad27253d882a8dbbce22279e/packages/coq/coq.8.16.0/opam#L46) - it calls `make "COQ_USE_DUNE=" "-j%{jobs}%"`
- this is executed after unpacking the tarball at [this url](https://github.com/ocaml/opam-repository/blob/a1fdc2d1a3d7ea17ad27253d882a8dbbce22279e/packages/coq/coq.8.16.0/opam#L53). we can browse the contents of that tarball [here (it's the V8.16.0 tag)](https://github.com/coq/coq/tree/V8.16.0)
- [the Makefile has the branching logic](https://github.com/coq/coq/blob/V8.16.0/Makefile). because `COQ_USE_DUNE` is set to the empty string, this calls out the make-based build

What confuses me is that in master, [the Makefile just calls out to dune](https://github.com/coq/coq/blob/ee748e6700e1ebe6bb4926f1ebf5df05c8f951fb/Makefile). But the version in the 8.16.0 release tarball does not have this so we're never going into `Makefile.dune` through opam.

Do you see what I mean? I don't know how the coq release process works in terms of branches and tags but the changes in the Makefile have not been propagated to the release tag.

**Comment by Alizter** [comment]
@emillon Sorry you are correct! It has been some time since I thought about it. I guess we have to wait one more version to take advantage of the Dune caching via opam.

**Comment by emillon** [comment]
Makes sense! so 8.17 should use the dune cache out of the box.

**Pull request closed without merging**
