### PR TITLE
fix(pkg): jobs var

### PR DESCRIPTION
**Pull request by Alizter**
We fix the expansion of the jobs var.

### CODE REVIEW

**Comment by Alizter** [comment]
The CI is failing because occasionally our Linux runners have gmake installed causing it to be preferred over make.

This highlights a bug that we have and I have created a test for it in #8750. I also have a fix ready. If I rerun the CI it will most likely go away.

**Comment by rgrinberg** [comment]
@Alizter what's going on with this PR?

**Comment by Alizter** [comment]
@rgrinberg I've fixed it. It was waiting for the removal of the user var which has now happened.

**Comment by rgrinberg** [comment]
Thanks.

**Pull request merged**
