### PR TITLE
Use dune_lang instead of csexp in dune_memory

### PR DESCRIPTION
**Pull request by diml**
As discussed on slack. This will simplify the code base

### CODE REVIEW

**Comment by diml** [comment]
This is ready for review. @mefyl could you have a look?

**Comment by aalekseyev** [comment]
What's the solution for how to deal with strings with special characters though?
Shouldn't we use Quoted_string for most things like paths etc. instead of Atom?

**Comment by diml** [comment]
Yes, either `Quoted_string` directly or `Dune_lang.atom_or_quoted_string`. It's a bit odd to quote things as this just a program talking to another program, but at the same time it'll allow to reuse the same versioning mechanisms.

One other alternative I was thinking of would be to generalise `Decoder.t` so that it could work with different underlying formats. Indeed, when looking at the various `Decoder.t` values, there is not much that specific to `Dune_lang.t`. With a bit of work, decoders could work with various underlying formats.

**Comment by diml** [comment]
Let's put this on hold for now. I'm going to explore some other path

**Pull request closed without merging**
