### PR TITLE
Remove unwrapped restriction for virtual libraries

### PR DESCRIPTION
**Pull request by rgrinberg**
As discussed with @avsm, this is actually necessary to port a lot of libraries in practice.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Hmm, somehow the tests are failing:

```
   $ dune build 2>&1 | grep -v ocamlc
   File "fooexe.ml", line 3, characters 0-7:
   Error (warning 3): deprecated: module Bar
-  Will be removed past 2020-20-20. Use Mylib.Bar instead.
+  . Use Mylib.Bar instead.
   File "fooexe.ml", line 4, characters 0-7:
   Error (warning 3): deprecated: module Foo
-  Will be removed past 2020-20-20. Use Mylib.Foo instead.
+  . Use Mylib.Foo instead.
   File "fooexe.ml", line 7, characters 11-22:
   Error (warning 3): deprecated: module Intf_only
-  Will be removed past 2020-20-20. Use Mylib.Intf_only instead.
+  . Use Mylib.Intf_only instead.
+RESULT=1
+'[' 0 -eq 0 ']'
+rm -rf /home/travis/.opam
+mv /home/travis/.opam-start /home/travis/.opam
+exit 1
```

And I can't reproduce this locally.

**Comment by emillon** [comment]
I can reproduce here. Do you want me to have a go at debugging this?

**Comment by rgrinberg** [comment]
Thanks. That would be helpful.

**Comment by rgrinberg** [comment]
Okay, I think that this line is at fault:

```
        let wrapped =
          match lib.wrapped, main_module_name with
          | This w, _ -> w
          | From _, Some _ -> Simple true
          | From _, None -> Simple false
        in
```

We should really just get the wrapped module using the `From` name. @emillon are you on this or shall I push a fix?

**Comment by emillon** [comment]
You can go ahead, I just have bisected the issue so far.

**Pull request merged**
