### PR TITLE
Fix doc generation with odoc-master branch

### PR DESCRIPTION
**Pull request by avsm**
This in turn lets us try @rizo's extremely cool PR in https://github.com/ocaml/odoc/pull/139 with a wider set of packages :-)

### CODE REVIEW

**Comment by rgrinberg** [comment]
`$ make accept-corrections` will promote the expect test results after running `$ make test`.

**Comment by diml** [comment]
@avsm please also rebase your PR and follow the instruction in the CONTRIBUTING.md file regarding the DCO :)

**Comment by avsm** [comment]
Done :-)

**Comment by rgrinberg** [comment]
Looks good to me. I'd like another look from @aantron or @trefis since I mostly just copied the existing template they had in place.

**Comment by trefis** [comment]
I'm not qualified to review that one (i.e. I don't know what requires the change from `{1 }` to `{2 }`).

**Comment by trefis** [comment]
(although the removal of the dot after `{!modules ...}` seems good indeed)

**Comment by aantron** [comment]
This looks good to me.

Btw, I suggest setting up CI against odoc master with a diverse enough set of libraries. We've fixed similar issues in Dune before, e.g. #367 "odoc: don't generate raw HTML and level 1 headings" is one instance, and Dune keeps having regressions.

In the longer term, as mentioned before, we should figure out how to move index generation into odoc, so we can maintain it there.

**Comment by rgrinberg** [comment]
@avsm @diml any idea why the DCO bot isn't satisfied. The commit message looks good to me.

**Comment by diml** [comment]
Seems like it was stuck. I clicked on `Update branch` and now it's happy. If it happens again we should look into it

**Comment by avsm** [comment]
> @aantron Btw, I suggest setting up CI against odoc master with a diverse enough set of libraries.

Agreed -- I'm working on this at the moment using Dune + a Duniverse of libraries + `jbuilder build @doc`. Will create a separate issue when it's live.

**Pull request merged**
