### PR TITLE
Add an expand-target command

### PR DESCRIPTION
**Pull request by NathanReb**
Following offline discussion I'm adding this command so that we can re-implement `ocamlc -i` from `ocaml-print-intf`.

I'm assuming this can be of use to other external scripts!

Let me know what you think!

For now it just prints aliases as well but not in a very helpful way. It should probably refuse aliases.

### CODE REVIEW

**Comment by nojb** [comment]
Sorry I did not follow the off-line discussion -- what is the use-case for this feature? How does it compare with #2925 ?

**Comment by NathanReb** [comment]
We want to use it for `ocaml-print-intf` so that you can use it easly to get the inferred interface of an OCaml module. The idea is that you'd run:
```
ocaml-print-intf foo/bar.ml
```
and it would, in essence run:
```
dune build %{cmi:foo/bar}
cmi-to-mli $(dune expand-target %{cmi:foo/bar})
```

I wasn't aware of #2925 and I'm happy to try and make this command either more generic or to somehow integrate the feature to `dune print-env`, which doesn't seem like a bad idea to be fair!

**Comment by rgrinberg** [comment]
I would prefer an approach that unifies the commands. The current print-env command is rarely used (by me) and the command introduced here will be equally unused (I can do all this directly in the editor), so a dedicated command seems like overkill.

**Comment by NathanReb** [comment]
Ok, I agree that's not the best. @rgrinberg just to clarify, would you be happy with this being part of the current `printenv` or do you have something else in mind?

**Comment by rgrinberg** [comment]
@NathanReb sorry for the late response. If it's still relevant, what I had in mind is:

- A new command `$ dune print <thing>`

- `$ dune print-env` would just be an alias for `$ dune print env`.

**Comment by jeremiedimino** [comment]
This is also getting similar to `dune describe` BTW

**Comment by jeremiedimino** [comment]
BTW, I'm thinking more about this and there is clearly a strong connection between:

- `dune print-env`
- `dune describe`
- the RPC we want to add

I feel like what we really want is a versioned RPC with a command line interface to:

- issue a single RPC query
- start a RPC through stdin/stdout

with the same `--lang` and `--format` argument as dune describe. Among other things, the RPC would offer queries for getting the environment, describing the workspace, etc... Having a single mechanism with multiple access point will make maintaining all these functionalities much easier.

So, let's work towards setting up this versioned RPC and once we have it we can evolve the various commands towards being just a thin compatibility layer on top of the general command to access the RPC from the command line.

**Pull request closed without merging**
