### PR TITLE
pkg: add cond expression to slang dsl

### PR DESCRIPTION
**Pull request by gridbugs**
Fixes https://github.com/ocaml/dune/issues/9522

### CODE REVIEW

**Comment by gridbugs** [comment]
Heads up that the tests will fail until https://github.com/ocaml/dune/pull/9531 is merged. I've tested this locally cherry-picking the fix.

**Comment by gridbugs** [comment]
More context for the motivation for this change is in the discussion here: https://github.com/ocaml/dune/issues/9451

**Comment by rgrinberg** [comment]
Why are we adding this construct to slang though? IIUC, slang is our WIP for translating opam build commands. While we need `cond` to evaluate conditionals in workspace files.

**Comment by gridbugs** [comment]
> Why are we adding this construct to slang though? IIUC, slang is our WIP for translating opam build commands.

That's just one application of slang. The intention is that slang is a general purpose string maniplation dsl for dune. Slang already has the ability to resolve conditionals and work with strings which as all we need to do to choose a lockdir by inspecting the current system.

**Comment by rgrinberg** [comment]
There's some features of slang that I wouldn't want the rest of the dune language to inherit. For example, the handling of undefined variables. In any case, I'd like to see how slang is actually integrated into the evaluation of dune files first.

**Comment by gridbugs** [comment]
Ah fair enough. What would you suggest to address https://github.com/ocaml/dune/issues/9451 then? Would it make sense to have a cond-like statement that's specific to the `lockdir` field? I guess we could add cond to the `lockdir` field first and then make it available in other parts of dune as appropriate over time?

**Comment by gridbugs** [comment]
More generally speaking, I think there's room for a general string manipulation language like slang in other parts of dune but I agree with your concerns about the handling of undefined variables. Maybe we should separate out the core of the language from parts that are only there to handle opam's idiosyncrasies and then use that core language for the `lockdir` field. That way users wouldn't need to learn yet another mini dsl.

**Comment by gridbugs** [comment]
Closing this. We can solve https://github.com/ocaml/dune/issues/9451 with a less general dsl than slang.

**Pull request closed without merging**
