### PR TITLE
Pass --warn-error to Odoc

### PR DESCRIPTION
**Pull request by Julow**
Hi !

The `--warn-error` option has been [added](https://github.com/ocaml/odoc/pull/398) to Odoc to turn warnings into errors (not yet released).
This PR add support for it in Dune.

By default the flag is not passed to Odoc, this can be changed with this in `dune-project`:
```
(odoc_warn_error true)
```

This flag is never passed in release mode.

Enabling this option and having an `Odoc` version that doesn't support it is an error. (no attempt is made to catch this)

### CODE REVIEW

**Comment by nojb** [comment]
Why not handle this as we do for `ocamlc_flags`, `ocamlopt_flags` and now also `menhir_flags` ? That is, why not add `odoc_flags` to the environment as well?

**Comment by Julow** [comment]
Not all Odoc commands take the `--warn-error` flag (this is probably a mistake) and Odoc commands have very few common options (so we would need at least `odoc_compile_flags` and `odoc_html_flags`).
Not exposing Odoc flags to the user allows Dune to change if they should be passed by default in the future.

**Comment by diml** [comment]
This feels like more like a field for `(env ...)` than for the `dune-project` file though. In particular, so that we can choose different settings based on the build profile. The default could follow the default for ocaml compilation: warnings are errors only in `dev` mode

**Comment by Julow** [comment]
I opened an other PR for using `(env ..)`: https://github.com/ocaml/dune/pull/3029
This PR can be closed.

**Pull request closed without merging**
