### PR TITLE
chore: In Makefile, use the variable BIN instead of repeating the file path

### PR DESCRIPTION
**Pull request by unfode**

### CODE REVIEW

**Comment by Alizter** [comment]
In your commit message, can you leave a space between the `signed off by` and commit message. The detection in the CI seems to be off.

**Comment by unfode** [comment]
done

**Comment by Alizter** [comment]
Ah that's not it. DCO is complaining because the email you've used to sign off differs from the one in GitHub. Have a look here:

https://github.com/ocaml/dune/commit/1c5a3debd81f1c91788601e20b22f8ee4c999b0a.patch

**Comment by unfode** [comment]
done

**Comment by Alizter** [comment]
If you click on the `Details` link next to the DCO job you will be taken to the summary page. At the very bottom it explains what it is complaining about. Now its about your username and real name conflicting. Sorry about all this annoying stuff.

**Comment by unfode** [comment]
Thank you for your patience. [CONTRIBUTING.md](https://github.com/ocaml/dune/blob/main/CONTRIBUTING.md) says that I need to use my real name to sign off. Do I need to change my username to my real name?

**Comment by rgrinberg** [comment]
The commit is signed off correctly using your real name and I have no idea why the DCO bot disagrees.

You should look into your github config somehow.

**Comment by unfode** [comment]
Thank you!

**Pull request merged**
