### PR TITLE
docs: use furo theme

### PR DESCRIPTION
**Pull request by emillon**
This theme has several advantages compared to `sphinx_rtd_theme`:

- support for light and dark mode
- a sidebar on the right with a table of contents for the current documentation
- better use of horizontal space (half of the screen is unused with `sphinx_rtd_theme`)
- "it looks better"

### CODE REVIEW

**Comment by emillon** [comment]
[Rendered version](https://dune--10786.org.readthedocs.build/en/10786/)

<summary>
Homepage
<details>

dune--10786 org readthedocs build_en_10786_ (1)

</details>
</summary>

<summary>
Light mode
<details>

dune--10786 org readthedocs build_en_10786_explanation_tour_rule-generation html

</details>
</summary>

<summary>
Dark mode
<details>

dune--10786 org readthedocs build_en_10786_explanation_tour_rule-generation html (1)

</details>
</summary>

<summary>
Right sidebar
<details>

dune--10786 org readthedocs build_en_10786_usage html

</details>
</summary>

**Comment by emillon** [comment]
If I'm being critical, there are a few things that don't quite look right:

<summary>
Captions
<details>

dune--10786 org readthedocs build_en_10786_reference_index html

</details>
</summary>

<summary>

`..describe::`

<details>

dune--10786 org readthedocs build_en_10786_reference_dune-project_package html

</details>
</summary>

But overall I think it's a net improvement.

**Comment by emillon** [comment]
And as follow-up (not in this PR), I'd like to show that it works pretty well with branding:

<summary>
Logo
<details>

127 0 0 1_8888_usage html

</details>
</summary>

**Review by christinerose — APPROVED** [review]

**Comment by emillon** [comment]
The private feedback I had can be summarized as: it's better than before, but it's too gray, too blue, the RTD embed is too black. This should all be fixable with CSS variables if need be, so we'll fix that later.
Thanks everyone

**Pull request merged**
