### PR TITLE
Simplify module field evaluator

### PR DESCRIPTION
**Pull request by bobot**
Reformulate the checks so that they are easier to check.

### CODE REVIEW

**Comment by rgrinberg** [comment]
@emillon mind reviewing this?

**Comment by emillon** [comment]
Sure! But it probably won't be before tomorrow.

**Comment by rgrinberg** [comment]
I ended up having time today after all.

Code looks very good and is one of the few cases where the operators increased the readability. I merged this with a few tweaks to the error messages and decluttering find_errors by hoisting up all the helper functions to `Properties`. Thanks Francois.

**Comment by emillon** [comment]
OK! I'm not convinced by the operators by I'm willing to try :)

**Comment by rgrinberg** [comment]
There's no drawback. I will force push and just merge via github.

**Pull request closed without merging**
