### PR TITLE
Support new locations of unix, str and dynlink

### PR DESCRIPTION
**Pull request by dra27**
Updates Dune for compatibility with the changes proposed in ocaml/ocaml#11198.

### CODE REVIEW

**Review by rgrinberg — APPROVED** [review]
Needs a CHANGES entry for 2.9.4

**Comment by dra27** [comment]
It does also need the upstream PR in OCaml to be merged first!

**Comment by dra27** [comment]
Rebased and added Changes entry to 2.9.4 (is it correct that it goes in the 2.9.4 section with PR number for main?).

The OCaml PR for this is about to be merged.

**Comment by lthls** [comment]
The flambda-backend compiler is planning to integrate ocaml/ocaml#11198 on a 4.14 branch, so we'd like some support for that in dune too. I've got a patch which more or less lowers the version bound for the code of this PR to 4.14, which should work because using the new code on a vanilla 4.14 compiler will still produce the expected result.
Should I submit this patch as a pull request ?

**Comment by dra27** [comment]
Presumably it also has to check for the files in two locations for the `exists_if` tests? Regardless, a PR with the patch seems the way to go, yes.

**Comment by lthls** [comment]
Could you point me to the `exists_if` tests in question ? I have patched the check for natdynlink support, but I haven't seen any other place where this was relevant.

**Pull request merged**
