### PR TITLE
refactor(coq): remove Value.t from coq_config

### PR DESCRIPTION
**Pull request by Alizter**
Using a polymorphic variant here makes more sense.

### CODE REVIEW

**Comment by rgrinberg** [comment]
I haven't really looked by why does it make more sense to use polymorphic variants?

**Comment by Alizter** [comment]
It makes the code easier to refactor if we want to add more "datatypes" to the values in the future.

**Comment by rgrinberg** [comment]
By that logic we can replace every variant in the code base with a polymorphic counterpart.

**Comment by Alizter** [comment]
@rgrinberg but in this case we only have the constructors that are used. Before we had constructors that were not used, and it was not immediately obvious that was the case.

**Comment by ejgallego** [comment]
I agree with Rudi, variants are hardly an improvement, and not in this case.

If you wanna check for unused constructors, just declare the type `private` and rely on the OCaml warning for unused ones.

**Pull request merged**
