### PR TITLE
Remove conflicts error

### PR DESCRIPTION
**Pull request by rgrinberg**
This error check for conflicts doesn't seem to be possible. If the
library is visited then the comparison [t = t'] will always return true

### CODE REVIEW

**Comment by rgrinberg** [comment]
@diml do you have a test case in mind that could have triggered this? Otherwise this looks like dead code to me.

**Comment by aalekseyev** [comment]
It looks like the only possible reason for `t` to be different from `t'` is to have two different `Lib.t` values with the same `id`. The problem is that `=` won't detect that anyway, so the current check is almost certainly dead code. Is that right?

**Comment by rgrinberg** [comment]
> It looks like the only possible reason for t to be different from t' is to have two different Lib.t values with the same unique_id. The problem is that = won't detect that anyway, so the current check is almost certainly dead code. Is that right?

Indeed that is the case. Perhaps it should be a code error? But I can't really think of anything that might cause it.

**Comment by rgrinberg** [comment]
@aalekseyev could you give this one an approval if you think I'm indeed removing dead code? We can revisit if we want this check later. I just need this PR to be merged to submit a subsequent one.

**Comment by diml** [comment]
Just had a look in the history. The original code made sense:

```ocaml
 match String.Map.find !visited t.name with
 | Some (t', stack') ->
   if t.unique_id = t'.unique_id then
     Ok ()
   else
     let req_by = Dep_stack.to_required_by ~stop_at:orig_stack in
     Error
       (Error (Conflict { lib1 = (t', req_by stack')
                        ; lib2 = (t , req_by stack )
                        }))
```

And i guess we just updated it mechanically when replace the `String.Map` by ` Map`, i.e. indexed by the library unique id rather than the name. I agree that the new code is dead code and this PR is correct.

**Comment by diml** [comment]
In particular, the case that was caught by the original code is now caught by the overlap check just after in the code.

**Pull request merged**
