### PR TITLE
Allow `context_name` in enabled_if of exectuable(s) and install stanzas

### LINKED ISSUE #3566: Allow `context_name` in `enable_if`
I think it would be very useful to allow `context_name` in `enable_if` rules: it will allow mirage to select which artefacts has to be  installed on which context.

```
File "tutorial/noop/dune", line 16, characters 18-31:
16 |  (enabled_if (= %{context_name} "mirage-spt"))
                       ^^^^^^^^^^^^^
Error: Only architecture, system, model, os_type, ccomp_type, profile and
ocaml_version variables are allowed in this 'enabled_if' field. If you think
that context_name should also be allowed, please file an issue about it.
```

### PR DESCRIPTION
**Pull request by voodoos**
Fixes #3566

### CODE REVIEW

**Comment by samoht** [comment]
This is blocking the mirage+dune integration so that would be nice if that could be merged/released in a not too distant future :-)

**Review by rgrinberg — APPROVED** [review]
> This is blocking the mirage+dune integration so that would be nice if that could be merged/released in a not too distant future :-)

Let's try to get some more substantial features in before we release :)

**Comment by samoht** [comment]
> Let's try to get some more substantial features in before we release :)

Any ETA?

**Comment by rgrinberg** [comment]
We discussed this a bit with Jeremie, and deemed it fine to make a release. @voodoos do you plan to work on this PR further? Otherwise, please merge.

**Pull request merged**
