### PR TITLE
[WIP] Merge findlib

### PR DESCRIPTION
**Pull request by bobot**
This MR is here to discuss the way to merge the two projects. We discussed the high level idea of merging the projects with @gerdstolpmann, but details remains.

Some advantages foreseen:
   - make `findlib` understand `dune` package format
   - make `findlib.dynload` able to load private libraries defined locally
   - make `findlib.dynload` able to register the version of the loaded libraries
   - make `dune` as well configured as `ocamlfind` is on debian/redhat ...
   - make `dune install` work as well as `ocamlfind install` in all situation 

Some questions:
 - [ ] Licence compatibility: the current licence of findlib seems to be already MIT like dune
 - [ ] DCO: Understand who (if someone) need to sign the DCO
 - [ ] Build: Who depends on who

### CODE REVIEW

**Comment by diml** [comment]
Looking forward to this merge! It's a pleasure for the Dune team to continue the maintenance of a project that had such a positive impact on the ecosystem :) Thanks @gerdstolpmann for developing it and maintaining it over the years!

Regarding the DCO, @bobot if findlib is already using the MIT license then point (b) basically allows you to sign this contribution alone.

**Comment by avsm** [comment]
Likewise, very much gratitude from me for @gerdstolpmann's tireless work over the years for such an important project!

Regarding the merge with dune, I've got a WIP tree in the duniverse staging area that makes it embeddable in a dune setup: 
- https://github.com/dune-universe/lib-findlib/commit/1c1f28464213295b545aa33eb26b9c86ab1a4d0d
- https://github.com/dune-universe/lib-findlib/commit/fc38253b9811bab97002177e3e7257d24c788bfc

It still needs some work to ensure that findlib.conf handling is respected, and META files are checked in instead of being generated as is done with the upstream release using configure, but it may help advance this PR.

**Comment by gerdstolpmann** [comment]
Found some time today to look into the dune sources, so I'm now a bit better prepared to discuss this PR. Regarding the question of @bobot how to set up the build deps, my preference would be to make dune depend on findlib, mainly because the latter is much smaller and also works independently. For functionality where dune is helpful, we can add hooks, or even functorize findlib. This strategy also allows it to distribute findlib alone as before (less work for package maintainers, and this makes people happy who don't want or cannot use dune for whatever reason).

So, if we follow this path, the question is then: what needs to change in findlib so that dune can directly link with it?

**Comment by diml** [comment]
My main concern if we do it this way is that we will need to maintain an alternative build system for findlib and that will make maintaining the dune repository more difficult. Making findlib depend on dune would make things simpler. Dune is now packages in most places and is very portable, so I feel like it's not too much of an issue to make findlib depend on Dune. What do you think?

**Comment by gerdstolpmann** [comment]
Well, the "alternative build system" is a trivial thing - findlib is small and doesn't use any of the complicated build patterns - you can probably build it with a three-line shell script.

The other point is that major functions of findlib will probably be moved to src/dune sooner or later if we do it this way, leaving only the command-line interface as a separate thing. Because otherwise you cannot get deep integration. While this may feel natural for a dune developer, for me it is a bit scary, because the packaging is then just another function of dune. In other words, findlib is sort of eaten by dune. That was not my intention - I thought more of a deeper integration while keeping major functionality separate and recognizable - and findlib lean. Dune is then a kind of privileged user of findlib.

Just talking about what I had in mind...

**Comment by diml** [comment]
I see. Just to clarify, would the findlib package contain only the ocamlfind binary or the findlib library as well?

**Comment by nojb** [comment]
Leaving the question of precise timing aside, it would be nice to discuss up front what the final state is supposed to to look like.

Personally, I think `ocamlfind` "being eaten by `dune`" would be a "good" thing, as it means there will be one less layer of of tooling/naming/etc to deal with.

In practice, on Windows (no `opam`), `dune`'s "composable vendoring" has de facto replaced `ocamlfind` for me, so the thought does not scare me that much.

**Comment by diml** [comment]
That's an excellent suggestion :) If we know were we are headed it will be easier to sort out the details to reach this point.

One way to determine the final state could be to discuss what both dune and ocamlfind provides, mark the features we think are important as "root" and then keep the freedom to refactor everything underneath to reach the optimal state, i.e. the best system that provides all these root feature.

Personally, the Dune features relevant to this discussion I consider important are:
- dune is configuration-less. One can drop a `dune` binary anywhere and it will recognise it's environment at runtime and adapt to it. Although, it is possible to embed some builtin paths into dune via an optional call to `./configure`
- as @nojb mentioned, with dune things work the same whether dependencies are installed or part of the workspace. This is true for libraries as well as tools. For instance, if one uses the base library and the cppo tool, they can either have these installed on the system or have their sources be part of the workspace dune is looking at. When they are part of the workspace, dune will build and re-build them on demand

**Comment by gerdstolpmann** [comment]
findlib has a different role than a build tool like dune (although there is clearly some overlap). Essentially it defines a standard that several tools can consume - not only the package manager (opam) and the build tool, but also also plugin loaders. It is pretty much in the center of that. The standard consists of several parts: the filesystem conventions, the `ocamlfind` interface, and the runtime loader.

For me the first and most important question is how to keep this standard alive. A standard is not only a technical function, but also needs to be accepted by the users. For these reasons I always tried to keep findlib lean and resisted to overload it with functionality. It needs to be easy to understand (no "magic") and easy to use for everybody. Also note that so far I kept some distance to build tools - that's simply because I don't believe in the single build tool for everybody. Building is too complex that one tool satisfies all requirements. That's also true for dune (which is certainly the best player now) - and don't be surprised that some day there will be a new tool coming up and take over the crown. (Hey, I've seen that several times! And don't forget the social aspect: when a new generation of engineers comes, they always do their own stuff.)

My goal of this undertaking is to improve the findlib standard, and to add all the functionality it needs to be usable by a sophisticated build tool.

What is definitely not relevant for me is to minimize the development effort.

Besides this "what is the role" question, I so far don't understand how you can support runtime loading when you make findlib dependent on dune, **and** avoid a bloated runtime loader. Looks like you would have to load the whole build tool at runtime?

**Comment by diml** [comment]
Well, we are definitely not looking for a crown :) And if someday some other tool replaces Dune, then so be it. At least Dune projects will be easy to port to whatever the next thing would be given that `dune` files are very simple and high level. In a way the standard created by Dune would helped move away from Dune if needed. Just as the ocamlfind standard helped build Dune.

For me, the most important is that we communicate with each other. I feel like too often we reinvent what others have done without taking the time to communicate with them beforehand.

At the end of the day, we are well aware that Dune doesn't satisfy all requirements, but it's nothing that can't be fixed.

**Comment by diml** [comment]
We just had a chat with @gerdstolpmann about this. In the end, we agreed on a different plan. Instead of merging the two projects, we are going to develop a standard that dune, findlib and possibly other tools in the future will respect, ensuring good interoperability. The standard will be developed in a new repository on github. We will start by describing the basics, such as how libraries should be described and then move to more complicated concept such as virtual libraries.

To make things easier, the findlib repository will move to github and the dune team will get comit rights to it. This will in particular be the occasion to add `dune` files to the findlib repository so that findlib can build with dune and be buildable inside a duniverse.

We all look forward to this cooperation!

**Pull request closed without merging**
