### PR TITLE
test: add a reproduction case for #8158

### PR DESCRIPTION
**Pull request by emillon**

### CODE REVIEW

**Review by Alizter — APPROVED** [review]
I guess you will update this when the fix is merged.

**Review by Alizter — APPROVED** [review]
I guess you will update this when the fix is merged.

**Comment by rgrinberg** [comment]
We have some existing tests for similar functionality written by @gridbugs that don't rely on ppxlib. I'd suggest to just follow along what he has.

**Comment by emillon** [comment]
@rgrinberg I just did that, let me know what you think.

**Review by rgrinberg — APPROVED** [review]

**Pull request merged**
