### PR TITLE
New stanza (dune_file_name FILE) in dune-project can change the name 'dune' to 'FILE'

### PR DESCRIPTION
**Pull request by lefessan**
This command can be useful for a project to use a different name than "dune" for build description files.
For example, in `drom`, we sometimes want to hide `dune` files to prevent users from messing with them, by calling them ".dune" files instead of "dune".

Note that this PR could remove the use for 'accept_alternative_dune_file_name' since a project may just use
`(dune_file_name dunefile)` instead.

### CODE REVIEW

**Comment by jeremiedimino** [comment]
Hi Fabrice,

when we introduced `accept_alternate_dune_file_name`, we discussed adding a general version but decided against it. One of the reason was that accepting any file name makes things harder for tools.

For drom, wouldn't it make more sense to fork Dune?

**Comment by lefessan** [comment]
What do you mean by forking dune ? Having my own version of dune ? Clearly, no, drom gives the choice between being a one-time scafolder and managing the project on the long term, forking dune would only make sense for the second use, not the first one.

In my case, I don’t really care about other tools, it would probably be a flag in drom to show or hide dune files, so the user would be able to recover them if needed.

**Comment by jeremiedimino** [comment]
> In my case, I don’t really care about other tools, it would probably be a flag in drom to show or hide dune files, so the user would be able to recover them if needed.

Fair enough, we didn't consider this use case in the original discussion. However, you'll still have a `dune-project` file visible to the user. Is that fine with drom or is this PR only half of the story?

**Comment by lefessan** [comment]
You are right that it would be nice to hide the `dune-project` file too. I can update the PR soon.

**Comment by lefessan** [comment]
Though after rethinking, it's a bit different, as I would need a configuration file to know the alternative name of the `dune-project` file. Maybe in this case, `dune` should lookup a statically hardcoded alternative file, such as `.dune-project` (and then have a precedence rule to choose the `dune-project` instead of the `dune-project` if both files are present in the same directory).

**Comment by jeremiedimino** [comment]
I'm not 100% sure about a precedence rule. It feels like we might end up in situation where the user is wondering why the system is ignoring their changes because they haven't noticed the file with higher precedence. It seems simpler to me to make having both files a hard error. Though it's not a strong opinion.

But looking for a `.dune-project` file seems like an interesting idea to better support programs that use Dune as a backend tool. I'm forwarding the idea to other dune devs to see what others think.

**Comment by jeremiedimino** [comment]
To give an updated on what's happening: we are going to discuss the idea at the developer meeting tomorrow.

**Comment by jeremiedimino** [comment]
We discussed it during the meeting and everyone is happy with the idea of making it easier to use Dune as a "backend tool". So happy to go ahead with the `.dune-project` idea. @lefessan you can go ahead and write a PR. If dune supports `.dune-project`, do you still need this PR? For instance we could say that when a project is defined by a `.dune-project` file, dune will look for `.dune` files rather than `dune` files.

**Comment by lefessan** [comment]
I am inclined to reply that this PR would not be necessary anymore (if `.dune-project` is available) as I was planning to use `.dune` for the name of the file, but at the same time, I am a bit worried that, for some reason, the name `.dune` may raise an unexpected issue (on a specific OS, or a specific project), and it will be impossible to change the name. Maybe it could be a combination of the two, i.e. `.dune-project` implies looking for `.dune` files, but there would still be the possibility to change the name using `(dune_file_name XXX)` ?

**Comment by lefessan** [comment]
Another reason would be to be more user friendly: for example, in the case of `drom`, calling the file `.drom-dune` or something like that would make the user easily understand that this file is handled by `drom` and should not be modified (or `.dune.lock`, etc.). For the `.dune-project`, `dune` could use either an env variable `DUNE_PROJECT_FILE` or a parameter `dune --project-file XXX`, so that the file could be named `.drom-dune-project` (of course, it means that the user should always call `dune` through `drom` in such a configuation).

**Comment by jeremiedimino** [comment]
We don't need to set things in stone right now. @lefessan I propose that you start with `.dune-project` and `.dune` and see how it goes. If you still need a different name for dune files we can revisit this PR. We could also allow to configure the file name only  in `.dune-project` and not in `dune-project`, so that the tooling remain simple for projects with user written dune configuration files.

> For the .dune-project, dune could use either an env variable DUNE_PROJECT_FILE or a parameter dune --project-file XXX, so that the file could be named .drom-dune-project (of course, it means that the user should always call dune through drom in such a configuation).

There is one thing we loose with this approach though: the ability to drop a drom project in a dune workspace (or vendor a drom project in a dune project).

**Comment by rgrinberg** [comment]
Let's re-open once @lefessan updates the PR.

**Pull request closed without merging**
