### PR TITLE
Do not look up dune in PATH

### LINKED ISSUE #3420: dune build @fmt should use the current executable instead of looking for it in PATH
Currently, when using `dune build @fmt` to format `dune` files, we look in the `PATH` to find a `dune` executable. There are two issues with this:

1) `dune` may not be in the `PATH`
2) if a directory in the `PATH` happens to contain any *file* named `dune`, then this file will be taken to be the `dune` executable

It seems to me a better way could be to simply use the currently executing `dune` binary instead of looking for it in the `PATH`.

### PR DESCRIPTION
**Pull request by nojb**
Fixes #3420 

(I tested briefly on Linux, but more testing is needed before merging.)

### CODE REVIEW

**Comment by emillon** [comment]
That seems right. It also means that we're going to use the dune binary while developing. Should there be special behavior when `dune` is part of the workspace?

**Comment by jberdine** [comment]
I wonder if it makes sense to call out in the docs that even though the current dune is used to format dune files, the PATH is still searched for ocamlformat (and refmt I presume)?

**Comment by jeremiedimino** [comment]
The intent of this PR seems fine to me, but we are effectively diverging from the general convention that we first look for binaries in the current workspace and then look them up in the `PATH`. That might become important if one day we change the way `dune` files are formatted. So let's discuss this before merging.

Given that the syntax and pretty printer for dune files are quite simple, we could commit to the fact that the formatting of `dune` files is a pure function of the `(lang dune x.y)` line. That means that if one day we change the way dune files are formatted, we will need to keep support for the old formatting. Then it doesn't matter if we use the binary in the `PATH`, the current binary or even if we do the formatting in-process without calling out to an external process because they will all do exactly the same thing.

Thoughts?

**Comment by nojb** [comment]
Versioning the formatting seems OK. The current PR is not urgent, so better to wait for the "right" fix. On the other hand, `dune` should check that the "dune" file it tries to execute looks like a binary file and not a text file before trying to run it.

**Comment by jeremiedimino** [comment]
Note that since we are currently not changing the formatting, we can immediately switch to doing the formatting in-process. If one day we want to change the formatting, we will have to be careful about versioning at this point.

**Comment by nojb** [comment]
Formatting in core is proposed in #3536

**Pull request closed without merging**
