### PR TITLE
Deforest dir_set + clean conditionals

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Review by aalekseyev — APPROVED** [review]
I'm not a fan of manual deforestation, but you probably already know that.
Anyway, the changes seem clearly OK technically, even though aesthetically I don't like them.

**Comment by rgrinberg** [comment]
I'm no fan either. Which is why these optimizations are mostly done in the hot path.

**Comment by aalekseyev** [comment]
Are there any benchmarks you're doing to guide these changes, by the way? I'm curious about their effect.

**Comment by rgrinberg** [comment]
Nothing rigorous, but I observe a few milliseconds shaved off clean builds in larger repos. From my profiling, quite a large chunk of rebuilds is GC (1/3+). So this still seems like it's worthwhile.

**Comment by aalekseyev** [comment]
Uh, OK.
FWIW, I expect most of these "forests" don't end up on major heap and therefore aren't contributing to gc time.

**Pull request merged**
