### PR TITLE
pkg: store solver variables in lockdir metadata

### PR DESCRIPTION
**Pull request by gridbugs**
Adds a "solver_vars" field to lockdir metadata which holds the values of variables which were evaluated while solving dependencies.

### CODE REVIEW

**Comment by gridbugs** [comment]
@rgrinberg we've discussed in the past the possibility of evaluating variables in commands and command filters at solve-time rather than build-time (at least for now). If/when we start doing that any variables that are expanded should be added to the solver_vars stored in the lockdir metadata.

**Comment by gridbugs** [comment]
fixes https://github.com/ocaml/dune/issues/8730

**Comment by gridbugs** [comment]
@rgrinberg can you take a look at this please

**Review by rgrinberg — APPROVED** [review]
Not a fan of having fields such as "string_variables". Why can't this just be "variables"? And why are we limiting this to strings?

I think what we're missing is something similar to OSL but for maps. The following is a short sketch:

1. `:standard` refers to the default set of bindings
2. `(:standard (foo bar))` adds the variable `foo` with value `bar`.
3. `(:standard \ baz)` removes the binding with the key `baz`.

Perhaps reusing the syntax of OSL is a mistake, but I think this is still conceptually cleaner than `unset_variables` and `string_variables`.

**Comment by gridbugs** [comment]
I'm happy to rename `string_variables` to `variables`. It's limited to strings because those are the only types of variables that we currently support. When we add flags we'll need a boolean type, though we may want to just stick to the current convention in dune and opam of using sentinel string values "true" and "false" to represent bools.

I don't see how using "OSL for maps" would let us remove the unset variables field. That field contains the set of variables that were read by the solver but which have no value. I suppose we could add them to the map with a special value "undefined" but adding an "undefined" value feels like a can of worms to me.

**Comment by gridbugs** [comment]
Discussed this with @rgrinberg on slack. We'll change the syntax of how variables are encoded in the lockdir to:
```
 (os linux)
 (os-distribution :unset)
 (with-test true)
```
...rather than having a separate field for unset variables.

I'll make that change in a future PR since another feature I'm working on depends on encoding the solver variables in the lockdir.

**Pull request merged**
