### PR TITLE
Introduce String.{take,drop,split_n}

### PR DESCRIPTION
**Pull request by rgrinberg**
This simplifies quite a lot of code

Signed-off-by: Rudi Grinberg <rudi.grinberg@gmail.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
I've added an unrelated commit that simplifies some code with Option.{map,bind}. All completely mechanical.

**Comment by rgrinberg** [comment]
I've looked over the PR again and there's really nothing controversial here. I will go ahead and merge. Feel free to suggest changes to the newly added functions, I have no strong preferences to any names/conventions.

**Comment by rgrinberg** [comment]
CI gives a false alert:

```
Network availability confirmed.
Fix WWDRCA Certificate
Unable to delete certificate matching "0950B6CD3D2F37EA246A1AAA20DFAADBD6FE1F75"
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by emillon** [comment]
:+1: thanks for this!

**Pull request merged**
