### PR TITLE
usage: Rename Opam field "build-test"

### PR DESCRIPTION
**Pull request by kevinji**
Opam's docs suggest that the `build-test` field is deprecated: https://opam.ocaml.org/doc/Manual.html#opamfield-build-test

### CODE REVIEW

**Comment by rgrinberg** [comment]
Note that this also requires this line to be present under `build:`
```
  ["dune" "runtest" "-p" name "-j" jobs] {with-test}
```

I suggest we mention it as well.

**Comment by kevinji** [comment]
What's the difference between including the above line under `build` and the original line under `build-test`? The docs don't make the distinction super clear.

**Comment by rgrinberg** [comment]
As far as I understand, one command is to build the tests and the other one is to run them. That doesn't really make sense with how dune does things however. As our runtest command will only run the tests once. Let's ask @avsm for what should be the recommendation here.

**Comment by avsm** [comment]
Hm, we should be using `run-test` really. That'll also cause the dependencies to be built anyway. Perhaps we need to change this more broadly in opam-repository as well. I wonder if there's a way to just do `build-test` in opam2 without doing the `run-test` right now, @AltGr @rjbou?

**Comment by rgrinberg** [comment]
@avsm assigning this to you.

**Comment by samoht** [comment]
I thought the pattern was simply to use:

```
build: [
 ["dune" "subst"] {pinned}
 ["dune" "build" "-p" name "-j" jobs]
 ["dune" "runtest" "-p" name] {with-test}
]
```

**Comment by Chris00** [comment]
Shouldn't `["dune" "build" "-p" name "-j" jobs "@doc"] {with-doc}` be mentioned as well?

**Comment by rjbou** [comment]
@avsm I don't completely understand your question. Internally, opam format upgrade add `build-test` actions to the `build` field with an `with-test` filter, and same for the deprecated `build-doc`. But if `build-test` is present in a opam2 file, these instructions are added on the `run-test` field.

**Comment by avsm** [comment]
@rjbou the question is: should we be recommending that dune users use the `run-test` opam field instead of executing tests from within the `build` field (guarded by `with-test`)?

The two options are:

```
build: [
 ["dune" "subst"] {pinned}
 ["dune" "build" "-p" name "-j" jobs]
 ["dune" "build" "-p" name "-j" jobs "@doc"] {with-doc}
 ["dune" "runtest" "-p" name] {with-test}
]
```

_vs_

```
build: [
 ["dune" "subst"] {pinned}
 ["dune" "build" "-p" name "-j" jobs]
 ["dune" "build" "-p" name "-j" jobs "@doc"] {with-doc}
]
run-test: [
 ["dune" "runtest" "-p" name]
]
```

Does opam2 do anything special with `run-test` fields _vs_ `build` fields?

**Comment by rjbou** [comment]
There is no treatment difference between having it on the `run-test`field or in the `build` field. The main point on having tests in the `build` is if precedence on commands is important.
opam order those fields [as follow](https://github.com/OCamlPro/opam/blob/master/src/client/opamAction.ml#L662):
1. `build` commands (including test or doc is option present
2. `run-test` commands (if test)
3. deprecated `with-doc` commands (if doc)

**Comment by samoht** [comment]
If there is not difference, I reckon we should deprecate the `run-test` field and use only the `build` command. Having different ways of doing the same is not ideal for an UX point of view.

**Comment by kevinji** [comment]
I've updated the PR to use the `build` command instead.

**Pull request merged**
