### PR TITLE
compiler-libs.native-toplevel fix

### LINKED ISSUE #4248: Crash when ocamlfind not installed because of duplicate compiler-libs.toplevel META
```
Internal error, please report upstream including the contents of _build/log.
Description:
  ("Map.add_exn: key already exists", { key = "compiler-libs.toplevel" })
Raised at file "src/stdune/code_error.ml", line 9, characters 30-62
Called from file "map.ml", line 281, characters 18-28
Called from file "map.ml", line 289, characters 21-33
Called from file "map.ml", line 289, characters 21-33
Called from file "src/dune_rules/findlib/findlib.ml", line 461, characters
  8-70
Called from file "list.ml", line 121, characters 24-34
Called from file "src/dune_rules/findlib/findlib.ml", line 474, characters
  6-79
Called from file "src/dune_rules/findlib/findlib.ml", line 538, characters
  28-50
Called from file "src/dune_rules/findlib/findlib.ml", line 570, characters
  14-43
Called from file "src/dune_rules/findlib/findlib.ml", line 576, characters
  11-59
...
```

Maybe related to #4175?

### PR DESCRIPTION
**Pull request by nojb**
Fixes #4248

Since `Native-toplevel` is not a valid module name, I had to change `Module.of_string` to `Module.of_string_allow_invalid`, but perhaps there is a better way?

### CODE REVIEW

**Comment by jeremiedimino** [comment]
This value seems to be generated in `meta.ml` (in the `main_modules` function). Maybe we could generate a different value there?

BTW, I'm confused as to what this code in `meta.ml` does. For the builtin meta, we are supposed to generate the same thing as the  `META` files distributed by findlib. @rgrinberg do you know what's going on there?

**Comment by rgrinberg** [comment]
> BTW, I'm confused as to what this code in meta.ml does. For the builtin meta, we are supposed to generate the same thing as the META files distributed by findlib. @rgrinberg do you know what's going on there?

It's to support `root_module` for libraries that aren't define with dune. We "guess" the list of toplevel modules from the list of cmi's for such libraries. This is useful for libraries such as `Unix` for example.

> Since Native-toplevel is not a valid module name, I had to change Module.of_string to Module.of_string_allow_invalid, but perhaps there is a better way?

I suppose we could just hard code it to the empty list for some libs.

**Comment by jeremiedimino** [comment]
What I'm thinking is the following: when findlib is installed, we don't use our builtin META files. Instead we use the ones installed by findlib and these don't have a `main_modules` field. What happens in this case?

**Comment by jeremiedimino** [comment]
We hit this issue while testing at Jane Street as well. I added a `String.map ~f:(function '-' -> '_' | c -> c_)` where we generated the offending `main_modules` field instead of allowing invalid module names.

I'm still curious as to why our builtin meta files are not the same as the one embed in findlib. This feels like a recipe for troubles.

**Comment by nojb** [comment]
> We hit this issue while testing at Jane Street as well. I added a `String.map ~f:(function '-' -> '_' | c -> c_)` where we generated the offending `main_modules` field instead of allowing invalid module names.

Thanks!

**Pull request merged**
