### PR TITLE
fix byte_for_jsoo, fix #5282

### LINKED ISSUE #5282: 3.0 regression: I/O error: *stubs.so: no such file or directory
Hi!

I just tested the latest version of dune (6a0314ce37c02b42f3147e4592fba1ce2d5c49a5) on [js-monorepo](https://github.com/emillon/js-monorepo).

I'm seeing build errors that happen on this dev version but not on 2.9.1.

More precisely here's the output of a second `dune build` (the first one contains extra warnings that are not relevant):

```
$ dune build
File "_none_", line 1:
Error: I/O error: dllnum_stubs.so: No such file or directory
File "_none_", line 1:
Error: I/O error: dllpcre_stubs.so: No such file or directory
File "_none_", line 1:
Error: I/O error: dllreplace_caml_modify_for_testing_stubs.so: No such file or directory
File "_none_", line 1:
Error: I/O error: dllzarith_c_stubs.so: No such file or directory
File "_none_", line 1:
Error: I/O error: dlllwt_unix_stubs.so: No such file or directory
```

## Reproduction

```
git clone https://github.com/emillon/js-monorepo
cd js-monorepo
opam monorepo pull
dune build
```

With 2.9.1 this succeeds, but with the dev version it fails.

### PR DESCRIPTION
**Pull request by hhugo**

### CODE REVIEW

**Comment by hhugo** [comment]
@emillon, can you check this fixes your issue.

**Comment by hhugo** [comment]
cc @nojb

**Comment by nojb** [comment]
@hhugo thanks for the ping, I will try to try this out today or tomorrow.

**Comment by emillon** [comment]
> @emillon, can you check this fixes your issue.

Yes, that works! thanks!

**Comment by hhugo** [comment]
Does anyone know the expected use-case for
`(context (default (disable_dynamically_linked_foreign_archives true)))` ? Is it expected that libraries compiled with this mode still mention a dynamic library in the cma archive ?

**Comment by nojb** [comment]
> Does anyone know the expected use-case for `(context (default (disable_dynamically_linked_foreign_archives true)))` ?

No idea. For sure @jeremiedimino knows, but he is on holidays until 2022.

> > @emillon, can you check this fixes your issue.
> 
> Yes, that works! thanks!

Following this confirmation, is there anything left to check for this PR @hhugo?

**Comment by hhugo** [comment]
I think this PR should be merged because it fixes a regression.
But the test also shows that js compilation is broken when disable_dynamically_linked_foreign_archives=true (which #5049 was trying to fix/implement). I'd be nice to know whether js compilation is broken on platform without dynamic library support.

**Comment by jeremiedimino** [comment]
> Does anyone know the expected use-case for
(context (default (disable_dynamically_linked_foreign_archives true))) ? Is it expected that libraries compiled with this mode still mention a dynamic library in the cma archive ?

The original PR to add this flag doesn't state a reason (#2864), however the timing seems to correspond with the time we were trying to use the upstream Dune rules to build Jane Street codebase. So it's well possible we added this simply because we needed it to build Jane Street code base.

**Comment by hhugo** [comment]
I've rebased the branch and signed the commit, it should be ready to be merged.

**Pull request merged**
