### PR TITLE
When the target is a directory use the default alias in it

### PR DESCRIPTION
**Pull request by rgrinberg**
As we've discussed in the default alias proposal.

### CODE REVIEW

**Comment by rgrinberg** [comment]
This is still not fully working. I'll add some tests and fix the bugs.

**Comment by rgrinberg** [comment]
This is ready for review. Just need to update the manual and change log.

**Review by ghost — APPROVED** [review]

**Comment by rgrinberg** [comment]
ping @emillon

**Review by emillon — APPROVED** [review]

**Comment by rgrinberg** [comment]
cc @andreypopp. You will be able to do `$ dune build dir` now.

**Comment by diml** [comment]
BTW, we also discussed the idea of changing the default to be: build everything. It seems a bit hard to change the meaning of `dune build` in one step, however it seems fine to do it for this new feature. i.e. `dune build .` would effectively build everything in the directory. In fact, `dune build <dir>` could mean building `(glob_files <dir>/*)`.

**Comment by nojb** [comment]
Sorry for the basic question, but what is "the default alias" ?

**Comment by diml** [comment]
It's a special alias, it's what dune builds when you do `dune build`: https://dune.readthedocs.io/en/latest/usage.html#default-alias

**Pull request merged**
