### PR TITLE
Doc: fix default location of cache on Windows

### PR DESCRIPTION
**Pull request by nojb**
Small Doc fix.

### CODE REVIEW

**Comment by Alizter** [comment]
Why is it there?

**Comment by Alizter** [comment]
I see, so it is for Windows users to easily manager their cache when it grows too large? In that case, shouldn't they be using `dune cache trim` rather than Windows nuking it?

**Review by Alizter — APPROVED** [review]
My questions are not really related to this PR. Looks good.

**Comment by nojb** [comment]
> I see, so it is for Windows users to easily manager their cache when it grows too large?

I wouldn't say there was a clear reason for this specific choice; the way I see it, in the absence of an specific reason, we chose to follow the choice done by GLib on Windows for `XDG_CACHE_HOME` as mentioned in https://github.com/ocaml/dune/issues/5808#issuecomment-1171561776. But if this location has downsides we can always revisit this choice.

In any case, the location was not chosen to simplify the manual management of the cache; as you mention one should use `dune cache trim` for that purpose.

**Pull request merged**
