### PR TITLE
[RPC] report build events to clients

### PR DESCRIPTION
**Pull request by rgrinberg**
These events are currently received when the client subscribes to build
progress.

### CODE REVIEW

**Review by cwong-ocaml — COMMENTED** [review]
Is this an API + client change only? I remember there were some issues with this from `build_system.ml`, such as `Fail` not being sent properly on error.

**Comment by rgrinberg** [comment]
There's also a change in the server to actually send the notifications.

**Comment by rgrinberg** [comment]
> such as Fail not being sent properly on error.

I forgot to reply to this bit. Yeah, `Interrupted` and `Fail` aren't yet detected properly. I'll work on that in a separate PR.

**Comment by rgrinberg** [comment]
Ping @cwong-ocaml

**Pull request merged**
