### PR TITLE
refactor: Dep.Fact.Files.group can be private

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by snowleopard** [comment]
I disagree that this function should be private. In fact, we should encourage using it from the rules, to share collections of dependencies. (This is quite important for our internal rules.)

**Comment by snowleopard** [comment]
One might argue that the current API is a little weird and that the second argument should be optional, which would be fine. The main feature of this function is combining lists of facts in a way that's shareable and is somewhat resilient to code changes.

**Comment by rgrinberg** [comment]
No objection against the function being public, it's just hard to tell from the current API the intention of this stuff.

**Comment by snowleopard** [comment]
Yeah, the comment isn't great. Instead of re-stating the type, it should state that this function is useful for sharing collections of dependencies in an efficient way.

**Pull request closed without merging**
