### PR TITLE
Allow $PKG_CONFIG_PATH to have effect on macOS

### PR DESCRIPTION
**Pull request by andreypopp**
Previously brew's `$PKG_CONFIG_PATH` took precedence over `$PKG_CONFIG_PATH`, this commit changes so that already set `$PKG_CONFIG_PATH` have effect over brew's path.

We are seeing that with esy dune prefers globally installed libraries on macOS b/c of how dune overrides `$PKG_CONFIG_PATH`. This fixes that.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Indeed the current behavior is bad, but I'm not sure if this PR fixes it. How would dune automatically use homebrew's sqlite for example? Perhaps that behavior is a bit too magical however. I think we'd be open to suggestions here.

**Comment by andreypopp** [comment]
> ndeed the current behavior is bad, but I'm not sure if this PR fixes it. How would dune automatically use homebrew's sqlite for example? 

The path for homebrew is still added, just that the previously set `$PKG_CONFIG_PATH` has precedence over it.

**Comment by diml** [comment]
IIRC, I was the one who wrote it in this order originally as otherwise I couldn't get async_ssl to build on OSX. TBH, I still don't understand why we have to call `brew` manually and why `brew` just doesn't set this variable itself.

**Comment by andreypopp** [comment]
I just tried to build aantron's luv with libuv installed by homebrew and this patch applied and it worked (dune's log list homebrew location in `-I` flags). 

I'm not sure why you weren't able to build async_ssl back then — my understanding is that even with this patch `pkg-config` should be able to find homebrew installed libs.

**Comment by diml** [comment]
@andreypopp what happens if you remove the whole `let env =  match ocaml_config_var c "system" with | Some "macosx" -> begin ... in` block?

Basically, I don't understand why we need this block at all. Surely it should be homebrew 's job to setup the environment. I makes no sense to me that dune has to be aware of homebrew.

**Comment by andreypopp** [comment]
@diml just tried it and it was able to find `libuv` installed with homebrew!

**Comment by andreypopp** [comment]
FWIW `pkg-config libuv` also works in terminal so indeed it seems setting `PKG_CONFIG_PATH` shouldn't be needed.

Should I remove it?

**Comment by rgrinberg** [comment]
I think the issue is that homebrew will refuse to make openssl available by default via pkg-config since OSX already has a systemwide SSL. I can confirm this on my laptop when listing all packages and not seeing `$ pkg-config --list-all`. Other brew packages are indeed listed here.

**Comment by rgrinberg** [comment]
So indeed I suppose this hack should go into the various ssl packages.

**Comment by diml** [comment]
Agreed. What about keeping the code in configurator but making it an explicit opt-in? For instance we could add a `?force_homebrew_on_osx:bool` flag to `Pkg_config.query`.

**Comment by rgrinberg** [comment]
That would work but it's probably still too forceful in general. We don't want to force homebrew versions on users even when they have it installed. I don't have any better suggestions however, so I'd accept such a change.

**Comment by diml** [comment]
That's what I would do as well, but I remember that it wasn't very easy for users. /cc @avsm, I remember that we discussed this in the past.

**Comment by andreypopp** [comment]
Let me know what's the best course of action then! I think the fix in this PR is relatively safe.

Another possible solution is to make `conf-openssl` package query `brew` for installed openssl package and set `$PKG_CONFIG_PATH` instead of dune doing that.

**Comment by rgrinberg** [comment]
I think we can just merge this PR and apply the appropriate fix to conf-ssl. Unless anyone objects, I will merge this PR once you add a CHANGES entry

**Comment by andreypopp** [comment]
> I think we can just merge this PR and apply the appropriate fix to conf-ssl. Unless anyone objects, I will merge this PR once you add a CHANGES entry

Done. I still don't think `conf-ssl` should be updated as brew's path will still end in `$PKG_CONFIG_PATH` just appended and not preprended.

**Comment by diml** [comment]
Now that I understand things a bit better, I realise that this PR in its current form is likely to break the build of async_ssl on OSX. Do you agree?

If async_ssl is the only affected package, then what we can do is release a new version of async_ssl with the `brew` hack directly in async_ssl, then just drop the call to `brew` altogether in dune and add a version constraint on dune in async_ssl.

Allowing the user to control which version is selected would be nice, however it seems to me that this is an improvement over the current situation, so there is no urgency on this side.

BTW, I don't know what conf-ssl does or where it is used, so I don't know how it is affected by all this.

**Comment by andreypopp** [comment]
> Now that I understand things a bit better, I realise that this PR in its current form is likely to break the build of async_ssl on OSX. Do you agree?

I disagree, this PR shouldn't break async_ssl (or any other sensible
build configuration), why do you think it should break it?

So I've tried to build async_ssl (master) with this PR and it's failed for me.
But it also failed for me without this PR with dune released on opam. The error
message is the same in both configurations:

```
openssl_helpers.c:2:10: fatal error: 'openssl/x509v3.h' file not found
#include <openssl/x509v3.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
```

And apparently the `bindings/dune` isn't passing ccopt flags discovered by
configurator. If I fix it with this patch:

```
diff --git a/bindings/dune b/bindings/dune
index 93126a3..50e42a7 100644
--- a/bindings/dune
+++ b/bindings/dune
@@ -12,8 +12,8 @@

 (library (name async_ssl_bindings) (public_name async_ssl.bindings)
  (c_names openssl_helpers)
- (c_flags (:standard \ -Werror -pedantic -Wall -Wunused))
+ (c_flags (:standard (:include openssl-ccopt) \ -Werror -pedantic -Wall -Wunused))
  (c_library_flags :standard (:include openssl-cclib.sexp))
  (libraries ctypes.stubs ctypes ctypes.foreign.threaded)
  (virtual_deps conf-openssl) (preprocessor_deps config.h)
```

Then it works well and builds both with stock dune and with dune patched with
this PR.

I also inspected `openssl-{cclib,ccopt}.sexp` and they have strings pointing to
brew installed version of openssl.

> Allowing the user to control which version is selected would be nice, however it seems to me that this is an improvement over the current situation, so there is no urgency on this side.

I disagree as this makes esy builds non deterministic - users might have
incorrect versions of software installed via brew and it might fail as esy
packages might expect newer versions. Moreover there's no workaround but to use
the patched dune version.

**Comment by diml** [comment]
Thanks for testing with master, it seems that this problem was introduced since the last release in opam. /cc @xclerc we need to add the `(:include openssl-ccopt)` before the next release.

> Then it works well and builds both with stock dune and with dune patched with this PR.
>
> I also inspected openssl-{cclib,ccopt}.sexp and they have strings pointing to brew installed version of openssl.

I'm not really sure what's going on. Could you try removing the call to `brew` entirely and see if you get the same behaviour? If yes, then it's likely we just don't need it anymore.

> I disagree as this makes esy builds non deterministic - users might have
incorrect versions of software installed via brew and it might fail as esy
packages might expect newer versions. Moreover there's no workaround but to use
the patched dune version.

I'm not sure we were talking about the same thing. @avsm was basically suggesting an option such as `dune configure --use-brew-ssl` or `dune configure --use-system-wide-ssl` to force the use of one or the other version. I don't believe this introduce non determinism.

**Comment by andreypopp** [comment]
>> Then it works well and builds both with stock dune and with dune patched with this PR.
>> 
>> I also inspected openssl-{cclib,ccopt}.sexp and they have strings pointing to brew installed version of openssl.

> I'm not really sure what's going on. Could you try removing the call to brew entirely and see if you get the same behaviour? If yes, then it's likely we just don't need it anymore.

The reason it still finds the brew's openssl is that this PR only changes the order of `$PKG_CONFIG_PATH` — it appends rather than prepends brew's path.

I've tried to remove brew's paths completely and it fails now:
```
discover.c:2:10: fatal error: 'openssl/ssl.h' file not found
#include <openssl/ssl.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

and `openssl-{cclib,ccopt}.sexp` contain empty lists `()` as expected.

**Comment by andreypopp** [comment]
> I'm not sure we were talking about the same thing. @avsm was basically suggesting an option such as dune configure --use-brew-ssl or dune configure --use-system-wide-ssl to force the use of one or the other version. I don't believe this introduce non determinism.

Sorry, I was indeed confused. I thought you are referring to the entire PR.

**Comment by diml** [comment]
I see. I thought `PKG_CONFIG_PATH` would be set to point to the system directories by default, and so changing the order would have an effect on which version of openssl is selected.

I have no objection on the current PR then.

**Comment by andreypopp** [comment]
> I see. I thought PKG_CONFIG_PATH would be set to point to the system directories by default, and so changing the order would have an effect on which version of openssl is selected.

By default you usually don't have `$PKG_CONFIG_PATH` set I believe. But if you have — then this PR will change the behaviour of dune — but in a sensible way I think — global brew's installations will still be available but as a fallabck after custom set `$PKG_CONFIG_PATH` is inspected by `pkg-config`.

**Comment by diml** [comment]
That makes sense to me

**Comment by vsiles** [comment]
For the record, I'm trying to use Configurator.V1.Pkg_config on a linux and a mac, and in both cases my PKG_CONFIG_PATH variable is totally ignored.

**Comment by vsiles** [comment]
> @vsiles it depends on if you are using opam or esy. Ping me on discord and I can help with either.

I'm very new to discord, how do I find you ?

**Comment by andreypopp** [comment]
@vsiles my nick is `andreypopp` there, I'm also on IRC freenode under the same nickname.

**Comment by andreypopp** [comment]
Friendly ping here.

**Comment by rgrinberg** [comment]
I merged manually

**Pull request closed without merging**
