### PR TITLE
refactor: use Pp.enumerate more

### PR DESCRIPTION
**Pull request by Alizter**
We use Pp.enumerate more and clean up some code.

(Previously we introduced Pp.enumerate_str but then decided against).

### CODE REVIEW

**Comment by rgrinberg** [comment]
I don't think function is useful enough.

**Comment by Alizter** [comment]
@rgrinberg Do you agree that we should use Pp.enumerate at least?

**Comment by rgrinberg** [comment]
Why not. If you think it helps with readability.

**Comment by Alizter** [comment]
Actually nevermind it was more readable before.

**Pull request closed without merging**
