### PR TITLE
Inline tests (on top of the sybsystems PR)

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by diml** [comment]
I wrote the doc: https://github.com/ocaml/dune/blob/inline-tests-subsystem/doc/tests.rst

I renamed the `gen` field to `generate_runner` to make things more explicit. One thing I'm not entirely sure is `backend`, i.e. to write an inline test backend you write:

```scheme
(library
 ((name ppx_inline_test)
  ...
  (inline_tests.backend (...))))
```

and to use a specific backend (when jbuilder can't detect it):

```scheme
(library
 ((name foo)
  (inline_tests ((backend qtest))))
```
Is it clear what it means?

**Comment by c-cube** [comment]
There's a typo in `(name simlpe_tests)`, but it looks good :+1: 
I'll try and write the qtest backend soon (assuming this change works on dune's dev branch).

**Comment by diml** [comment]
Thanks, I fixed the typo

**Comment by rgrinberg** [comment]
Looks good @diml this was much simpler to review. Thanks for keeping the history in good shape.

Should we disable the ppx_inline_test/ppx_expect tests for now? Until versions with backends are released. Why don't we have a simple test with a custom test backend for ppx_inline_test for now instead?

**Comment by diml** [comment]
> Should we disable the ppx_inline_test/ppx_expect tests for now? Until versions with backends are released. Why don't we have a simple test with a custom test backend for ppx_inline_test for now instead?

Sounds good

**Comment by diml** [comment]
Actually I just rewrote the tests to use local backends, this way the tests are more self contained.

**Comment by c-cube** [comment]
Still not sure how to use it (I tried adding a pseudo library in qtest, with jbuilder pinned to dev, and it doesn't seem  to work).

Would it make sense to be able to attach `inline_tests.backend (…)` to the generator instead of the library?

**Comment by diml** [comment]
Can you show what you tried?

**Comment by c-cube** [comment]
Was trying to use qtest at https://github.com/c-cube/ocaml-containers/blob/wip-qtest-backend/src/core/jbuild
and to define the backend at https://github.com/vincent-hugot/qtest/blob/wip-jbuilder/src/jbuild
(I tried several things but did not record everything).

**Comment by diml** [comment]
Ok, are you getting an error or is `jbuilder runtest` just doing nothing?

**Comment by diml** [comment]
Ah, BTW, the `flags` field of `inline_tests` is for flags passed to the runner, not the runner generator. Maybe that's the issue?

**Pull request merged**
