### PR TITLE
Improve stack info for variants

### PR DESCRIPTION
**Pull request by rgrinberg**
Implementations introduced by variants or defaults should include their
source. This PR includes the source as part of the stack information.

### CODE REVIEW

**Comment by rgrinberg** [comment]
The fact that the user might get libraries in the stack trace that he hasn't written always bothered me. I've tried to include this information in the dependency stack. I'm not sure if this is the right approach, but it seems simple enough.

**Comment by diml** [comment]
Could you add a test before this PR showing a stack trace that is changed by this PR?

**Comment by diml** [comment]
> The fact that the user might get libraries in the stack trace that he hasn't written always bothered me.

Yh, what's important is that for every library reported in an error message, we can attach it to something written by the user via a dependency stack. This way, the user can always understand what source fragment is causing dune to complain about something.

**Comment by rgrinberg** [comment]
> Could you add a test before this PR showing a stack trace that is changed by this PR? That would help grasp what the PR is changing.

I added such a test for the variant case. Can also add one for the default implementation case.

**Comment by diml** [comment]
Thanks, with the test it became much more concrete to me what this PR was doing :)

**Pull request merged**
