### PR TITLE
Fix libexec variable behavior

### LINKED ISSUE #4057: The `libexec` variable doesn't expand to the host-context library in case of cross-compilation
## Expected Behavior

As documented, the `libexec` variable should expand to the file from the host build context in case of cross-compilation.  

## Actual Behavior

Using `libexec` in a cross-compilation setup fails to find the requested library even if it's available in the host context.

## Reproduction

With dune master branch, `dune build lib/host-config` fails on this example:
https://github.com/TheLortex/dune-libexec-bug

By the way this bug is acknowledged in the source code, `dune_rules/expander.ml`:
```
(* TODO: The [exec = true] case is currently not handled correctly and
         does not match the documentation. *)
```

### PR DESCRIPTION
**Pull request by TheLortex**
Should fix https://github.com/ocaml/dune/issues/4057

For the tests I took inspiration from `lib.t` blackbox tests, but they are not ready yet. I wanted some comments first on if the fix shall be as simple as that or if there are some subtle changes to make ?

### CODE REVIEW

**Comment by rgrinberg** [comment]
The fix looks good to me.

**Comment by TheLortex** [comment]
Thank you @rgrinberg, I found some issues in the fix while setting up the tests but now it is good for review !

**Comment by rgrinberg** [comment]
Looks good once you update the CHANGES

**Comment by TheLortex** [comment]
Great, `CHANGES` updated and now it's ready.

**Pull request merged**
