### PR TITLE
Add a reproduction case for issue #4429

### PR DESCRIPTION
**Pull request by CraigFe**

### CODE REVIEW

**Comment by jeremiedimino** [comment]
Thanks for the repro case. Could you use `dune-build-info` instead of the cache to reproduce this bug? @snowleopard is doing some restructuring of the code for the shared cache and the cache will stop calling git. So this repro case will soon stop working.

**Comment by snowleopard** [comment]
> Thanks for the repro case. Could you use `dune-build-info` instead of the cache to reproduce this bug? @snowleopard is doing some restructuring of the code for the shared cache and the cache will stop calling git. So this repro case will soon stop working.

Thanks, indeed. 

@CraigFe After some upcoming changes, Dune cache will no longer require VCS information. The only reason it currently needs it is to support bulk download of build artifacts corresponding to a given commit but we found that in practice downloading artifacts for individual rules is simpler and fast enough.

**Comment by CraigFe** [comment]
Thanks both. I've altered the reproduction as you suggest.

**Comment by jeremiedimino** [comment]
It's because we don't include the actual info when building executables in the _build directory. This is so that `dune-build-info` doesn't hurt incrementality, otherwise we'd end up rebuilding a bunch of stuff everytime we do a commit. There are two ways of getting the actual info:

- with `dune install`
- by adding `(promote (until-clean))` to the `executable` stanza to make dune promote the exe

**Comment by CraigFe** [comment]
Thanks for the explanation :-) Now using `dune-build-info` properly.

**Review by jeremiedimino — APPROVED** [review]
Looks good.

**Pull request merged**
