### PR TITLE
[rpc] Use dune's latest version in versioning rpc

### PR DESCRIPTION
**Pull request by rgrinberg**
@jeremiedimino I tried moving this to a shared file and using a copy rule like
we discussed, but then we need to complicate bootstrap. It doesn't seem worth it
to go through all that when we can just write it in the rpc.

### CODE REVIEW

**Comment by jeremiedimino** [comment]
It still feels a little odd to me to go in the RPC code to change the latest version of the Dune language. Why not use a library? This is the natural way of sharing code.

**Comment by rgrinberg** [comment]
> Why not use a library? This is the natural way of sharing code.

Such a library would have to be public and hence live in a package. There's no good package to put this library in unfortunately.

**Comment by jeremiedimino** [comment]
Alright, well we don't need to spend to much time on this, but we do need a comment in `stanza.ml` explaining why the version number lives in the RPC library. Otherwise, it's a bit weird when you read the code. Once you add this comment that seems fine to merge.

**Comment by rgrinberg** [comment]
> Alright, well we don't need to spend to much time on this, but we do need a comment in stanza.ml explaining why the version number lives in the RPC library. Otherwise, it's a bit weird when you read the code. Once you add this comment that seems fine to merge.

Yes, I think we should just proceed with this PR and improve things later. Tbh, I tried altering the bootstrap procedure but I couldn't find a satisfactory way of doing it. If you can think of a way, a PR would be most welcome.

**Comment by jeremiedimino** [comment]
Let's keep the bar high for complicating the bootstrap. This doesn't feel like it passes the bar.

**Pull request merged**
