### PR TITLE
Change alias interface to take Dep.t values rather than paths

### PR DESCRIPTION
**Pull request by rgrinberg**
This refactoring seemed straighforward but the alias stamp files aren't being created for some reason. I will have to take another look (unless someone beats me to it).

### CODE REVIEW

**Comment by rgrinberg** [comment]
Ah this is annoying because now we need a `Digest_files` action. This is too much work to refactor so I think I should just move to the new aliases in this PR.

**Comment by diml** [comment]
What is the status of this PR?

**Comment by rgrinberg** [comment]
The stats is as follows:

* To make this PR work, we need to add an action like `Digest_files` that will work for `Dep.Set.t`. This is a non trivial amount of work.

* Or, we can implement the new alias system that would hopefully eliminate the need for that. But I'm not sure how that would work.

**Comment by rgrinberg** [comment]
Long since implemented.

**Pull request closed without merging**
