### PR TITLE
Add a test showing that inotify reports events in chronoligical order

### PR DESCRIPTION
**Pull request by jeremiedimino**
Which is an assumption we are making for the inotify sync mechanism.

### CODE REVIEW

**Review by snowleopard — APPROVED** [review]
Nice! It's of course good to have this test but there is one limitation: all file changes are coming from the same process. During the build, both Dune and other processes that it starts are changing the file system, so there will be some non-determinism when changes actually happen in parallel. Presumably, what we really care about is that synchronisation points are respected, e.g., if Dune waits for a process to finish and then makes a file change, then we will first see all events from that process, and only afterwards the file change that Dune made after the process finished. (Whether this really holds or not remains untested.)

**Comment by snowleopard** [comment]
P.S.: Ah, there seem to be some non-determinism about `Move` events: the CI is unhappy.

**Comment by jeremiedimino** [comment]
Agreed, it'd be good to have tests for this.

I'll remove the rename from the test. Renames are always a bit tedious with file watchers.

**Comment by jeremiedimino** [comment]
We could also loosen the matching instead of not doing renames, but I'll leave that for later.

**Pull request merged**
