### PR TITLE
Add tests for include qualified features

### PR DESCRIPTION
**Pull request by rgrinberg**
* basic usage
* lib interface modules
* pp specification
* virtual modules

None of this works, but I'll appreciate some review of the dune files written, so we have agreement on the spec for this feature.

### CODE REVIEW

**Comment by rgrinberg** [comment]
The main point that I'd like to clarify is the syntax for specifying nested modules in the various modules fields. For example, when saying that a nested module should be virtual, should we do:

```
(virtual_modules foo.bar)
```

Or:

```
(virtual_modules foo/bar)
```

Does anyone have an argument for either one?

**Comment by emillon** [comment]
I don't have an opinion on syntax, but if that makes it easier we could start by disallowing the combination of qualified and virtual modules.

**Comment by rgrinberg** [comment]
Ah but it doesn't really help. For example the same problem arises with private modules and specifying preprocessors per module.

**Comment by diml** [comment]
I have slight preference for `.`. On the other hand, will we allow sub-trees to have a custom API? I believe this is a common thing to do. In that case, `foo.bar` might not exist at all even if `foo/bar.ml` exist, so that could be slightly confusing.

**Comment by rgrinberg** [comment]
> On the other hand, will we allow sub-trees to have a custom API? I believe this is a common thing to do

Oh indeed. Yeah, I suppose we should just stick to file paths without extension. That will be least confusing for users.

**Comment by diml** [comment]
BTW, is this ready to be reviewed? I wasn't sure if it was ready or not

**Comment by rgrinberg** [comment]
It's just tests, so as long as we argue how module paths should be specified then I think we can merge this.

**Comment by diml** [comment]
Ok

**Pull request merged**
