### PR TITLE
Add blackbox test for #3306

### PR DESCRIPTION
**Pull request by hcarty**
Test for #3306

### CODE REVIEW

**Comment by rgrinberg** [comment]
I've fixed the little syntax error in your test and promoted the result of the test. However, it still does not reproduce the stacktrace you're talking about.

**Comment by hcarty** [comment]
@rgrinberg Sorry, just fixed + force pushed

**Comment by hcarty** [comment]
And I apologize - I think I force-pushed over your typo fix.  2b67439 includes the test w/backtrace output.

**Comment by emillon** [comment]
#3306 has been fixed so I'm closing this. Thanks

**Pull request closed without merging**
