### PR TITLE
feat(pkg): Remove `opam-repository-url` option

### PR DESCRIPTION
**Pull request by Leonidas-from-XIV**
Since the repositories are specified in the workspace file where more information like URL, branch or tag can be stored this makes for a better set-up.

### CODE REVIEW

**Review by rgrinberg — APPROVED** [review]
LGTM. I think you can remove the opam repository path option as well.

**Review by gridbugs — APPROVED** [review]

**Comment by Leonidas-from-XIV** [comment]
>  I think you can remove the opam repository path option as well.

I tried but that will currently leave us without a way to specify directories as opam-repos, as the `dune-workspace` currently only supports git repos. So maybe the way forward would be to allow that first and then remove that option?

**Comment by Leonidas-from-XIV** [comment]
Ok, also removed the `opam-repository-path`, but that required a lot of changes and modifying `dune-workspace` with Unix tools is quite painful.

**Comment by Alizter** [comment]
In #9343 I am removing all the --context arguments and replacing them with positional lock directories. Maybe we should hold off on the opam-repository-path changes until thats done, since it will simplify the current workspace wrangling.

**Comment by rgrinberg** [comment]
I'll leave it to Marek to decide, but I would suggest not to delay merging this PR for other work. There's some work I'd like to do that is waiting for this PR to be merged first.

**Comment by Leonidas-from-XIV** [comment]
I've merged this because at the end of the day, someone will have to rebase (and I know it sucks, I just did and more tests broke). Like Rudi I also have some work that is blocked on this, so if merging this unblocks both of us that's some compromise.

Changing the CLI is always painful because it touches a lot of tests. Though I assume this will get better once we have a post-1.0 CLI interface.

**Pull request merged**
