### PR TITLE
chore: kprintf -> ksprintf

### LINKED ISSUE #6767: Update build_path_prefix_map
To fix these warnings:

```sh
$ nix shell nixpkgs#ocaml-ng.ocamlPackages_5_0.ocaml -c make -B _boot/dune.exe 
ocamlc -output-complete-exe -w -24 -g -o .duneboot.exe -I boot -I +unix unix.cma boot/libs.ml boot/duneboot.ml
./.duneboot.exe
Done: 55/974 (jobs: 4)cd _boot && /nix/store/4j1a8c3nkl97v7a01fifgdf0xjzkk5iy-ocaml-5.0.0/bin/ocamlopt.opt -c -g -no-alias-deps -w -49-6 -alert -unstable -I +unix -I +threads build_path_prefix_map.ml
File "vendor/build_path_prefix_map/src/build_path_prefix_map.ml", line 5, characters 17-31:
Alert deprecated: Stdlib.Printf.kprintf
Use Printf.ksprintf instead.
Done: 213/974 (jobs: 4)cd _boot && /nix/store/4j1a8c3nkl97v7a01fifgdf0xjzkk5iy-ocaml-5.0.0/bin/ocamlopt.opt -c -g -no-alias-deps -w -49-6 -alert -unstable -I +unix -I +threads opamLexer.ml
File "vendor/opam-file-format/src/opamLexer.mll", line 21, characters 2-16:
Alert deprecated: Stdlib.Printf.kprintf
Use Printf.ksprintf instead.

```

but doesn't seem fatal.

_Originally posted by @Alizter in https://github.com/ocaml/dune/issues/6753#issuecomment-1363453542_

### PR DESCRIPTION
**Pull request by Alizter**
close #6767

### CODE REVIEW

**Comment by rgrinberg** [comment]
Shouldn't you update the build script for this to the latest version? This is a vendored dependency so we shouldn't be modifying it here apart from updating.

**Comment by Alizter** [comment]
ah yes, let me do that.

**Comment by Alizter** [comment]
I will wait for https://github.com/ocaml/opam-file-format/pull/54 so that I can update the vendor script. I've updated the one for build_path_prefix_map.

**Comment by Alizter** [comment]
Actually lets just do these separately

**Pull request closed without merging**
