### PR TITLE
Build & dune and run tests more eagerly

### PR DESCRIPTION
**Pull request by rgrinberg**
Currently, we wait until the opam dependencies are downloaded and built before
adding the tests. That is quite a bit slower then building dune and running the
tests that have no external deps. Hence, we should build & run those tests
before asking opam to do anything.

### CODE REVIEW

**Comment by diml** [comment]
Sounds good, but doesn't that mean that the output of `dune runtest` and `opam install` will be interleaved?

**Comment by rgrinberg** [comment]
Yeah, I suppose that could cause some issues if for example `$ opam install` fails. Otherwise, we could just make `$ opam install` quiet to mitigate this problem.

Another solution would be to re-run the tests after the installation. It's quite cheap compared to the cost of building and installing the external packages.

**Comment by diml** [comment]
what about dumping the output of opam install to a file and catting it after?

**Comment by rgrinberg** [comment]
There's a few opam commands whose output needs to be saved. I can save the output of runtest-no-deps however, and then cat it latter. How about that?

**Comment by diml** [comment]
Sounds good

**Comment by diml** [comment]
Ah wait, I think I misunderstood the changes. We are not running commands in parallel in the end? I thought that this PR was about running things in parallel. So we probably don't need to dump the output to a file.

Anyway, I should probably not review this script as I'm not familiar with it... so just ignore my reivew.

**Comment by rgrinberg** [comment]
> Ah wait, I think I misunderstood the changes. We are not running commands in parallel in the end? I thought that this PR was about running things in parallel. So we probably don't need to dump the output to a file.

The original situation was that we ran a bunch of expensive opam commands before running the test suite. That's sub optimal because there's no need to wait for so long if the test suite is failing. In my opinion it's better to run the tests that don't depend on external things right away.

This helps in situations where you're debugging things in CI and don't want to wait ages for results.

**Comment by diml** [comment]
I see, yh that makes sense

**Pull request merged**
