### PR TITLE
Move FAQ & Known Issues to manual

### PR DESCRIPTION
**Pull request by rgrinberg**
These sections are valid parts of the manual and just clutter up the current
README

### CODE REVIEW

**Comment by rgrinberg** [comment]
There's 2 more sections in the README that I'm not sure belong in the readme. That's the hacking and roadmap sections. I'm not sure how relevant they are to a user manual, but perhaps they should be included anyway?

**Comment by diml** [comment]
I guess we could put the hacking section in a separate file. For the roadmap, it hasn't been updated in a long time. We basically use github issues instead, so I think we should just delete it

**Comment by rgrinberg** [comment]
Yeah, we should just tag things appropriately in the issues to construct the roadmap.

**Comment by diml** [comment]
Yh, in the settings I've also seen a "Projects" feature. I think it's for creating roadmaps, we could try that as well

**Comment by rgrinberg** [comment]
OK, I've done a couple of related updates to the readme. I think the advocacy section belong in the README, though we really need to update it. The roadmap section really brings memories...

**Pull request merged**
