### PR TITLE
Document (deps (universe)) in page on cache.

### LINKED ISSUE #3538: Ability to mark rules as non-reproducible.
## Desired Behavior

I have a dune `(rule ...)` which runs a command to download a file from the internet and promotes it in my repository. This file is known to evolve: to be specific, it is the GitHub GraphQL schema, it is a dependency of my build, through [`graphql_ppx`](https://opam.ocaml.org/packages/graphql_ppx/), and I appreciate that building my project will automatically update to the latest version of the schema (and thus check compatibility with it), while if running with option `--ignore-promoted-rules` or `-p` will allow users to build the project without requiring an HTTP call.

Now that I'm also using Dune cache, I discover that the two do not play well together because Dune assumes that build rules are reproducible (and has even an option to check for this).

I'd love an option `non-reproducible` or `(cache disabled)` that I could pass to `rule` to automatically disable the cache for this rule specifically, that I know is not reproducible. Ideally, Dune would then check the checksum of the target of the rule, and if it hasn't changed, it would use the cache to skip whatever can be.

## Example

```
(rule
 (targets random)
 (action (with-stdout-to random (bash "echo $(($RANDOM%2))")))
 (cache disabled))
(rule
 (deps random)
 (targets random_bis)
 (action
  (with-stdout-to random_bis
   (progn
    (cat random)
    (cat random)))))
```

The output of the first rule is never cached. The output of the second rule is cached, thus if the checksum of the output of the first rule (`random`) has not changed, then the second rule is not run again.

### PR DESCRIPTION
**Pull request by Zimmi48**
Closes #3538.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Looks good. I'd like a second opinion from someone more familiar with the cache however. @snowleopard could you have a glance at this?

**Comment by snowleopard** [comment]
Continuing the thought from my review comment, when talking about "cache" it is worth clarifying which cache we mean to avoid confusion. There are three cache mechanisms in Dune:
* Build directory `_build` (local);
* Cache shared between different projects on the same machine (shared);
* Cache shared between different machines (distributed).

**Comment by Zimmi48** [comment]
Interesting consideration. Maybe this doesn't fully solve #3538 then, since it could be worthwhile to have a way of specifying that we don't want to use the non-local cache (i.e. we want the rule to be re-run after a `dune clean`) but do not want either to re-run the rule every time we call `dune build` in the same session (for instance in this use case where this requires making a download from the internet).

**Comment by snowleopard** [comment]
@Zimmi48 I haven't looked into #3538 in detail but indeed it might be the case that `(deps (universe))` is not what you need. In general, non-deterministic build rules are difficult to reason about, and some build systems forbid them altogether.

Are you happy for this PR to be merged?

**Comment by Zimmi48** [comment]
> Are you happy for this PR to be merged?

Yes, I'm fine with the current state.

**Comment by rgrinberg** [comment]
@snowleopard please merge this PR if you're happy with it

**Comment by snowleopard** [comment]
Done! Sorry for the delay.

**Pull request merged**
