### PR TITLE
"dune top" fixes + improvements

### LINKED ISSUE #4231: "dune top" output does not property escape strings
eg:
```
$ cat mlfip.mltop
#directory "c:\cygwin64\home\nojebar\mlfi2\_build/default/applications/csharp_interface/.interfaces.objs/byte";;
#directory "c:\cygwin64\home\nojebar\mlfi2\_build/default/applications/csharp_interface/.interfaces.objs/native";;
#directory "c:\cygwin64\home\nojebar\mlfi2\_build/default/applications/csml/.csml_standalone.objs/byte";;
#directory "c:\cygwin64\home\nojebar\mlfi2\_build/default/applications/csml/.csml_standalone.objs/native";;
#directory "c:\cygwin64\home\nojebar\mlfi2\_build/default/private/a1a3_migration/.a1a3_migration.objs/native";;
#directory "c:\cygwin64\home\nojebar\mlfi2\_build/default/private/a1a3_migration/.a1a3_migration.objs/public_cmi";;
```

### PR DESCRIPTION
**Pull request by nojb**
In this PR:

- Fix the escaping of the toplevel directives emitted by `dune top`
- Include the directories containing C stubs for those libraries which have them in the list of `#directory` directives. This allows the toplevel to locate and load said C stubs, which results in a seamless experience in many cases.

Fixes #4231

### CODE REVIEW

**Review by rgrinberg — APPROVED** [review]
Looks good. Can we get

* Some tests demonstrating fixes
* Changes entries

**Comment by nojb** [comment]
> Looks good. Can we get
> 
> * Some tests demonstrating fixes
> * Changes entries

Done! BTW, this could also go into 2.8.3...

**Comment by nojb** [comment]
I pushed one more commit so that the `toplevel` stanza also includes the directories needed to find C stubs.

**Comment by rgrinberg** [comment]
@nojb anything blocking this PR?

**Comment by nojb** [comment]
> @nojb anything blocking this PR?

No, thanks for the ping. Will merge once CI passes.

**Pull request merged**
