### PR TITLE
Add a `copy_dir` stanza

### PR DESCRIPTION
**Pull request by voodoos**
This PR adds a `copy_dir` stanza to the dune_file syntax.

So far, this stanza accept only the following syntax:

`(copy_dir <dir>)`

Where `<dir>` is a relative path to a single directory that may use variables.
The selected directory, along with all it's content will be "copied" recursively at the root of the build directory in a similar way as the `copy_files`.

## Todo:

- [ ] Add a "#" version of the stanza, similar in effect as the "#" version of `copy_files`
- [ ] Add `alias` and `mode` as in #3631
- [ ] Support external paths as in #3639

### CODE REVIEW

**Comment by nojb** [comment]
> The selected directory, along with all it's content will be "copied" recursively at the root of the build directory in a similar way as the `copy_files`.

What does it mean "recursively" here? Will the stanza create subdirectories at the destination?

**Comment by voodoos** [comment]
> > The selected directory, along with all it's content will be "copied" recursively at the root of the build directory in a similar way as the `copy_files`.
> 
> What does "recursively" mean here? Will the stanza create subdirectories at the destination?

Yes.

For instance if you have the following directory structure:
```
to_copy
└── foo
    ├── bar.md
    └── fooer
        └── barer.md
```

And you use `(copy_dir to_copy/foo)`. Then the entire subtree will be copied in the build directory:
```
_build
├── default
│   ├── foo
│   │   ├── bar.md
│   │   └── fooer
│   │       └── barer.md
```

**Comment by nojb** [comment]
Two unrelated remarks:

- I think that supporting the non-recursive case is also interesting.

- I thought that having targets in the current directory was a basic assumption in a lot of places. After this PR would it be (at least in principle) possible to, say, have rules with targets in other directories apart from the current one? (I'm not saying this would be a good idea, just wondering if it would be technically possible)

**Comment by jeremiedimino** [comment]
> I thought that having targets in the current directory was a basic assumption in a lot of places. After this PR would it be (at least in principle) possible to, say, have rules with targets in other directories apart from the current one? (I'm not saying this would be a good idea, just wondering if it would be technically possible)

Actually, that reminds me that this is something to consider for this PR. Technically, all we need is a policy so that Dune can always identify the code that produces the rules for a file. Currently, the assumption is that it is calling the `gen_rules` callback passed to the build system with the directory of the file that will produce the rule to produce this file.

A simple policy would be that a rule is allowed to produce targets in the tree it is rooted at. This would mean that to produce the rules for a directory, we need to call `gen_rules` not only for the current directory but also for all its ancestors. This might not be too bad in practice.

In any case, it might be sound or not depending on how we handle directory overlaps between source and destinations. Actually, @voodoos you should add tests with clashes like this.

**Comment by rgrinberg** [comment]
Perhaps it's a bit late to reconsider the design, but what about a general `copy` stanza instead? `files` or `dirs` can just be a field in this stanza. In my opinion, all these specialized operations do not deserve their own stanzas.

**Comment by nojb** [comment]
> Perhaps it's a bit late to reconsider the design, but what about a general `copy` stanza instead? `files` or `dirs` can just be a field in this stanza. In my opinion, all these specialized operations do not deserve their own stanzas.

I think it makes sense!

**Comment by voodoos** [comment]
> Perhaps it's a bit late to reconsider the design, but what about a general `copy` stanza instead? `files` or `dirs` can just be a field in this stanza. In my opinion, all these specialized operations do not deserve their own stanzas.

It's not to late, I was expecting more design discussions so I kept the PR in draft state.

I also agree that copying directories should be an option of a more general `copy` stanza. (Even the "todos" of this PR demonstrate the similarity between these features).


If we decide to do this I suppose we need to carefully transition before dune_lang 3 ?
By adding the new `copy` and deprecating `copy_files` while keeping it ?
(Another option would be to keep adding options to copy_files without renaming it.)

**Comment by jeremiedimino** [comment]
> If we decide to do this I suppose we need to carefully transition before dune_lang 3. By adding the new copy and deprecating copy_files while keeping it ? (Another option would be to keep adding options to copy_files without renaming it.)

The general rule is:

- add the new better feature, and deprecate the old one starting from the next minor language version
- in the next major language version, remove the old feature (from the syntax only)

In any case, support for the old feature remains for older projects. To keep the code base sustainable, it is good if the new feature is strictly more general and the old one can be implemented in terms of the new one.

> I have a question about copy_files: what happen if the user tries to overwrite a file that is part of the sources, already copied, or even generated ?

You get an error "multiples rules generated for ..."

**Comment by rgrinberg** [comment]
Is it actually necessary to deprecate any other copy stanza if we introduce `copy`? We already have some redundant stanzas in dune which are not deprecated. I think it's fine to keep old stuff working as long as it's not a maintenance pain and it doesn't have any serious disadvantages.

**Comment by jeremiedimino** [comment]
We should aim at keeping the language concise. Having redundant way of doing the same thing is not great as it is more to learn.

In any case, as always the deprecation should be tied to the dune language version. So existing projects won't see the deprecation until they take action and update the version of the dune language they use.

**Comment by jeremiedimino** [comment]
Thinking more about this, it seems clear to me that in the next major version of the language we should remove duplicate stanza to keep the language clean and minimal. However, it is slightly less clear that we need to deprecate the duplicate right in the next minor version of the language. Both choices change nothing for existing projects until they take action, however if we deprecate the duplicate in Dune 2.7, then users switching to 2.7 can immediately adopt the most modern and future syntax by making their dune file warning free. On the other hand, users might not like being forced to upgrade their dune files to avoid warnings between minor versions, instead they might prefer to stick with the original dune 2.x language until the next major release.

So perhaps the general should be:

- if we replace a piece of syntax by another one and the old one is considered harmful, we should deprecate it immediately
- if we replace a piece of syntax by another one and we prefer the new one purely for aesthetic reasons, we keep the old one non-deprecated

In both case, in the next major version we delete the old syntax.

In this particular case, it feels like we are in the second case. The new stanza is more general and supersede the old one, but the old one is not wrong in any way. So we should keep `copy_files`  as it until `(lang dune 3.0)`.

**Pull request closed without merging**
