### PR TITLE
Move Dyn into own library & package

### PR DESCRIPTION
**Pull request by rgrinberg**
As mentioned before, this module is quite useful on its own and I'd like to use it in dune-rpc (and elsewhere) without depending on stdune.

### CODE REVIEW

**Review by jeremiedimino — APPROVED** [review]
Seems fine. A bit sad that we have to loose the `Ordering.t` though

**Comment by rgrinberg** [comment]
We just need to find a way to transition the rest of the world to use Ordering.t. Problem solved :)

**Comment by jeremiedimino** [comment]
Haha, that has always been one of my dream :) I introduced `Ordering.t` in the first proposal for Base, but the idea was deemed too ambitious. That being said, we could extract `Ordering` into its own library and depend on it.

**Comment by rgrinberg** [comment]
Hmm, it looks like a spurious dependency cycle is being reported:

```
Error: Dependency cycle between:
   alias .stdune-unstable-files
-> alias .dyn-files
-> alias .stdune-unstable-files
-> required by alias .dune-configurator-files
-> required by alias otherlibs/configurator/test/blackbox-tests/runtest
```

**Comment by jeremiedimino** [comment]
A dependency between `.xxx-files` aliases means a dependency between the `xxx` packages. As a side note, it'd be nice to replace these `.xxx-files` aliases by dedicated memoised functions. Then we could attach a nicer human readable description  and get instead:

```
Error: Dependency cycle between:
   package stdune-unstable
-> package dyn
-> package stdune-unstable
-> required by package dune-configurator
-> required by alias otherlibs/configurator/test/blackbox-tests/runtest
```

**Comment by jeremiedimino** [comment]
The cycle is due to `pp` being part of `stdune-unstable`:

```
$ cat vendor/pp/src/dune
(library
 (name pp)
 (public_name stdune-unstable.pp))
```

**Comment by rgrinberg** [comment]
> As a side note, it'd be nice to replace these .xxx-files aliases by dedicated memoised functions. Then we could attach a nicer human readable description and get instead:

That's true, but I think what's really needed are entries that describe where the cycle was introduced. In this case, I would have liked to see that stdune package both includes the pp library and depends on it in one of its sub-libraries.

> The cycle is due to pp being part of stdune-unstable:

Good catch. For now I'll change the package to dune-rpc for dyn as a quick workaround. We really need to revive https://github.com/ocaml/dune/pull/3575 and get rid of this vendoring mess though.

**Pull request merged**
