### PR TITLE
Preview: upgrade to ocamlformat.0.17.0

### PR DESCRIPTION
**Pull request by gpetiot**
edit: This is a preview of the not-yet-released ocamlformat.0.17.0, please wait until the package is published in opam to merge this PR.

Hi, this pull-request is a preview of the soon to be released ocamlformat.0.16.0. The main change in the diff is that `indicate-multiline-delimiters` option has now be switched to `no` on the conventional profile to improve consistency and minimize the diffs in the future.
Let me now if you notice any regressions.

Signed-off-by: Guillaume Petiot <guillaume@tarides.com>

### CODE REVIEW

**Comment by gpetiot** [comment]
Hi, do you have any feedback on the upgrade from ocamlformat 0.16.0 to 0.17.0 (last commit) before I make the release? Thanks!

**Comment by jeremiedimino** [comment]
I eyeballed a third of the diff. IMO, the new formatting looks better (in particular, less spaces after '('/before ')' is welcome), except for a few cases:

- in some cases, it's putting `::` on its own line, while IMO it looked better as it was before
- in some cases, it's replacing `with exn ->` by `with<newline-ident>|exn ->`, which doesn't feel necessary

But neither feel particularly problematic.

**Comment by gpetiot** [comment]
Sorry for the inconvenience, we are constantly improving ocamlformat but sometimes to fix a bug we are forced to simplify some part of the code or remove some sugaring and that can have some impact like these ones. This might be improved in a future release, we're getting there!

**Comment by jeremiedimino** [comment]
No worries and thanks for the good work on ocamlformat!

**Pull request closed without merging**
