### PR TITLE
configurator: allow sizeof in C symbols import

### PR DESCRIPTION
**Pull request by Chris00**
This is an alternative proposal to https://github.com/ocaml/dune/pull/1723 — with tests.   Count on the CI to show it works with all targeted compilers.

### CODE REVIEW

**Comment by avsm** [comment]
Your way is indeed better! Closing my PR.

**Comment by Chris00** [comment]
Except that it seems not to work with older GCC (on my machine `gcc --version` reports `8.2.0`).

**Comment by Chris00** [comment]
@avsm @rgrinberg Do you think I should use other macro names (such as `DUNE_ABS` and `DUNE_SIGN`) to avoid potential conflicts with some C header files?

**Comment by Chris00** [comment]
I've done so.

**Comment by Chris00** [comment]
Done.

**Comment by avsm** [comment]
We should try to bind libdune the numerical library to check for conflicts :)

**Review by rgrinberg — APPROVED** [review]

**Comment by avsm** [comment]
I've tested this on the ctypes port and it's working fine for me.

**Comment by emillon** [comment]
I missed that one because of the missing cross-ref. I'll add this and merge, thanks!

**Pull request merged**
