### PR TITLE
test(fiber): allocation tests for parallel_iter

### PR DESCRIPTION
**Pull request by rgrinberg**
Make the allocation tests more robusts. Instead of testing that we
allocated nothing, we should check that extra overhead is constant wrt
the number of elements.

@snowleopard do you have time to review this? It is extracted from #5230

### CODE REVIEW

**Review by snowleopard — APPROVED** [review]
The test looks good but it would be even better if we could see the actual allocation numbers in `%expect` output, to make the test a bit more self-documenting. Keeping the asserts is fine too, of course.

Perhaps, allocation numbers aren't reproducible? If yes, I wonder what's the reason behind this.

**Comment by rgrinberg** [comment]
They're all reproducible (at least on my machine). I'll add them in and let's see if CI approves

**Comment by rgrinberg** [comment]
Looks like it works.

**Comment by snowleopard** [comment]
Great!

**Pull request merged**
