### PR TITLE
refactor(coq): move install functions

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Review by ejgallego — COMMENTED** [review]
What's the point of this?

**Comment by Alizter** [comment]
To keep the order of the file somewhat related. Since the install rules are usually done last they should come last. Before there were build rules either side which made them harder to find.

**Comment by ejgallego** [comment]
> To keep the order of the file somewhat related. Since the install rules are usually done last they should come last. Before there were build rules either side which made them harder to find.

Mmm, I think it makes more sense to keep the rules grouped per-stanza, as it is now.

What does it mean for a rule to be done "last" ? As far as I know the ordering is not relevant.

**Comment by Alizter** [comment]
Never mind then. If it causes this much thinking, it isn't worth doing.

**Comment by ejgallego** [comment]
Well organization of the code is one of the things that usually requires more thinking. coq_rules is growing too large.

**Pull request closed without merging**
