### PR TITLE
Add proper parsing errors when failing to extract values

### PR DESCRIPTION
**Pull request by rgrinberg**
This helped me debug #1736

### CODE REVIEW

**Comment by rgrinberg** [comment]
@Chris00 feel free to push the fix on top of this PR btw. I'm not entirely sure how the behavior of int_of_string changed since 4.02 so I'm not confident enough to fix this.

**Comment by rgrinberg** [comment]
Thanks @Chris00. I tested this out and it seems to work.

I'll let @emillon or @avsm give this an opportunity to review before merging.

**Comment by diml** [comment]
In this case, the exception that is being discarded is `Invalid_argument "bool_of_string"` which would be of no-use to the user. We could possibly use `(t, unit) result` rather than `t option`, to make the failure clearer.

**Comment by rgrinberg** [comment]
Returning a proper message makes sense when are interested in the modes of failures. Doesn't seem to be the case here.

**Pull request merged**
