### PR TITLE
Make User_message's annotations a Univ_map

### PR DESCRIPTION
**Pull request by jeremiedimino**
Last `User_message` improvement for today: make annotations a `Univ_map`, since it is really what it is.

### CODE REVIEW

**Comment by snowleopard** [comment]
> Last `User_message` improvement for today

Maybe not the last one because I have one more coming =)

**Comment by jeremiedimino** [comment]
Gentle ping. The diff is much smaller than what github pretends. The PR mostly removes code from `User_message` and replaces it by re-using `Univ_map`.

**Review by snowleopard — APPROVED** [review]
Good improvement type-wise but probably a slight regression in terms of verbosity of the call sites (where we add annotations). On balance, I like the new version better.

**Comment by jeremiedimino** [comment]
Agreed

**Pull request merged**
