### PR TITLE
chore: fmt dune file in test

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by rgrinberg** [comment]
How did you format this file? `make fmt` isn't doing it.

**Comment by Alizter** [comment]
@rgrinberg I did from inside my editor. `make fmt` won't touch it since it is inside a cram test.

**Comment by Alizter** [comment]
@emillon the sendfile fix caught this PR instead, can you reopen and fix the changelog.

**Comment by emillon** [comment]
Sorry about that. I fixed the changelog while merging it.

**Comment by rgrinberg** [comment]
Unless we have a systematic way to format these files, let's not bother with this. Also, the concrete formatting changes in this PR aren't even beneficial and we should tweak our formatter to be a little more compact.

**Pull request closed without merging**
