### PR TITLE
Do not use DUNE_RPC in dune tests

### PR DESCRIPTION
**Pull request by aalekseyev**
Before this PR, when I try to run dune tests in watching mode, the tests connect to the outer dune instead of using the one spawned for the test.

I think this behavior is relatively new, but I'm not sure when it was introduced.

I'm fixing it by ignoring the DUNE_RPC variable in tests.
Ideally, we'd simply avoid inheriting it in the first place, but that's a bigger change and may need larger consensus on the design.

Signed-off-by: Arseniy Alekseyev <aalekseyev@janestreet.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
> Ideally, we'd simply avoid inheriting it in the first place, but that's a bigger change and may need larger consensus on the design

To give some context, the point of this environment variable was to simplify connection for actions. Build scripts such as configurator could use RPC to query dune for various build environment info. 

I suppose we could require rules to specify a dependency on dune-rpc, but we would have preferred to make the whole things automatic.

By the way, since we don't rely on this behavior anywhere yet, you could all fix this issue by changing `getenv` in `dune_rpc_impl/where.ml` to always return `None`. Perhaps that's a big confusing, but it's a much smaller "workaround"

**Comment by rgrinberg** [comment]
of course, I forgot to mention that you could simply unset the environment variable in your test.

**Comment by aalekseyev** [comment]
We can't unset the environment variable, actually, because getenv looks at the initial environment and that's immutable.
Even if we made it look at the mutable glibc environment (questionable idea), you still can't unset it because `Sys.unsetenv` is not a thing. (yeah...)

I'd like to be able to declare in the jbuild file that the test should not inherit this environment variable, but I don't think that's supported. (after all, we add to the environment unconditionally)

> Build scripts such as configurator could use RPC to query dune for various build environment info

Perhaps it would make sense to only provide access to such an info instead of a full-featured RPC server.

> I suppose we could require rules to specify a dependency on dune-rpc, but we would have preferred to make the whole things automatic.

But if you don't declare this dependency, then you have to re-start *all* actions any time anything in the environment changes, which seems terrible.

> you could all fix this issue by changing getenv in dune_rpc_impl/where.ml to always return None. Perhaps that's a big confusing, but it's a much smaller "workaround"

Hum, I think that's very confusing. At that point, wouldn't it be better to just delete the getenv logic entirely, and re-introduce it if we need it in the future?

There's another workaround: simply avoid setting DUNE_RPC for now. I like that better than "crippling" `getenv`, and if you say you're fine with disabling this feature for now then that seems to be a good way to do it. What do you think?

**Comment by aalekseyev** [comment]
@rgrinberg, I pushed that change, effectively reverting most of the PR and replacing it with a one-line change.

**Comment by rgrinberg** [comment]
> We can't unset the environment variable, actually, because getenv looks at the initial environment and that's immutable.
Even if we made it look at the mutable glibc environment (questionable idea), you still can't unset it because Sys.unsetenv is not a thing. (yeah...)

I thought we could have used `unset DUNE_RPC` in bash, but now I remember the tests aren't written in cram.

> Perhaps it would make sense to only provide access to rpcs that provide this info instead of a full-featured RPC server.

Possibly. Though I'm not sure if this is worth the complexity. As you say, it's sufficient to just hide the variable in the action somehow.

> But if you don't declare this dependency, then you have to re-start all actions any time anything in the environment changes, which seems terrible. (hm, maybe the idea is to track the dependencies automatically, which could work)

Yes, going for something fully automatic would be the goal here. In the future, it might make sense for the dynamic action plugin to use RPC to ask dune to provide dependencies. So this could be the only environment variable that is inherited by default.

> There's another workaround: simply avoid setting DUNE_RPC for now. I like that better than "crippling" getenv, and if you say you're fine with disabling this feature for now then that seems to be a good way to do it. What do you think?

Seems fine with me.

**Comment by aalekseyev** [comment]
> Seems fine with me.

Sounds like an "approval" to me. Merging.

**Pull request merged**
