### PR TITLE
Add support for (empty_module_interface_if_absent)

### LINKED ISSUE #4952: [RFC] Opt-in generation of empty interfaces of modules without `.mli` ?
When a module is used solely for their side-effects, one typically wants to add an empty interface file to benefit from the various "unused" warnings, faster incremental compilation, etc.

In our case we have some libraries where we have dozens and dozens of such files. It would be nice if we could have `dune` generate the empty interface files on demand, eg having a field `(modules_without_interface ...)` that would tell `dune` to generate empty interface files for the listed modules (both in libraries and executables).

(In case you are curious, we currently patch the compiler to avoid having to actually create all these empty interfaces, but it seems like a task that would fit nicely to Dune.)

Opinions?

### PR DESCRIPTION
**Pull request by nojb**
Fixes #4952

### CODE REVIEW

**Comment by nojb** [comment]
I find the name `(empty_module_interface_if_absent)` a bit of a mouthful. Suggestions welcome!

**Comment by rgrinberg** [comment]
Looks fine to me. Does it make sense to enable this by default for modules that are entry point of executables? As suggested by @CraigFe elsewhere.

**Comment by nojb** [comment]
> Looks fine to me. Does it make sense to enable this by default for modules that are entry point of executables? As suggested by @CraigFe elsewhere.

I thought that was the plan for 3.0.

**Review by ghost — APPROVED** [review]
Looks good!

(there is just a typo in the changelog)

**Comment by nojb** [comment]
Thanks @jeremiedimino for the review! Will merge once CI passes.

**Pull request merged**
