### PR TITLE
Refactor & Optimize Fiber Pool

### PR DESCRIPTION
**Pull request by rgrinberg**
This a series of commits that optimizes Fiber.Pool by implementing it from scratch on top of fiber's core rather than relying on unrelated primitives. The result is a much simpler implementation that affords a lot of optimizations:

* There's no need for a reader queue because a pool always has one reader.
* We can fuse the mvar and pool fields and get a more compact memory layout
* We don't need to rely on indirection from Fiber.Stream. This shaves off a whole lot of closures and removes the lock/unlock mutations which insert more of the write barrier.
* We inline and reuse a bunch of closures when reading from the queue. We no longer rely on general purpose stream/mvar primitives which allows us to specialize this code path a lot better.

The PR is composed of a series of commits that all do individual specializations/simplifications. I will squash them at the end. 

After this PR I have another PR with even more optimizations/simplifications but it subtly changes the semantics somewhat (for the better IMO). I will submit it after.

### CODE REVIEW

**Review by snowleopard — COMMENTED** [review]
Do you have any performance figures to motivate this change? 

You say the result is "simpler" but a lot of tricky code was copied and subtly modified from the original, which can be costly in terms of future maintenance.

This 50 line diff is tricky to review and I don't have a high confidence it doesn't introduce a bug.

(I suppose I could just mechanically follow the inlining to convince myself the transformation is correct but... humans aren't as good for this sort of thing as compilers!)

**Comment by rgrinberg** [comment]
> Do you have any performance figures to motivate this change?

I can provide some. As I said there's also a subsequent PR that simplifies things further. So I thought about batching it.

> You say the result is "simpler" but a lot of tricky code was copied and subtly modified from the original, which can be costly in terms of future maintenance.

It can be costly, but I think in this case I've made a much larger mistake of reusing Stream/Mvar to implement this feature in the first place and it already cost me a lot of debugging time. Note that I only wrote Pool in this way because I was in a huge rush and needed something working for LSP, we shouldn't place too much weight in the decisions of the old implementation.

> This 50 line diff is tricky to review and I don't have a high confidence it doesn't introduce a bug.

Every commit is a single refactoring step that you can read to convince yourself it's the same. I can leave more comments if some things aren't clear.

**Comment by snowleopard** [comment]
> I've made a much larger mistake of reusing Stream/Mvar to implement this feature in the first place and it already cost me a lot of debugging time.

I don't follow. Reusing code is hardly a mistake on its own. In fact, I'd say it's pretty desirable! You seem to claim that this PR is not just an equivalent transformation of an existing code (via inlining) but somehow makes it better. Can you be more specific?

Better performance may be one such specific thing. Stopping to use inappropriate (in some sense) abstractions may be another, but I don't understand how reusing Mvar was inappropriate here. It seems pretty appropriate to me. How is inlining the Mvar code help with debugging?

**Comment by rgrinberg** [comment]
> I don't follow. Reusing code is hardly a mistake on its own. In fact, I'd say it's pretty desirable!

I agree whole heartedly which is why I tried to achieve it in the first place. I just have two reservations in this particular case:

* We actually implemented an Mvar just to implement this Pool module. After this PR, it's only being used to implement a single function inside `stream` which is only used in tests. So we could easily get rid of it and make the diff a net negative. (Although I don't think it's worth pursuing as it might come handy later and there might be other users outside of us still using it)

* The stream module is problematic. It was designed and re-designed a few times and the end result was always lacking. I don't like how streams have this internal locking mechanism and that we must remember to use the magical `parallel_iter` to process them without leaking memory.

> Better performance may be one such specific thing. Stopping to use inappropriate (in some sense) abstractions may be another, but I don't understand how reusing Mvar was inappropriate here. It seems pretty appropriate to me. How does inlining the Mvar code help with debugging?

Better performance is the only observable change in this PR.  On purpose I might add, because I think it would be simpler for you to review optimizations and changes of semantics when they're clearly separated.

>  Can you be more specific?

I gave you a little riddle [here](https://github.com/ocaml/dune/pull/6812/files#r1059241110). I would not want to spoil it :)

**Comment by snowleopard** [comment]
Thanks! It seems to me from what you wrote that the main benefit of this PR is actually dropping the dependency on `Stream` because that module is problematic. That does sound like a good reason to make some changes.

But then, shouldn't we just start with exactly that and not attempt to squeeze out some further optimisations by noticing that the MVar in this case has only one reader? This seems much less important. MVar is a very well-known and understood abstraction, so it seems useful to provide support for it in the Fiber library.

**Comment by snowleopard** [comment]
> I gave you a little riddle [here](https://github.com/ocaml/dune/pull/6812/files#r1059241110). I would not want to spoil it :)

Wait, if MVar is just an incorrect abstraction for pools, then going to the trouble of inlining them before presumably getting rid of them seems pretty roundabout.

**Comment by rgrinberg** [comment]
> But then, shouldn't we just start with exactly that and not attempt to squeeze out some further optimisations by noticing that the MVar in this case has only one reader? This seems much less important. MVar is a very well-known and understood abstraction, so it seems useful to provide support for it in the Fiber library.

Right, but there's also this queuing property of mvars that isn't needed and is a source of deadlocks.

> Wait, if MVar is just an incorrect abstraction for pools, then going to the trouble of inlining them before presumably getting rid of them seems pretty roundabout.

I suppose. I actually tried doing it the way you're proposing but ended up in a state where I wasn't sure if some changes to behavior were intended or bugs. So I tried this approach:

* First simplify the implementation as much as possible and drop all the dependencies. The optimizations are just the icing on the cake.
* Then make a commit that fixes the bugs and improves the semantics. This one ends up being much smaller but depends on this set of commits.

**Comment by snowleopard** [comment]
Right, makes sense now. 

After this discussion, I think it would be easier for me to just review the whole change at once, i.e. a new implementation of `Pool`, without going through the inlining exercise. Could you create a new PR which jumps straight to the final state? (Let's keep this one for now.)

**Pull request closed without merging**
