### PR TITLE
Remove the example directory

### PR DESCRIPTION
**Pull request by jeremiedimino**
It feels superfluous now that we have the quickstart guide

### CODE REVIEW

**Comment by jeremiedimino** [comment]
That's not a bad idea at all

**Comment by MdeLv** [comment]
The example directory is useful in addition to [quickstart](https://dune.readthedocs.io/en/stable/quick-start.html#).
It's no more in dev branch, and not in https://github.com/ocaml-dune .
Where is it now?
Thanks.

btw, this example directory was useful to detect and learn that dune gives not enough information to its user about what it does and what it does not and why (in this case, `--root .` was required and undocumented).
This is an issue (see  #3429, #1584...) that would need a dedicated discussion.
I'm no more an OCaml beginner but I had/I'm having hard time with dune, compared to the build system of other mainstream PLs, while it's a key component of the OCaml toolchain. It's not easy to characterize dune.

**Comment by jeremiedimino** [comment]
It is still in the git repo. I'm planning to merge this PR once I have created a separate repo under https://github.com/ocaml-dune

**Comment by jeremiedimino** [comment]
This PR is getting old, closing it.

**Comment by MdeLv** [comment]
Have you "merged this PR once created a separate repo under https://github.com/ocaml-dune", as announced in May 2020?

**Comment by jeremiedimino** [comment]
Nope. This PR is too low priority on my stack to keep it open.

**Pull request closed without merging**
