### PR TITLE
melange: add build benchmark to ci

### PR DESCRIPTION
**Pull request by jchavarri**
Adds a new workflow `melange-bench` that compiles a demo project ([pupilfirst](https://github.com/jchavarri/pupilfirst/)) using melange and the version of dune of each commit pushed to `main`.

The benchmark relies on a couple of external tools:
- [hyperfine](https://github.com/sharkdp/hyperfine): a command line benchmarking tool
- [github-action-benchmark](https://github.com/benchmark-action/github-action-benchmark/): a GitHub Action for continuous benchmarking

The latter requires some permissions to push the results of each benchmark to a branch (`gh-pages` by default), so that they can be visualized by simply visiting a url. A sample of the results can be seen in https://jchavarri.github.io/dune/dev/bench/.

A sample run in ci can be found here: https://github.com/jchavarri/dune/actions/runs/3794378989.

In order to use this action, the `gh-pages` branch should be created first:
```
git checkout --orphan gh-pages
echo "Dune benchmarks" > index.html
git add index.html
git commit -m "First gh-pages commit"
git push origin gh-pages
```

Before merging, the workflow should be updated to run only on `main` branch, for safety.

### CODE REVIEW

**Comment by jchavarri** [comment]
In the last commit, I used some other features from the github action. There is a threshold that can be set to define where alerts are triggered (see below). I set it to 5% initially to test, but will update it to 125% (e.g. if last build took 40s and next one takes 50s, it will trigger an alert).

Also defined a few other fields to:
- fail the workflow if threshold is exceeded
- add a comment on the commit that triggered the failure (example can be seen [here](https://github.com/jchavarri/dune/commit/e1df5380f22a927507e6cf20ead22a545f9b3a63#commitcomment-94425390))
- mention myself in the comment (let me know if anyone else wants to be added)

**Review by rgrinberg — APPROVED** [review]

**Comment by rgrinberg** [comment]
> In order to use this action, the gh-pages branch should be created first:

Do I need to do this before merging?

**Comment by jchavarri** [comment]
> Do I need to do this before merging?

I did it in https://github.com/ocaml/dune/pull/6791/commits/0bc022a1a2d435794243933d8359a970b4250086.

The only thing missing before merging should be creating the `gh-pages` branch, the PR description includes steps to do so.

**Comment by anmonteiro** [comment]
Results seem to be appearing in https://ocaml.github.io/dune/dev/bench/

**Comment by Alizter** [comment]
Could we put the link in the developer documentation?

**Comment by rgrinberg** [comment]
Sure, why not.

**Comment by jchavarri** [comment]
Added in https://github.com/ocaml/dune/pull/6864.

**Pull request merged**
