### PR TITLE
Disable new name check for dune_lang < 2.7.0 or 3.0 ?

### PR DESCRIPTION
**Pull request by voodoos**
Prior to version 2.7 dune was not checking if the field `names` of executables was or wasn't populated with valid module names.

Now it does, but this should not break compilation of projects using dune lang <= 2.6 as was revealed by the opam CI:
https://github.com/ocaml/opam-repository/pull/17005

### CODE REVIEW

**Comment by rgrinberg** [comment]
I think we need to disable the name  check until 3.0 basically. Otherwise users aren't able to upgrade freely.

**Comment by voodoos** [comment]
Ok, do we keep it in the code with a check for dune_lang < 3.0 ?

**Comment by rgrinberg** [comment]
We can. Although I think we need some discussion with the rest of the team if this restriction is worth it in the end.

**Comment by voodoos** [comment]
Ok, "wait for 3.0" as a mitigation for this release, and we can discuss it on the next dune-meeting ?

**Comment by rgrinberg** [comment]
Sounds good to me.

**Pull request merged**
