### PR TITLE
Enforce new OCaml compatibility policy

### PR DESCRIPTION
**Pull request by diml**
- restore compatibility with OCaml 4.06 and 4.07
- restore testing in the CI of OCaml 4.06 and 4.07
- drop older < 4.06 compatibility code in stdune
- make sure we fail with a nice error message in bootstrap.ml when using an older compiler

### CODE REVIEW

**Comment by XVilka** [comment]
Does it make sense to add also the testing of 4.09 in this PR too?

**Comment by diml** [comment]
I wanted to do that, however I tried to install 4.09 beta1 on my machine via opam but I couldn't figure out how to do that. If it's difficult to install on our machines then it's going to be difficult to debug build failures. So for now I think we should hold off adding 4.09 to the CI.

**Comment by diml** [comment]
I see that 4.09.0 has just been released, trying again.

**Comment by diml** [comment]
Alright, it's added

**Pull request merged**
