### PR TITLE
Avoid running a pager when running 'git diff'

### PR DESCRIPTION
**Pull request by AltGr**
my parallel tests hang because of this

### CODE REVIEW

**Comment by nojb** [comment]
I'm surprised by this PR; `git diff` never uses a pager when run under `dune` for me (even when I would like it to :)). Do you have a specific configuration in place?

**Comment by AltGr** [comment]
This happened on an OSX machine with obsolete versions:
```
$ git --version
git version 2.17.2 (Apple Git-113)
$ diff --version
diff (GNU diffutils) 2.8.1
```
but I suspect this https://travis-ci.org/github/ocaml/opam/jobs/740866285 to be the same issue.

**Comment by rgrinberg** [comment]
This seems good to me. @nojb when is it useful for for git to run the pager?

**Comment by nojb** [comment]
> This seems good to me. @nojb when is it useful for for git to run the pager?

Well, when the diff is rather big sometimes I wish I had the pager to look around. But I can see that the interaction with the rest of `dune` (buffering, etc) is not clear, so it is not something I am asking for :)

**Comment by AltGr** [comment]
@nojb at least there should be checks for no concurrency (`-j 1` ?) and a terminal ; it would be OK to re-enable the pager in this case I guess, but it would need more care.

**Review by aalekseyev — APPROVED** [review]
Looks good to me.

**Pull request merged**
