### PR TITLE
fix(nix): fix melange build and update flake

### PR DESCRIPTION
**Pull request by Alizter**
We need to use melange 1.0 because later versions don't work with OCaml 4.14. Annoyingly, this version of melange has a test that is run by the flake which is non reproducible between differing versions of Dune due to the order of execution. This leads to the failure observed in https://github.com/ocaml/dune/issues/9154.

Updating melange is not an option, so I've gone ahead and forked melange 1.0 and manually removed the offending test. This lets `nix develop` work again which was broken for a while.

### CODE REVIEW

**Comment by anmonteiro** [comment]
Isn't `melange.overrideAttrs (_: { doCheck = false; })` enough?

**Comment by Alizter** [comment]
@anmonteiro I seem to recall trying that before and it not working. Let me give it another go.

**Comment by Alizter** [comment]
@anmonteiro Is there any issue with continuing like this from your end?

**Comment by anmonteiro** [comment]
feel free to go ahead. We should remember to update Melange once Dune runs its tests on 5.1 instead.

**Comment by Alizter** [comment]
ping @rgrinberg

**Pull request merged**
