### PR TITLE
Attempt to fix #3862

### LINKED ISSUE #3862: Trace files should also contain dune internal computations
## Desired Behavior

When building a target with the `--trace-file` option, dune currently logs the time taken when running an external process (nproc, ocamldep, ocamlopt, ...). But it doesn't contain any detail about what's happening inside dune. For example, it doesn't tell us how long it takes to scan all the dependencies in a project (in a dir? unsure what the best granularity would be), how long it needs to compute the rules, ...

We end up with `dune build ./some_target.bc --trace-file=trace.json` calls doing nothing but taking close to 8 seconds without any detail of what is causing such delay. Or a long delay at the start and the middle of a build without knowing what is going on.

Also it would be great to know how many cores are assigned to each task.

### PR DESCRIPTION
**Pull request by rgrinberg**
Memoize traces of globs. This is a naive attempt, and I'm not sure if it's
correct.

### CODE REVIEW

**Comment by aalekseyev** [comment]
Looks reasonable.
The correctness, of course, depends on if we ever modify (and refresh the Cached_digest for) files during a build after having computed its trace, but I don't think we do that.

Do you have any performance measurements of this change?

**Comment by rgrinberg** [comment]
I'll prepare some benchmarks. Off the top of my head, dune's own build and other common projects aren't representative since they reuse globs that much. @Khady mind testing this?

**Comment by rgrinberg** [comment]
@Khady ping on testing this.

**Comment by Khady** [comment]
Sorry I was on holidays, I didn't have time to look at this.

**Comment by Khady** [comment]
It looks like this version of dune doesn't provide dune.configurator anymore. And one of our dependencies needs it. So I am not able to try this PR currently.

**Comment by rgrinberg** [comment]
> It looks like this version of dune doesn't provide dune.configurator anymore. And one of our dependencies needs it. So I am not able to try this PR currently.

`dune.configurator` has been deprecated to `dune-configurator` a while ago, and dune has maintained this alias for a while. So I'm not sure what the problem is.

**Comment by rgrinberg** [comment]
I did some benchmarking of this myself. I created a setup where

* There's a directory with 10k small files
* There's 20 rules that all depend on the directory above in a glob.

This PR makes clean builds around 2x faster (`0.6s` vs. `1.2s`).

**Comment by aalekseyev** [comment]
Sounds great!

**Review by aalekseyev — APPROVED** [review]

**Comment by Khady** [comment]
My problem was with an old package that didn't declare explicitly the dependency on dune-configurator and was previously installed in the switch only by luck.

I gave a try to dune master after this branch was merged. The clean build of my project takes about the same time than with 2.7.1. The next `dune build` calls (so with nothing to build) take 6.5s with dune master vs 8.5s with dune 2.7.1 so there is a nice improvement even if 6.5s is still too long.

**Comment by rgrinberg** [comment]
Could you profile with memtrace again with master? 6 seconds is indeed quite slow.

**Comment by Khady** [comment]
Yes, I will give it a go

**Comment by rgrinberg** [comment]
While you're at it, could you give us a `perf` report as well? Would be quite useful.

**Pull request merged**
