### PR TITLE
chore: move .opam files into opam/ and bump dune lang

### PR DESCRIPTION
**Pull request by Alizter**
We had to bump the dune lang to 3.8 so I went ahead and bumped it to 3.9. Unless we need a lower bound for any reason?

### CODE REVIEW

**Comment by Alizter** [comment]
@gridbugs I had to tweak the docker file for the bench. Could you take a look?

**Comment by emillon** [comment]
If we don't need 3.9, I think we should stick to 3.8. It makes bisecting a bit easier since we can keep dune 3.8.x for the test-deps for a larger range of commits.

**Comment by rgrinberg** [comment]
Isn't this the same as https://github.com/ocaml/dune/pull/7490?

**Comment by Alizter** [comment]
I need some help with the Windows and MSVC CIs. @jonahbeckford could you take a look?

**Comment by Alizter** [comment]
@rgrinberg Oh I completely missed that! I'll close this.

**Pull request closed without merging**
