### PR TITLE
Fix a bug in Fiber.finalize

### LINKED ISSUE #2958: dune 2.0.0: promotion stops after first rule failure
When shifting RWO [to dune 2.0](https://github.com/realworldocaml/book/pull/3232) and then to [ocaml 4.08](https://github.com/realworldocaml/book/pull/3233), we noticed that `dune build` errors out after failing the first promotion.  Previously, it would continue on until all the promotions were attempted.

This means that we have to iteratively run `dune build` on RWO via `for in in 1 2 3 4 5 6 7 8 9; do dune build || dune promote; done` to get the complete diff.  I believe the dune 1 behaviour is the right one here, since auto-promote also seems to fail with dune 2 in the current state.

### PR DESCRIPTION
**Pull request by ghost**
This fixes #2958.

The problem was the `finally` was called too late in case of error. I also removed `wait_errors` from the API as it's unused and it seems like it could cause the same issue.

### CODE REVIEW

**Comment by aalekseyev** [comment]
Hmm, I find both versions of this function suspicious.

Before this PR, `finally` would run only after all errors are handled, which, as you say, is a bit too late.

After this PR, `finally` runs just before the first error is handled. If the concurrent fibers continue executing after that error, we have `finally` running during execution, which I think contradicts the docs.

Maybe a good behavior is to have `finalize` collect all errors without handling them until all computations are done and then run `finally` and emit all errors to the surrounding handler?

**Comment by diml** [comment]
Indeed, I hadn't considered we would still have code from `f` running after after `finally` has been called. Buffering errors seems like the right thing to do indeed. Doing that.

**Comment by diml** [comment]
I reworked the code. The result is probably not as efficient as it could be, but at least the implementation of `finalize` is straightforward.

I also changed `collect_errors` so that the errors are reraised in the same order as they were originally raised.

**Review by aalekseyev — APPROVED** [review]
Looks good

**Pull request merged**
