### PR TITLE
WIP: add doc about release process

### PR DESCRIPTION
**Pull request by emillon**

### CODE REVIEW

**Review by christinerose — APPROVED** [review]

**Comment by Alizter** [comment]
@emillon Can you explain what this does?

**Comment by Alizter** [comment]
Oh I see it in rich text now:

```mermaid
gitGraph
  commit id: "feat(1)"
  commit id: "feat(2)"
  commit id: "feat(3)"
  branch "3.10-0~alpha"
  commit tag: "3.10.0~alpha1"
  checkout main
  commit id: "fix(1)"
  checkout "3.10-0~alpha"
  cherry-pick id: "fix(1)"
  commit tag: "3.10.0~alpha2"
  checkout main
  commit tag: "3.10.0"
  commit id: "fix(3)"
  commit id: "feat(4)"
  commit id: "fix(4)"
  commit tag: "3.10.0"
  branch 3.10
  cherry-pick id: "fix(3)"
  cherry-pick id: "fix(4)"
  commit tag: "3.10.1"
  checkout main
```

**Review by christinerose — APPROVED** [review]

**Comment by emillon** [comment]
Sorry, I forgot to mark this as draft, but this was intended to be. I'll ask again for reviews once it's ready.

**Comment by emillon** [comment]
I made that a [wiki page](https://github.com/ocaml/dune/wiki/Release-process) instead.

**Pull request closed without merging**
