### PR TITLE
chore(stdune): rename stdune-unstable to stdune

### PR DESCRIPTION
**Pull request by rgrinberg**

### CODE REVIEW

**Comment by rgrinberg** [comment]
@snowleopard might reviewing this one? it's just a trivial rename

**Review by snowleopard — APPROVED** [review]
Looks good!

One thing I don't quite understand is: why does `stdune` live in `otherlibs`? How is it different from, e.g., `fiber` that lives in `src`?

**Comment by rgrinberg** [comment]
> One thing I don't quite understand is: why does stdune live in otherlibs? How is it different from, e.g., fiber that lives in src?

It should be moved to `otherlibs` as well. I don't want to do it right to avoid creating conflicts for Jeremie who is working on fiber.

**Comment by snowleopard** [comment]
> > One thing I don't quite understand is: why does stdune live in otherlibs? How is it different from, e.g., fiber that lives in src?
> 
> It should be moved to `otherlibs` as well. I don't want to do it right to avoid creating conflicts for Jeremie who is working on fiber.

That makes sense but I still don't understand the meaning of "other" in the `otherlibs` and how we decide what to put there and what under `src`.

**Comment by rgrinberg** [comment]
This is the intention:

* Otherlibs is for things that are published outside of dune (configurator, stdune, etc.)
* src is for things that are dune specific.

I think the distinction is a little arbitrary and would prefer to just have a separate directory for every package. I never get  a good opportunity to do this refactor however as it would cause rebase heartbreak for everyone.

**Comment by snowleopard** [comment]
Got it, thanks! Yes, I would also prefer to have everything in one place.

**Comment by jeremiedimino** [comment]
If it's just file moves the rebase should be alright. However, are you thinking of creating many new toplevel directories?

I'm not a big fan of projects that have a ton of files and directories at the toplevel. I find them difficult to navigate, especially when getting started. It's especially annoying on github as you end up having to scroll down several pages in order to see the readme.

**Comment by snowleopard** [comment]
Agreed, I'd prefer to just have something like `lib` at the top-level. I guess `vendor` could also go there as `lib/vendored`.

**Comment by rgrinberg** [comment]
Sure I don't mind a top level directory. Something like:

src/<pkg>/dune
sec/<pkg>/test

Etc.

**Comment by jeremiedimino** [comment]
Did you mean `src//test`?

I would still expect to have a toplevel `test` directory containing all the test of `dune` as a software, i.e. most of our cram tests. Unit tests could go closer to what they test.

**Comment by rgrinberg** [comment]
Whoops, I fixed the formatting of the last comment.

What's the advantage of a toplevel test directory? It complicates running the set of tests for a particular package. I find it more useful to organize tests by what they're testing and not the kind of test.

**Comment by jeremiedimino** [comment]
> Whoops, I fixed the formatting of the last comment.

`sec` is a typo, right?

So, for fiber we'd have:

```
src/fiber/fiber.{ml,mli}
src/fiber/dune
src/fiber/test/fiber_tests.{ml,mli}
src/fiber/test/dune
```

?

> I find it more useful to organize tests by what they're testing and not the kind of test.

Agreed. I'm just highlighting that I expect main `dune` package to be inlined at the toplevel rather than live at the same level of other packages such as stdune or dune-configurator.

**Comment by rgrinberg** [comment]
> So, for fiber we'd have:

That's exactly what I meant. However, I would also expect cram tests to live under the test directory as well. So let's say for dune-action-plugin:
```
src/dap/dap.ml
src/dap/test/unit/dap_tests.ml
src/dap/test/cram/{foo.t,bar.t,...}
```

> Agreed. I'm just highlighting that I expect main dune package to be inlined at the toplevel rather than live at the same level of other packages such as stdune or dune-configurator.

So all in all:

```
lib/<pkg>/ # libraries
dune/ # dune itself
```

And the tests would live in the `test/` subdirectory of a package respectively.

**Comment by jeremiedimino** [comment]
Where would `src/dune_engine/build_system.ml` or `bin/main.ml` live?

**Comment by rgrinberg** [comment]
I'd propose this way:

dune/dune_engine/build_system.ml
dune/main.ml

**Comment by jeremiedimino** [comment]
I find it odd to have a directory `dune` inside the `dune` repo. We'd have `dune/dune/...` which feels repetitive. IMO, the source code for `dune` should be inside a `src` directory in the `dune` repo.

**Comment by snowleopard** [comment]
> IMO, the source code for `dune` should be inside a `src` directory in the `dune` repo.

Indeed. Using `src/dune_engine` for Dune sources and `test` for whole-Dune tests seems good to me.

**Comment by rgrinberg** [comment]
I think being uniform is more important than being pleasing to the eye usually. A lot of dune metadata could be made redundant and tooling simplified if we introduced some conventions.

Sure there's a little repetitiveness, but the two identifiers you're pointing out are of a different kind. One "dune" is the repository name, and the other is the name of a package. If we were more accurate, the name of the repo would be something like dune-monorepo as it includes a bunch of packages. Where would you expect the tests for the dune package to live? In the src directory as well?

**Comment by jeremiedimino** [comment]
It seems that we are thinking of the dune repository slightly differently. I think of the dune repository as the repository for the dune software + a few auxiliary packages, while it seems to me that you are thinking of the dune repository as a repository for a collection of packages and one of them is dune.

I don't think the organisation I suggest prevents from simplifying the tooling. IIRC, to simplify the tooling we need to associate a package to a directory. But we could still do that with what I propose. We would have:

- package fiber -> src/fiber
- package dune-configurator -> src/dune-configurator
- package dune -> .

It just means that we would allow packages to live inside others, which is in line with what we do for workspaces and projects: a project can live inside another project.

> Where would you expect the tests for the dune package to live? In the src directory as well?

I would put `src` and `test` as the same level. In my head:

- `src` is for the source code of the software
- `test` is for the tests of the software

So having `test` inside `src` seems a bit odd to me.

**Comment by rgrinberg** [comment]
> I would put src and test as the same level. In my head:

In this case, you will no longer be able to associate one directory with every package. The association I had in mind would include the tests for a package (unless you want to split tests into a separate package)

**Comment by jeremiedimino** [comment]
If you want to put packages inside `src`, yes that wouldn't work with what I am saying. You'd have to use another structure. Maybe `pkg/<name>/src` and `pkg/<name>/test`.

Anyway, putting `src` and `test` at the same level or inlining the `dune` package are my opinions. Since many people are working on the codebase, it'd be good to ask what everyone thinks before moving directories around. If you'd like to push for this, could you prepare a concrete proposal?

**Comment by rgrinberg** [comment]
Sure, let's hear what others are saying. @bobot @nojb @voodoos 

By the way, I'm not really concerned with the concrete layout. As long as we follow the rule of associating one directory per package, I'm fine with any layout.

**Comment by voodoos** [comment]
Personally I don't feel the need for a reorganization of the current layout, but I am not against the proposed changes. I am just not sure what would be the benefits.

I also personally like the fact that the dune package is somehow more visible than the others with toplevel `src` and `test` directory. It means that a guest visiting the repo is implicitly guided towards the core source code.

**Comment by rgrinberg** [comment]
> Personally I don't feel the need for a reorganization of the current layout, but I am not against the proposed changes either. I am just not sure what would be the benefits.

The benefit is thus:
* `dune runtest <pkg dir>` can now run all the tests for a particular package
* In the future, we can add a more implicit mode where `package` fields can be dropped where they can be inferred from the directory.
* The interpretation of `--only-packages` can be formalized.

**Pull request merged**
