### PR TITLE
fix segfault on empty package name

### LINKED ISSUE #3253: segfault
Hi,

On [this project](https://git.zapashcanon.fr/zapashcanon/dddddml/src/branch/dunesegfault) (make sure you are on the `dunesegfault` branch), when running `dune build @all` I've got:

```txt
Internal error, please report upstream including the contents of _build/log.
Description:
  ("Invalid Package.Name.t", { s = "" })
Raised at file "src/stdune/code_error.ml", line 9, characters 30-62
Called from file "src/dune/findlib/findlib.ml", line 521, characters 31-59
...
```
It's on ocaml `4.09.0` and dune `2.4.0`.

Here's the content of `_build/log`:

```txt
# dune build @all
# OCAMLPARAM: unset
# Workspace root: /home/zapashcanon/dev/ml/dddddml
$ /usr/bin/nproc > /tmp/dunea5e29c.output 2> /dev/null
# Auto-detected concurrency: 8
# disable binary cache
$ /home/zapashcanon/.config/opam/4.09.0/bin/ocamlc.opt -config > /tmp/dune1fdcbd.output
# Dune context:
#  { name = "default"
#  ; kind = "default"
#  ; profile = Dyn
#  ; merlin = true
#  ; for_host = None
#  ; fdo_target_exe = None
#  ; build_dir = "default"
#  ; toplevel_path =
#      Some External "/home/zapashcanon/.config/opam/4.09.0/lib/toplevel"
#  ; ocaml_bin = External "/home/zapashcanon/.config/opam/4.09.0/bin"
#  ; ocaml = Ok External "/home/zapashcanon/.config/opam/4.09.0/bin/ocaml"
#  ; ocamlc = External "/home/zapashcanon/.config/opam/4.09.0/bin/ocamlc.opt"
#  ; ocamlopt =
#      Ok External "/home/zapashcanon/.config/opam/4.09.0/bin/ocamlopt.opt"
#  ; ocamldep =
#      Ok External "/home/zapashcanon/.config/opam/4.09.0/bin/ocamldep.opt"
#  ; ocamlmklib =
#      Ok External "/home/zapashcanon/.config/opam/4.09.0/bin/ocamlmklib.opt"
#  ; env =
#      map
#        { "INSIDE_DUNE" : "/home/zapashcanon/dev/ml/dddddml/_build/default"
#        ; "OCAMLFIND_IGNORE_DUPS_IN" :
#            "/home/zapashcanon/dev/ml/dddddml/_build/install/default/lib"
#        ; "OCAMLPATH" :
#            "/home/zapashcanon/dev/ml/dddddml/_build/install/default/lib"
#        ; "OCAML_COLOR" : "always"
#        ; "OPAMCOLOR" : "always"
#        }
#  ; findlib_path = [ External "/home/zapashcanon/.config/opam/4.09.0/lib" ]
#  ; arch_sixtyfour = true
#  ; natdynlink_supported = true
#  ; supports_shared_libraries = true
#  ; ocaml_config =
#      { version = "4.09.0"
#      ; standard_library_default =
#          "/home/zapashcanon/.config/opam/4.09.0/lib/ocaml"
#      ; standard_library = "/home/zapashcanon/.config/opam/4.09.0/lib/ocaml"
#      ; standard_runtime = "the_standard_runtime_variable_was_deleted"
#      ; ccomp_type = "cc"
#      ; c_compiler = "gcc"
#      ; ocamlc_cflags = [ "-O2"; "-fno-strict-aliasing"; "-fwrapv"; "-fPIC" ]
#      ; ocamlopt_cflags = [ "-O2"; "-fno-strict-aliasing"; "-fwrapv" ]
#      ; bytecomp_c_compiler =
#          [ "gcc"
#          ; "-O2"
#          ; "-fno-strict-aliasing"
#          ; "-fwrapv"
#          ; "-fPIC"
#          ; "-D_FILE_OFFSET_BITS=64"
#          ; "-D_REENTRANT"
#          ]
#      ; bytecomp_c_libraries = [ "-lm"; "-ldl"; "-lpthread" ]
#      ; native_c_compiler =
#          [ "gcc"
#          ; "-O2"
#          ; "-fno-strict-aliasing"
#          ; "-fwrapv"
#          ; "-D_FILE_OFFSET_BITS=64"
#          ; "-D_REENTRANT"
#          ]
#      ; native_c_libraries = [ "-lm"; "-ldl" ]
#      ; cc_profile = []
#      ; architecture = "amd64"
#      ; model = "default"
#      ; int_size = 63
#      ; word_size = 64
#      ; system = "linux"
#      ; asm = [ "as" ]
#      ; asm_cfi_supported = true
#      ; with_frame_pointers = false
#      ; ext_exe = ""
#      ; ext_obj = ".o"
#      ; ext_asm = ".s"
#      ; ext_lib = ".a"
#      ; ext_dll = ".so"
#      ; os_type = "Unix"
#      ; default_executable_name = "a.out"
#      ; systhread_supported = true
#      ; host = "x86_64-pc-linux-gnu"
#      ; target = "x86_64-pc-linux-gnu"
#      ; profiling = false
#      ; flambda = false
#      ; spacetime = false
#      ; safe_string = false
#      ; exec_magic_number = "Caml1999X026"
#      ; cmi_magic_number = "Caml1999I026"
#      ; cmo_magic_number = "Caml1999O026"
#      ; cma_magic_number = "Caml1999A026"
#      ; cmx_magic_number = "Caml1999Y026"
#      ; cmxa_magic_number = "Caml1999Z026"
#      ; ast_impl_magic_number = "Caml1999M026"
#      ; ast_intf_magic_number = "Caml1999N026"
#      ; cmxs_magic_number = "Caml1999D026"
#      ; cmt_magic_number = "Caml1999T026"
#      ; natdynlink_supported = true
#      ; supports_shared_libraries = true
#      ; windows_unicode = false
#      }
#  }
```

Changing [this line](https://git.zapashcanon.fr/zapashcanon/dddddml/src/branch/dunesegfault/src/dune#L15) to be `  (pps bisect_ppx -conditional -exclude-file exclude)))` (removing the dot of `.exclude`) seems to fix the issue.

### PR DESCRIPTION
**Pull request by zapashcanon**
This is a WIP PR attempting to fix #3253. If someone is willing to provide some guidance to me, I'm all for it. :)

I found two ways to get a segfault, slightly related. Here's the dune file needed for the first one:

```
(library
 (name hello)
 (preprocess (pps .iaminvalid)))
```
With the stack trace, I found that it's caused by a call to `Lib_name.split`. I found three calls to `split`, I wrapped them with a `try ... with _ -> failwith ...` and numbered them 1, 2 and 3.

The one with number 2 is responsible for the failure (`dune build` gives `Error: exception Failure("invalid package name 2")`).

What happens is that we try to split `.iaminvalid`, but as the package name is empty, it fails.

As I'm not familiar with the code base and error handling in it, I have two questions. Is the call to `Lib_name.split` the good place to check that the package name is not empty or should I do this before ? How should I report the error ?

Once this is resolved, there are other things to fix: are the other calls (with number 1 and 3) to `split` safe ? How to fix the second segfault that you get with this file:

```
(library
 (name hello)
 (public_name .iaminvalid))
```

It looks similar but isn't the result of a call to `split`. Which leads to think you can also get similar errors using an invalid name in other places, that would need to be checked.

I would also like to add test case for these.

### CODE REVIEW

**Comment by rgrinberg** [comment]
A good start would be to add validation to library names. A library name that start with a `.` is invalid and we should validate this. To fix this, we need to fix this function to do the validation: https://github.com/rgrinberg/jbuilder/blob/expander-less-params/src/dune/lib_name.ml#L77

**Comment by zapashcanon** [comment]
It looks like you're looking at an outdated code ? In master, the check is already done (but that doesn't change anything, I guess it just prevents the error from happening in cases like:

```
(library
  (name .hello))
```

Which I tried before opening the PR and is indeed correctly catched:

```
Error: ".hello" is an invalid library name.
Library names must be non-empty and composed only of the following
characters: 'A'..'Z', 'a'..'z', '_' or '0'..'9'.
```

The thing is that, in the `name` field, you can't have `a.b` as you just wand a library name (no package).

In the cases I'm describing (`public_name` and the pps one), this could be something like `a.b`, but in the case where `a` is the empty string, we currently segfault when we should be reporting an error.

**Comment by rgrinberg** [comment]
The fix looks good. The debugging code needs to be removed however.

**Comment by zapashcanon** [comment]
Will do. Should I add a test ?

**Comment by rgrinberg** [comment]
Tests wouldn't hurt.

**Comment by rgrinberg** [comment]
I've converted this PR to draft as it seems like you're still working on it. Let us know when it's ready for review!

**Comment by zapashcanon** [comment]
@rgrinberg, I added a test and I think this is ready to get merged ; sorry for the delay !

**Comment by rgrinberg** [comment]
Thanks!

**Pull request merged**
