### PR TITLE
Fix 1918

### PR DESCRIPTION
**Pull request by rgrinberg**
This bug was not introduced in 1.8, but it's fairly critical so I will make a release as soon as it's merged.

### CODE REVIEW

**Comment by rgrinberg** [comment]
PS, this PR also omits empty versions. Those don't seem to be useful.

**Review by emillon — APPROVED** [review]

**Comment by aalekseyev** [comment]
FWIW, I'm a bit confused:
- Why is empty string a valid version at all? If we want to treat it the same way as None (I don't know why), isn't it better to normalize it on the way in rather than the way out?
- How was the bug introduced and what's the bug?

That said, I can't think of any specific problem with this patch so feel free to merge.

**Review by aalekseyev — APPROVED** [review]

**Comment by rgrinberg** [comment]
> Why is empty string a valid version at all? If we want to treat it the same way as None (I don't know why), isn't it better to normalize it on the way in rather than the way out?

That's a good point. Perhaps we should just change the type of version to `""` and have that mean the empty version. How about I just revert the change where I coerce `""` to `None`, and we can discuss it separately. The gist of it is that the version can optionally be provided by the user, but unfortunately, we never validated versions given from the user.

> How was the bug introduced and what's the bug?

When we introduced the `dune-package` format, the serialization code for versions was faulty. In particular, it did not handle empty versions which the user can in fact manually provide.

**Comment by aalekseyev** [comment]
I see. Thanks.

> How about I just revert the change where I coerce "" to None

Yeah, I would weakly prefer that.

**Pull request merged**
