### PR TITLE
New fiber implementation

### PR DESCRIPTION
**Pull request by rgrinberg**
Extracted from #5230

### CODE REVIEW

**Comment by snowleopard** [comment]
I like the new implementation but I'm a bit worried that we merged it without first evaluating the performance impact on our internal builds. I'll run some benchmarks when I'm back from vacation. Fortunately, it seems easy to revert this PR if we hit a problem.

**Comment by rgrinberg** [comment]
Ah yes that's a good point. Fwiw the micro benchmarks looked really good.

**Comment by snowleopard** [comment]
> Fwiw the micro benchmarks looked really good.

Yes, I remember seeing some good preliminary results. Do you have the before/after tables for this PR? (Can't run the benchmarks at the moment but curious to look at the latest figures.)

**Comment by rgrinberg** [comment]
Here's before:

```
┌───────────────────────────────────────────────────────┬──────────┬──────────┬───────────┬───────────┬────────────┐
│ Name                                                  │ Time/Run │  mWd/Run │  mjWd/Run │  Prom/Run │ Percentage │
├───────────────────────────────────────────────────────┼──────────┼──────────┼───────────┼───────────┼────────────┤
│ [bench/micro/fiber_bench.ml] bind                     │   7.28us │  21.06kw │     4.49w │     4.49w │     13.28% │
│ [bench/micro/fiber_bench.ml] ivar                     │  53.48us │  56.08kw │    16.61w │    16.61w │     97.61% │
│ [bench/micro/fiber_bench.ml] Var.set                  │  38.69us │  32.06kw │ 1_268.64w │ 1_268.64w │     70.61% │
│ [bench/micro/fiber_bench.ml] Var.get                  │  15.28us │  29.09kw │     8.31w │     8.31w │     27.89% │
│ [bench/micro/fiber_bench.ml] catching exceptions      │  19.87us │  21.15kw │     9.67w │     9.67w │     36.27% │
│ [bench/micro/fiber_bench.ml] installing handlers      │  54.79us │ 106.06kw │    37.96w │    37.96w │    100.00% │
│ [bench/micro/fiber_bench.ml] Fiber.fork_and_join      │  39.65us │  39.06kw │ 1_067.05w │ 1_067.05w │     72.37% │
│ [bench/micro/fiber_bench.ml] Fiber.fork_and_join_unit │  22.37us │  23.06kw │   315.95w │   315.95w │     40.84% │
│ [bench/micro/fiber_bench.ml] Fiber.parallel_iter      │  10.24us │   5.08kw │     1.02w │     1.02w │     18.70% │
│ [bench/micro/fiber_bench.ml] Fiber.parallel_map       │  43.44us │  12.07kw │ 3_154.67w │ 2_153.67w │     79.29% │
│ [bench/micro/fiber_bench.ml] Fiber.Map.parallel_iter  │  18.99us │  10.08kw │     2.26w │     2.26w │     34.66% │
│ [bench/micro/fiber_bench.ml] Fiber.Map.parallel_map   │  53.28us │  33.08kw │ 1_551.55w │ 1_551.55w │     97.25% │
└───────────────────────────────────────────────────────┴──────────┴──────────┴───────────┴───────────┴────────────┘
```

And here's after:

```
┌───────────────────────────────────────────────────────┬──────────┬─────────┬───────────┬───────────┬────────────┐
│ Name                                                  │ Time/Run │ mWd/Run │  mjWd/Run │  Prom/Run │ Percentage │
├───────────────────────────────────────────────────────┼──────────┼─────────┼───────────┼───────────┼────────────┤
│ [bench/micro/fiber_bench.ml] bind                     │   8.78us │ 21.05kw │     2.09w │     2.09w │     18.34% │
│ [bench/micro/fiber_bench.ml] ivar                     │  37.34us │ 59.06kw │    13.64w │    13.64w │     78.05% │
│ [bench/micro/fiber_bench.ml] Var.set                  │  47.85us │ 42.05kw │ 1_485.86w │ 1_485.86w │    100.00% │
│ [bench/micro/fiber_bench.ml] Var.get                  │  18.97us │ 32.09kw │     6.48w │     6.48w │     39.65% │
│ [bench/micro/fiber_bench.ml] catching exceptions      │  23.16us │ 20.11kw │   237.19w │   237.19w │     48.41% │
│ [bench/micro/fiber_bench.ml] installing handlers      │  38.20us │ 77.05kw │    13.62w │    13.62w │     79.84% │
│ [bench/micro/fiber_bench.ml] Fiber.fork_and_join      │  46.18us │ 39.05kw │ 1_070.61w │ 1_070.61w │     96.51% │
│ [bench/micro/fiber_bench.ml] Fiber.fork_and_join_unit │  11.91us │ 18.05kw │     1.95w │     1.95w │     24.90% │
│ [bench/micro/fiber_bench.ml] Fiber.parallel_iter      │   8.94us │ 10.06kw │     1.40w │     1.40w │     18.68% │
│ [bench/micro/fiber_bench.ml] Fiber.parallel_map       │  18.95us │ 11.07kw │ 1_021.22w │    20.22w │     39.60% │
│ [bench/micro/fiber_bench.ml] Fiber.Map.parallel_iter  │  17.65us │ 26.07kw │     7.28w │     7.28w │     36.89% │
│ [bench/micro/fiber_bench.ml] Fiber.Map.parallel_map   │  36.78us │ 25.09kw │ 1_297.30w │   296.30w │     76.88% │
└───────────────────────────────────────────────────────┴──────────┴─────────┴───────────┴───────────┴────────────┘
```

**Comment by snowleopard** [comment]
Thanks! The biggest change here is `Fiber.parallel_map` that apparently got 2.3x faster. Do you know if this is a meaningful change or a result of a new optimisation that could have also been applied to the previous Fiber representation?

**Comment by snowleopard** [comment]
I'm seeing a huge (like 100x-ish) regression internally with the most recent version of Dune, and this PR is the greatest suspect for now.

**Comment by snowleopard** [comment]
After reverting these changes internally I'm still seeing the regression. Sorry for jumping to conclusions! 

Now trying to benchmark specifically this PR on our internal builds.

**Comment by snowleopard** [comment]
OK, benchmarking this change in isolation shows a noticeable 10-20% performance regression for some large builds, and an opposite change (i.e. improvement) for some smaller builds, which I think is acceptable for now.

There is hopefully some scope for further optimisation of the new implementation.

**Comment by rgrinberg** [comment]
> OK, benchmarking this change in isolation shows a noticeable 10-20% performance regression for large incremental builds,

Is this for all large builds, or only the ones that exhibit the memory leak?

**Comment by snowleopard** [comment]
The memory leak that I mentioned isn't related to this PR. It's something else that happened in `main` in the last month or so. I'll investigate.

This PR only contributes small +/- 10-20% changes to incremental null builds.

**Pull request merged**
