### PR TITLE
Fix main module name handling for variants

### PR DESCRIPTION
**Pull request by rgrinberg**
* the main module name should be inherited for implementations of virtual libraries
* main module name should be optional as it isn't present for unwrapped libraries

`Library_modules.t` still isn't looking ideal. `alias_module` and `main_module_name` should both be either present or absent. I can introduce a type like:

```
module Library_module : sig
  module Wrapped : sig
    type t =
      { module_ : 
      }
  end
  type t =
    { ..
    ; wrapped : Wrapped.t option
    }
end 
```

to reflect this property. Also, `Library_module.make` should be split to handle the wrapped and unwrapped cases separately. This would make things a lot cleaner I think.

### CODE REVIEW

**Comment by rgrinberg** [comment]
> Library_modules.t still isn't looking ideal. alias_module and main_module_name should both be either present or absent. I can introduce a type like:

Actually this is wrong. There's a case with `(wrapped true)` where the alias module might not exist. This is the case when there's only a single module in the library and it's named after the main module.

**Comment by rgrinberg** [comment]
@diml this is ready for review now. The last commit simplifies things quite a bit. I'm still to open suggestions on how to simplify things. For example, `alias_module` being `Some` should guarantee that `main_module_name` exists, but our type doesn't reflect that.

**Comment by diml** [comment]
Have you tried a type that encode exactly the possible cases? i.e.:

```ocaml
type t =
  | Single_module of Module.t
  | Unwrapped of Module.Name_map.t
  | Wrapped of { main_module : Module.t; alias_module : Module.t; modules : Module.Name_map.t }
```

**Comment by rgrinberg** [comment]
@diml yeah that's a good idea. I've made the type abstract to make that change easier. Would like to do it in a separate PR if you don't mind.

**Comment by diml** [comment]
Looks good, however I'm slightly worried about accessing the library database to compute the directory contents. While it's fine now, it will become an issue when we make polling builds scale to large workspaces: it means that when you modify a library file all the directories contents will be invalidated.

Could you try using a type like this for the main module name:

```ocaml
type t = None | Some of Module.Name.t | Inherited
```

This mean that we would have to work a bit more whenever we want to access the main module name.

**Comment by rgrinberg** [comment]
Sure, I'll give that type a try.

**Comment by rgrinberg** [comment]
@diml actually, I'm not sure how this would work. Without the main module name, we can't really wrap the modules properly, can't setup the transition modules, etc.

**Comment by diml** [comment]
The idea would be that when it's `Inherited`, we would resolve the virtual library when we want to access the main module name.

**Comment by rgrinberg** [comment]
> The idea would be that when it's Inherited, we would resolve the virtual library when we want to access the main module name.

I think that's how it currently works. Unless you mean you'd like the resolution to be done by the caller.

**Comment by rgrinberg** [comment]
With that being said, it's not really correct to pass the `~scope` via Dir_contents (since it makes the dir based caching wrong). We could somehow make `Library_modules` take the scope as input instead.

**Comment by diml** [comment]
That's the idea. Basically, if you need to access the library database to compute `Lib_modules.t`, then whenever the libdb changes you need to recompute all the `Lib_modules.t`. If we only store a symbolic value in `Lib_modules.t` and let the caller resolve it, then we don't need to recompute the `Lib_modules.t` when the libdb changes.

**Comment by rgrinberg** [comment]
Okay, I see. But then `Lib_modules.t` would be the one that would need to change (and not the main module name). For example, it would need to be something like:

```
module Lib_modules : sig
  type t' = { ... }
  type t =
    | Resolved of t'
    | Inherited_from of Loc.t * Lib_name.t * (Module.Name.t -> t')

  val resolve : t -> scope:Scope.t -> t'
end
```

Or something like that

**Comment by rgrinberg** [comment]
> While it's fine now, it will become an issue when we make polling builds scale to large workspaces: it means that when you modify a library file all the directories contents will be invalidated.

Btw, isn't this already an issue because of how we're doing the closure outside the arrow? For example, renaming a library will invalidate the build rules for all libraries.

**Comment by diml** [comment]
> The other fields all need main_module_name to be resolved to be calculated.

Ah, yes that's true

> Btw, isn't this already an issue because of how we're doing the closure outside the arrow? For example, renaming a library will invalidate the build rules for all libraries.

Yes, that'll be an issue. We won't need to go back to doing the closure in the arrow, however we might need to track a bit more what part the library database the code generating the rules accesses. Thinking about it again, this might solve this problem as well.

**Pull request merged**
