### PR TITLE
fix(staged_pps): expand path relative to root

### LINKED ISSUE #8158: regression: staged_pps in main
Since #8109, `(staged_pps)` is broken in some cases. This can be reproduced by trying to build `frama-c` for example.

```
File "src/libraries/utils/unicode.ml", line 1:
Error: I/O error: ../.ppx/40f2e64236f938e28b7a041b2e0f4895/ppx.exe --as-ppx --cookie 'library-name="frama_c_kernel"' '/tmp/build_2b39c9_dune/camlppx57b0a7' '/tmp/build_2b39c9_dune/camlppx5a05f1'
File "src/.frama_c_kernel.objs/_unknown_", line 1, characters 0-0:
sh: 1: ../.ppx/40f2e64236f938e28b7a041b2e0f4895/ppx.exe: not found
File "src/libraries/datatype/unmarshal_z.ml", line 1:
Error: I/O error: ../.ppx/40f2e64236f938e28b7a041b2e0f4895/ppx.exe --as-ppx --cookie 'library-name="frama_c_kernel"' '/tmp/build_2b39c9_dune/camlppx71944c' '/tmp/build_2b39c9_dune/camlppxeb3e01'
File "src/.frama_c_kernel.objs/_unknown_", line 1, characters 0-0:
sh: 1: ../.ppx/40f2e64236f938e28b7a041b2e0f4895/ppx.exe: not found
```

### PR DESCRIPTION
**Pull request by emillon**
Fixes #8158

This is an error introduced in #8109, not part of a release.

### CODE REVIEW

**Comment by Alizter** [comment]
Doesn't have to be in this PR, but do we not have any tests touching this? It would be good to have some for the future at least.

**Comment by emillon** [comment]
We have tests but only with libs at the root. This one is on me; I checked that `dir` and `ctx.dir` were equal in the test suite so I tried to simplify it further but that assertion doesn't hold in general.

**Review by rgrinberg — APPROVED** [review]
A test would be useful indeed

**Review by rgrinberg — APPROVED** [review]
A test would be useful indeed

**Review by Alizter — APPROVED** [review]

**Pull request merged**
