### PR TITLE
chore: remove pointless polymorphic compare

### PR DESCRIPTION
**Pull request by rgrinberg**
easily replaced by String.compare

### CODE REVIEW

**Comment by rgrinberg** [comment]
Not sure I like the same `fast_sort`, but at least it's familiar to those from stdlib. Maybe `unstable_sort` is a better name for stdune?

**Comment by snowleopard** [comment]
> Not sure I like the same `fast_sort`, but at least it's familiar to those from stdlib. Maybe `unstable_sort` is a better name for stdune?

Wait, it's actually stable sort, it's defined as follows in the stdlib:

```ocaml
let fast_sort = stable_sort
```

I would just call it `stable_sort` and use it. I find the name `fast_sort` pretty misleading.

**Review by snowleopard — APPROVED** [review]
Looks fine but I'd use `stable_sort` instead of `fast_sort`.

**Comment by rgrinberg** [comment]
I just made a normal sort. The stability here is pointless anyway.

**Comment by snowleopard** [comment]
Agreed!

**Pull request closed without merging**
