### PR TITLE
fix(coq): pass correct flags to coqdep when building boot libs

### LINKED ISSUE #7909: [coq] Composition with (boot) theories is not working in Dune 3.8
Steps to reproduce:
```
$ git clone https://github.com/coq/coq.git
$ cd coq && cp theories/dune.disabled theories/dune
$ dune build @default
```
result is that `-boot` flag is missing from the first coqdep call:
```
File "theories/dune", line 2, characters 0-588:
 2 | (coq.theory
 3 |  (name Coq)
 4 |  (package coq-stdlib)
....
28 | 
29 |    coq-core.plugins.ssreflect
30 |    coq-core.plugins.derive))
cannot guess a path for Coq libraries; please use -coqlib option or ensure you have installed the package containing Coq's stdlib (coq-stdlib in OPAM) If you intend to use Coq without a standard library, the -boot -noinit options must be used.
```
This can only be tested up to `(lang coq 0.6)`, as newer lang versions are blocked https://github.com/ocaml/dune/issues/7908

### PR DESCRIPTION
**Pull request by Alizter**
fix #7909

I've tested the reproduction in #7909 and it works. I will not add a test for this.

- [x] changelog

### CODE REVIEW

**Comment by ejgallego** [comment]
Thanks @Alizter , will review (and hopefully merge) ASAP.

**Comment by Alizter** [comment]
@ejgallego feel free to takeover. It seemed to work for me.

**Comment by ejgallego** [comment]
> @ejgallego feel free to takeover. It seemed to work for me.

I see CI / Coq test suite is broken, isn't it?

**Comment by Alizter** [comment]
@ejgallego only updating thr new flags.

**Comment by Alizter** [comment]
If this is the right fix, please resurrect.

**Comment by ejgallego** [comment]
> @ejgallego only updating the new flags.

I see a truly broken test-case and a few suspicious things, don't you?

It seems that combining `-boot` (>= 0.8) and theories that doesn't ( < 0.8) could turn out the be quite tricky, see for example the discussion at https://coq.zulipchat.com/#narrow/stream/240550-Dune-devs-.26-users/topic/Adding.20transitive.20deps.20into.20theories

**Pull request closed without merging**
