### PR TITLE
raise error when using describe pp command with staged_pps

### LINKED ISSUE #6945: `dune describe pp` doesn't work with staged pps
`dune describe pp foo.ml` doesn't work when a staged pps is used. Example:

```ocaml
type t = { foo : string } [@@deriving ppx_yojson]
```

with dune file:
```lisp
 (preprocess (pps ppx_deriving_yojson))
```
works fine, but with dune file:
```lisp
 (preprocess (staged_pps ppx_deriving_yojson))
```
it produces the input file

### PR DESCRIPTION
**Pull request by tatchi**
This is my attempt to fix https://github.com/ocaml/dune/issues/6945; apologies in advance if I did some silly things 😅

### CODE REVIEW

**Comment by rgrinberg** [comment]
LGTM. Do you want to try fixing this in this PR?

**Comment by tatchi** [comment]
> LGTM. Do you want to try fixing this in this PR?

Do you mean that `describe pp` should work with `staged-pps`? According to https://github.com/ocaml/dune/issues/6945#issuecomment-1408317642, it wasn't very clear if dune should support this scenario. cc @emillon

**Comment by rgrinberg** [comment]
Personally, I don't see the issue with running `-dsource` (with the appropriate `-stop-after-x`). Sure, it's a bit ugly, but there's no reason why we shouldn't support it.

**Comment by tatchi** [comment]
Okay, let me try this, but if you don't mind in another PR.

**Pull request merged**
