### PR TITLE
Upgrade ocamlformat to 0.12

### PR DESCRIPTION
**Pull request by emillon**
Hi,

This PR upgrades ocamlformat to 0.12.

As usual, this comes with some formatting changes - sorry about that.
In order to minimize the diff I split the PR in several commits :
- something that minimizes the diff on the current code base (+100 -70, not too bad)
- further commits that align the codebase with the new defaults (+800 -1100 followed by +90-130)

Let me expand a bit: before ocamlformat 0.12, there was a bug with how margin is computed in some cases, causing it to break a character before. This means that the default behaviour of ocamlformat 0.11 is close to ocamlformat 0.12 with margin=79. This is why I changed the value in a first commit and removed it in another one.

Similarly, there's now a special handling for expressions like `e1 >>= fun x -> e2`: if `e2` is long enough, it will now keep `>>= fun x ->` at the end of the line. Same strategy here: I opted out of this behavior in the "upgrade" commit and added an extra commit that gets back to the new default.

I think that both of these new behaviors are fixes and improve the style of the code base, so I'm in favor of keeping them, but we can remove it from the PR (keeping churn a bit lower, but diverging from the defaults).

What do you think?

### CODE REVIEW

**Comment by rgrinberg** [comment]
Looks good to me. Is it possible to fix the indentation to be at most 2 spaces now?

**Comment by emillon** [comment]
Thanks, I'll rebase and merge.

> Is it possible to fix the indentation to be at most 2 spaces now?

Some cases have been fixes in 0.12 but it's not great yet. It's something we want to improve in 0.13.

**Comment by rgrinberg** [comment]
@emillon don't forget to announce this in #dune-dev once you merge. So that we people don't forget to upgrade.

**Comment by diml** [comment]
@emillon can this be merged? It'd be good to move to the latest ocamlformat so that we can remove our pins on ocamlformat.

**Comment by emillon** [comment]
yes, I'll rebase and merge!

**Pull request merged**
