### PR TITLE
Improve error message for `dune utop`

### PR DESCRIPTION
**Pull request by emillon**
It's possible to be a bit more descriptive, but at least this does not leak the internal implementation in the error message.

### CODE REVIEW

**Comment by emillon** [comment]
cc @dra27

**Review by ghost — APPROVED** [review]

**Comment by emillon** [comment]
Is there an easy way to build a map from source directory to libraries? It'd be nice to display:

```
You can try dune utop DIR when DIR is one of the following:
- dir_a (contains lib_a, lib_b, internal_lib)
- dir_b (contains lib_c)
```

That seems possible through `Super_context.{public_libs,internal_lib_names}`, but there's a lot of plumbing involved.

**Comment by diml** [comment]
You could also scan the list of stanzas, they are already grouped by directory.

**Comment by rgrinberg** [comment]
I wonder if the correct behavior is to make `$ dune utop` a little more clever and work "recursively". It's a bit annoying to have to specify the exact directory in some of these situations. In any case, I'm not sure how to implement so we might have to settle on a better error message for now.

**Review by rgrinberg — APPROVED** [review]

**Comment by emillon** [comment]
Thanks. We can improve the error message later, it's already better than it was before. Thanks @dra27 for the report!

**Pull request merged**
