### PR TITLE
Spawned processes have inherited dune's signal mask SIGINT, SIGQUIT and SIGTERM

### PR DESCRIPTION
**Pull request by camlspotter**
This patch simply revert the change to `src/spawn.ml` of d895a1b5b8700.

In Tezos, we have several tests of our server:  we launch it, sends some requests, then terminate it by sending SIGTERM.  These tests worked fine until we change `dune` from `1.6.x` to `1.7.x`: the server never receives SIGTERM with `dune.1.7.x`.

We found that it is because child processes launched by `dune.1.7.x` inherit `dune`'s signal mask, which blocks SIGINT, SIGQUIT and SIGTERM.  Their signal masks must be reset before calling `execvp`.

### CODE REVIEW

**Comment by diml** [comment]
Starting the sub-processes with a clear signal mask seems good. However, that also mean that when you press Control+C in the terminal, it only kills one of the sub-process rather than the whole build :/

**Comment by diml** [comment]
I guess, we could at least unblock SIGTERM and keep SIGINT and SIGQUIT blocked. What do you think?

**Comment by abate** [comment]
`SIGTERM` looks good to me. At the moment as workaround we are using `SIGUSR1`, that's clearly not meant to kill a process ...

**Comment by aalekseyev** [comment]
Me and @diml investigated this more closely, and it seems that it should be OK to unblock even SIGINT because when you hit Ctrl+C the signal is sent to all processes in the process group, not just to a random one of them.

It seems that there are other bugs in Ctrl+C handling in dune (e.g. the discussion in https://github.com/ocaml/dune/issues/1671) and I'm going to look at those. Hopefully whatever extra bugs are exposed by this PR will be fixed then.

@diml, so I propose we just merge this PR unchanged.

**Comment by diml** [comment]
Agreed

**Pull request merged**
