### PR TITLE
Test to reproduce bug with duplicate mld's in same package

### PR DESCRIPTION
**Pull request by rgrinberg**
Odoc doesn't actually allow this so this test will turn into an error later on.

cc @trefis

### CODE REVIEW

**Comment by trefis** [comment]
(nitpick: It's not exactly that it is not allowed, it's just that one will overwrite the other.)
This test seems good to have, if it indeed becomes an error that is.

**Comment by rgrinberg** [comment]
Overwriting definitely seems undesirable so we'd like it to be an error.

What about the `index.mld` that is generated (unless it's present) for every library? Could we possibly pick a unique entry point mld per library?

**Comment by trefis** [comment]
> What about the index.mld that is generated (unless it's present) for every library?

IIRC we've discussed this before: that shouldn't be done. The scope of the doc is really the package, not the library. So we should generate an `index.mld` for a package if there isn't one already, but that's it.

**Comment by rgrinberg** [comment]
> IIRC we've discussed this before: that shouldn't be done. The scope of the doc is really the package, not the library. So we should generate an index.mld for a package if there isn't one already, but that's it.

To clarify, how would you imagine this index page to look then: https://ocaml.janestreet.com/ocaml-core/latest/doc/

It contains entry points for every library, not package. Will you have an entry point for every package instead, and list libraries and their respective entry modules in that package index? I think that's acceptable, but is clearly a little worse than what is available now.

**Comment by trefis** [comment]
> Will you have an entry point for every package instead, and list libraries and their respective entry modules in that package index?

Yep, that sounds right to me.

**Pull request merged**
