### PR TITLE
Ignore special files (BLK, CHR, FIFO, SOCKET)

### LINKED ISSUE #3124: Exception in dune build when Unix domain socket in directory
The **dune build** command raises the following exception when a Unix domain socket file is in the same directory:

Error: exception Sys_error("fail.sock: No such device or address")

## Reproduction

1.) Create a new directory

2.) Create a "dune' file with the following content
```
(executable
 (name unixsocket)
 (libraries unix))
```

3.) Create a "dune-project" file with the following content

`(lang dune 2.2)`

4.) Creating an empty .ml file without code.

`echo "" > unixsocket.ml`

5.) Create a Unix domain socket file (press ctrl+c to quit netcat)

`nc -Ul fail.sock`

6.) Run "dune build"

## Specifications

- Version of `dune` (output of `dune --version`): 2.2.0
- Version of `ocaml` (output of `ocamlc --version`): 4.09.0
- Operating system (distribution and version): Debian GNU/Linux 10 (buster)

## Additional information 

https://gist.github.com/verbosemode/7e7374309df5d6436a3400737fd8b3ad

### LINKED ISSUE #3546: Crash if source directory contains a socket
## Expected Behavior

I have a Unix-domain socket file in the source directory (used for testing). I would expect dune to ignore this.

## Actual Behavior

```
Error: exception Sys_error("socket: No such device or address")
Raised by primitive operation at file "stdlib.ml", line 398, characters 28-54
Called from file "stdlib.ml" (inlined), line 406, characters 2-47
Called from file "digest.ml", line 39, characters 11-31
Called from file "src/stdune/digest.ml" (inlined), line 14, characters 13-38
Called from file "src/stdune/digest.ml", line 42, characters 13-19
Called from file "src/dune/cached_digest.ml" (inlined), line 98, characters
  15-46
Called from file "src/dune/cached_digest.ml", line 104, characters 2-19
Called from file "src/dune/cached_digest.ml" (inlined), line 149, characters
  12-22
Called from file "src/dune/dep.ml", line 57, characters 42-63
Called from file "src/dune/dep.ml", line 62, characters 28-43
Called from file "src/stdune/list.ml", line 19, characters 12-15
Called from file "src/dune/dep.ml", line 133, characters 6-74
Called from file "src/dune/build_system.ml", line 1317, characters 8-56
Called from file "src/fiber/fiber.ml", line 114, characters 10-15
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters
  33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters
  33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters
  33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17
Re-raised at file "src/stdune/exn.ml" (inlined), line 37, characters 27-56
Called from file "src/stdune/exn_with_backtrace.ml", line 13, characters
  33-71
Called from file "src/fiber/fiber.ml", line 85, characters 10-17

I must not crash.  Uncertainty is the mind-killer. Exceptions are the
little-death that brings total obliteration.  I will fully express my cases. 
Execution will pass over me and through me.  And when it has gone past, I
will unwind the stack along its path.  Where the cases are handled there will
be nothing.  Only I will remain.
```

## Reproduction

```
mkdir test
cd test
dune init exe main
ocaml <<EOF
#load "unix.cma";;
let () =
  let socket = Unix.(socket PF_UNIX SOCK_STREAM 0) in
  Unix.bind socket (Unix.ADDR_UNIX "socket");;
EOF
dune build
```

## Specifications

- Version of `dune` (output of `dune --version`): `2.5.1`
- Version of `ocaml` (output of `ocamlc --version`): `4.10.0`
- Operating system (distribution and version): `Debian GNU/Linux 10`

### PR DESCRIPTION
**Pull request by ejgallego**
Fixes #3124 , fixes #3546

TODO: we should add some tests but I'm unsure about portability here.

### CODE REVIEW

**Comment by ejgallego** [comment]
This may have some bad side effects in terms of compatibility, I wonder if someone is depending on pipe creation in rules / tests?

**Review by rgrinberg — APPROVED** [review]
Looks good. Pinging @jeremiedimino just so that he's aware.

**Comment by ejgallego** [comment]
@jeremiedimino does this look OK to you?

**Comment by jeremiedimino** [comment]
Yes, that looks OK to me. But two comments about Path.is_special`:

- the comments looks a bit odd to me. More precisely, it makes sense if you consider the code base as a whole, but if you are just looking at the `Path` module it is not super clear. I would keep it general: `(** Returns [true] for special file kinds such as sockets or character devices *)`. If the function is specific to Dune for some reason, I would leave it hidden in `file_tree.ml`.
- this looks like a predicate on file kinds to me, why take a full `Unix.stats` rather than just `Unix.file_kind`?

**Comment by ejgallego** [comment]
> Yes, that looks OK to me. But two comments about Path.is_special`:

Indeed, when I wrote this I was not super sure how to proceed, in particular about whether to make this function internal to `file_tree`.

I'm leaning towards that option indeed, and leaving `Path.t` untouched. Would that be OK?

**Comment by jeremiedimino** [comment]
Well, if it's a general purpose function with no specific logic, it seems fine to me to share it in a central place. Though `Path` doesn't seem like the right module given that this function doesn't operate on paths. So for now, yes, keeping it private in `file_tree.ml` seems best. If we need it in other places, we can think of a better place.

**Comment by ejgallego** [comment]
Done, still would be good to add a test, can we assume `mkfifo` exists on all supported dev platforms?

**Comment by jeremiedimino** [comment]
Maybe not on Windows, but it seems reasonable to disable this test on Windows.

**Comment by rgrinberg** [comment]
@ejgallego ping on finishing this PR.

**Comment by samoht** [comment]
We've hit a similar issue in irmin test-cases where we use unix domain socket; dune is complaining about these files and it would be nice if it would just skip those :-)

**Comment by ejgallego** [comment]
> @ejgallego ping on finishing this PR.

Sorry for the delay, should be good, tho I'm unsure what's gonna happen on windows [let's wait for CI]

**Comment by ejgallego** [comment]
> I'm unsure what's gonna happen on windows [let's wait for CI]

Seems to work (TM) , on linux I've checked manually that indeed the test is effective [Dune will hand if we revert the fix]

**Pull request merged**
