### PR TITLE
Rewrite promotion with 'a option Fiber.t

### PR DESCRIPTION
**Pull request by rgrinberg**
Introduce 'a option Fiber.t monad that allows us to exit computations by
returning Fiber.return None. This is useful to refactor some code that
was drifting to the right with extremely long if clauses.

I wasn't sure if want to add a `Fiber.Option` module I just did it inline.

### CODE REVIEW

**Comment by aalekseyev** [comment]
I think the cure is worse than the disease in this case.
Basically, I don't see this "drift to the right" as a problem, definitely not worth the cost of mental switching between the monads.

By the way, `sequential_iter` doesn't actually do the correct monad traversal. It should either be called [sequential_iter_ignore_failures] (in which case maybe it shouldn't return an option?), or (better) be removed. The thing with that name shouldn't ignore failures.

**Comment by rgrinberg** [comment]
Yeah, the end result isn't inspiring but I disagree that right drift is an issue. I should also point out that it's confusing to read huge if clauses with correponding else's that do nothing. I'll close this for now as I'm not satisfied with this PR.

**Comment by aalekseyev** [comment]
I've found the following trick useful in the past for large ifs:

```
match condition with
| false -> simple branch
| true ->
   big
   complicated
   branch
```

(you could do it with a "not" too, but I personally prefer a match)

**Comment by aalekseyev** [comment]
(also, splitting large functions in multiple pieces is often a good trick)

**Comment by rgrinberg** [comment]
> I've found the following trick useful in the past for large ifs to re-order branches:

That's a good idea. I pushed a commit that does that. Have another look please.

> (also, splitting large functions in multiple pieces is often a good trick)

It works when you can think of non-artificial names. Otherwise it makes things even more convoluted.

**Comment by aalekseyev** [comment]
Yeah, that looks good to me! 
(I would invert the last condition though while we're at it, just to reduce the number of negations).
(by the way github doesn't update the closed PRs so I was confused for some time)

**Comment by rgrinberg** [comment]
> (I would invert the last condition though while we're at it, just to reduce the number of negations).

Done.

> (by the way github doesn't update the closed PRs so I was confused for some time)

Ah yeah, I've reopened.

**Pull request closed without merging**
