### PR TITLE
Add Dep module and make Dep.Set.t be the old Deps.t

### PR DESCRIPTION
**Pull request by rgrinberg**
This refactoring simplifies adding new types of dependencies

### CODE REVIEW

**Comment by diml** [comment]
The new module seems nicer indeed, but we should measure the impact in terms of memory footprint, given that we manipulate a lot of these values. For instance, we could print the GC stats at the end of a null build on the platform repository.

**Comment by rgrinberg** [comment]
0 rebuilds for the platforms are not affected by this PR. I will now get some GC numbers.

**Comment by rgrinberg** [comment]
[pr.txt](https://github.com/ocaml/dune/files/2932264/pr.txt)
[master.txt](https://github.com/ocaml/dune/files/2932265/master.txt)

Seems like this PR increases the amount of words allocate by almost 1% on the platform. It would have been best if there was no increase, but I think that the best way to address this problem is to just have a way to iterate in parallel over sets without creating the intermediate list. This should cut our allocation much more significantly and probably make this change noise.

**Comment by diml** [comment]
Ok, that seems acceptable to me.

**Pull request merged**
