### PR TITLE
dune describe: include executables in output

### LINKED ISSUE #3892: "dune describe" should include information about executables
What the title says: it would be great if `dune describe` where to include information about executables defined in the workspace (it currently includes information only about libraries). Is there any technical reason that would make this difficult?

### PR DESCRIPTION
**Pull request by nojb**
Fixes #3892

### CODE REVIEW

**Comment by nojb** [comment]
Review welcome :)

**Review by rgrinberg — APPROVED** [review]

**Comment by nojb** [comment]
Thanks! Do you think this needs a Changes entry?

**Comment by rgrinberg** [comment]
It won't hurt I suppose. Especially since we don't promise to keep this command stable.

**Comment by nojb** [comment]
I made one more change, by including `include_dirs` in the executable output, just like we do for libraries.

**Pull request merged**
