### PR TITLE
feature: extend traces to include source scans

### PR DESCRIPTION
**Pull request by rgrinberg**
Source scans can be quite slow. Record them in the trace.

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
Actually we no longer share the source tree code so there's nothing to review here.

**Comment by snowleopard** [comment]
Can you show an example trace of some non-trivial build to see how much it takes?

**Comment by rgrinberg** [comment]
So for doing a null build on dune, `dune.exe build @check` is around 2.5 seconds. 1.3 seconds of that is scanning the source tree.

**Comment by snowleopard** [comment]
Oh, wow. I now want some similar tracing internally =)

**Comment by Khady** [comment]
What does “source scans” refer to exactly? Is it only about checking timestamp and hashes, or does it also include the creation and/or execution of rules?

**Comment by rgrinberg** [comment]
A source scan refers to traversing the entire source tree to extract all project and dune files.

**Pull request merged**
