### PR TITLE
External dune shutdown command

### PR DESCRIPTION
**Pull request by cwong-ocaml**
It is friendly to provide an external way to shutdown the dune build in a workspace regardless of whether an RPC connection to that build is currently held.

Signed-off-by: Cameron Wong <cwong@janestreet.com>

### CODE REVIEW

**Comment by rgrinberg** [comment]
The implementation looks good, but it's a bit strange to have this under `dune rpc`. It's just a shutdown operation,  not really specific to RPC.

**Comment by cwong-ocaml** [comment]
Didn't have any particular reason to put it into `rpc`, i suppose. I guess I was thinking of it as a "shutdown the running server", but making it toplevel is fine too.

**Comment by cwong-ocaml** [comment]
It looks like watch mode doesn't work within the CI and the output formatting of `ps -p` is kinda gross. Any advice?

**Comment by rgrinberg** [comment]
Yes, I've given up on using cram for RPC tests. There are some existing tests that use Lwt, but those are more about testing the Lwt client. I'm in the process of extracting some parts of the scheduler so that we can write tests with ppx_expect + fiber for RPC.

**Review by rgrinberg — APPROVED** [review]

**Comment by cwong-ocaml** [comment]
I'll leave the flaky test out for now, then.

**Pull request merged**
