### PR TITLE
Remove most useless parentheses from the syntax

### PR DESCRIPTION
**Pull request by diml**
Most parentheses in the syntax are useless. This PR removes most of these.

For instance `src/dune` goes from:

```scheme
(library
 ((name        dune)
  (libraries   (unix
                stdune
                fiber
                xdg
                re
                opam_file_format
                usexp
                ocaml_config))
  (synopsis    "Internal Dune library, do not use!")))

(ocamllex (meta_lexer glob_lexer dune_lexer))

(rule
 ((targets (setup.ml))
  (mode    fallback)
  (action  (copy# setup.defaults.ml setup.ml))))
```

to:

```scheme
(library
 (name        dune)
 (libraries   unix
              stdune
              fiber
              xdg
              re
              opam_file_format
              usexp
              ocaml_config)
 (synopsis    "Internal Dune library, do not use!"))

(ocamllex meta_lexer glob_lexer dune_lexer)

(rule
 (targets setup.ml)
 (mode    fallback)
 (action  (copy# setup.defaults.ml setup.ml)))
```

### CODE REVIEW

**Comment by diml** [comment]
I didn't change the ordered set language yet. Since it is a bit more complex, I think it will deserve its own PR.

**Comment by diml** [comment]
Good point. The only cases where we were using `record` or `list` explicitly were for explicit jbuild parsers, plus I forgot a couple of `list`. I renamed `Stanza.Of_sexp_helpers` to `Stanza.Of_sexp` and made it an overlay of `Sexp.Of_sexp` that changes `record` and `list`.

**Comment by emillon** [comment]
Sorry to comment after the merge. The feature and the implementation look great.

I just wonder what the error messages look like when one writes `(library (a b))` instead of `(library a b)` (out of habit, or when just renaming a file when converting). Do you think we should try to detect that a file is using the former syntax, and write a helpful message in that case?

**Comment by diml** [comment]
That would be better indeed. Currently the error is something like `Atom or quoted string expected` which is not great...

**Comment by trefis** [comment]
Somewhat related: could `action` become `actions` and expect a list instead of requiring the use of `(progn ...)`?

**Comment by diml** [comment]
I guess we chould just allow all constructions to be variadic without changing the name of the field. i.e.:

```scheme
(action (run x) (chdir foo (run y) (run z)))
```

rather than:

```scheme
(action (progn (run x) (chdir foo (progn (run y) (run z))))
```

**Pull request merged**
