### PR TITLE
Upgrade templates for subsystems

### PR DESCRIPTION
**Pull request by rgrinberg**
Do this when encoding subsystems

Fix #1631

### CODE REVIEW

**Comment by rgrinberg** [comment]
@xclerc I've added fatal errors for templates that cannot be upgraded.

There's an unrelated error in CI. Looks like odoc is causing it:
```
#=== ERROR while compiling odoc.1.3.0 =========================================#
# context     2.0.0 | linux/x86_64 | ocaml-system.4.06.0 | https://opam.ocaml.org#0b1b3456
# path        ~/.opam/default/.opam-switch/build/odoc.1.3.0
# command     ~/.opam/default/bin/dune build -p odoc -j 1
# exit-code   1
# env-file    ~/.opam/log/odoc-8491-87c04a.env
# output-file ~/.opam/log/odoc-8491-87c04a.out
### output ###
# [...]
# Warning 3: deprecated: Html__.Utils.Html.pcdata
# Use txt instead
#     ocamlopt src/html/.html.objs/html__To_re_html_tree.{cmx,o}
# File "src/html/to_re_html_tree.ml", line 50, characters 27-38:
# Warning 3: deprecated: Html__.Utils.Html.pcdata
# Use txt instead
# File "src/html/to_re_html_tree.ml", line 57, characters 18-29:
# Warning 3: deprecated: Html__.Utils.Html.pcdata
# Use txt instead
# File "src/html/to_re_html_tree.ml", line 69, characters 12-23:
# Warning 3: deprecated: Html__.Utils.Html.pcdata
# Use txt instead
```

cc @jonludlam and @aantron

**Comment by xclerc** [comment]
Thanks, I think it will make debugging easier.

**Comment by rgrinberg** [comment]
We've agreed to do the upgrading in the decoding rather than the encoding pass. The idea is going to be that once we read jbuild files, we will translate them on the fly to dune files. After that point in the code, we'll no longer have to worry about jbuild files anymore.

**Comment by aantron** [comment]
The odoc error should have been fixed by ocaml/odoc#255.

**Pull request merged**
