### PR TITLE
Tweak dune file formatting: avoid pure vertical layout when formatting wrapped lists

### LINKED ISSUE #10860: auto formatting of `run` shouldn't split its content into one word per line
## Desired Behavior

When using `run` in a rule stanza we can have long command with many arguments which quickly end up being split into one word per line. It would tend to look better if `run` could keep everything on a single line as much as possible. And when it splits things into multiple lines it would put as much content as possible on every line.

## Example

The current

```
(rule
 (target sql_file1.ml)
 (deps
  gen_file2.sql
  gen_file3.sql)
 (mode promote)
 (action
  (with-stdout-to
   %{target}
   (run
    sqlgg
    -static-header
    -gen
    caml_io
    -name
    Make
    -params
    unnamed
    -category
    none
    gen_file2.sql
    -category
    all
    gen_file3.sql))))
```

could look more like this

```lisp
(rule
 (target sql_file1.ml)
 (deps 
  gen_file2.sql
  gen_file3s.sql)
 (mode promote)
 (action
  (with-stdout-to
   %{target}
   (run  sqlgg -static-header -gen caml_io -name Make -params unnamed -category none gen_file2.sql -category all gen_file3.sql))))
```

or if the line is longer than the limit, it could look like this
```
   (run  sqlgg -static-header -gen caml_io -name Make -params unnamed -category none 
            gen_file2.sql -category all gen_file3.sql))))
```

### PR DESCRIPTION
**Pull request by nojb**
Fixes #10860

The effect of the change is illustrated in the tests.

cc @Khady

### CODE REVIEW

**Review by rgrinberg — APPROVED** [review]
LGTM. Changes entry please

**Comment by Khady** [comment]
Thanks! It would definitely help with `run`. I don't have a real opinion about the impact on other wrapped lists. From the diff it generally looks good. Two points where it could look worse are `modules` and `libraries` where it can be useful to have things kept in a alphabetical order to ease reading. I tend to think that the horizontal layout would be fine anyway.

**Comment by nojb** [comment]
> I don't have a real opinion about the impact on other wrapped lists.

Unfortunately, the formatter works at the level of s-expressions; so we don't really know the difference between "run" and other lists, so using different formatting for different types of wrapped lists is not straightforward at the moment.

**Review by Khady — APPROVED** [review]
thanks :)

**Comment by Leonidas-from-XIV** [comment]
I added a changelog entry and merged it to move this a bit forward :-) @nojb feel free to adjust the wording if that's not what you had in mind.

**Comment by nojb** [comment]
@Leonidas-from-XIV Seems fine, thanks. The reason I had not merged it is that I was not 100% sure that the new style is always better than the old style, but I guess there's no harm to try it out. Thanks!

**Comment by maiste** [comment]
While releasing [3.17]() we found that this PR seems to break odoc `@runtest` (see the [CI](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f1d49be945320c030eb896dc36ee563859d291dc/variant/compilers,4.14,dune-configurator.3.17.0~alpha0,revdeps,odoc.2.4.3)). @nojb is the version here related to the `dune` version or the version from the `lang dune <version>` in `dune-project`? If this is the executable version, it would break dune for people doing some tests with `sexpr` as long as they upgrade to `dune.3.17.0`.

**Comment by nojb** [comment]
> While releasing [3.17](https://github.com/ocaml/dune/issues/11143#issuecomment-2502349062) we found that this PR seems to break odoc `@runtest` (see the [CI](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f1d49be945320c030eb896dc36ee563859d291dc/variant/compilers,4.14,dune-configurator.3.17.0~alpha0,revdeps,odoc.2.4.3)). @nojb is the version here related to the `dune` version or the version from the `lang dune <version>` in `dune-project`? If this is the executable version, it would break dune for people doing some tests with `sexpr` as long as they upgrade to `dune.3.17.0`.

I'm away from my computer at the moment. I'll take a look later and post back here any findings.

**Comment by nojb** [comment]
> > While releasing [3.17](https://github.com/ocaml/dune/issues/11143#issuecomment-2502349062) we found that this PR seems to break odoc `@runtest` (see the [CI](https://opam.ci.ocaml.org/github/ocaml/opam-repository/commit/f1d49be945320c030eb896dc36ee563859d291dc/variant/compilers,4.14,dune-configurator.3.17.0~alpha0,revdeps,odoc.2.4.3)). @nojb is the version here related to the `dune` version or the version from the `lang dune <version>` in `dune-project`? If this is the executable version, it would break dune for people doing some tests with `sexpr` as long as they upgrade to `dune.3.17.0`.
> 
> I'm away from my computer at the moment. I'll take a look later and post back here any findings.

From a quick glance: the rule in question

https://github.com/ocaml/odoc/blob/822d266232fccdffbd4922434c81c45ab6d583f4/test/generators/dune#L11-L16

uses `dune format-dune-file` without a `--dune-version` argument, so the latest available version of the Dune language will be used, in which the case the observed behaviour is the expected one.

**Comment by nojb** [comment]
> Is this behaviour specific to `dune format-dune-file` where you have to specify the version or it will use the executable version?

Yes, it is specific to this command, which does not assume to be in a Dune workspace at all to begin with.

**Comment by Leonidas-from-XIV** [comment]
Thanks for the investigation, you're right that `format-dune-file` has this documented:

```
       --dune-version=VERSION (absent=3.17)
           Which version of Dune language to use.
```

I personally would argue that this is quite unhelpful default as then the editor needs to parse the dune lang version or have something that's changing depening on which dune version your package management tool has selected.

It's also different from how the rest of Dune works.

**Comment by nojb** [comment]
> It's also different from how the rest of Dune works.

Not really, as there are no analogs of this command in Dune: Dune is not typically supposed to call Dune in a user rule, and indeed `dune format-dune-file` was mostly added as a debugging aid, not meant to be used from user rules. Instead, we could/should expose a new type of action (ie `(format_dune_file <path>)`) that could be used in user rules and that would take into account the current version of the Dune language.

I can look into adding this, but it won't fix the immediate issue, of course.

**Comment by maiste** [comment]
@nojb would it be a problem if we remove the fix from `3.17.0` and reintroduce it in a future dune release? It would give us more time to "fix" `odoc` and make them ready to support this change. WDYT?

**Comment by nojb** [comment]
> @nojb would it be a problem if we remove the fix from `3.17.0` and reintroduce it in a future dune release? It would give us more time to "fix" `odoc` and make them ready to support this change. WDYT?

Sounds good to me.

**Comment by Leonidas-from-XIV** [comment]
The documentation states that this is also supposed to be used for editors, but if an editor does not use the `--dune-version` command, then it will still format the files in an inconsistent way.

And while I can see the point of being independent from the workspace, I would expect that in the presence of the workspace there would be a way to use the dune-lang version, without having to parse `dune-project` manually.

The reason why I think it is wrong is because I am thinking what what PR to send upstream to odoc to fix this:

1. I can add `--dune-version=3.16` to keep it at a fixed version, but this will break the lower-bounds check if OPAM selects Dune 3.7
2. I can specify `--dune-version=3.7` but this is fairly ugly because now odoc needs to update two places. I thought that maybe `--dune-version=%{dune_lang_version}` could be used, but the variable does not exist
3. We could introduce `--read-dune-version-from-workspace` but I really don't like flags of the `--do-the-right-thing` kind as people need to be aware of them so it pushes the duty to do the right thing onto users.
4. We could, as you suggest expose an action, but this doesn't help editors, so if they use this command they still need to determine the dune-lang version to use it properly.

My suggestion would be skipping this from 3.17 and reintroducing this in 3.18 with a change that if `--dune-version` is not specified, it tries to read the version from the project and if that fails then it falls back to using the dune-version. WDYT?

**Comment by nojb** [comment]
> > with a change that if `--dune-version` is not specified, it tries to read the version from the project and if that fails then it falls back to using the dune-version.
> 
> Sounds reasonable.

Thinking more about this: reading the version from *which* project? The one corresponding to the current working directory, or the one containing the target Dune file? I guess the latter, as otherwise the result of the command would depend on the current directory.

**Comment by Leonidas-from-XIV** [comment]
The one that the file would be belonging to, a little bit like vendoring a project creates a barrier for automatic formatting.

**Comment by Khady** [comment]
if `dune format-dune-file` starts to read some of the dune config for the project, could it go all the way and solve https://github.com/ocaml/dune/issues/3516?

**Comment by nojb** [comment]
> if `dune format-dune-file` starts to read some of the dune config for the project, could it go all the way and solve #3516?

I guess so. I think it would be the same as calling `dune build @fmt` but restricting the effect to a single file. Needs to be checked that this behaviour is OK for existing users of `dune format-dune-file`. You mentioned OCaml-LSP in #3516. Are you aware of any others?

Incidentally, in #11166 there is a first (orthogonal) step which is to expose a `(format-dune-file)` action to be used within Dune files instead of calling `dune format-dune-file`.

**Comment by Khady** [comment]
> Are you aware of any others?

Nothing that comes directly to my mind

**Comment by mbarbin** [comment]
> You mentioned OCaml-LSP in #3516. Are you aware of any others?

I'll add [dunolint](https://github.com/mbarbin/dunolint) to the list of `dune format-dune-file` users.

**Pull request merged**
