### PR TITLE
refactor(top-module): module object directories

### PR DESCRIPTION
**Pull request by rgrinberg**
Instead of copying cmi's to a temp dir, we setup proper rules with
dedicated object directories for every module. As a result, we just load
the object file directly instead of relying on [#use]

Signed-off-by: Rudi Grinberg <me@rgrinberg.com>

ps-id: 09ec1765-fdb6-4f25-a190-3dfda2aceec4

### CODE REVIEW

**Review by emillon — APPROVED** [review]
The implementation itself is a bit too intense to formally review but the changes in the test suite look good.

**Review by Alizter — APPROVED** [review]
Code looks good and I tested `./dune.exe ocaml top` and it seems to be working fine.

**Comment by rgrinberg** [comment]
> Code looks good and I tested ./dune.exe ocaml top and it seems to be working fine.

Is that a typo? `ocaml top` is not the command this PR affects.

**Comment by emillon** [comment]
It's `dune ocaml top-module` isn't it? cmdliner will allow any prefix if it's not ambiguous.

**Comment by rgrinberg** [comment]
Right, but `ocaml top` is yet another command already.

**Comment by rgrinberg** [comment]
Tested it myself. Seems to work well.

**Comment by Alizter** [comment]
I had also tested `top-module`.

**Pull request merged**
