### PR TITLE
[2.9-backport] Add (enabled_if) support to the mdx stanza

### PR DESCRIPTION
**Pull request by emillon**
This brings useful workflows such as disabling failing mdx test depending on the OS.

This is an ad-hoc solution until #4080 is implemented but looks safer for 2.x.

### CODE REVIEW

**Comment by jeremiedimino** [comment]
@ejgallego how do you want to proceed for merging PRs against the 2.9 branch? Are you merging the PRs or should the submitter merge them once CI passes?

**Comment by emillon** [comment]
I tried to follow https://github.com/ocaml/dune/wiki/Release-Plan-for-Dune-2.9 but wasn't sure which steps I should do myself.

**Comment by ejgallego** [comment]
> @ejgallego how do you want to proceed for merging PRs against the 2.9 branch? Are you merging the PRs or should the submitter merge them once CI passes?

What we wrote is that the RM merge the PRs as to ensure CHANGES is consistent mainly, I will do pass on all the stuff pending for 2.9 this week and report back.

**Review by ejgallego — APPROVED** [review]
LGTM for 2.9 thanks!

**Pull request merged**
