### PR TITLE
Add feature request issue templates

### PR DESCRIPTION
**Pull request by shonfeder**
Followup to #3005

With the new "Bug report" issue templates enabled, it's not immediately clear when creating new issues how to open a feature request. This address that by adding a blank "feature request" template.

Signed-off-by: Shon Feder <shon.feder@gmail.com>

### CODE REVIEW

**Comment by shonfeder** [comment]
I've made this a PR in case there are suggestions about actual content we want to encourage in the feature request PR.

**Comment by diml** [comment]
Seems good! Regarding the contents, I find that often feature requests would be easier to grasp with a concrete example. Maybe we could invite the author to write up a concrete example with concrete file examples?

**Comment by shonfeder** [comment]
Thank @diml 

I added some content, including a request for an example as you suggested. Let me know if it sparks any other ideas, or if you think this is good as is.

**Comment by diml** [comment]
Looks good to me! You can ignore the travis failure BTW. I accidentally broke master last week when merging a PR and I fixed it this morning.

**Pull request merged**
