### PR TITLE
Use .utop.ml to avoid creating a separate dir for utop rules

### PR DESCRIPTION
**Pull request by rgrinberg**
This isn't as simple as I thought (as the failing test shows).

### CODE REVIEW

**Comment by rgrinberg** [comment]
The exe rules overwrite the obj_name even if the user sets it. I'm not sure if this is the right fix though. Should we just make set_obj_name smarter?

**Comment by rgrinberg** [comment]
Note that if we merge this, we'll need another way to reproduce #538

**Comment by diml** [comment]
> The exe rules overwrite the obj_name even if the user sets it. I'm not sure if this is the right fix though. Should we just make set_obj_name smarter?

It shouldn't be an issue given that the object file is generated in its own sub-directory. BTW, I'm wondering if we shouldn't use `_utop.exe`, to avoid clashes programs named utop.

**Comment by rgrinberg** [comment]
> It shouldn't be an issue given that the object file is generated in its own sub-directory. BTW, I'm wondering if we shouldn't use _utop.exe, to avoid clashes programs named utop.

What about source level conflicts? I.e. the user could have a `utop.ml` module defined. Like we do in jbuilder for example.

**Comment by diml** [comment]
> What about source level conflicts? I.e. the user could have a utop.ml module defined. Like we do in jbuilder for example.

That shouldn't be an issue given that the file we generate is now ".utop.ml".

**Comment by rgrinberg** [comment]
Ok so this is exactly what this PR does right now

**Comment by diml** [comment]
Ok, so we need to set the object name explicitely otherwise it will be the empty string right? What about using "_utop.ml"?

**Comment by rgrinberg** [comment]
The CI failure is unrelated (jsoo failed to install).

**Pull request merged**
