### PR TITLE
Build bootstrap with -custom in dev

### PR DESCRIPTION
**Pull request by rgrinberg**
This allows one to change switches without redoing bootstrap

### CODE REVIEW

**Comment by rgrinberg** [comment]
I'm not enabling this by default because I assume it results in a slower build.

I don't know why we didn't do this earlier, could have saved us so much time :)

**Comment by diml** [comment]
I can't think of a reason why it would be slower actually. Plus `-custom` is supposed to be more portable, I propose to use `-custom` unconditionally

**Comment by rgrinberg** [comment]
I just tested it out and it's the same.

Why isn't -custom the default then?

**Comment by diml** [comment]
No idea. I guess executables are smaller without `-custom`...

**Comment by rgrinberg** [comment]
Indeed that's why I thought avoiding `-custom` would be slower. The binaries are bigger and disks aren't so fast. However, the filesize doesn't seem very different for me between `-custom` or no `-custom`.

**Comment by diml** [comment]
Yh, the only additional weight are the stubs for the unix library.

**Pull request merged**
