### PR TITLE
Disallow dangling tests in 1.10

### PR DESCRIPTION
**Pull request by rgrinberg**
As discussed in the opam PR:

Starting from 1.10, we make the user associate tests defined using aliases or the test stanza to a package.

### CODE REVIEW

**Comment by diml** [comment]
Given that it is a breaking change, this should be a warning rather than an error.

**Comment by diml** [comment]
Thinking about this again, if not specifying the package field is really not the right thing to do, then making this an error right now will make things easier for both us and users.

**Comment by diml** [comment]
Hmm, inline tests are not covered by these checks, which is not great :/

Another case that is not covered is when the user uses a different alias than runtest for a bunch of tests, as we do in dune for instance.

**Comment by rgrinberg** [comment]
Such tests would not be executed by opam anyway.

**Comment by diml** [comment]
I agree in the case of dune itself, but in general it seems to me that they would.

BTW, attaching tests to packages is a bit abstract to me as I don't know when opam execute tests. I.e. when you do `opam install pkg`, the tests are not executed. In pratice, when are tests executed by opam?

I would have thought that nowadays everybody is running their testsuite inside some CI system. And in this case, running all the tests at once seems much simpler and much more efficient.

**Comment by rgrinberg** [comment]
> I agree in the case of dune itself, but in general it seems to me that they would.

Yeah, it's not foolproof. A user can have a `@integration-tests` alias for example. Or some alias to run part of the tests. It doesn't seem so important to me.

>  I would have thought that nowadays everybody is running their testsuite inside some CI system. And in this case, running all the tests at once seems much simpler and much more efficient.

`$ opam install -t foo` will build and run tests for foo. I believe that opam's own ci and most people's CI setups use this to run tests.

**Comment by diml** [comment]
> Yeah, it's not foolproof. A user can have a @integration-tests alias for example. Or some alias to run part of the tests. It doesn't seem so important to me.

Agreed. It's important for inline tests thought, as these are typically used for writing unit tests.

> $ opam install -t foo will build and run tests for foo. I believe that opam's own ci and most people's CI setups use this to run tests.

Ok. The case that really interests us is the case when a project defines several packages. What do people do in this case?

**Comment by rgrinberg** [comment]
> The case that really interests us is the case when a project defines several packages. What do people do in this case?

The same way. All the packages in the repo are pinned and the tests are ran when they are installed.

**Comment by diml** [comment]
I see. I suppose testing the installation of the various packages this way makes sense to check that the opam metadata are correct. However, doing the same for tests seems a bit extra to me, especially if we can't provide strong guarantee on the partitioning.

What about the following workflow:
- the user remove all the `(package ...)` fields from tests
- the CI installs the various packages by pinning them
- the CI runs: `dune runtest -p ""`

that gives us exactly what we want:
- the installation of the various packages via opam is tested
- everything is built/run exactly once

**Comment by rgrinberg** [comment]
We'll still have the problem where we can't run tests for an individual package. For some repos, that workflow is important. They will have to partition their test suite manually

**Comment by diml** [comment]
But why is it important? That's the part I don't understand.

**Comment by avsm** [comment]
The most obvious problem is the _individual_ opam packages that are released.

Right now there might be some tests defined across multiple packages: e.g.` cohttp` and cohttp-async, but the tests actually require cohttp-async to compile correctly.  In this case, the opam test for `cohttp` needs to know not to run that test, and `cohttp-async` should know to run it.

But when running in CI, the `cohttp` package doesn't know anything about the broader dune repository it came from.  It also cannot pin `cohttp-async` just to run the tests since that would pull in a big set of downstream packages.

Things also get ambiguous when the tests just depend on `cohttp`, since they will be repeated when run in the `cohttp-async` package.

All in all, life would be much easier if a test was ascribed to a particular package where there is ambiguity involved...

**Comment by diml** [comment]
> All in all, life would be much easier if a test was ascribed to a particular package where there is ambiguity involved...

The problem is that the current PR is incomplete: only a subset of tests are guaranteed to be assigned to a package. Making it complete seems like opening a can of worms to me. So I just want to be sure we are all on the same page regarding the motivations.

Right now, I understand the problem, but I'm still not convinced by the motivations. Anyway, I put this on the list of things to discuss during the videoconf meeting tomorrow. It should be easier to discuss this during live conversation.

**Comment by rgrinberg** [comment]
From the discussion in the meeting: the value this PR brings isn't worth the complexity.

**Pull request closed without merging**
