### PR TITLE
test(coq): remove macos coq native restriction

### PR DESCRIPTION
**Pull request by Alizter**
We don't test on macos and it shouldn't be Dune's job to do so anyway.

### CODE REVIEW

**Comment by ejgallego** [comment]
IIRC this was added so people could run Coq tests on OSX locally.

This PR needs confirmation from an OSX dev as to be sure they can run Coq tests even after this diff.

**Comment by Alizter** [comment]
@ejgallego I would rather that the test fails for OSX devs and they know about it rather than silently succeeding.

We only test Ubuntu in the Coq job of the Dune CI and I think that's fine. OSX devs should jusylt run the tests they need to and the CI will catch anything that might need updating.

**Comment by ejgallego** [comment]
> @ejgallego I would rather that the test fails for OSX devs and they know about it rather than silently succeeding.

Wouldn't that be very confusing for them? I'm not sure enabling broken tests leads to a good workflow.

Indeed, the current reasoning was to allow OSX devs to catch native issues in the CI.
 
> We only test Ubuntu in the Coq job of the Dune CI and I think that's fine. OSX devs should jusylt run the tests they need to and the CI will catch anything that might need updating.

I think the CI testing is fine; this issue is about local testing; I'd rather have `make test-coq` partially working and delegate the rest to CI than having that test target always broken.

So this PR needs first feedback from OSX devs to see what happens when they do install `coq-native` and do `make test-coq`

**Comment by Alizter** [comment]
Tried on the CI looks like it still doesn't work. I'm closing this since its not worth anymore time.

**Comment by ejgallego** [comment]
Yup, if that doesn't work then we can't merge this. Tho the error deserves its own bug:
```
+++ b/_build/.sandbox/fac578e7fc24c97bfc0799ec6c383b39/default/test/blackbox-tests/test-cases/coq/native-single.t/run.t.corrected
@@ -3,6 +3,7 @@
         coqdep foo.v.d
           coqc Nbasic_foo.{cmi,cmxs},foo.{glob,vo}
           coqc Nbasic_bar.{cmi,cmxs},bar.{glob,vo}
+  ld: warning: directory not found for option '-L$TESTCASE_ROOT/_build/default/.coq-native'
 ```
This should def not happen.

**Pull request closed without merging**
